
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 29 2025 16:43:26 -03 (Sep 29 2025 19:43:26 UTC)

// Verification Directory fv/h_decoder_16_11 

module h_decoder_16_11(i_CodeWord, o_DecodWord, o_ErrorC, o_ErrorD);
  input [15:0] i_CodeWord;
  output [10:0] o_DecodWord;
  output o_ErrorC, o_ErrorD;
  wire [15:0] i_CodeWord;
  wire [10:0] o_DecodWord;
  wire o_ErrorC, o_ErrorD;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_28, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_45, n_46, n_47, n_48, n_49;
  XNOR2X2 g966__2398(.A (n_49), .B (i_CodeWord[5]), .Y
       (o_DecodWord[1]));
  XNOR2X2 g970__5107(.A (n_33), .B (i_CodeWord[11]), .Y
       (o_DecodWord[6]));
  XNOR2X2 g975__6260(.A (i_CodeWord[12]), .B (n_43), .Y
       (o_DecodWord[7]));
  XNOR2X2 g969__4319(.A (n_35), .B (i_CodeWord[15]), .Y
       (o_DecodWord[10]));
  XNOR2X2 g968__8428(.A (i_CodeWord[7]), .B (n_42), .Y
       (o_DecodWord[3]));
  XNOR2X2 g971__5526(.A (i_CodeWord[3]), .B (n_37), .Y
       (o_DecodWord[0]));
  XNOR2X2 g972__6783(.A (i_CodeWord[6]), .B (n_39), .Y
       (o_DecodWord[2]));
  XNOR2X2 g974__3680(.A (i_CodeWord[9]), .B (n_46), .Y
       (o_DecodWord[4]));
  XNOR2X2 g967__1617(.A (n_41), .B (i_CodeWord[14]), .Y
       (o_DecodWord[9]));
  XNOR2X2 g973__2802(.A (i_CodeWord[13]), .B (n_48), .Y
       (o_DecodWord[8]));
  NAND3XL g976__1705(.A (n_23), .B (n_24), .C (n_47), .Y (n_49));
  NAND2XL g981__5122(.A (n_45), .B (n_47), .Y (n_48));
  NAND2XL g985__8246(.A (n_45), .B (n_36), .Y (n_46));
  XNOR2X2 g977__7098(.A (n_28), .B (i_CodeWord[10]), .Y
       (o_DecodWord[5]));
  NAND2XL g986__6131(.A (n_45), .B (n_40), .Y (n_43));
  NAND2XL g979__1881(.A (n_38), .B (n_47), .Y (n_42));
  NAND2XL g978__5115(.A (n_34), .B (n_40), .Y (n_41));
  NAND2XL g983__7482(.A (n_38), .B (n_40), .Y (n_39));
  NAND2XL g982__4733(.A (n_38), .B (n_36), .Y (n_37));
  NAND2XL g980__6161(.A (n_34), .B (n_47), .Y (n_35));
  NAND2XL g984__9315(.A (n_34), .B (n_36), .Y (n_33));
  NOR3XL g988__9945(.A (n_32), .B (n_31), .C (n_30), .Y (n_47));
  NOR3BXL g990__2883(.AN (n_32), .B (n_31), .C (n_30), .Y (n_36));
  NOR3BXL g991__2346(.AN (n_31), .B (n_32), .C (n_30), .Y (n_40));
  AND2X2 g987__1666(.A (n_26), .B (n_30), .Y (o_ErrorD));
  NAND3BXL g989__7410(.AN (n_25), .B (n_34), .C (o_ErrorC), .Y (n_28));
  INVXL g992(.A (o_ErrorC), .Y (n_30));
  XNOR2X2 g993__6417(.A (n_14), .B (n_22), .Y (o_ErrorC));
  NAND3BXL g994__5477(.AN (n_25), .B (n_24), .C (n_23), .Y (n_26));
  MX2X1 g995__2398(.A (n_23), .B (n_21), .S0 (n_16), .Y (n_22));
  NOR2XL g998__5107(.A (n_21), .B (n_24), .Y (n_38));
  AND2X1 g999__6260(.A (n_21), .B (n_24), .Y (n_45));
  NAND2XL g996__4319(.A (n_32), .B (n_31), .Y (n_25));
  NOR2XL g997__8428(.A (n_24), .B (n_23), .Y (n_34));
  INVXL g1001(.A (n_23), .Y (n_21));
  XNOR2X1 g1000__5526(.A (n_6), .B (n_20), .Y (n_31));
  XNOR2X1 g1002__6783(.A (n_10), .B (n_19), .Y (n_24));
  XNOR2X1 g1003__3680(.A (n_3), .B (n_17), .Y (n_23));
  XNOR2X1 g1004__1617(.A (n_9), .B (n_18), .Y (n_20));
  XNOR2X1 g1005__2802(.A (n_8), .B (n_18), .Y (n_19));
  XNOR2X1 g1006__1705(.A (n_0), .B (n_15), .Y (n_17));
  XNOR2X1 g1007__5122(.A (n_16), .B (n_15), .Y (n_32));
  XNOR2X1 g1008__8246(.A (n_1), .B (n_2), .Y (n_16));
  XNOR2X1 g1009__7098(.A (n_13), .B (n_11), .Y (n_15));
  XNOR2X1 g1010__6131(.A (n_5), .B (n_4), .Y (n_14));
  XNOR2X1 g1011__1881(.A (n_7), .B (n_12), .Y (n_18));
  XNOR2X1 g1017__5115(.A (i_CodeWord[12]), .B (i_CodeWord[13]), .Y
       (n_13));
  XNOR2X1 g1013__7482(.A (i_CodeWord[11]), .B (i_CodeWord[15]), .Y
       (n_12));
  XNOR2X1 g1021__4733(.A (i_CodeWord[14]), .B (i_CodeWord[15]), .Y
       (n_11));
  XNOR2X1 g1014__6161(.A (i_CodeWord[6]), .B (i_CodeWord[14]), .Y
       (n_10));
  XNOR2X1 g1015__9315(.A (i_CodeWord[1]), .B (i_CodeWord[9]), .Y (n_9));
  XNOR2X1 g1016__9945(.A (i_CodeWord[2]), .B (i_CodeWord[10]), .Y
       (n_8));
  XNOR2X1 g1012__2883(.A (i_CodeWord[3]), .B (i_CodeWord[7]), .Y (n_7));
  XNOR2X1 g1024__2346(.A (i_CodeWord[5]), .B (i_CodeWord[13]), .Y
       (n_6));
  XNOR2X1 g1019__1666(.A (i_CodeWord[0]), .B (i_CodeWord[1]), .Y (n_5));
  XNOR2X1 g1025__7410(.A (i_CodeWord[2]), .B (i_CodeWord[3]), .Y (n_4));
  XNOR2X1 g1020__6417(.A (i_CodeWord[10]), .B (i_CodeWord[11]), .Y
       (n_3));
  XNOR2X1 g1022__5477(.A (i_CodeWord[5]), .B (i_CodeWord[7]), .Y (n_2));
  XNOR2X1 g1023__2398(.A (i_CodeWord[4]), .B (i_CodeWord[6]), .Y (n_1));
  XNOR2X1 g1018__5107(.A (i_CodeWord[8]), .B (i_CodeWord[9]), .Y (n_0));
endmodule

