/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Oct  9 11:04:05 2025
#  Design:            bch_bm_block_p
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_bm_block_p/bch_bm_block_p_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 26 2025 11:41:01 -03 (Sep 26 2025 14:41:01 UTC)
// Verification Directory fv/bch_bm_block_p 
module gf_divider (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;

   NAND3BXL g2032__2398 (.Y(q[2]),
	.AN(n_77),
	.B(n_76),
	.C(n_67));
   OAI211X1 g2033__5107 (.Y(q[0]),
	.A0(n_66),
	.A1(n_68),
	.B0(n_73),
	.C0(n_67));
   OAI211X1 g2034__6260 (.Y(q[1]),
	.A0(n_65),
	.A1(n_68),
	.B0(n_76),
	.C0(n_72));
   OAI211X1 g2035__4319 (.Y(q[3]),
	.A0(n_28),
	.A1(n_70),
	.B0(n_74),
	.C0(n_67));
   OAI22XL g2036__8428 (.Y(n_77),
	.A0(n_53),
	.A1(n_75),
	.B0(n_61),
	.B1(n_68));
   NOR2XL g2037__5526 (.Y(n_75),
	.A(n_69),
	.B(n_71));
   NAND2XL g2038__6783 (.Y(n_76),
	.A(n_61),
	.B(n_69));
   OAI21XL g2039__3680 (.Y(n_74),
	.A0(n_53),
	.A1(n_63),
	.B0(n_71));
   NAND3BXL g2040__1617 (.Y(n_73),
	.AN(n_53),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2041__2802 (.Y(n_72),
	.AN(n_61),
	.B(n_29),
	.C(n_64));
   NAND2XL g2042__1705 (.Y(n_70),
	.A(n_65),
	.B(n_64));
   NOR2XL g2043__5122 (.Y(n_71),
	.A(n_28),
	.B(n_66));
   NOR3BXL g2044__8246 (.Y(n_69),
	.AN(n_65),
	.B(n_28),
	.C(n_63));
   NAND3XL g2045__7098 (.Y(n_68),
	.A(n_29),
	.B(n_53),
	.C(n_63));
   NAND4XL g2046__6131 (.Y(n_67),
	.A(n_29),
	.B(n_60),
	.C(n_63),
	.D(n_65));
   OR2X1 g2047__1881 (.Y(n_66),
	.A(n_60),
	.B(n_65));
   XNOR2X1 g2048__5115 (.Y(n_65),
	.A(n_58),
	.B(n_62));
   CLKXOR2X1 g2049__7482 (.Y(n_64),
	.A(n_53),
	.B(n_63));
   ADDFX1 g2050__4733 (.CO(n_62),
	.S(n_63),
	.A(n_55),
	.B(n_54),
	.CI(n_59));
   INVXL g2051 (.Y(n_60),
	.A(n_61));
   ADDFX1 g2052__6161 (.CO(n_59),
	.S(n_61),
	.A(n_35),
	.B(n_50),
	.CI(n_52));
   XNOR2X1 g2053__9315 (.Y(n_58),
	.A(n_56),
	.B(n_57));
   XNOR2X1 g2054__9945 (.Y(n_57),
	.A(n_27),
	.B(n_51));
   OAI21XL g2055__2883 (.Y(n_56),
	.A0(n_42),
	.A1(n_49),
	.B0(n_43));
   OAI21XL g2056__2346 (.Y(n_55),
	.A0(n_40),
	.A1(n_49),
	.B0(n_38));
   XNOR2X1 g2057__1666 (.Y(n_54),
	.A(n_44),
	.B(n_49));
   XNOR2X1 g2058__7410 (.Y(n_52),
	.A(n_41),
	.B(n_49));
   XNOR2X1 g2059__6417 (.Y(n_51),
	.A(n_26),
	.B(n_49));
   XNOR2X1 g2060__5477 (.Y(n_53),
	.A(n_37),
	.B(n_49));
   NOR2BX1 g2061__2398 (.Y(n_50),
	.AN(n_37),
	.B(n_49));
   OAI21XL g2062__5107 (.Y(n_49),
	.A0(n_26),
	.A1(n_47),
	.B0(n_48));
   OAI2BB1X1 g2063__6260 (.Y(n_48),
	.A0N(n_26),
	.A1N(n_47),
	.B0(n_27));
   OA21X1 g2064__4319 (.Y(n_47),
	.A0(n_42),
	.A1(n_46),
	.B0(n_43));
   AND2X1 g2065__8428 (.Y(n_46),
	.A(n_45),
	.B(n_38));
   NAND2BXL g2066__5526 (.Y(n_45),
	.AN(n_40),
	.B(n_35));
   XNOR2X1 g2067__6783 (.Y(n_44),
	.A(n_36),
	.B(n_39));
   NAND2BXL g2068__3680 (.Y(n_43),
	.AN(n_39),
	.B(n_36));
   NOR2BX1 g2069__1617 (.Y(n_42),
	.AN(n_39),
	.B(n_36));
   XNOR2X1 g2070__2802 (.Y(n_41),
	.A(n_32),
	.B(n_33));
   NOR2BX1 g2071__1705 (.Y(n_40),
	.AN(n_33),
	.B(n_32));
   OAI211X1 g2072__5122 (.Y(n_39),
	.A0(b[2]),
	.A1(n_7),
	.B0(n_12),
	.C0(n_25));
   NAND2BXL g2073__8246 (.Y(n_38),
	.AN(n_33),
	.B(n_32));
   OAI21XL g2074__7098 (.Y(n_37),
	.A0(n_30),
	.A1(n_31),
	.B0(n_35));
   NAND2XL g2075__6131 (.Y(n_36),
	.A(n_13),
	.B(n_34));
   AOI31X1 g2076__1881 (.Y(n_34),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_1),
	.B0(n_24));
   NAND2XL g2077__5115 (.Y(n_35),
	.A(n_30),
	.B(n_31));
   OAI222XL g2078__7482 (.Y(n_33),
	.A0(b[0]),
	.A1(n_18),
	.B0(n_5),
	.B1(n_17),
	.C0(b[2]),
	.C1(n_12));
   OAI222XL g2079__4733 (.Y(n_32),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_4),
	.B1(n_19),
	.C0(a[2]),
	.C1(n_13));
   INVX1 g2080 (.Y(n_28),
	.A(n_29));
   OAI222XL g2081__6161 (.Y(n_31),
	.A0(b[0]),
	.A1(n_8),
	.B0(n_12),
	.B1(n_9),
	.C0(b[2]),
	.C1(n_16));
   AOI221X1 g2082__9315 (.Y(n_30),
	.A0(n_1),
	.A1(n_15),
	.B0(n_4),
	.B1(n_10),
	.C0(n_21));
   NOR2XL g2083__9945 (.Y(n_29),
	.A(n_22),
	.B(n_23));
   AOI32X1 g2084__2883 (.Y(n_25),
	.A0(b[2]),
	.A1(n_5),
	.A2(n_11),
	.B0(b[3]),
	.B1(n_8));
   OAI22XL g2085__2346 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2086__1666 (.Y(n_27),
	.A0(n_1),
	.A1(n_4),
	.B0(a[1]),
	.B1(n_13),
	.C0(a[0]),
	.C1(n_14));
   OAI222XL g2087__7410 (.Y(n_26),
	.A0(b[1]),
	.A1(n_12),
	.B0(n_0),
	.B1(n_5),
	.C0(b[0]),
	.C1(n_16));
   NOR4X1 g2088__6417 (.Y(n_23),
	.A(a[0]),
	.B(a[3]),
	.C(a[1]),
	.D(a[2]));
   NOR4X1 g2089__5477 (.Y(n_22),
	.A(b[0]),
	.B(b[3]),
	.C(b[1]),
	.D(b[2]));
   NOR2XL g2090__2398 (.Y(n_21),
	.A(n_13),
	.B(n_10));
   AOI21XL g2091__5107 (.Y(n_20),
	.A0(a[2]),
	.A1(a[3]),
	.B0(n_3));
   AOI21XL g2092__6260 (.Y(n_18),
	.A0(b[2]),
	.A1(b[3]),
	.B0(n_2));
   NAND2XL g2093__4319 (.Y(n_17),
	.A(b[2]),
	.B(n_11));
   NAND3XL g2094__8428 (.Y(n_19),
	.A(a[1]),
	.B(a[2]),
	.C(n_6));
   INVXL g2095 (.Y(n_15),
	.A(n_14));
   NAND2XL g2096__5526 (.Y(n_16),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g2097__6783 (.Y(n_14),
	.A(a[1]),
	.B(a[3]));
   NAND2XL g2098__3680 (.Y(n_13),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2099__1617 (.Y(n_12),
	.A(b[0]),
	.B(b[3]));
   INVXL g2100 (.Y(n_9),
	.A(n_8));
   NOR2XL g2101__2802 (.Y(n_11),
	.A(b[3]),
	.B(n_2));
   NAND2XL g2102__1705 (.Y(n_7),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2103__5122 (.Y(n_10),
	.A(a[2]),
	.B(n_3));
   NOR2XL g2104__8246 (.Y(n_8),
	.A(b[1]),
	.B(n_0));
   INVXL g2105 (.Y(n_6),
	.A(a[3]));
   INVX1 g2106 (.Y(n_5),
	.A(b[0]));
   INVX1 g2107 (.Y(n_4),
	.A(a[0]));
   INVXL g2108 (.Y(n_3),
	.A(a[1]));
   INVXL g2109 (.Y(n_2),
	.A(b[1]));
   INVX1 g2110 (.Y(n_1),
	.A(a[2]));
   INVXL g2111 (.Y(n_0),
	.A(b[2]));
endmodule

module bm_stage_1 (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	l1_1, 
	S1_o, 
	S2_o, 
	S3_o);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   output [3:0] l1_1;
   output [3:0] S1_o;
   output [3:0] S2_o;
   output [3:0] S3_o;

   // Internal wires
   wire [3:0] div1;

   gf_divider u_div1 (.a(S2),
	.b(S1),
	.q(div1));
   DFFRHQX1 \l1_1_reg[1]  (.Q(l1_1[1]),
	.D(div1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_1_reg[0]  (.Q(l1_1[0]),
	.D(div1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_1_reg[2]  (.Q(l1_1[2]),
	.D(div1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_1_reg[3]  (.Q(l1_1[3]),
	.D(div1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[1]  (.Q(S3_o[1]),
	.D(S3[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_o_reg[1]  (.Q(S2_o[1]),
	.D(S2[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_o_reg[3]  (.Q(S2_o[3]),
	.D(S2[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[0]  (.Q(S1_o[0]),
	.D(S1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[2]  (.Q(S3_o[2]),
	.D(S3[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[3]  (.Q(S1_o[3]),
	.D(S1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[2]  (.Q(S1_o[2]),
	.D(S1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[3]  (.Q(S3_o[3]),
	.D(S3[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_o_reg[2]  (.Q(S2_o[2]),
	.D(S2[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_o_reg[0]  (.Q(S2_o[0]),
	.D(S2[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[1]  (.Q(S1_o[1]),
	.D(S1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[0]  (.Q(S3_o[0]),
	.D(S3[0]),
	.RN(rst),
	.CK(clk));
endmodule

module gf_multiplier (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__7098 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__6131 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__1881 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__5115 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__7482 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__4733 (.Y(n_74),
	.AN(n_68),
	.B(n_57),
	.C(n_61));
   NAND2XL g1996__6161 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__9315 (.Y(n_70),
	.A0(n_56),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__9945 (.Y(n_71),
	.A0(n_56),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__2883 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__2346 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__1666 (.Y(n_67),
	.A(n_56),
	.B(n_65));
   AOI21XL g2003__7410 (.Y(n_66),
	.A0(n_55),
	.A1(n_57),
	.B0(n_63));
   XNOR2X1 g2004__6417 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__5477 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__2398 (.Y(n_62),
	.A(n_57),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__5107 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__6260 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__4319 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__8428 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__5526 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__6783 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__3680 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI211XL g2017__1617 (.Y(n_52),
	.A0(n_37),
	.A1(n_47),
	.B0(n_38),
	.C0(n_51));
   NOR2XL g2018__2802 (.Y(n_51),
	.A(n_49),
	.B(n_50));
   NAND3BXL g2019__1705 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__5122 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__8246 (.CO(n_47),
	.S(n_48),
	.A(n_43),
	.B(n_44),
	.CI(n_45));
   ADDFX1 g2022__7098 (.CO(n_45),
	.S(n_46),
	.A(n_41),
	.B(n_39),
	.CI(n_36));
   OAI211X1 g2023__6131 (.Y(n_44),
	.A0(n_9),
	.A1(n_34),
	.B0(n_14),
	.C0(n_21));
   OAI211X1 g2024__1881 (.Y(n_43),
	.A0(n_10),
	.A1(n_33),
	.B0(n_16),
	.C0(n_23));
   NOR2BX1 g2025__5115 (.Y(n_42),
	.AN(n_37),
	.B(n_38));
   OAI221X1 g2026__7482 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_16),
	.C0(n_18));
   OAI221X1 g2027__4733 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_14),
	.C0(n_19));
   XNOR2X1 g2028__6161 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__9315 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__9945 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__2883 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__2346 (.Y(n_34),
	.A0(n_4),
	.A1(n_22),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__1666 (.Y(n_33),
	.A0(n_5),
	.A1(n_24),
	.B0(a[0]),
	.B1(n_11));
   AOI221X1 g2034__7410 (.Y(n_35),
	.A0(n_15),
	.A1(n_10),
	.B0(a[3]),
	.B1(n_11),
	.C0(n_20));
   AOI222X1 g2035__6417 (.Y(n_32),
	.A0(n_7),
	.A1(n_15),
	.B0(a[2]),
	.B1(a[0]),
	.C0(a[1]),
	.C1(n_12));
   AOI221X1 g2036__5477 (.Y(n_31),
	.A0(b[2]),
	.A1(b[0]),
	.B0(b[1]),
	.B1(n_13),
	.C0(n_25));
   AOI221X1 g2037__2398 (.Y(n_30),
	.A0(b[3]),
	.A1(n_17),
	.B0(n_4),
	.B1(n_8),
	.C0(n_26));
   OAI33X1 g2038__5107 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[3]),
	.B1(a[2]),
	.B2(n_18));
   AOI31X1 g2039__6260 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_12));
   AOI31X1 g2040__4319 (.Y(n_27),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_0),
	.B0(n_13));
   NOR2XL g2041__8428 (.Y(n_26),
	.A(n_14),
	.B(n_8));
   NOR2XL g2042__5526 (.Y(n_25),
	.A(b[1]),
	.B(n_14));
   NOR2XL g2043__6783 (.Y(n_24),
	.A(a[3]),
	.B(n_11));
   NAND2XL g2044__3680 (.Y(n_23),
	.A(a[3]),
	.B(n_10));
   NOR2XL g2045__1617 (.Y(n_22),
	.A(b[3]),
	.B(n_17));
   NAND2XL g2046__2802 (.Y(n_21),
	.A(b[3]),
	.B(n_9));
   NOR2XL g2047__1705 (.Y(n_20),
	.A(a[0]),
	.B(n_10));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   NAND2XL g2049__5122 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2050__8246 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2051__7098 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NAND2XL g2052__6131 (.Y(n_16),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2053__1881 (.Y(n_14),
	.A(b[0]),
	.B(b[3]));
   INVXL g2054 (.Y(n_8),
	.A(n_9));
   NOR2XL g2055__5115 (.Y(n_13),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__7482 (.Y(n_12),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__4733 (.Y(n_11),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__6161 (.Y(n_10),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__9315 (.Y(n_9),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVXL g2061 (.Y(n_6),
	.A(a[3]));
   INVXL g2062 (.Y(n_5),
	.A(a[0]));
   INVX1 g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module xor_4 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__9945 (.Y(y[3]),
	.A(b[3]),
	.B(a[3]));
   CLKXOR2X1 g38__2883 (.Y(y[1]),
	.A(b[1]),
	.B(a[1]));
   CLKXOR2X1 g39__2346 (.Y(y[0]),
	.A(b[0]),
	.B(a[0]));
   CLKXOR2X1 g40__1666 (.Y(y[2]),
	.A(b[2]),
	.B(a[2]));
endmodule

module bm_stage_2 (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	l1_1, 
	l1_2, 
	l2_2, 
	S1_o);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   input [3:0] l1_1;
   output [3:0] l1_2;
   output [3:0] l2_2;
   output [3:0] S1_o;

   // Internal wires
   wire [3:0] mult1;
   wire [3:0] xor1;

   gf_multiplier u_mult1 (.a(l1_1),
	.b(S2),
	.p(mult1));
   xor_4 u_xor1 (.a(mult1),
	.b(S3),
	.y(xor1));
   DFFRHQX1 \l2_2_reg[1]  (.Q(l2_2[1]),
	.D(xor1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_2_reg[2]  (.Q(l2_2[2]),
	.D(xor1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_2_reg[3]  (.Q(l2_2[3]),
	.D(xor1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_2_reg[0]  (.Q(l2_2[0]),
	.D(xor1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[3]  (.Q(l1_2[3]),
	.D(l1_1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[2]  (.Q(l1_2[2]),
	.D(l1_1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[1]  (.Q(l1_2[1]),
	.D(l1_1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[0]  (.Q(l1_2[0]),
	.D(l1_1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[1]  (.Q(S1_o[1]),
	.D(S1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[0]  (.Q(S1_o[0]),
	.D(S1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[2]  (.Q(S1_o[2]),
	.D(S1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[3]  (.Q(S1_o[3]),
	.D(S1[3]),
	.RN(rst),
	.CK(clk));
endmodule

module gf_divider_24 (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;

   NAND3BXL g2032__7410 (.Y(q[2]),
	.AN(n_77),
	.B(n_76),
	.C(n_67));
   OAI211X1 g2033__6417 (.Y(q[0]),
	.A0(n_66),
	.A1(n_68),
	.B0(n_73),
	.C0(n_67));
   OAI211X1 g2034__5477 (.Y(q[1]),
	.A0(n_65),
	.A1(n_68),
	.B0(n_76),
	.C0(n_72));
   OAI211X1 g2035__2398 (.Y(q[3]),
	.A0(n_28),
	.A1(n_70),
	.B0(n_74),
	.C0(n_67));
   OAI22XL g2036__5107 (.Y(n_77),
	.A0(n_53),
	.A1(n_75),
	.B0(n_61),
	.B1(n_68));
   NOR2XL g2037__6260 (.Y(n_75),
	.A(n_69),
	.B(n_71));
   NAND2XL g2038__4319 (.Y(n_76),
	.A(n_61),
	.B(n_69));
   OAI21XL g2039__8428 (.Y(n_74),
	.A0(n_53),
	.A1(n_63),
	.B0(n_71));
   NAND3BXL g2040__5526 (.Y(n_73),
	.AN(n_53),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2041__6783 (.Y(n_72),
	.AN(n_61),
	.B(n_29),
	.C(n_64));
   NAND2XL g2042__3680 (.Y(n_70),
	.A(n_65),
	.B(n_64));
   NOR2XL g2043__1617 (.Y(n_71),
	.A(n_28),
	.B(n_66));
   NOR3BXL g2044__2802 (.Y(n_69),
	.AN(n_65),
	.B(n_28),
	.C(n_63));
   NAND3BXL g2045__1705 (.Y(n_68),
	.AN(n_28),
	.B(n_53),
	.C(n_63));
   NAND4XL g2046__5122 (.Y(n_67),
	.A(n_29),
	.B(n_60),
	.C(n_63),
	.D(n_65));
   OR2X1 g2047__8246 (.Y(n_66),
	.A(n_60),
	.B(n_65));
   XNOR2X1 g2048__7098 (.Y(n_65),
	.A(n_58),
	.B(n_62));
   CLKXOR2X1 g2049__6131 (.Y(n_64),
	.A(n_53),
	.B(n_63));
   ADDFX1 g2050__1881 (.CO(n_62),
	.S(n_63),
	.A(n_55),
	.B(n_54),
	.CI(n_59));
   INVXL g2051 (.Y(n_60),
	.A(n_61));
   ADDFX1 g2052__5115 (.CO(n_59),
	.S(n_61),
	.A(n_35),
	.B(n_50),
	.CI(n_52));
   XNOR2X1 g2053__7482 (.Y(n_58),
	.A(n_56),
	.B(n_57));
   XNOR2X1 g2054__4733 (.Y(n_57),
	.A(n_27),
	.B(n_51));
   OAI21XL g2055__6161 (.Y(n_56),
	.A0(n_42),
	.A1(n_49),
	.B0(n_43));
   OAI21XL g2056__9315 (.Y(n_55),
	.A0(n_40),
	.A1(n_49),
	.B0(n_38));
   XNOR2X1 g2057__9945 (.Y(n_54),
	.A(n_44),
	.B(n_49));
   XNOR2X1 g2058__2883 (.Y(n_52),
	.A(n_41),
	.B(n_49));
   XNOR2X1 g2059__2346 (.Y(n_51),
	.A(n_26),
	.B(n_49));
   XNOR2X1 g2060__1666 (.Y(n_53),
	.A(n_37),
	.B(n_49));
   NOR2BX1 g2061__7410 (.Y(n_50),
	.AN(n_37),
	.B(n_49));
   OAI21XL g2062__6417 (.Y(n_49),
	.A0(n_26),
	.A1(n_47),
	.B0(n_48));
   OAI2BB1X1 g2063__5477 (.Y(n_48),
	.A0N(n_26),
	.A1N(n_47),
	.B0(n_27));
   OA21X1 g2064__2398 (.Y(n_47),
	.A0(n_42),
	.A1(n_46),
	.B0(n_43));
   AND2X1 g2065__5107 (.Y(n_46),
	.A(n_45),
	.B(n_38));
   NAND2BXL g2066__6260 (.Y(n_45),
	.AN(n_40),
	.B(n_35));
   XNOR2X1 g2067__4319 (.Y(n_44),
	.A(n_36),
	.B(n_39));
   NAND2BXL g2068__8428 (.Y(n_43),
	.AN(n_39),
	.B(n_36));
   NOR2BX1 g2069__5526 (.Y(n_42),
	.AN(n_39),
	.B(n_36));
   XNOR2X1 g2070__6783 (.Y(n_41),
	.A(n_32),
	.B(n_33));
   NOR2BX1 g2071__3680 (.Y(n_40),
	.AN(n_33),
	.B(n_32));
   OAI211X1 g2072__1617 (.Y(n_39),
	.A0(b[2]),
	.A1(n_7),
	.B0(n_12),
	.C0(n_25));
   NAND2BXL g2073__2802 (.Y(n_38),
	.AN(n_33),
	.B(n_32));
   OAI21XL g2074__1705 (.Y(n_37),
	.A0(n_30),
	.A1(n_31),
	.B0(n_35));
   NAND2XL g2075__5122 (.Y(n_36),
	.A(n_13),
	.B(n_34));
   AOI31X1 g2076__8246 (.Y(n_34),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_1),
	.B0(n_24));
   NAND2XL g2077__7098 (.Y(n_35),
	.A(n_30),
	.B(n_31));
   OAI222XL g2078__6131 (.Y(n_33),
	.A0(b[0]),
	.A1(n_18),
	.B0(n_5),
	.B1(n_17),
	.C0(b[2]),
	.C1(n_12));
   OAI222XL g2079__1881 (.Y(n_32),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_4),
	.B1(n_19),
	.C0(a[2]),
	.C1(n_13));
   INVX1 g2080 (.Y(n_28),
	.A(n_29));
   OAI222XL g2081__5115 (.Y(n_31),
	.A0(b[0]),
	.A1(n_8),
	.B0(n_12),
	.B1(n_9),
	.C0(b[2]),
	.C1(n_16));
   AOI221X1 g2082__7482 (.Y(n_30),
	.A0(n_1),
	.A1(n_15),
	.B0(n_4),
	.B1(n_10),
	.C0(n_21));
   NOR2XL g2083__4733 (.Y(n_29),
	.A(n_22),
	.B(n_23));
   AOI32X1 g2084__6161 (.Y(n_25),
	.A0(b[2]),
	.A1(n_5),
	.A2(n_11),
	.B0(b[3]),
	.B1(n_8));
   OAI22XL g2085__9315 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2086__9945 (.Y(n_27),
	.A0(n_1),
	.A1(n_4),
	.B0(a[1]),
	.B1(n_13),
	.C0(a[0]),
	.C1(n_14));
   OAI222XL g2087__2883 (.Y(n_26),
	.A0(n_0),
	.A1(n_5),
	.B0(b[1]),
	.B1(n_12),
	.C0(b[0]),
	.C1(n_16));
   NOR4X1 g2088__2346 (.Y(n_23),
	.A(a[3]),
	.B(a[1]),
	.C(a[2]),
	.D(a[0]));
   NOR4X1 g2089__1666 (.Y(n_22),
	.A(b[3]),
	.B(b[1]),
	.C(b[2]),
	.D(b[0]));
   NOR2XL g2090__7410 (.Y(n_21),
	.A(n_13),
	.B(n_10));
   AOI21XL g2091__6417 (.Y(n_20),
	.A0(a[3]),
	.A1(a[2]),
	.B0(n_3));
   AOI21XL g2092__5477 (.Y(n_18),
	.A0(b[3]),
	.A1(b[2]),
	.B0(n_2));
   NAND2XL g2093__2398 (.Y(n_17),
	.A(b[2]),
	.B(n_11));
   NAND3XL g2094__5107 (.Y(n_19),
	.A(a[2]),
	.B(a[1]),
	.C(n_6));
   INVXL g2095 (.Y(n_15),
	.A(n_14));
   NAND2XL g2096__6260 (.Y(n_16),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g2097__4319 (.Y(n_14),
	.A(a[1]),
	.B(a[3]));
   NAND2XL g2098__8428 (.Y(n_13),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2099__5526 (.Y(n_12),
	.A(b[0]),
	.B(b[3]));
   INVXL g2100 (.Y(n_9),
	.A(n_8));
   NOR2XL g2101__6783 (.Y(n_11),
	.A(b[3]),
	.B(n_2));
   NAND2XL g2102__3680 (.Y(n_7),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2103__1617 (.Y(n_10),
	.A(a[2]),
	.B(n_3));
   NOR2XL g2104__2802 (.Y(n_8),
	.A(b[1]),
	.B(n_0));
   INVXL g2105 (.Y(n_6),
	.A(a[3]));
   INVX1 g2106 (.Y(n_5),
	.A(b[0]));
   INVX1 g2107 (.Y(n_4),
	.A(a[0]));
   INVXL g2108 (.Y(n_3),
	.A(a[1]));
   INVXL g2109 (.Y(n_2),
	.A(b[1]));
   INVX1 g2110 (.Y(n_1),
	.A(a[2]));
   INVXL g2111 (.Y(n_0),
	.A(b[2]));
endmodule

module bm_stage_3 (
	clk, 
	rst, 
	S1, 
	l1_2, 
	l2_2, 
	l1, 
	l2);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] l1_2;
   input [3:0] l2_2;
   output [3:0] l1;
   output [3:0] l2;

   // Internal wires
   wire [3:0] div1;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;

   gf_divider_24 u_div1 (.a(l2_2),
	.b(S1),
	.q(div1));
   DFFRX2 \l2_reg[2]  (.Q(l2[2]),
	.QN(UNCONNECTED),
	.D(div1[2]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l2_reg[3]  (.Q(l2[3]),
	.QN(UNCONNECTED0),
	.D(div1[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l2_reg[1]  (.Q(l2[1]),
	.QN(UNCONNECTED1),
	.D(div1[1]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l2_reg[0]  (.Q(l2[0]),
	.QN(UNCONNECTED2),
	.D(div1[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[3]  (.Q(l1[3]),
	.QN(UNCONNECTED3),
	.D(l1_2[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[2]  (.Q(l1[2]),
	.QN(UNCONNECTED4),
	.D(l1_2[2]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[0]  (.Q(l1[0]),
	.QN(UNCONNECTED5),
	.D(l1_2[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[1]  (.Q(l1[1]),
	.QN(UNCONNECTED6),
	.D(l1_2[1]),
	.RN(rst),
	.CK(clk));
endmodule

module bch_bm_block_p (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	lambda1, 
	lambda2);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   output [3:0] lambda1;
   output [3:0] lambda2;

   // Internal wires
   wire [3:0] l1_1;
   wire [3:0] S1_o;
   wire [3:0] S2_o;
   wire [3:0] S3_o;
   wire [3:0] l1_2;
   wire [3:0] l2_2;
   wire [3:0] S1_o2;

   bm_stage_1 s1 (.clk(clk),
	.rst(rst),
	.S1(S1),
	.S2(S2),
	.S3(S3),
	.l1_1(l1_1),
	.S1_o(S1_o),
	.S2_o(S2_o),
	.S3_o(S3_o));
   bm_stage_2 s2 (.clk(clk),
	.rst(rst),
	.S1(S1_o),
	.S2(S2_o),
	.S3(S3_o),
	.l1_1(l1_1),
	.l1_2(l1_2),
	.l2_2(l2_2),
	.S1_o(S1_o2));
   bm_stage_3 s3 (.clk(clk),
	.rst(rst),
	.S1(S1_o2),
	.l1_2(l1_2),
	.l2_2(l2_2),
	.l1(lambda1),
	.l2(lambda2));
endmodule

