/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Oct  9 10:48:33 2025
#  Design:            bch_31_syndrome
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_31_syndrome/bch_31_syndrome_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct  8 2025 10:37:06 -03 (Oct  8 2025 13:37:06 UTC)
// Verification Directory fv/bch_31_syndrome 
module bch_31_syndrome (
	codeword, 
	S1, 
	S2, 
	S3, 
	S4);
   input [30:0] codeword;
   output [4:0] S1;
   output [4:0] S2;
   output [4:0] S3;
   output [4:0] S4;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_23;
   wire n_24;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_70;
   wire n_71;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_136;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_144;
   wire n_147;
   wire n_150;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;

   assign S4[1] = S2[3] ;
   assign S4[4] = S2[2] ;
   assign S2[1] = S1[3] ;
   assign S2[4] = S1[2] ;

   XNOR2X4 g3506__2398 (.Y(S1[2]),
	.A(n_37),
	.B(n_150));
   XNOR2X2 g3505__5107 (.Y(S3[0]),
	.A(n_139),
	.B(n_147));
   XNOR2X2 g3511__6260 (.Y(S3[1]),
	.A(n_42),
	.B(n_144));
   XNOR2X1 g3508__4319 (.Y(n_150),
	.A(n_111),
	.B(n_140));
   XNOR2X2 g3509__8428 (.Y(S3[2]),
	.A(n_57),
	.B(n_136));
   XNOR2X2 g3510__5526 (.Y(S4[0]),
	.A(n_38),
	.B(n_133));
   XNOR2X1 g3507__6783 (.Y(n_147),
	.A(n_10),
	.B(n_138));
   XNOR2X2 g3516__3680 (.Y(S1[1]),
	.A(n_115),
	.B(n_132));
   XNOR2X2 g3512__1617 (.Y(S1[0]),
	.A(n_108),
	.B(n_128));
   XNOR2X1 g3526__2802 (.Y(n_144),
	.A(n_49),
	.B(n_191));
   XNOR2X4 g3523__1705 (.Y(S2[3]),
	.A(n_92),
	.B(n_131));
   XNOR2X4 g3525__5122 (.Y(S1[3]),
	.A(n_94),
	.B(n_124));
   XNOR2X2 g3522__8246 (.Y(S2[0]),
	.A(n_86),
	.B(n_126));
   XNOR2X2 g3515__7098 (.Y(S3[3]),
	.A(n_80),
	.B(n_127));
   XNOR2X2 g3514__6131 (.Y(S3[4]),
	.A(n_87),
	.B(n_130));
   XNOR2X1 g3519__1881 (.Y(n_140),
	.A(n_139),
	.B(n_125));
   XNOR2X1 g3518__5115 (.Y(n_138),
	.A(n_104),
	.B(n_120));
   XNOR2X2 g3521__7482 (.Y(S1[4]),
	.A(n_105),
	.B(n_119));
   XNOR2X4 g3527__4733 (.Y(S2[2]),
	.A(n_90),
	.B(n_116));
   XNOR2X1 g3517__6161 (.Y(n_136),
	.A(n_189),
	.B(n_121));
   XNOR2X2 g3520__9315 (.Y(S4[2]),
	.A(n_106),
	.B(n_123));
   XNOR2X2 g3513__9945 (.Y(S4[3]),
	.A(n_81),
	.B(n_122));
   XNOR2X1 g3524__2883 (.Y(n_133),
	.A(n_66),
	.B(n_118));
   XNOR2X1 g3528__2346 (.Y(n_132),
	.A(n_188),
	.B(n_48));
   XNOR2X1 g3536__1666 (.Y(n_131),
	.A(n_83),
	.B(n_110));
   XNOR2X1 g3534__7410 (.Y(n_130),
	.A(n_62),
	.B(n_112));
   XNOR2X1 g3537__5477 (.Y(n_128),
	.A(n_71),
	.B(n_97));
   XNOR2X1 g3540__2398 (.Y(n_127),
	.A(n_12),
	.B(n_99));
   XNOR2X1 g3539__5107 (.Y(n_126),
	.A(n_103),
	.B(n_89));
   XNOR2X1 g3538__6260 (.Y(n_125),
	.A(n_63),
	.B(n_101));
   XNOR2X1 g3541__4319 (.Y(n_124),
	.A(n_84),
	.B(n_192));
   XNOR2X1 g3529__8428 (.Y(n_123),
	.A(n_96),
	.B(n_79));
   XNOR2X1 g3533__5526 (.Y(n_122),
	.A(n_68),
	.B(n_93));
   XNOR2X1 g3535__6783 (.Y(n_121),
	.A(n_113),
	.B(n_117));
   XNOR2X1 g3542__3680 (.Y(n_120),
	.A(n_98),
	.B(n_78));
   XNOR2X1 g3531__1617 (.Y(n_119),
	.A(n_30),
	.B(n_74));
   XNOR2X1 g3530__2802 (.Y(n_118),
	.A(n_88),
	.B(n_117));
   XNOR2X1 g3543__1705 (.Y(n_116),
	.A(n_28),
	.B(n_76));
   XNOR2X1 g3553__5122 (.Y(n_115),
	.A(n_193),
	.B(n_36));
   XNOR2X1 g3572__7098 (.Y(n_112),
	.A(n_111),
	.B(n_100));
   XNOR2X1 g3544__6131 (.Y(n_110),
	.A(n_19),
	.B(n_109));
   XNOR2X1 g3568__1881 (.Y(n_108),
	.A(n_190),
	.B(n_85));
   XNOR2X1 g3555__7482 (.Y(n_106),
	.A(n_67),
	.B(n_8));
   XNOR2X1 g3554__4733 (.Y(n_105),
	.A(n_91),
	.B(n_104));
   XNOR2X1 g3556__6161 (.Y(n_103),
	.A(n_9),
	.B(n_109));
   XNOR2X1 g3560__9315 (.Y(n_101),
	.A(n_21),
	.B(n_100));
   XNOR2X1 g3561__9945 (.Y(n_99),
	.A(n_98),
	.B(n_100));
   XNOR2X1 g3562__2883 (.Y(n_97),
	.A(n_82),
	.B(n_100));
   XNOR2X1 g3546__2346 (.Y(n_96),
	.A(n_7),
	.B(n_95));
   XNOR2X1 g3570__1666 (.Y(n_94),
	.A(n_1),
	.B(n_31));
   XNOR2X1 g3545__7410 (.Y(n_93),
	.A(n_2),
	.B(n_95));
   XNOR2X1 g3571__6417 (.Y(n_92),
	.A(n_15),
	.B(n_91));
   XNOR2X1 g3569__5477 (.Y(n_90),
	.A(n_4),
	.B(n_46));
   XNOR2X1 g3548__2398 (.Y(n_89),
	.A(n_43),
	.B(n_88));
   XNOR2X1 g3547__5107 (.Y(n_87),
	.A(n_47),
	.B(n_50));
   XNOR2X1 g3573__6260 (.Y(n_117),
	.A(n_39),
	.B(n_75));
   XNOR2X1 g3567__4319 (.Y(n_86),
	.A(n_85),
	.B(n_34));
   XNOR2X1 g3550__8428 (.Y(n_84),
	.A(n_73),
	.B(n_88));
   XNOR2X1 g3552__5526 (.Y(n_83),
	.A(n_82),
	.B(n_77));
   XNOR2X1 g3557__6783 (.Y(n_81),
	.A(n_52),
	.B(n_40));
   XNOR2X1 g3559__3680 (.Y(n_80),
	.A(n_27),
	.B(n_33));
   XNOR2X1 g3563__1617 (.Y(n_79),
	.A(n_88),
	.B(n_111));
   XNOR2X1 g3564__2802 (.Y(n_78),
	.A(n_53),
	.B(n_77));
   XNOR2X1 g3566__1705 (.Y(n_76),
	.A(n_56),
	.B(n_75));
   XNOR2X1 g3549__5122 (.Y(n_74),
	.A(n_73),
	.B(n_139));
   XNOR2X1 g3577__8246 (.Y(n_71),
	.A(n_11),
	.B(n_70));
   OAI22XL g3582__6131 (.Y(n_68),
	.A0(n_60),
	.A1(n_70),
	.B0(n_82),
	.B1(n_113));
   AOI22XL g3584__1881 (.Y(n_67),
	.A0(codeword[11]),
	.A1(n_73),
	.B0(n_23),
	.B1(n_61));
   XNOR2X1 g3583__5115 (.Y(n_66),
	.A(n_64),
	.B(codeword[0]));
   XNOR2X1 g3585__7482 (.Y(n_104),
	.A(n_64),
	.B(codeword[28]));
   MX2X1 g3590__4733 (.Y(n_109),
	.A(n_63),
	.B(n_58),
	.S0(codeword[27]));
   AOI22XL g3595__6161 (.Y(n_62),
	.A0(n_61),
	.A1(n_82),
	.B0(n_60),
	.B1(n_73));
   XNOR2X1 g3607__9945 (.Y(n_57),
	.A(n_24),
	.B(n_56));
   XNOR2X1 g3591__2346 (.Y(n_100),
	.A(n_64),
	.B(n_54));
   XNOR2X1 g3576__1666 (.Y(n_53),
	.A(codeword[0]),
	.B(n_35));
   XNOR2X1 g3578__7410 (.Y(n_52),
	.A(codeword[19]),
	.B(n_51));
   XNOR2X1 g3579__6417 (.Y(n_50),
	.A(codeword[3]),
	.B(n_63));
   XNOR2X1 g3580__5477 (.Y(n_49),
	.A(codeword[26]),
	.B(n_54));
   XNOR2X1 g3597__2398 (.Y(n_48),
	.A(n_41),
	.B(n_47));
   CLKXOR2X1 g3593__5107 (.Y(n_46),
	.A(n_45),
	.B(n_44));
   XNOR2X1 g3587__6260 (.Y(n_77),
	.A(codeword[20]),
	.B(n_45));
   XNOR2X1 g3588__4319 (.Y(n_111),
	.A(codeword[19]),
	.B(n_44));
   XNOR2X1 g3589__8428 (.Y(n_95),
	.A(codeword[6]),
	.B(n_32));
   XNOR2X1 g3586__5526 (.Y(n_139),
	.A(codeword[14]),
	.B(n_43));
   XNOR2X1 g3592__6783 (.Y(n_88),
	.A(codeword[21]),
	.B(n_98));
   XNOR2X1 g3604__3680 (.Y(n_42),
	.A(n_41),
	.B(n_29));
   XNOR2X1 g3599__1617 (.Y(n_40),
	.A(n_39),
	.B(n_43));
   XNOR2X1 g3600__2802 (.Y(n_38),
	.A(n_6),
	.B(n_37));
   XNOR2X1 g3601__1705 (.Y(n_36),
	.A(n_45),
	.B(n_35));
   XNOR2X1 g3602__5122 (.Y(n_34),
	.A(n_39),
	.B(n_54));
   XNOR2X1 g3603__8246 (.Y(n_33),
	.A(n_32),
	.B(n_56));
   XNOR2X1 g3598__7098 (.Y(n_31),
	.A(n_43),
	.B(n_51));
   XNOR2X1 g3605__6131 (.Y(n_30),
	.A(n_5),
	.B(n_29));
   XNOR2X1 g3606__1881 (.Y(n_28),
	.A(n_3),
	.B(n_29));
   XNOR2X1 g3608__5115 (.Y(n_27),
	.A(n_13),
	.B(n_14));
   XNOR2X1 g3610__7482 (.Y(n_75),
	.A(n_51),
	.B(n_35));
   XNOR2X1 g3609__4733 (.Y(n_91),
	.A(n_39),
	.B(n_44));
   INVXL g3612 (.Y(n_70),
	.A(n_113));
   AOI22XL g3638__6161 (.Y(n_24),
	.A0(codeword[15]),
	.A1(n_20),
	.B0(codeword[12]),
	.B1(n_16));
   INVXL g3634 (.Y(n_60),
	.A(n_82));
   INVXL g3636 (.Y(n_61),
	.A(n_73));
   OAI22XL g3631__9315 (.Y(n_113),
	.A0(codeword[11]),
	.A1(n_18),
	.B0(codeword[17]),
	.B1(n_23));
   AOI22XL g3617__9945 (.Y(n_21),
	.A0(codeword[12]),
	.A1(n_23),
	.B0(codeword[11]),
	.B1(n_20));
   AOI22XL g3641__2883 (.Y(n_19),
	.A0(codeword[26]),
	.A1(n_18),
	.B0(codeword[17]),
	.B1(n_17));
   INVXL g3613 (.Y(n_58),
	.A(n_63));
   OAI22XL g3655__2346 (.Y(n_64),
	.A0(codeword[15]),
	.A1(n_17),
	.B0(codeword[26]),
	.B1(n_16));
   XNOR2X1 g3619__1666 (.Y(n_15),
	.A(codeword[3]),
	.B(codeword[8]));
   XNOR2X1 g3620__7410 (.Y(n_14),
	.A(codeword[17]),
	.B(codeword[20]));
   XNOR2X1 g3642__6417 (.Y(n_13),
	.A(codeword[4]),
	.B(codeword[7]));
   XNOR2X1 g3637__5477 (.Y(n_12),
	.A(codeword[1]),
	.B(codeword[18]));
   XNOR2X1 g3621__2398 (.Y(n_11),
	.A(codeword[22]),
	.B(codeword[23]));
   XNOR2X1 g3622__5107 (.Y(n_10),
	.A(codeword[5]),
	.B(codeword[16]));
   XNOR2X1 g3623__6260 (.Y(n_9),
	.A(codeword[7]),
	.B(codeword[11]));
   XNOR2X1 g3624__4319 (.Y(n_8),
	.A(codeword[5]),
	.B(codeword[27]));
   XNOR2X1 g3625__8428 (.Y(n_7),
	.A(codeword[26]),
	.B(codeword[28]));
   XNOR2X1 g3626__5526 (.Y(n_6),
	.A(codeword[12]),
	.B(codeword[22]));
   XNOR2X1 g3627__6783 (.Y(n_32),
	.A(codeword[2]),
	.B(codeword[3]));
   XNOR2X1 g3643__3680 (.Y(n_85),
	.A(codeword[0]),
	.B(codeword[18]));
   XNOR2X1 g3644__1617 (.Y(n_47),
	.A(codeword[24]),
	.B(codeword[30]));
   XNOR2X1 g3648__2802 (.Y(n_56),
	.A(codeword[13]),
	.B(codeword[25]));
   XNOR2X1 g3630__1705 (.Y(n_54),
	.A(codeword[5]),
	.B(codeword[8]));
   XNOR2X1 g3632__5122 (.Y(n_63),
	.A(codeword[23]),
	.B(codeword[28]));
   XNOR2X1 g3656__8246 (.Y(n_73),
	.A(codeword[16]),
	.B(codeword[25]));
   XNOR2X1 g3614__7098 (.Y(n_5),
	.A(codeword[9]),
	.B(codeword[17]));
   XNOR2X1 g3615__6131 (.Y(n_4),
	.A(codeword[1]),
	.B(codeword[11]));
   XNOR2X1 g3618__1881 (.Y(n_3),
	.A(codeword[4]),
	.B(codeword[23]));
   XNOR2X1 g3640__5115 (.Y(n_2),
	.A(codeword[5]),
	.B(codeword[15]));
   XNOR2X1 g3616__7482 (.Y(n_1),
	.A(codeword[8]),
	.B(codeword[23]));
   XNOR2X1 g3639__4733 (.Y(n_0),
	.A(codeword[3]),
	.B(codeword[15]));
   XNOR2X1 g3645__6161 (.Y(n_37),
	.A(codeword[2]),
	.B(codeword[20]));
   XNOR2X1 g3628__9315 (.Y(n_41),
	.A(codeword[9]),
	.B(codeword[16]));
   XNOR2X1 g3629__9945 (.Y(n_45),
	.A(codeword[6]),
	.B(codeword[12]));
   XNOR2X1 g3649__2883 (.Y(n_29),
	.A(codeword[10]),
	.B(codeword[21]));
   XNOR2X1 g3646__2346 (.Y(n_44),
	.A(codeword[7]),
	.B(codeword[22]));
   XNOR2X1 g3647__1666 (.Y(n_35),
	.A(codeword[18]),
	.B(codeword[19]));
   XNOR2X1 g3650__7410 (.Y(n_98),
	.A(codeword[9]),
	.B(codeword[29]));
   XNOR2X1 g3652__6417 (.Y(n_39),
	.A(codeword[4]),
	.B(codeword[30]));
   XNOR2X1 g3654__5477 (.Y(n_43),
	.A(codeword[13]),
	.B(codeword[24]));
   XNOR2X1 g3653__2398 (.Y(n_82),
	.A(codeword[10]),
	.B(codeword[29]));
   XNOR2X1 g3651__5107 (.Y(n_51),
	.A(codeword[14]),
	.B(codeword[27]));
   INVXL g3659 (.Y(n_16),
	.A(codeword[15]));
   INVXL g3660 (.Y(n_23),
	.A(codeword[11]));
   INVXL g3657 (.Y(n_17),
	.A(codeword[26]));
   INVXL g3661 (.Y(n_20),
	.A(codeword[12]));
   INVXL g3658 (.Y(n_18),
	.A(codeword[17]));
   MXI2XL g2 (.Y(n_188),
	.A(n_70),
	.B(n_113),
	.S0(n_109));
   MXI2XL g3662 (.Y(n_189),
	.A(n_63),
	.B(n_58),
	.S0(n_54));
   MXI2XL g3663 (.Y(n_190),
	.A(n_73),
	.B(n_61),
	.S0(n_51));
   XOR2XL g3664 (.Y(n_191),
	.A(n_95),
	.B(n_117));
   XOR2XL g3665 (.Y(n_192),
	.A(n_0),
	.B(n_77));
   XOR2XL g3666 (.Y(n_193),
	.A(codeword[1]),
	.B(n_64));
endmodule

