/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Oct  9 11:15:54 2025
#  Design:            bch_syndrome_block
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_syndrome_block/bch_syndrome_block_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 22 2025 10:59:03 -03 (Sep 22 2025 13:59:03 UTC)
// Verification Directory fv/bch_syndrome_block 
module bch_syndrome_block (
	codeword, 
	S1, 
	S2, 
	S3);
   input [14:0] codeword;
   output [3:0] S1;
   output [3:0] S2;
   output [3:0] S3;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_31;
   wire n_32;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_39;
   wire n_61;
   wire n_62;

   assign S2[1] = S1[2] ;
   assign S2[3] = S1[3] ;

   XNOR2X2 g957__2398 (.Y(S3[3]),
	.A(n_62),
	.B(n_32));
   XNOR2X4 g960__5107 (.Y(S1[2]),
	.A(n_10),
	.B(n_39));
   XNOR2X2 g959__6260 (.Y(S2[0]),
	.A(n_15),
	.B(n_36));
   XNOR2X2 g958__4319 (.Y(S3[0]),
	.A(n_24),
	.B(n_34));
   XNOR2X1 g969__5526 (.Y(n_39),
	.A(n_35),
	.B(n_25));
   XNOR2X4 g971__6783 (.Y(S1[3]),
	.A(n_13),
	.B(n_27));
   XNOR2X2 g968__3680 (.Y(S1[1]),
	.A(n_23),
	.B(n_17));
   XNOR2X2 g967__1617 (.Y(S2[2]),
	.A(n_61),
	.B(n_21));
   XNOR2X1 g963__2802 (.Y(n_36),
	.A(n_6),
	.B(n_35));
   XNOR2X1 g965__1705 (.Y(n_34),
	.A(codeword[0]),
	.B(n_31));
   XNOR2X2 g966__5122 (.Y(S1[0]),
	.A(n_11),
	.B(n_9));
   XNOR2X1 g964__8246 (.Y(n_32),
	.A(n_35),
	.B(n_31));
   XNOR2X2 g962__7098 (.Y(S3[2]),
	.A(n_31),
	.B(n_12));
   XNOR2X2 g961__6131 (.Y(S3[1]),
	.A(n_31),
	.B(n_16));
   MX2X1 g974__5115 (.Y(n_25),
	.A(n_24),
	.B(n_22),
	.S0(codeword[12]));
   OAI22XL g982__7482 (.Y(n_23),
	.A0(n_22),
	.A1(n_20),
	.B0(n_19),
	.B1(n_24));
   XNOR2X1 g983__4733 (.Y(n_21),
	.A(n_3),
	.B(n_22));
   MX2X1 g986__6161 (.Y(n_27),
	.A(n_20),
	.B(n_19),
	.S0(n_18));
   XNOR2X1 g980__9315 (.Y(n_17),
	.A(n_4),
	.B(n_0));
   XNOR2X1 g973__9945 (.Y(n_16),
	.A(codeword[8]),
	.B(n_18));
   XNOR2X1 g975__2883 (.Y(n_15),
	.A(codeword[0]),
	.B(n_14));
   XNOR2X1 g978__2346 (.Y(n_31),
	.A(n_14),
	.B(codeword[9]));
   XNOR2X1 g985__1666 (.Y(n_13),
	.A(n_5),
	.B(n_8));
   XNOR2X1 g976__7410 (.Y(n_12),
	.A(codeword[2]),
	.B(n_20));
   XNOR2X1 g984__6417 (.Y(n_11),
	.A(n_2),
	.B(n_10));
   XNOR2X1 g972__5477 (.Y(n_9),
	.A(n_20),
	.B(n_14));
   XNOR2X1 g977__2398 (.Y(n_35),
	.A(codeword[2]),
	.B(n_8));
   INVXL g993 (.Y(n_19),
	.A(n_20));
   INVXL g995 (.Y(n_22),
	.A(n_24));
   XNOR2X1 g996__5107 (.Y(n_6),
	.A(codeword[5]),
	.B(codeword[7]));
   XNOR2X1 g991__6260 (.Y(n_5),
	.A(codeword[9]),
	.B(codeword[14]));
   XNOR2X1 g990__4319 (.Y(n_4),
	.A(codeword[1]),
	.B(codeword[4]));
   XNOR2X1 g992__8428 (.Y(n_10),
	.A(codeword[8]),
	.B(codeword[13]));
   CLKXOR2X1 g1001__5526 (.Y(n_14),
	.A(codeword[4]),
	.B(codeword[14]));
   XNOR2X1 g1000__6783 (.Y(n_20),
	.A(codeword[7]),
	.B(codeword[12]));
   XNOR2X1 g988__3680 (.Y(n_3),
	.A(codeword[1]),
	.B(codeword[6]));
   XNOR2X1 g989__1617 (.Y(n_2),
	.A(codeword[0]),
	.B(codeword[10]));
   XNOR2X1 g997__2802 (.Y(n_1),
	.A(codeword[1]),
	.B(codeword[8]));
   XNOR2X1 g987__1705 (.Y(n_0),
	.A(codeword[9]),
	.B(codeword[11]));
   XNOR2X1 g998__5122 (.Y(n_8),
	.A(codeword[6]),
	.B(codeword[11]));
   XNOR2X1 g999__8246 (.Y(n_18),
	.A(codeword[3]),
	.B(codeword[13]));
   XNOR2X1 g1002__7098 (.Y(n_24),
	.A(codeword[5]),
	.B(codeword[10]));
   XOR2XL g2 (.Y(n_61),
	.A(n_14),
	.B(n_18));
   XOR2XL g1003 (.Y(n_62),
	.A(n_1),
	.B(n_27));
endmodule

