/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Oct 13 12:20:58 2025
#  Design:            h_decoder_12_7
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/h_decoder_12_7/h_decoder_12_7_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct 13 2025 12:20:19 -03 (Oct 13 2025 15:20:19 UTC)
// Verification Directory fv/h_decoder_12_7 
module h_decoder_12_7 (
	i_CodeWord, 
	o_DecodWord, 
	o_Syndrome, 
	o_ErrorC, 
	o_ErrorD);
   input [11:0] i_CodeWord;
   output [6:0] o_DecodWord;
   output [4:0] o_Syndrome;
   output o_ErrorC;
   output o_ErrorD;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;

   CLKXOR2X2 g912__2398 (.Y(o_DecodWord[6]),
	.A(n_34),
	.B(i_CodeWord[11]));
   CLKXOR2X2 g915__5107 (.Y(o_DecodWord[3]),
	.A(n_31),
	.B(i_CodeWord[7]));
   CLKXOR2X2 g916__6260 (.Y(o_DecodWord[0]),
	.A(n_33),
	.B(i_CodeWord[3]));
   XNOR2X2 g910__4319 (.Y(o_DecodWord[4]),
	.A(n_30),
	.B(i_CodeWord[9]));
   XNOR2X2 g911__8428 (.Y(o_DecodWord[1]),
	.A(n_27),
	.B(i_CodeWord[5]));
   XNOR2X2 g914__5526 (.Y(o_DecodWord[5]),
	.A(n_23),
	.B(i_CodeWord[10]));
   XNOR2X2 g913__6783 (.Y(o_DecodWord[2]),
	.A(n_24),
	.B(i_CodeWord[6]));
   NOR2XL g917__3680 (.Y(n_34),
	.A(n_16),
	.B(n_32));
   NOR2XL g919__1617 (.Y(n_33),
	.A(n_12),
	.B(n_32));
   NOR2XL g918__2802 (.Y(n_31),
	.A(n_17),
	.B(n_32));
   NAND3BXL g920__1705 (.Y(n_30),
	.AN(o_Syndrome[2]),
	.B(o_Syndrome[4]),
	.C(n_25));
   NAND3BXL g923__5122 (.Y(n_27),
	.AN(o_Syndrome[2]),
	.B(o_Syndrome[3]),
	.C(n_25));
   NAND2XL g924__8246 (.Y(n_32),
	.A(o_Syndrome[2]),
	.B(n_25));
   NAND3BXL g921__7098 (.Y(n_24),
	.AN(n_22),
	.B(o_Syndrome[3]),
	.C(o_Syndrome[2]));
   NAND3BXL g922__6131 (.Y(n_23),
	.AN(n_22),
	.B(o_Syndrome[4]),
	.C(o_Syndrome[2]));
   AND2X2 g926__1881 (.Y(o_ErrorD),
	.A(n_13),
	.B(n_18));
   AND2X1 g925__5115 (.Y(n_25),
	.A(o_ErrorC),
	.B(o_Syndrome[1]));
   NAND2BXL g927__7482 (.Y(n_22),
	.AN(o_Syndrome[1]),
	.B(o_ErrorC));
   INVXL g928 (.Y(n_18),
	.A(o_ErrorC));
   OA21X2 g929__4733 (.Y(o_ErrorC),
	.A0(n_17),
	.A1(n_16),
	.B0(o_Syndrome[0]));
   XNOR2X2 g930__6161 (.Y(o_Syndrome[0]),
	.A(n_10),
	.B(n_14));
   XNOR2X1 g931__9315 (.Y(n_14),
	.A(o_Syndrome[2]),
	.B(i_CodeWord[0]));
   OR3XL g932__9945 (.Y(n_13),
	.A(o_Syndrome[1]),
	.B(n_12),
	.C(o_Syndrome[2]));
   CLKXOR2X2 g933__2883 (.Y(o_Syndrome[2]),
	.A(i_CodeWord[2]),
	.B(n_11));
   XNOR2X1 g934__2346 (.Y(n_11),
	.A(i_CodeWord[10]),
	.B(n_8));
   XNOR2X1 g935__1666 (.Y(n_10),
	.A(i_CodeWord[8]),
	.B(n_9));
   NAND2XL g936__7410 (.Y(n_12),
	.A(n_17),
	.B(n_16));
   INVXL g937 (.Y(n_16),
	.A(o_Syndrome[4]));
   XNOR2X1 g940__6417 (.Y(n_9),
	.A(i_CodeWord[4]),
	.B(n_6));
   CLKXOR2X2 g939__5477 (.Y(o_Syndrome[4]),
	.A(i_CodeWord[10]),
	.B(n_5));
   XNOR2X1 g938__2398 (.Y(n_8),
	.A(i_CodeWord[6]),
	.B(n_7));
   CLKXOR2X2 g941__5107 (.Y(o_Syndrome[1]),
	.A(n_7),
	.B(n_6));
   INVXL g944 (.Y(n_17),
	.A(o_Syndrome[3]));
   XNOR2X1 g942__6260 (.Y(n_5),
	.A(i_CodeWord[8]),
	.B(n_4));
   XNOR2X1 g943__4319 (.Y(n_6),
	.A(i_CodeWord[9]),
	.B(n_2));
   XNOR2X1 g945__8428 (.Y(n_7),
	.A(i_CodeWord[11]),
	.B(n_0));
   CLKXOR2X2 g946__5526 (.Y(o_Syndrome[3]),
	.A(n_1),
	.B(n_3));
   XNOR2X1 g948__6783 (.Y(n_4),
	.A(i_CodeWord[9]),
	.B(i_CodeWord[11]));
   XNOR2X1 g949__3680 (.Y(n_3),
	.A(i_CodeWord[4]),
	.B(i_CodeWord[7]));
   XNOR2X1 g950__1617 (.Y(n_2),
	.A(i_CodeWord[1]),
	.B(i_CodeWord[5]));
   XNOR2X1 g947__2802 (.Y(n_1),
	.A(i_CodeWord[5]),
	.B(i_CodeWord[6]));
   XNOR2X1 g951__1705 (.Y(n_0),
	.A(i_CodeWord[3]),
	.B(i_CodeWord[7]));
endmodule

