/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Aug 21 16:05:55 2025
#  Design:            and16
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug 21 2025 12:38:29 -03 (Aug 21 2025 15:38:29 UTC)
// Verification Directory fv/and16 
module and16 (
	a, 
	y);
   input [15:0] a;
   output y;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;

   AND2X1 g192__2398 (.Y(y),
	.A(n_1),
	.B(n_4));
   NOR4BBX1 g193__5107 (.Y(n_4),
	.AN(a[5]),
	.BN(a[0]),
	.C(n_0),
	.D(n_3));
   NAND3BXL g194__6260 (.Y(n_3),
	.AN(n_2),
	.B(a[14]),
	.C(a[15]));
   NAND4XL g196__4319 (.Y(n_2),
	.A(a[6]),
	.B(a[7]),
	.C(a[10]),
	.D(a[11]));
   AND4X1 g195__8428 (.Y(n_1),
	.A(a[1]),
	.B(a[2]),
	.C(a[3]),
	.D(a[4]));
   NAND4XL g197__5526 (.Y(n_0),
	.A(a[8]),
	.B(a[9]),
	.C(a[12]),
	.D(a[13]));
endmodule

