
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  4 2025 14:43:14 -03 (Sep  4 2025 17:43:14 UTC)

// Verification Directory fv/h_decoder_11_7 

module h_decoder_11_7(i_CodeWord, o_DecodWord, o_Syndrome, o_ErrorFlag);
  input [11:0] i_CodeWord;
  output [6:0] o_DecodWord;
  output [3:0] o_Syndrome;
  output o_ErrorFlag;
  wire [11:0] i_CodeWord;
  wire [6:0] o_DecodWord;
  wire [3:0] o_Syndrome;
  wire o_ErrorFlag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_18, n_20, n_21, n_22, n_26, n_28, n_29, n_33;
  wire n_49;
  assign o_DecodWord[6] = i_CodeWord[11];
  XNOR2X2 g1046__2398(.A (n_29), .B (i_CodeWord[7]), .Y
       (o_DecodWord[3]));
  OR2X2 g1047__5107(.A (o_Syndrome[3]), .B (n_33), .Y (o_ErrorFlag));
  XNOR2X2 g1050__6260(.A (n_21), .B (i_CodeWord[10]), .Y
       (o_DecodWord[5]));
  OAI211X1 g1054__4319(.A0 (n_13), .A1 (n_12), .B0 (n_14), .C0 (n_28),
       .Y (n_33));
  XNOR2X2 g1052__8428(.A (n_22), .B (i_CodeWord[9]), .Y
       (o_DecodWord[4]));
  XNOR2X2 g1051__5526(.A (n_26), .B (i_CodeWord[6]), .Y
       (o_DecodWord[2]));
  XNOR2X2 g1049__6783(.A (n_49), .B (i_CodeWord[3]), .Y
       (o_DecodWord[0]));
  NAND2XL g1053__3680(.A (o_Syndrome[3]), .B (n_28), .Y (n_29));
  XNOR2X2 g1048__1617(.A (n_18), .B (i_CodeWord[5]), .Y
       (o_DecodWord[1]));
  NAND3BXL g1059__2802(.AN (n_15), .B (o_Syndrome[0]), .C
       (o_Syndrome[1]), .Y (n_26));
  NAND3BXL g1060__5122(.AN (o_Syndrome[0]), .B (n_20), .C
       (o_Syndrome[1]), .Y (n_22));
  NAND3XL g1057__8246(.A (n_20), .B (o_Syndrome[0]), .C
       (o_Syndrome[1]), .Y (n_21));
  NOR3XL g1058__7098(.A (o_Syndrome[2]), .B (o_Syndrome[0]), .C
       (o_Syndrome[1]), .Y (n_28));
  NAND2XL g1055__6131(.A (n_17), .B (o_Syndrome[1]), .Y (n_18));
  XNOR2X2 g1062__1881(.A (i_CodeWord[3]), .B (n_11), .Y
       (o_Syndrome[1]));
  NOR2XL g1063__5115(.A (n_15), .B (o_Syndrome[0]), .Y (n_17));
  NAND2XL g1064__7482(.A (n_13), .B (n_12), .Y (n_14));
  XNOR2X1 g1067__4733(.A (n_7), .B (n_10), .Y (n_12));
  NAND2XL g1068__6161(.A (o_Syndrome[2]), .B (n_8), .Y (n_15));
  XNOR2X1 g1066__9315(.A (i_CodeWord[11]), .B (n_10), .Y (n_11));
  NOR2XL g1069__9945(.A (o_Syndrome[2]), .B (n_8), .Y (n_20));
  XNOR2X2 g1065__2883(.A (i_CodeWord[7]), .B (n_13), .Y
       (o_Syndrome[0]));
  INVXL g1072(.A (o_Syndrome[3]), .Y (n_8));
  XNOR2X1 g1070__2346(.A (n_4), .B (n_5), .Y (n_7));
  XNOR2X1 g1071__1666(.A (i_CodeWord[7]), .B (n_1), .Y (n_10));
  XNOR2X1 g1075__7410(.A (n_0), .B (n_6), .Y (n_13));
  XNOR2X2 g1074__6417(.A (i_CodeWord[5]), .B (n_3), .Y (o_Syndrome[2]));
  CLKXOR2X2 g1076__5477(.A (n_6), .B (n_2), .Y (o_Syndrome[3]));
  XNOR2X1 g1083__2398(.A (i_CodeWord[1]), .B (i_CodeWord[4]), .Y (n_5));
  XNOR2X1 g1077__5107(.A (i_CodeWord[2]), .B (i_CodeWord[8]), .Y (n_4));
  XNOR2X1 g1078__6260(.A (i_CodeWord[6]), .B (i_CodeWord[7]), .Y (n_3));
  XNOR2X1 g1082__4319(.A (i_CodeWord[8]), .B (i_CodeWord[10]), .Y
       (n_2));
  XNOR2X1 g1080__8428(.A (i_CodeWord[6]), .B (i_CodeWord[10]), .Y
       (n_1));
  XNOR2X1 g1081__5526(.A (i_CodeWord[3]), .B (i_CodeWord[5]), .Y (n_0));
  XNOR2X1 g1079__6783(.A (i_CodeWord[9]), .B (i_CodeWord[11]), .Y
       (n_6));
  NAND2BXL g2(.AN (o_Syndrome[1]), .B (n_17), .Y (n_49));
endmodule

