
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  4 2025 15:09:17 -03 (Sep  4 2025 18:09:17 UTC)

// Verification Directory fv/h_decoder_11_7 

module h_decoder_11_7(i_CodeWord, o_DecodWord, o_Syndrome, o_ErrorFlag);
  input [11:0] i_CodeWord;
  output [6:0] o_DecodWord;
  output [4:0] o_Syndrome;
  output o_ErrorFlag;
  wire [11:0] i_CodeWord;
  wire [6:0] o_DecodWord;
  wire [4:0] o_Syndrome;
  wire o_ErrorFlag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_38;
  OR2X2 g1007__2398(.A (o_Syndrome[2]), .B (n_38), .Y (o_ErrorFlag));
  OR4X1 g1008__5107(.A (o_Syndrome[4]), .B (o_Syndrome[3]), .C
       (o_Syndrome[1]), .D (o_Syndrome[0]), .Y (n_38));
  XNOR2X2 g1012__6260(.A (n_25), .B (i_CodeWord[11]), .Y
       (o_DecodWord[6]));
  XNOR2X2 g1010__4319(.A (n_26), .B (i_CodeWord[9]), .Y
       (o_DecodWord[4]));
  XNOR2X2 g1015__8428(.A (n_22), .B (i_CodeWord[10]), .Y
       (o_DecodWord[5]));
  XNOR2X2 g1009__5526(.A (n_12), .B (n_19), .Y (o_Syndrome[0]));
  XNOR2X2 g1013__6783(.A (n_23), .B (i_CodeWord[6]), .Y
       (o_DecodWord[2]));
  XNOR2X2 g1011__3680(.A (n_21), .B (i_CodeWord[5]), .Y
       (o_DecodWord[1]));
  XNOR2X2 g1016__1617(.A (n_18), .B (i_CodeWord[3]), .Y
       (o_DecodWord[0]));
  XNOR2X2 g1014__2802(.A (n_17), .B (i_CodeWord[7]), .Y
       (o_DecodWord[3]));
  NAND2XL g1018__1705(.A (n_20), .B (n_24), .Y (n_26));
  NAND2XL g1020__5122(.A (o_Syndrome[2]), .B (n_24), .Y (n_25));
  NAND3BXL g1022__8246(.AN (o_Syndrome[1]), .B (n_13), .C
       (o_Syndrome[2]), .Y (n_23));
  NAND4XL g1024__7098(.A (n_10), .B (o_Syndrome[4]), .C (n_14), .D
       (o_Syndrome[2]), .Y (n_22));
  NAND2XL g1019__6131(.A (n_16), .B (n_20), .Y (n_21));
  XNOR2X1 g1017__1881(.A (o_Syndrome[2]), .B (i_CodeWord[0]), .Y
       (n_19));
  NAND3BXL g1021__5115(.AN (o_Syndrome[4]), .B (n_15), .C
       (o_Syndrome[2]), .Y (n_18));
  NAND2XL g1023__7482(.A (n_16), .B (o_Syndrome[2]), .Y (n_17));
  AND2X1 g1025__4733(.A (n_15), .B (o_Syndrome[4]), .Y (n_24));
  INVXL g1026(.A (o_Syndrome[2]), .Y (n_20));
  NOR2XL g1028__6161(.A (o_Syndrome[3]), .B (n_14), .Y (n_15));
  CLKXOR2X2 g1027__9315(.A (n_5), .B (n_11), .Y (o_Syndrome[2]));
  AND2X1 g1029__9945(.A (o_Syndrome[1]), .B (n_13), .Y (n_16));
  INVXL g1031(.A (o_Syndrome[1]), .Y (n_14));
  XNOR2X1 g1030__2883(.A (n_4), .B (n_8), .Y (n_12));
  XNOR2X1 g1032__2346(.A (i_CodeWord[6]), .B (n_9), .Y (n_11));
  NOR2XL g1034__1666(.A (o_Syndrome[4]), .B (n_10), .Y (n_13));
  CLKXOR2X2 g1033__7410(.A (n_9), .B (n_8), .Y (o_Syndrome[1]));
  INVXL g1037(.A (o_Syndrome[3]), .Y (n_10));
  XNOR2X1 g1035__6417(.A (i_CodeWord[9]), .B (n_7), .Y (n_8));
  XNOR2X1 g1036__5477(.A (i_CodeWord[3]), .B (n_2), .Y (n_9));
  CLKXOR2X2 g1038__2398(.A (n_1), .B (n_0), .Y (o_Syndrome[3]));
  CLKXOR2X2 g1039__5107(.A (n_6), .B (n_3), .Y (o_Syndrome[4]));
  XNOR2X1 g1046__6260(.A (i_CodeWord[1]), .B (i_CodeWord[5]), .Y (n_7));
  XNOR2X1 g1045__4319(.A (i_CodeWord[8]), .B (i_CodeWord[9]), .Y (n_6));
  XNOR2X1 g1044__8428(.A (i_CodeWord[2]), .B (i_CodeWord[10]), .Y
       (n_5));
  XNOR2X1 g1047__5526(.A (i_CodeWord[4]), .B (i_CodeWord[8]), .Y (n_4));
  XNOR2X1 g1042__6783(.A (i_CodeWord[10]), .B (i_CodeWord[11]), .Y
       (n_3));
  XNOR2X1 g1041__3680(.A (i_CodeWord[7]), .B (i_CodeWord[11]), .Y
       (n_2));
  XNOR2X1 g1040__1617(.A (i_CodeWord[4]), .B (i_CodeWord[5]), .Y (n_1));
  XNOR2X1 g1043__2802(.A (i_CodeWord[6]), .B (i_CodeWord[7]), .Y (n_0));
endmodule

