/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Oct  9 11:13:21 2025
#  Design:            bch_chien_block
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_chien_block/bch_chien_block_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 24 2025 10:07:16 -03 (Sep 24 2025 13:07:16 UTC)
// Verification Directory fv/bch_chien_block 
module bch_chien_block (
	lambda1, 
	lambda2, 
	error_vector, 
	error_found);
   input [3:0] lambda1;
   input [3:0] lambda2;
   output [14:0] error_vector;
   output error_found;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_242;
   wire n_247;
   wire n_248;
   wire n_252;
   wire n_256;
   wire n_260;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;

   OR3X2 g7912__2398 (.Y(error_found),
	.A(error_vector[4]),
	.B(error_vector[3]),
	.C(n_260));
   OR4X1 g7913__5107 (.Y(n_260),
	.A(error_vector[9]),
	.B(error_vector[8]),
	.C(error_vector[6]),
	.D(n_256));
   OR4X1 g7914__6260 (.Y(n_256),
	.A(error_vector[7]),
	.B(error_vector[5]),
	.C(error_vector[10]),
	.D(n_252));
   OR4X1 g7915__4319 (.Y(n_252),
	.A(error_vector[12]),
	.B(n_247),
	.C(error_vector[11]),
	.D(error_vector[2]));
   AND2X2 g7920__8428 (.Y(error_vector[11]),
	.A(n_239),
	.B(n_248));
   AND4X2 g7918__5526 (.Y(error_vector[2]),
	.A(n_125),
	.B(n_158),
	.C(n_213),
	.D(n_265));
   AOI221X1 g7921__6783 (.Y(n_248),
	.A0(n_234),
	.A1(n_217),
	.B0(n_235),
	.B1(n_218),
	.C0(n_242));
   AND4X2 g7916__3680 (.Y(error_vector[3]),
	.A(n_159),
	.B(n_216),
	.C(n_229),
	.D(n_240));
   AND4X2 g7917__1617 (.Y(error_vector[10]),
	.A(n_176),
	.B(n_160),
	.C(n_236),
	.D(n_237));
   AND4X2 g7919__2802 (.Y(error_vector[4]),
	.A(n_219),
	.B(n_264),
	.C(n_211),
	.D(n_233));
   OR4X1 g7923__1705 (.Y(n_247),
	.A(error_vector[0]),
	.B(error_vector[14]),
	.C(error_vector[13]),
	.D(error_vector[1]));
   OAI211X1 g7926__5122 (.Y(n_242),
	.A0(n_205),
	.A1(n_222),
	.B0(n_206),
	.C0(n_227));
   XNOR2X1 g7932__7098 (.Y(n_240),
	.A(n_230),
	.B(n_238));
   XNOR2X1 g7933__6131 (.Y(n_239),
	.A(n_174),
	.B(n_238));
   XNOR2X1 g7930__1881 (.Y(n_237),
	.A(n_226),
	.B(n_238));
   AOI22XL g7935__5115 (.Y(n_236),
	.A0(n_235),
	.A1(n_231),
	.B0(n_234),
	.B1(n_232));
   AND4X2 g7922__7482 (.Y(error_vector[5]),
	.A(n_199),
	.B(n_203),
	.C(n_170),
	.D(n_224));
   AOI22XL g7937__4733 (.Y(n_233),
	.A0(n_232),
	.A1(n_212),
	.B0(n_231),
	.B1(n_230));
   AOI22XL g7938__6161 (.Y(n_229),
	.A0(n_228),
	.A1(n_231),
	.B0(n_223),
	.B1(n_232));
   AND4X2 g7924__9315 (.Y(error_vector[12]),
	.A(n_30),
	.B(n_151),
	.C(n_209),
	.D(n_221));
   XNOR2X1 g7936__9945 (.Y(n_227),
	.A(n_226),
	.B(n_232));
   AND4X2 g7928__2883 (.Y(error_vector[1]),
	.A(n_18),
	.B(n_11),
	.C(n_123),
	.D(n_208));
   AND4X2 g7943__2346 (.Y(error_vector[13]),
	.A(n_145),
	.B(n_201),
	.C(n_207),
	.D(n_154));
   NAND2XL g7944__1666 (.Y(n_238),
	.A(n_54),
	.B(n_215));
   AND4X2 g7957__7410 (.Y(error_vector[14]),
	.A(n_15),
	.B(n_9),
	.C(n_148),
	.D(n_204));
   AND4X2 g7934__6417 (.Y(error_vector[8]),
	.A(n_161),
	.B(n_171),
	.C(n_139),
	.D(n_189));
   AND4X2 g7925__5477 (.Y(error_vector[6]),
	.A(n_195),
	.B(n_182),
	.C(n_191),
	.D(n_194));
   OAI22XL g7946__2398 (.Y(n_224),
	.A0(n_228),
	.A1(n_220),
	.B0(n_223),
	.B1(n_222));
   AOI22XL g7941__5107 (.Y(n_221),
	.A0(n_234),
	.A1(n_222),
	.B0(n_235),
	.B1(n_220));
   AND4X2 g7927__6260 (.Y(error_vector[7]),
	.A(n_144),
	.B(n_187),
	.C(n_184),
	.D(n_178));
   INVXL g7951 (.Y(n_231),
	.A(n_232));
   AOI22XL g7956__4319 (.Y(n_219),
	.A0(n_223),
	.A1(n_218),
	.B0(n_228),
	.B1(n_217));
   AOI22XL g7955__8428 (.Y(n_216),
	.A0(n_197),
	.A1(n_218),
	.B0(n_210),
	.B1(n_217));
   AOI32X1 g7961__5526 (.Y(n_215),
	.A0(n_172),
	.A1(n_214),
	.A2(n_185),
	.B0(n_150),
	.B1(n_186));
   OAI21XL g7958__6783 (.Y(n_232),
	.A0(n_214),
	.A1(n_164),
	.B0(n_105));
   AOI22XL g7949__3680 (.Y(n_213),
	.A0(n_175),
	.A1(n_212),
	.B0(n_173),
	.B1(n_230));
   XNOR2X1 g7942__1617 (.Y(n_211),
	.A(n_210),
	.B(n_222));
   AOI22XL g7964__2802 (.Y(n_209),
	.A0(n_155),
	.A1(n_218),
	.B0(n_226),
	.B1(n_217));
   AOI22XL g7950__1705 (.Y(n_208),
	.A0(n_166),
	.A1(n_212),
	.B0(n_167),
	.B1(n_230));
   AND4X2 g7929__5122 (.Y(error_vector[9]),
	.A(n_168),
	.B(n_156),
	.C(n_162),
	.D(n_137));
   AOI22XL g7987__8246 (.Y(n_207),
	.A0(n_196),
	.A1(n_235),
	.B0(n_198),
	.B1(n_234));
   NAND2XL g7953__7098 (.Y(n_206),
	.A(n_205),
	.B(n_222));
   AOI22XL g7977__6131 (.Y(n_204),
	.A0(n_200),
	.A1(n_152),
	.B0(n_202),
	.B1(n_205));
   XNOR2X1 g7980__1881 (.Y(n_203),
	.A(n_202),
	.B(n_190));
   OAI22XL g8002__5115 (.Y(n_201),
	.A0(lambda1[1]),
	.A1(n_202),
	.B0(n_146),
	.B1(n_200));
   AOI22XL g7979__7482 (.Y(n_199),
	.A0(n_198),
	.A1(n_197),
	.B0(n_196),
	.B1(n_210));
   INVXL g7967 (.Y(n_220),
	.A(n_222));
   AOI22XL g7981__4733 (.Y(n_195),
	.A0(n_169),
	.A1(n_210),
	.B0(n_153),
	.B1(n_197));
   XNOR2X1 g7947__6161 (.Y(n_194),
	.A(n_192),
	.B(n_202));
   AOI22XL g7989__9945 (.Y(n_191),
	.A0(n_177),
	.A1(n_190),
	.B0(n_147),
	.B1(n_188));
   AOI22XL g7991__2883 (.Y(n_189),
	.A0(lambda2[2]),
	.A1(n_190),
	.B0(n_183),
	.B1(n_188));
   AOI22XL g7992__2346 (.Y(n_187),
	.A0(lambda2[1]),
	.A1(n_190),
	.B0(n_181),
	.B1(n_188));
   OAI2BB1X1 g7978__1666 (.Y(n_186),
	.A0N(n_163),
	.A1N(n_185),
	.B0(n_127));
   AOI22XL g7963__7410 (.Y(n_184),
	.A0(lambda2[2]),
	.A1(n_179),
	.B0(n_183),
	.B1(n_180));
   OAI22XL g7960__6417 (.Y(n_182),
	.A0(n_181),
	.A1(n_180),
	.B0(lambda2[1]),
	.B1(n_179));
   XNOR2X1 g7940__5477 (.Y(n_178),
	.A(n_177),
	.B(n_192));
   AOI22XL g7973__2398 (.Y(n_176),
	.A0(n_165),
	.A1(n_175),
	.B0(n_174),
	.B1(n_173));
   INVXL g7972 (.Y(n_212),
	.A(n_230));
   AOI221X1 g7970__5107 (.Y(n_222),
	.A0(n_133),
	.A1(n_128),
	.B0(n_130),
	.B1(n_172),
	.C0(n_84));
   AOI22XL g7954__6260 (.Y(n_171),
	.A0(lambda2[3]),
	.A1(n_179),
	.B0(n_143),
	.B1(n_180));
   XNOR2X1 g7945__4319 (.Y(n_170),
	.A(n_169),
	.B(n_192));
   OAI22XL g7988__8428 (.Y(n_168),
	.A0(n_167),
	.A1(n_174),
	.B0(n_166),
	.B1(n_165));
   OA22X1 g7990__5526 (.Y(n_164),
	.A0(n_121),
	.A1(n_185),
	.B0(n_149),
	.B1(n_163));
   AOI22XL g7952__6783 (.Y(n_162),
	.A0(lambda2[0]),
	.A1(n_179),
	.B0(n_138),
	.B1(n_180));
   AOI22XL g7993__3680 (.Y(n_161),
	.A0(n_136),
	.A1(n_165),
	.B0(n_124),
	.B1(n_174));
   INVXL g7986 (.Y(n_217),
	.A(n_218));
   AOI22XL g7965__1617 (.Y(n_160),
	.A0(n_167),
	.A1(n_141),
	.B0(n_166),
	.B1(n_142));
   AOI22XL g7974__2802 (.Y(n_159),
	.A0(lambda1[0]),
	.A1(n_173),
	.B0(n_157),
	.B1(n_175));
   AOI22XL g8004__1705 (.Y(n_158),
	.A0(lambda1[0]),
	.A1(n_166),
	.B0(n_157),
	.B1(n_167));
   AOI22XL g7969__5122 (.Y(n_156),
	.A0(n_155),
	.A1(n_173),
	.B0(n_226),
	.B1(n_175));
   INVXL g8014 (.Y(n_234),
	.A(n_235));
   AOI22XL g7983__8246 (.Y(n_154),
	.A0(n_169),
	.A1(n_205),
	.B0(n_153),
	.B1(n_152));
   AOI22XL g7982__7098 (.Y(n_151),
	.A0(n_196),
	.A1(n_205),
	.B0(n_198),
	.B1(n_152));
   INVXL g7996 (.Y(n_223),
	.A(n_228));
   AOI22XL g7995__6131 (.Y(n_218),
	.A0(n_150),
	.A1(n_172),
	.B0(n_149),
	.B1(n_185));
   OAI221X1 g7975__1881 (.Y(n_230),
	.A0(n_131),
	.A1(n_110),
	.B0(n_134),
	.B1(n_109),
	.C0(n_132));
   AOI22XL g8006__5115 (.Y(n_148),
	.A0(lambda1[1]),
	.A1(n_147),
	.B0(n_146),
	.B1(n_177));
   AOI22XL g8003__7482 (.Y(n_145),
	.A0(n_19),
	.A1(n_147),
	.B0(lambda1[2]),
	.B1(n_177));
   OAI22XL g7959__4733 (.Y(n_144),
	.A0(n_143),
	.A1(n_142),
	.B0(lambda2[3]),
	.B1(n_141));
   INVXL g8008 (.Y(n_197),
	.A(n_210));
   OAI211X1 g8000__6161 (.Y(n_228),
	.A0(n_119),
	.A1(n_135),
	.B0(n_113),
	.C0(n_117));
   AOI22XL g7962__9315 (.Y(n_139),
	.A0(lambda2[0]),
	.A1(n_141),
	.B0(n_138),
	.B1(n_142));
   XNOR2X1 g7966__9945 (.Y(n_137),
	.A(n_136),
	.B(n_141));
   INVXL g8009 (.Y(n_190),
	.A(n_188));
   INVXL g8019 (.Y(n_202),
	.A(n_200));
   AOI31X1 g8017__2883 (.Y(n_235),
	.A0(n_91),
	.A1(n_135),
	.A2(n_87),
	.B0(n_129));
   INVXL g8007 (.Y(n_163),
	.A(n_172));
   INVXL g8012 (.Y(n_165),
	.A(n_174));
   NAND2XL g8011__2346 (.Y(n_188),
	.A(n_93),
	.B(n_120));
   AOI221X1 g8010__1666 (.Y(n_210),
	.A0(n_134),
	.A1(n_268),
	.B0(n_62),
	.B1(n_89),
	.C0(n_66));
   INVXL g8018 (.Y(n_214),
	.A(n_150));
   AOI21XL g8026__7410 (.Y(n_200),
	.A0(n_101),
	.A1(n_133),
	.B0(n_111));
   INVXL g7976 (.Y(n_180),
	.A(n_179));
   OAI211X1 g7971__6417 (.Y(n_192),
	.A0(n_116),
	.A1(n_95),
	.B0(n_86),
	.C0(n_266));
   NAND4XL g8005__5477 (.Y(n_132),
	.A(n_71),
	.B(n_90),
	.C(n_108),
	.D(n_131));
   NOR2XL g8020__2398 (.Y(n_130),
	.A(n_68),
	.B(n_126));
   OAI21XL g8021__5107 (.Y(n_129),
	.A0(n_96),
	.A1(n_51),
	.B0(n_100));
   INVXL g8013 (.Y(n_152),
	.A(n_205));
   AOI21XL g8024__6260 (.Y(n_150),
	.A0(n_115),
	.A1(n_122),
	.B0(n_128));
   NOR2BX1 g8023__4319 (.Y(n_185),
	.AN(n_127),
	.B(n_126));
   NAND3BXL g8015__8428 (.Y(n_174),
	.AN(n_63),
	.B(n_118),
	.C(n_92));
   AOI22XL g8032__5526 (.Y(n_125),
	.A0(lambda1[3]),
	.A1(n_136),
	.B0(n_17),
	.B1(n_124));
   AOI22XL g8033__6783 (.Y(n_123),
	.A0(lambda1[0]),
	.A1(n_136),
	.B0(n_157),
	.B1(n_124));
   INVXL g7997 (.Y(n_173),
	.A(n_175));
   INVXL g8027 (.Y(n_167),
	.A(n_166));
   INVXL g8041 (.Y(n_198),
	.A(n_196));
   AOI21XL g8025__3680 (.Y(n_172),
	.A0(n_97),
	.A1(n_122),
	.B0(n_121));
   NOR2XL g7984__1617 (.Y(n_179),
	.A(n_32),
	.B(n_104));
   AOI221X1 g8030__2802 (.Y(n_120),
	.A0(n_134),
	.A1(n_75),
	.B0(n_119),
	.B1(n_118),
	.C0(n_50));
   OAI211X1 g8029__1705 (.Y(n_117),
	.A0(n_116),
	.A1(n_65),
	.B0(n_114),
	.C0(n_76));
   INVXL g8028 (.Y(n_147),
	.A(n_177));
   OAI211X1 g8001__5122 (.Y(n_175),
	.A0(n_107),
	.A1(n_115),
	.B0(n_26),
	.C0(n_81));
   AOI32X1 g8016__8246 (.Y(n_205),
	.A0(n_114),
	.A1(n_103),
	.A2(n_113),
	.B0(n_268),
	.B1(n_74));
   OAI31X1 g8043__7098 (.Y(n_111),
	.A0(n_102),
	.A1(n_106),
	.A2(n_48),
	.B0(n_85));
   AND2X1 g8036__6131 (.Y(n_110),
	.A(n_109),
	.B(n_108));
   INVXL g7985 (.Y(n_141),
	.A(n_142));
   OAI211X1 g8047__1881 (.Y(n_196),
	.A0(n_107),
	.A1(n_77),
	.B0(n_267),
	.C0(n_78));
   AOI221X1 g8034__5115 (.Y(n_166),
	.A0(n_49),
	.A1(n_64),
	.B0(n_106),
	.B1(n_105),
	.C0(n_133));
   OA22X1 g7999__7482 (.Y(n_104),
	.A0(n_58),
	.A1(n_98),
	.B0(n_103),
	.B1(n_116));
   NAND2XL g8038__4733 (.Y(n_127),
	.A(n_102),
	.B(n_122));
   NOR2XL g8037__6161 (.Y(n_128),
	.A(n_101),
	.B(n_122));
   OAI22XL g8035__9315 (.Y(n_177),
	.A0(n_83),
	.A1(n_69),
	.B0(n_40),
	.B1(n_115));
   OAI22XL g8045__9945 (.Y(n_100),
	.A0(n_59),
	.A1(n_88),
	.B0(n_134),
	.B1(n_119));
   NOR2XL g8039__2346 (.Y(n_121),
	.A(n_97),
	.B(n_122));
   NOR2XL g8040__1666 (.Y(n_126),
	.A(n_80),
	.B(n_122));
   OAI222XL g7994__7410 (.Y(n_142),
	.A0(n_96),
	.A1(n_95),
	.B0(n_72),
	.B1(n_98),
	.C0(n_94),
	.C1(n_93));
   OAI211X1 g8042__6417 (.Y(n_92),
	.A0(n_268),
	.A1(n_70),
	.B0(n_91),
	.C0(n_90));
   NOR2XL g8050__5477 (.Y(n_89),
	.A(n_88),
	.B(n_87));
   INVXL g8049 (.Y(n_149),
	.A(n_122));
   NOR2BX1 g8046__2398 (.Y(n_131),
	.AN(n_86),
	.B(n_52));
   OAI21XL g8057__5107 (.Y(n_85),
	.A0(n_102),
	.A1(n_84),
	.B0(n_83));
   NAND2XL g8053__6260 (.Y(n_108),
	.A(n_55),
	.B(n_82));
   OR2X1 g8060__4319 (.Y(n_109),
	.A(n_90),
	.B(n_82));
   INVXL g8056 (.Y(n_136),
	.A(n_124));
   OAI211X1 g8031__8428 (.Y(n_81),
	.A0(n_80),
	.A1(n_67),
	.B0(n_35),
	.C0(n_97));
   NOR2XL g8055__5526 (.Y(n_122),
	.A(n_107),
	.B(n_60));
   NAND2XL g8067__6783 (.Y(n_78),
	.A(n_83),
	.B(n_77));
   INVXL g8065 (.Y(n_76),
	.A(n_75));
   NAND2XL g8070__3680 (.Y(n_74),
	.A(n_45),
	.B(n_90));
   NAND3BXL g8062__1617 (.Y(n_124),
	.AN(n_28),
	.B(n_36),
	.C(n_267));
   AOI21XL g8058__2802 (.Y(n_72),
	.A0(n_71),
	.A1(n_70),
	.B0(n_103));
   OA21X1 g8059__1705 (.Y(n_69),
	.A0(n_68),
	.A1(n_56),
	.B0(n_67));
   NAND2XL g8052__5122 (.Y(n_86),
	.A(n_66),
	.B(n_65));
   NAND2XL g8054__8246 (.Y(n_113),
	.A(n_116),
	.B(n_65));
   OAI21XL g8022__7098 (.Y(n_98),
	.A0(n_114),
	.A1(n_57),
	.B0(n_41));
   NAND2XL g8075__6131 (.Y(n_64),
	.A(n_44),
	.B(n_80));
   NOR2XL g8069__1881 (.Y(n_75),
	.A(n_94),
	.B(n_63));
   XNOR2X1 g8071__5115 (.Y(n_82),
	.A(n_62),
	.B(n_66));
   INVXL g8074 (.Y(n_88),
	.A(n_135));
   INVXL g8063 (.Y(n_101),
	.A(n_61));
   NOR2XL g8079__7482 (.Y(n_133),
	.A(n_97),
	.B(n_80));
   ADDHX1 g8066__4733 (.CO(n_60),
	.S(n_61),
	.A(n_42),
	.B(n_115));
   AND2X1 g8068__6161 (.Y(n_59),
	.A(n_91),
	.B(n_93));
   NOR2XL g8044__9315 (.Y(n_58),
	.A(n_268),
	.B(n_57));
   AOI21XL g8072__9945 (.Y(n_87),
	.A0(n_134),
	.A1(n_53),
	.B0(n_119));
   NAND2XL g8077__2883 (.Y(n_77),
	.A(n_115),
	.B(n_56));
   NOR2XL g8078__2346 (.Y(n_84),
	.A(n_107),
	.B(n_105));
   NAND2XL g8080__1666 (.Y(n_135),
	.A(n_55),
	.B(n_93));
   OAI21XL g8084__7410 (.Y(n_83),
	.A0(n_38),
	.A1(n_107),
	.B0(n_54));
   NOR2XL g8086__6417 (.Y(n_90),
	.A(n_53),
	.B(n_52));
   INVXL g8064 (.Y(n_51),
	.A(n_95));
   NOR2XL g8051__5477 (.Y(n_50),
	.A(n_94),
	.B(n_118));
   XNOR2X1 g8081__2398 (.Y(n_49),
	.A(n_115),
	.B(n_47));
   NOR2BX1 g8076__5107 (.Y(n_63),
	.AN(n_53),
	.B(n_46));
   INVXL g8087 (.Y(n_48),
	.A(n_105));
   XNOR2X1 g8082__4319 (.Y(n_67),
	.A(n_107),
	.B(n_115));
   OA21X1 g8083__8428 (.Y(n_65),
	.A0(n_268),
	.A1(n_46),
	.B0(n_118));
   INVXL g8088 (.Y(n_80),
	.A(n_56));
   OAI21XL g8061__5526 (.Y(n_57),
	.A0(n_268),
	.A1(n_45),
	.B0(n_103));
   INVXL g8073 (.Y(n_70),
	.A(n_116));
   NAND2BXL g8090__6783 (.Y(n_54),
	.AN(n_44),
	.B(n_115));
   XNOR2X1 g8085__3680 (.Y(n_95),
	.A(n_268),
	.B(n_45));
   NOR2XL g8094__1617 (.Y(n_52),
	.A(n_103),
	.B(n_43));
   NOR2XL g8097__2802 (.Y(n_66),
	.A(n_94),
	.B(n_43));
   NOR2XL g8093__1705 (.Y(n_56),
	.A(n_42),
	.B(n_47));
   NAND2XL g8091__5122 (.Y(n_93),
	.A(n_55),
	.B(n_43));
   NAND2XL g8092__8246 (.Y(n_105),
	.A(n_37),
	.B(n_115));
   NOR2XL g8095__7098 (.Y(n_53),
	.A(n_94),
	.B(n_268));
   OAI21XL g8096__6131 (.Y(n_91),
	.A0(n_114),
	.A1(n_94),
	.B0(n_41));
   NAND2XL g8098__1881 (.Y(n_118),
	.A(n_268),
	.B(n_46));
   INVXL g8100 (.Y(n_40),
	.A(n_42));
   OAI21XL g8099__5115 (.Y(n_116),
	.A0(n_114),
	.A1(n_134),
	.B0(n_96));
   NAND2XL g8109__7482 (.Y(n_44),
	.A(n_38),
	.B(n_107));
   NOR2XL g8105__4733 (.Y(n_42),
	.A(n_37),
	.B(n_38));
   OAI211X1 g8107__6161 (.Y(n_115),
	.A0(n_181),
	.A1(n_7),
	.B0(n_27),
	.C0(n_33));
   NOR2XL g8113__9315 (.Y(n_106),
	.A(n_102),
	.B(n_107));
   INVXL g8101 (.Y(n_43),
	.A(n_268));
   NOR2XL g8114__9945 (.Y(n_119),
	.A(n_134),
	.B(n_103));
   OAI2BB1X1 g8108__2883 (.Y(n_36),
	.A0N(n_34),
	.A1N(n_102),
	.B0(n_97));
   NOR2XL g8104__2346 (.Y(n_47),
	.A(n_97),
	.B(n_102));
   NAND2XL g8110__7410 (.Y(n_41),
	.A(n_114),
	.B(n_94));
   NOR2XL g8111__6417 (.Y(n_46),
	.A(n_62),
	.B(n_134));
   NAND2XL g8112__5477 (.Y(n_45),
	.A(n_62),
	.B(n_134));
   NAND2XL g8103__2398 (.Y(n_96),
	.A(n_114),
	.B(n_134));
   INVXL g8115 (.Y(n_38),
	.A(n_97));
   INVXL g8121 (.Y(n_103),
	.A(n_94));
   INVXL g8125 (.Y(n_55),
	.A(n_134));
   NAND2XL g8123__5107 (.Y(n_107),
	.A(n_35),
	.B(n_34));
   AOI22XL g8127__6260 (.Y(n_33),
	.A0(n_21),
	.A1(n_153),
	.B0(lambda2[3]),
	.B1(n_29));
   INVXL g8120 (.Y(n_37),
	.A(n_102));
   NAND3BXL g8124__4319 (.Y(n_94),
	.AN(n_32),
	.B(n_24),
	.C(n_71));
   OAI211X1 g8129__8428 (.Y(n_134),
	.A0(lambda1[2]),
	.A1(n_8),
	.B0(n_23),
	.C0(n_16));
   OAI222XL g8117__5526 (.Y(n_31),
	.A0(n_146),
	.A1(n_1),
	.B0(n_20),
	.B1(n_226),
	.C0(lambda1[1]),
	.C1(n_22));
   AOI22XL g8126__6783 (.Y(n_30),
	.A0(lambda1[1]),
	.A1(n_169),
	.B0(n_146),
	.B1(n_153));
   INVXL g8116 (.Y(n_62),
	.A(n_114));
   OAI21XL g8118__3680 (.Y(n_97),
	.A0(lambda2[0]),
	.A1(n_29),
	.B0(n_25));
   AND4X2 g8130__1617 (.Y(error_vector[0]),
	.A(n_12),
	.B(n_13),
	.C(n_14),
	.D(n_10));
   AOI221X1 g8131__2802 (.Y(n_34),
	.A0(lambda2[0]),
	.A1(lambda2[2]),
	.B0(lambda2[1]),
	.B1(n_6),
	.C0(n_28));
   OAI221X1 g8122__1705 (.Y(n_102),
	.A0(lambda2[0]),
	.A1(n_4),
	.B0(lambda2[2]),
	.B1(n_27),
	.C0(n_26));
   AOI222X1 g8119__5122 (.Y(n_114),
	.A0(lambda1[1]),
	.A1(n_0),
	.B0(n_157),
	.B1(n_3),
	.C0(lambda1[2]),
	.C1(n_32));
   INVXL g8134 (.Y(n_68),
	.A(n_35));
   AOI32X1 g8128__8246 (.Y(n_25),
	.A0(lambda2[3]),
	.A1(lambda2[1]),
	.A2(n_183),
	.B0(n_5),
	.B1(n_29));
   AOI32X1 g8139__7098 (.Y(n_24),
	.A0(lambda1[3]),
	.A1(lambda1[1]),
	.A2(n_157),
	.B0(lambda1[0]),
	.B1(lambda1[2]));
   INVXL g8133 (.Y(n_155),
	.A(n_226));
   INVXL g8132 (.Y(n_153),
	.A(n_169));
   OAI2BB1X1 g8135__6131 (.Y(n_23),
	.A0N(lambda1[1]),
	.A1N(n_22),
	.B0(n_157));
   NAND3XL g8137__1881 (.Y(n_35),
	.A(n_181),
	.B(n_183),
	.C(n_21));
   NAND3BXL g8136__5115 (.Y(n_71),
	.AN(n_20),
	.B(n_146),
	.C(n_19));
   AOI22XL g8150__7482 (.Y(n_18),
	.A0(lambda1[3]),
	.A1(n_138),
	.B0(lambda2[0]),
	.B1(n_17));
   NAND4XL g8138__4733 (.Y(n_16),
	.A(lambda1[0]),
	.B(lambda1[2]),
	.C(lambda1[1]),
	.D(n_17));
   AOI22XL g8141__6161 (.Y(n_15),
	.A0(n_17),
	.A1(n_183),
	.B0(lambda2[2]),
	.B1(lambda1[3]));
   AOI22XL g8151__9315 (.Y(n_14),
	.A0(lambda1[3]),
	.A1(n_143),
	.B0(lambda2[3]),
	.B1(n_17));
   OAI22XL g8148__9945 (.Y(n_13),
	.A0(lambda2[1]),
	.A1(lambda1[1]),
	.B0(n_181),
	.B1(n_146));
   NAND4XL g8140__2883 (.Y(n_26),
	.A(lambda2[0]),
	.B(lambda2[2]),
	.C(lambda2[1]),
	.D(n_143));
   AOI22XL g8153__2346 (.Y(n_226),
	.A0(n_19),
	.A1(n_146),
	.B0(lambda1[1]),
	.B1(lambda1[2]));
   AOI22XL g8143__1666 (.Y(n_12),
	.A0(n_157),
	.A1(n_138),
	.B0(lambda2[0]),
	.B1(lambda1[0]));
   AOI22XL g8149__7410 (.Y(n_11),
	.A0(lambda1[2]),
	.A1(n_143),
	.B0(lambda2[3]),
	.B1(n_19));
   AOI22XL g8147__6417 (.Y(n_10),
	.A0(lambda1[2]),
	.A1(n_183),
	.B0(lambda2[2]),
	.B1(n_19));
   AOI22XL g8152__5477 (.Y(n_9),
	.A0(lambda1[2]),
	.A1(n_181),
	.B0(lambda2[1]),
	.B1(n_19));
   NOR2XL g8144__2398 (.Y(n_28),
	.A(lambda2[1]),
	.B(n_27));
   NOR2XL g8145__5107 (.Y(n_32),
	.A(lambda1[1]),
	.B(n_8));
   AOI22XL g8146__6260 (.Y(n_169),
	.A0(n_183),
	.A1(n_181),
	.B0(lambda2[1]),
	.B1(lambda2[2]));
   NAND2XL g8164__4319 (.Y(n_7),
	.A(lambda2[0]),
	.B(n_183));
   NOR2XL g8162__8428 (.Y(n_6),
	.A(lambda2[0]),
	.B(n_143));
   INVXL g8155 (.Y(n_5),
	.A(n_27));
   NAND2XL g8158__5526 (.Y(n_20),
	.A(n_17),
	.B(n_157));
   NOR2XL g8166__6783 (.Y(n_29),
	.A(lambda2[1]),
	.B(n_183));
   AOI21XL g8142__3680 (.Y(n_4),
	.A0(lambda2[2]),
	.A1(lambda2[3]),
	.B0(n_181));
   NAND2XL g8165__1617 (.Y(n_3),
	.A(lambda1[2]),
	.B(n_146));
   NAND2XL g8163__2802 (.Y(n_1),
	.A(lambda1[0]),
	.B(n_19));
   NOR2XL g8161__1705 (.Y(n_0),
	.A(lambda1[2]),
	.B(n_17));
   NAND2XL g8157__5122 (.Y(n_22),
	.A(lambda1[2]),
	.B(lambda1[3]));
   NOR2XL g8156__8246 (.Y(n_21),
	.A(lambda2[0]),
	.B(lambda2[3]));
   NAND2XL g8159__7098 (.Y(n_8),
	.A(lambda1[0]),
	.B(lambda1[3]));
   NAND2XL g8160__6131 (.Y(n_27),
	.A(lambda2[0]),
	.B(lambda2[3]));
   INVXL g8172 (.Y(n_138),
	.A(lambda2[0]));
   INVXL g8167 (.Y(n_17),
	.A(lambda1[3]));
   INVXL g8168 (.Y(n_157),
	.A(lambda1[0]));
   INVXL g8170 (.Y(n_183),
	.A(lambda2[2]));
   INVXL g8171 (.Y(n_143),
	.A(lambda2[3]));
   INVXL g8173 (.Y(n_19),
	.A(lambda1[2]));
   INVXL g8174 (.Y(n_146),
	.A(lambda1[1]));
   INVXL g8169 (.Y(n_181),
	.A(lambda2[1]));
   MXI2XL g2 (.Y(n_264),
	.A(n_198),
	.B(n_196),
	.S0(n_192));
   XOR2XL g8175 (.Y(n_265),
	.A(n_228),
	.B(n_238));
   NAND3X1 g8176 (.Y(n_266),
	.A(n_113),
	.B(n_94),
	.C(n_98));
   NAND2BX1 g8177 (.Y(n_267),
	.AN(n_115),
	.B(n_47));
   NOR2BX1 g8178 (.Y(n_268),
	.AN(n_8),
	.B(n_31));
endmodule

