/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Oct  6 17:07:00 2025
#  Design:            bch_toplevel
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_toplevel/bch_toplevel_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 24 2025 12:00:03 -03 (Sep 24 2025 15:00:03 UTC)
// Verification Directory fv/bch_toplevel 
module gf_divider (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;

   NAND3BXL g2084__2398 (.Y(q[2]),
	.AN(n_78),
	.B(n_74),
	.C(n_77));
   OAI211X1 g2085__5107 (.Y(q[0]),
	.A0(n_70),
	.A1(n_71),
	.B0(n_76),
	.C0(n_77));
   OAI211X1 g2086__6260 (.Y(q[1]),
	.A0(n_67),
	.A1(n_71),
	.B0(n_74),
	.C0(n_72));
   OAI211X1 g2087__4319 (.Y(q[3]),
	.A0(n_69),
	.A1(n_68),
	.B0(n_75),
	.C0(n_77));
   OAI221X1 g2088__8428 (.Y(n_78),
	.A0(n_66),
	.A1(n_69),
	.B0(n_61),
	.B1(n_71),
	.C0(n_73));
   NAND3XL g2089__5526 (.Y(n_76),
	.A(n_29),
	.B(n_54),
	.C(n_70));
   NAND3BXL g2090__6783 (.Y(n_75),
	.AN(n_70),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2091__3680 (.Y(n_77),
	.AN(n_69),
	.B(n_62),
	.C(n_65));
   NAND3BXL g2092__1617 (.Y(n_73),
	.AN(n_70),
	.B(n_29),
	.C(n_54));
   NAND3BXL g2093__2802 (.Y(n_72),
	.AN(n_68),
	.B(n_29),
	.C(n_62));
   NAND3BXL g2094__1705 (.Y(n_74),
	.AN(n_69),
	.B(n_61),
	.C(n_64));
   NAND3BXL g2095__5122 (.Y(n_71),
	.AN(n_54),
	.B(n_29),
	.C(n_65));
   OR2X1 g2096__8246 (.Y(n_70),
	.A(n_62),
	.B(n_67));
   NAND2XL g2097__7098 (.Y(n_69),
	.A(n_29),
	.B(n_67));
   XNOR2X1 g2098__6131 (.Y(n_68),
	.A(n_54),
	.B(n_64));
   XNOR2X1 g2099__1881 (.Y(n_67),
	.A(n_59),
	.B(n_63));
   NAND2XL g2100__5115 (.Y(n_66),
	.A(n_54),
	.B(n_64));
   INVX1 g2101 (.Y(n_64),
	.A(n_65));
   ADDFX1 g2102__7482 (.CO(n_63),
	.S(n_65),
	.A(n_55),
	.B(n_52),
	.CI(n_60));
   INVX1 g2103 (.Y(n_62),
	.A(n_61));
   ADDFX1 g2104__4733 (.CO(n_60),
	.S(n_61),
	.A(n_37),
	.B(n_51),
	.CI(n_53));
   XNOR2X1 g2105__6161 (.Y(n_59),
	.A(n_57),
	.B(n_58));
   XNOR2X1 g2106__9315 (.Y(n_58),
	.A(n_27),
	.B(n_56));
   OAI21XL g2107__9945 (.Y(n_57),
	.A0(n_45),
	.A1(n_50),
	.B0(n_44));
   XNOR2X1 g2108__2883 (.Y(n_56),
	.A(n_26),
	.B(n_50));
   OAI21XL g2109__2346 (.Y(n_55),
	.A0(n_40),
	.A1(n_50),
	.B0(n_42));
   XNOR2X1 g2110__1666 (.Y(n_53),
	.A(n_43),
	.B(n_50));
   XNOR2X1 g2111__7410 (.Y(n_52),
	.A(n_46),
	.B(n_50));
   XNOR2X1 g2112__6417 (.Y(n_54),
	.A(n_39),
	.B(n_50));
   NOR2XL g2113__5477 (.Y(n_51),
	.A(n_39),
	.B(n_50));
   OAI22XL g2114__2398 (.Y(n_50),
	.A0(n_35),
	.A1(n_49),
	.B0(n_26),
	.B1(n_28));
   OA21X1 g2115__5107 (.Y(n_49),
	.A0(n_45),
	.A1(n_48),
	.B0(n_44));
   NOR2BX1 g2116__6260 (.Y(n_48),
	.AN(n_42),
	.B(n_47));
   NOR2BX1 g2117__4319 (.Y(n_47),
	.AN(n_37),
	.B(n_40));
   XNOR2X1 g2118__8428 (.Y(n_46),
	.A(n_41),
	.B(n_38));
   NOR2BX1 g2119__5526 (.Y(n_45),
	.AN(n_41),
	.B(n_38));
   NAND2BXL g2120__6783 (.Y(n_44),
	.AN(n_41),
	.B(n_38));
   XNOR2X1 g2121__3680 (.Y(n_43),
	.A(n_36),
	.B(n_34));
   NAND2BXL g2122__1617 (.Y(n_42),
	.AN(n_36),
	.B(n_34));
   NAND2XL g2123__2802 (.Y(n_41),
	.A(n_7),
	.B(n_33));
   NOR2BX1 g2124__1705 (.Y(n_40),
	.AN(n_36),
	.B(n_34));
   OA21X1 g2125__5122 (.Y(n_39),
	.A0(n_31),
	.A1(n_30),
	.B0(n_37));
   NAND2XL g2126__8246 (.Y(n_38),
	.A(n_9),
	.B(n_32));
   AND2X1 g2127__7098 (.Y(n_35),
	.A(n_28),
	.B(n_26));
   NAND2XL g2128__6131 (.Y(n_37),
	.A(n_31),
	.B(n_30));
   OAI211X1 g2129__1881 (.Y(n_36),
	.A0(n_3),
	.A1(n_20),
	.B0(n_16),
	.C0(n_23));
   AOI31X1 g2130__5115 (.Y(n_33),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_1),
	.B0(n_25));
   AOI31X1 g2131__7482 (.Y(n_32),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_0),
	.B0(n_24));
   OAI222XL g2132__4733 (.Y(n_34),
	.A0(a[0]),
	.A1(n_21),
	.B0(n_4),
	.B1(n_19),
	.C0(n_9),
	.C1(a[2]));
   OAI222XL g2133__6161 (.Y(n_31),
	.A0(b[0]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_12),
	.C0(n_14),
	.C1(b[2]));
   AOI221X1 g2134__9315 (.Y(n_30),
	.A0(n_18),
	.A1(n_0),
	.B0(n_4),
	.B1(n_10),
	.C0(n_22));
   AOI33XL g2135__9945 (.Y(n_29),
	.A0(n_2),
	.A1(n_15),
	.A2(n_1),
	.B0(n_13),
	.B1(n_4),
	.B2(n_0));
   INVXL g2136 (.Y(n_28),
	.A(n_27));
   OAI22XL g2137__2883 (.Y(n_25),
	.A0(b[0]),
	.A1(n_20),
	.B0(n_2),
	.B1(n_12));
   OAI22XL g2138__2346 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2139__1666 (.Y(n_27),
	.A0(n_4),
	.A1(n_0),
	.B0(a[1]),
	.B1(n_9),
	.C0(a[0]),
	.C1(n_17));
   OAI222XL g2140__7410 (.Y(n_26),
	.A0(n_3),
	.A1(n_1),
	.B0(b[1]),
	.B1(n_7),
	.C0(b[0]),
	.C1(n_14));
   AOI32X1 g2141__6417 (.Y(n_23),
	.A0(b[3]),
	.A1(n_3),
	.A2(b[2]),
	.B0(n_8),
	.B1(n_1));
   NOR2XL g2142__5477 (.Y(n_22),
	.A(n_9),
	.B(n_10));
   AOI21XL g2143__2398 (.Y(n_21),
	.A0(a[3]),
	.A1(a[2]),
	.B0(n_5));
   NAND3BXL g2144__5107 (.Y(n_20),
	.AN(n_1),
	.B(b[1]),
	.C(n_2));
   NAND3XL g2145__6260 (.Y(n_19),
	.A(n_6),
	.B(a[1]),
	.C(a[2]));
   INVXL g2146 (.Y(n_18),
	.A(n_17));
   INVXL g2147 (.Y(n_16),
	.A(n_15));
   NOR2XL g2148__4319 (.Y(n_13),
	.A(a[3]),
	.B(a[1]));
   NAND2XL g2149__8428 (.Y(n_17),
	.A(a[3]),
	.B(a[1]));
   NOR2XL g2150__5526 (.Y(n_15),
	.A(b[1]),
	.B(b[0]));
   NAND2XL g2151__6783 (.Y(n_14),
	.A(b[1]),
	.B(b[3]));
   INVXL g2152 (.Y(n_12),
	.A(n_11));
   INVXL g2153 (.Y(n_8),
	.A(n_7));
   NOR2XL g2154__3680 (.Y(n_11),
	.A(b[1]),
	.B(n_1));
   NAND2XL g2155__1617 (.Y(n_10),
	.A(n_5),
	.B(a[2]));
   NAND2XL g2156__2802 (.Y(n_9),
	.A(a[3]),
	.B(a[0]));
   NAND2XL g2157__1705 (.Y(n_7),
	.A(b[0]),
	.B(b[3]));
   INVXL g2158 (.Y(n_6),
	.A(a[3]));
   INVXL g2159 (.Y(n_5),
	.A(a[1]));
   INVX1 g2160 (.Y(n_4),
	.A(a[0]));
   INVX1 g2161 (.Y(n_3),
	.A(b[0]));
   INVX1 g2162 (.Y(n_2),
	.A(b[3]));
   INVX1 g2163 (.Y(n_1),
	.A(b[2]));
   INVX1 g2164 (.Y(n_0),
	.A(a[2]));
endmodule

module gf_divider_484 (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;

   NAND3BXL g2084__5122 (.Y(q[2]),
	.AN(n_78),
	.B(n_74),
	.C(n_77));
   OAI211X1 g2085__8246 (.Y(q[0]),
	.A0(n_70),
	.A1(n_71),
	.B0(n_76),
	.C0(n_77));
   OAI211X1 g2086__7098 (.Y(q[1]),
	.A0(n_67),
	.A1(n_71),
	.B0(n_74),
	.C0(n_72));
   OAI211X1 g2087__6131 (.Y(q[3]),
	.A0(n_69),
	.A1(n_68),
	.B0(n_75),
	.C0(n_77));
   OAI221X1 g2088__1881 (.Y(n_78),
	.A0(n_69),
	.A1(n_66),
	.B0(n_61),
	.B1(n_71),
	.C0(n_73));
   NAND3XL g2089__5115 (.Y(n_76),
	.A(n_29),
	.B(n_54),
	.C(n_70));
   NAND3BXL g2090__7482 (.Y(n_75),
	.AN(n_70),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2091__4733 (.Y(n_77),
	.AN(n_69),
	.B(n_62),
	.C(n_65));
   NAND3BXL g2092__6161 (.Y(n_73),
	.AN(n_70),
	.B(n_29),
	.C(n_54));
   NAND3BXL g2093__9315 (.Y(n_72),
	.AN(n_68),
	.B(n_29),
	.C(n_62));
   NAND3BXL g2094__9945 (.Y(n_74),
	.AN(n_69),
	.B(n_61),
	.C(n_64));
   NAND3BXL g2095__2883 (.Y(n_71),
	.AN(n_54),
	.B(n_29),
	.C(n_65));
   OR2X1 g2096__2346 (.Y(n_70),
	.A(n_62),
	.B(n_67));
   NAND2XL g2097__1666 (.Y(n_69),
	.A(n_29),
	.B(n_67));
   XNOR2X1 g2098__7410 (.Y(n_68),
	.A(n_54),
	.B(n_64));
   XNOR2X1 g2099__6417 (.Y(n_67),
	.A(n_59),
	.B(n_63));
   NAND2XL g2100__5477 (.Y(n_66),
	.A(n_54),
	.B(n_64));
   INVX1 g2101 (.Y(n_64),
	.A(n_65));
   ADDFX1 g2102__2398 (.CO(n_63),
	.S(n_65),
	.A(n_55),
	.B(n_52),
	.CI(n_60));
   INVX1 g2103 (.Y(n_62),
	.A(n_61));
   ADDFX1 g2104__5107 (.CO(n_60),
	.S(n_61),
	.A(n_37),
	.B(n_51),
	.CI(n_53));
   XNOR2X1 g2105__6260 (.Y(n_59),
	.A(n_57),
	.B(n_58));
   XNOR2X1 g2106__4319 (.Y(n_58),
	.A(n_27),
	.B(n_56));
   OAI21XL g2107__8428 (.Y(n_57),
	.A0(n_45),
	.A1(n_50),
	.B0(n_44));
   XNOR2X1 g2108__5526 (.Y(n_56),
	.A(n_26),
	.B(n_50));
   OAI21XL g2109__6783 (.Y(n_55),
	.A0(n_40),
	.A1(n_50),
	.B0(n_42));
   XNOR2X1 g2110__3680 (.Y(n_53),
	.A(n_43),
	.B(n_50));
   XNOR2X1 g2111__1617 (.Y(n_52),
	.A(n_46),
	.B(n_50));
   XNOR2X1 g2112__2802 (.Y(n_54),
	.A(n_39),
	.B(n_50));
   NOR2XL g2113__1705 (.Y(n_51),
	.A(n_39),
	.B(n_50));
   OAI22XL g2114__5122 (.Y(n_50),
	.A0(n_35),
	.A1(n_49),
	.B0(n_26),
	.B1(n_28));
   OA21X1 g2115__8246 (.Y(n_49),
	.A0(n_45),
	.A1(n_48),
	.B0(n_44));
   NOR2BX1 g2116__7098 (.Y(n_48),
	.AN(n_42),
	.B(n_47));
   NOR2BX1 g2117__6131 (.Y(n_47),
	.AN(n_37),
	.B(n_40));
   XNOR2X1 g2118__1881 (.Y(n_46),
	.A(n_41),
	.B(n_38));
   NOR2BX1 g2119__5115 (.Y(n_45),
	.AN(n_41),
	.B(n_38));
   NAND2BXL g2120__7482 (.Y(n_44),
	.AN(n_41),
	.B(n_38));
   XNOR2X1 g2121__4733 (.Y(n_43),
	.A(n_36),
	.B(n_34));
   NAND2BXL g2122__6161 (.Y(n_42),
	.AN(n_36),
	.B(n_34));
   NAND2XL g2123__9315 (.Y(n_41),
	.A(n_7),
	.B(n_33));
   NOR2BX1 g2124__9945 (.Y(n_40),
	.AN(n_36),
	.B(n_34));
   OA21X1 g2125__2883 (.Y(n_39),
	.A0(n_31),
	.A1(n_30),
	.B0(n_37));
   NAND2XL g2126__2346 (.Y(n_38),
	.A(n_9),
	.B(n_32));
   AND2X1 g2127__1666 (.Y(n_35),
	.A(n_28),
	.B(n_26));
   NAND2XL g2128__7410 (.Y(n_37),
	.A(n_31),
	.B(n_30));
   OAI211X1 g2129__6417 (.Y(n_36),
	.A0(n_3),
	.A1(n_20),
	.B0(n_16),
	.C0(n_23));
   AOI31X1 g2130__5477 (.Y(n_33),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_1),
	.B0(n_25));
   AOI31X1 g2131__2398 (.Y(n_32),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_0),
	.B0(n_24));
   OAI222XL g2132__5107 (.Y(n_34),
	.A0(a[0]),
	.A1(n_21),
	.B0(n_4),
	.B1(n_19),
	.C0(n_9),
	.C1(a[2]));
   OAI222XL g2133__6260 (.Y(n_31),
	.A0(b[0]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_12),
	.C0(n_14),
	.C1(b[2]));
   AOI221X1 g2134__4319 (.Y(n_30),
	.A0(n_4),
	.A1(n_10),
	.B0(n_18),
	.B1(n_0),
	.C0(n_22));
   AOI33XL g2135__8428 (.Y(n_29),
	.A0(n_2),
	.A1(n_15),
	.A2(n_1),
	.B0(n_13),
	.B1(n_4),
	.B2(n_0));
   INVXL g2136 (.Y(n_28),
	.A(n_27));
   OAI22XL g2137__5526 (.Y(n_25),
	.A0(b[0]),
	.A1(n_20),
	.B0(n_2),
	.B1(n_12));
   OAI22XL g2138__6783 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2139__3680 (.Y(n_27),
	.A0(n_4),
	.A1(n_0),
	.B0(a[1]),
	.B1(n_9),
	.C0(a[0]),
	.C1(n_17));
   OAI222XL g2140__1617 (.Y(n_26),
	.A0(n_3),
	.A1(n_1),
	.B0(b[1]),
	.B1(n_7),
	.C0(b[0]),
	.C1(n_14));
   AOI32X1 g2141__2802 (.Y(n_23),
	.A0(b[3]),
	.A1(n_3),
	.A2(b[2]),
	.B0(n_8),
	.B1(n_1));
   NOR2XL g2142__1705 (.Y(n_22),
	.A(n_9),
	.B(n_10));
   AOI21XL g2143__5122 (.Y(n_21),
	.A0(a[3]),
	.A1(a[2]),
	.B0(n_5));
   NAND3BXL g2144__8246 (.Y(n_20),
	.AN(n_1),
	.B(b[1]),
	.C(n_2));
   NAND3BXL g2145__7098 (.Y(n_19),
	.AN(n_0),
	.B(n_6),
	.C(a[1]));
   INVXL g2146 (.Y(n_18),
	.A(n_17));
   INVXL g2147 (.Y(n_16),
	.A(n_15));
   NOR2XL g2148__6131 (.Y(n_13),
	.A(a[3]),
	.B(a[1]));
   NAND2XL g2149__1881 (.Y(n_17),
	.A(a[3]),
	.B(a[1]));
   NOR2XL g2150__5115 (.Y(n_15),
	.A(b[1]),
	.B(b[0]));
   NAND2XL g2151__7482 (.Y(n_14),
	.A(b[1]),
	.B(b[3]));
   INVXL g2152 (.Y(n_12),
	.A(n_11));
   INVXL g2153 (.Y(n_8),
	.A(n_7));
   NOR2XL g2154__4733 (.Y(n_11),
	.A(b[1]),
	.B(n_1));
   NAND2XL g2155__6161 (.Y(n_10),
	.A(n_5),
	.B(a[2]));
   NAND2XL g2156__9315 (.Y(n_9),
	.A(a[3]),
	.B(a[0]));
   NAND2XL g2157__9945 (.Y(n_7),
	.A(b[0]),
	.B(b[3]));
   INVXL g2158 (.Y(n_6),
	.A(a[3]));
   INVXL g2159 (.Y(n_5),
	.A(a[1]));
   INVX1 g2160 (.Y(n_4),
	.A(a[0]));
   INVX1 g2161 (.Y(n_3),
	.A(b[0]));
   INVX1 g2162 (.Y(n_2),
	.A(b[3]));
   INVX1 g2163 (.Y(n_1),
	.A(b[2]));
   INVX1 g2164 (.Y(n_0),
	.A(a[2]));
endmodule

module ff_4 (
	clk, 
	rst, 
	a, 
	q);
   input clk;
   input rst;
   input [3:0] a;
   output [3:0] q;

   DFFRHQX1 \q_reg[0]  (.Q(q[0]),
	.D(a[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \q_reg[3]  (.Q(q[3]),
	.D(a[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \q_reg[1]  (.Q(q[1]),
	.D(a[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \q_reg[2]  (.Q(q[2]),
	.D(a[2]),
	.RN(rst),
	.CK(clk));
endmodule

module ff_4_615 (
	clk, 
	rst, 
	a, 
	q);
   input clk;
   input rst;
   input [3:0] a;
   output [3:0] q;

   DFFRHQX1 \q_reg[0]  (.Q(q[0]),
	.D(a[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \q_reg[3]  (.Q(q[3]),
	.D(a[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \q_reg[1]  (.Q(q[1]),
	.D(a[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \q_reg[2]  (.Q(q[2]),
	.D(a[2]),
	.RN(rst),
	.CK(clk));
endmodule

module gf_multiplier (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__2883 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__2346 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__1666 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__7410 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__6417 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__5477 (.Y(n_74),
	.AN(n_68),
	.B(n_57),
	.C(n_61));
   NAND2XL g1996__2398 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__5107 (.Y(n_70),
	.A0(n_56),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__6260 (.Y(n_71),
	.A0(n_56),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__4319 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__8428 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__5526 (.Y(n_67),
	.A(n_56),
	.B(n_65));
   AOI21XL g2003__6783 (.Y(n_66),
	.A0(n_55),
	.A1(n_57),
	.B0(n_63));
   XNOR2X1 g2004__3680 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__1617 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__2802 (.Y(n_62),
	.A(n_57),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__1705 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__5122 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__8246 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__7098 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__6131 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__1881 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__5115 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI211XL g2017__7482 (.Y(n_52),
	.A0(n_37),
	.A1(n_47),
	.B0(n_38),
	.C0(n_51));
   NOR2XL g2018__4733 (.Y(n_51),
	.A(n_49),
	.B(n_50));
   NAND3BXL g2019__6161 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__9315 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__9945 (.CO(n_47),
	.S(n_48),
	.A(n_43),
	.B(n_44),
	.CI(n_45));
   ADDFX1 g2022__2883 (.CO(n_45),
	.S(n_46),
	.A(n_41),
	.B(n_39),
	.CI(n_36));
   OAI211X1 g2023__2346 (.Y(n_44),
	.A0(n_9),
	.A1(n_34),
	.B0(n_14),
	.C0(n_21));
   OAI211X1 g2024__1666 (.Y(n_43),
	.A0(n_10),
	.A1(n_33),
	.B0(n_15),
	.C0(n_23));
   NOR2BX1 g2025__7410 (.Y(n_42),
	.AN(n_37),
	.B(n_38));
   OAI221X1 g2026__6417 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__5477 (.Y(n_39),
	.A0(n_27),
	.A1(n_1),
	.B0(n_14),
	.B1(b[2]),
	.C0(n_19));
   XNOR2X1 g2028__2398 (.Y(n_40),
	.A(n_35),
	.B(n_30));
   NOR2XL g2029__5107 (.Y(n_38),
	.A(n_32),
	.B(n_31));
   NAND2XL g2030__6260 (.Y(n_37),
	.A(n_32),
	.B(n_31));
   NOR2XL g2031__4319 (.Y(n_36),
	.A(n_35),
	.B(n_30));
   AOI22XL g2032__8428 (.Y(n_34),
	.A0(n_4),
	.A1(n_22),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__5526 (.Y(n_33),
	.A0(n_5),
	.A1(n_24),
	.B0(a[0]),
	.B1(n_11));
   AOI221X1 g2034__6783 (.Y(n_35),
	.A0(n_10),
	.A1(n_16),
	.B0(a[3]),
	.B1(n_11),
	.C0(n_20));
   AOI222X1 g2035__3680 (.Y(n_32),
	.A0(a[1]),
	.A1(n_12),
	.B0(n_7),
	.B1(n_16),
	.C0(a[2]),
	.C1(a[0]));
   AOI221X1 g2036__1617 (.Y(n_31),
	.A0(b[0]),
	.A1(b[2]),
	.B0(b[1]),
	.B1(n_13),
	.C0(n_25));
   AOI221X1 g2037__2802 (.Y(n_30),
	.A0(b[3]),
	.A1(n_17),
	.B0(n_4),
	.B1(n_8),
	.C0(n_26));
   OAI33X1 g2038__1705 (.Y(n_29),
	.A0(b[3]),
	.A1(n_19),
	.A2(b[2]),
	.B0(a[2]),
	.B1(a[3]),
	.B2(n_18));
   AOI31X1 g2039__5122 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_12));
   AOI31X1 g2040__8246 (.Y(n_27),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_0),
	.B0(n_13));
   NOR2XL g2041__7098 (.Y(n_26),
	.A(n_14),
	.B(n_8));
   NOR2XL g2042__6131 (.Y(n_25),
	.A(b[1]),
	.B(n_14));
   NOR2XL g2043__1881 (.Y(n_24),
	.A(a[3]),
	.B(n_11));
   NAND2XL g2044__5115 (.Y(n_23),
	.A(a[3]),
	.B(n_10));
   NOR2XL g2045__7482 (.Y(n_22),
	.A(b[3]),
	.B(n_17));
   NAND2XL g2046__4733 (.Y(n_21),
	.A(b[3]),
	.B(n_9));
   NOR2XL g2047__6161 (.Y(n_20),
	.A(a[0]),
	.B(n_10));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   NAND2XL g2049__9315 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2050__9945 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2051__2883 (.Y(n_17),
	.A(n_3),
	.B(b[2]));
   NOR2XL g2052__2346 (.Y(n_16),
	.A(n_6),
	.B(n_5));
   NAND2XL g2053__1666 (.Y(n_14),
	.A(b[0]),
	.B(b[3]));
   INVXL g2054 (.Y(n_8),
	.A(n_9));
   NOR2XL g2055__7410 (.Y(n_13),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__6417 (.Y(n_12),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__5477 (.Y(n_11),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__2398 (.Y(n_10),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__5107 (.Y(n_9),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVX1 g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVXL g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module gf_multiplier_487 (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__6260 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__4319 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__8428 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__5526 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__6783 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__3680 (.Y(n_74),
	.AN(n_68),
	.B(n_57),
	.C(n_61));
   NAND2XL g1996__1617 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__2802 (.Y(n_70),
	.A0(n_56),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__1705 (.Y(n_71),
	.A0(n_56),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__5122 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__8246 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__7098 (.Y(n_67),
	.A(n_56),
	.B(n_65));
   AOI21XL g2003__6131 (.Y(n_66),
	.A0(n_55),
	.A1(n_57),
	.B0(n_63));
   XNOR2X1 g2004__1881 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__5115 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__7482 (.Y(n_62),
	.A(n_57),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__4733 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__6161 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__9315 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__9945 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__2883 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__2346 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__1666 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI211XL g2017__7410 (.Y(n_52),
	.A0(n_37),
	.A1(n_47),
	.B0(n_38),
	.C0(n_51));
   NOR2XL g2018__6417 (.Y(n_51),
	.A(n_49),
	.B(n_50));
   NAND3BXL g2019__5477 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__2398 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__5107 (.CO(n_47),
	.S(n_48),
	.A(n_43),
	.B(n_44),
	.CI(n_45));
   ADDFX1 g2022__6260 (.CO(n_45),
	.S(n_46),
	.A(n_41),
	.B(n_39),
	.CI(n_36));
   OAI211X1 g2023__4319 (.Y(n_44),
	.A0(n_9),
	.A1(n_34),
	.B0(n_14),
	.C0(n_21));
   OAI211X1 g2024__8428 (.Y(n_43),
	.A0(n_10),
	.A1(n_33),
	.B0(n_15),
	.C0(n_23));
   NOR2BX1 g2025__5526 (.Y(n_42),
	.AN(n_37),
	.B(n_38));
   OAI221X1 g2026__6783 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__3680 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_14),
	.C0(n_19));
   XNOR2X1 g2028__1617 (.Y(n_40),
	.A(n_35),
	.B(n_30));
   NOR2XL g2029__2802 (.Y(n_38),
	.A(n_32),
	.B(n_31));
   NAND2XL g2030__1705 (.Y(n_37),
	.A(n_32),
	.B(n_31));
   NOR2XL g2031__5122 (.Y(n_36),
	.A(n_35),
	.B(n_30));
   AOI22XL g2032__8246 (.Y(n_34),
	.A0(n_4),
	.A1(n_22),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__7098 (.Y(n_33),
	.A0(n_5),
	.A1(n_24),
	.B0(a[0]),
	.B1(n_11));
   AOI221X1 g2034__6131 (.Y(n_35),
	.A0(n_10),
	.A1(n_16),
	.B0(a[3]),
	.B1(n_11),
	.C0(n_20));
   AOI222X1 g2035__1881 (.Y(n_32),
	.A0(a[1]),
	.A1(n_12),
	.B0(n_7),
	.B1(n_16),
	.C0(a[2]),
	.C1(a[0]));
   AOI221X1 g2036__5115 (.Y(n_31),
	.A0(b[2]),
	.A1(b[0]),
	.B0(b[1]),
	.B1(n_13),
	.C0(n_25));
   AOI221X1 g2037__7482 (.Y(n_30),
	.A0(b[3]),
	.A1(n_17),
	.B0(n_4),
	.B1(n_8),
	.C0(n_26));
   OAI33X1 g2038__4733 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[2]),
	.B1(a[3]),
	.B2(n_18));
   AOI31X1 g2039__6161 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_12));
   AOI31X1 g2040__9315 (.Y(n_27),
	.A0(n_0),
	.A1(b[0]),
	.A2(b[1]),
	.B0(n_13));
   NOR2XL g2041__9945 (.Y(n_26),
	.A(n_14),
	.B(n_8));
   NOR2XL g2042__2883 (.Y(n_25),
	.A(b[1]),
	.B(n_14));
   NOR2XL g2043__2346 (.Y(n_24),
	.A(a[3]),
	.B(n_11));
   NAND2XL g2044__1666 (.Y(n_23),
	.A(a[3]),
	.B(n_10));
   NOR2XL g2045__7410 (.Y(n_22),
	.A(b[3]),
	.B(n_17));
   NAND2XL g2046__6417 (.Y(n_21),
	.A(b[3]),
	.B(n_9));
   NOR2XL g2047__5477 (.Y(n_20),
	.A(a[0]),
	.B(n_10));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   NAND2XL g2049__2398 (.Y(n_19),
	.A(n_4),
	.B(n_3));
   NAND2XL g2050__5107 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2051__6260 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NOR2XL g2052__4319 (.Y(n_16),
	.A(n_6),
	.B(n_5));
   NAND2XL g2053__8428 (.Y(n_14),
	.A(b[3]),
	.B(b[0]));
   INVXL g2054 (.Y(n_8),
	.A(n_9));
   NOR2XL g2055__5526 (.Y(n_13),
	.A(n_0),
	.B(b[0]));
   NOR2XL g2056__6783 (.Y(n_12),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__3680 (.Y(n_11),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__1617 (.Y(n_10),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__2802 (.Y(n_9),
	.A(n_1),
	.B(b[1]));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVX1 g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVX1 g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module gf_multiplier_486 (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__1705 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__5122 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__8246 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__7098 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__6131 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__1881 (.Y(n_74),
	.AN(n_68),
	.B(n_57),
	.C(n_61));
   NAND2XL g1996__5115 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__7482 (.Y(n_70),
	.A0(n_56),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__4733 (.Y(n_71),
	.A0(n_56),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__6161 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__9315 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__9945 (.Y(n_67),
	.A(n_56),
	.B(n_65));
   AOI21XL g2003__2883 (.Y(n_66),
	.A0(n_55),
	.A1(n_57),
	.B0(n_63));
   XNOR2X1 g2004__2346 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__1666 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__7410 (.Y(n_62),
	.A(n_57),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__6417 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__5477 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__2398 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__5107 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__6260 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__4319 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__8428 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI211XL g2017__5526 (.Y(n_52),
	.A0(n_37),
	.A1(n_47),
	.B0(n_38),
	.C0(n_51));
   NOR2XL g2018__6783 (.Y(n_51),
	.A(n_49),
	.B(n_50));
   NAND3BXL g2019__3680 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__1617 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__2802 (.CO(n_47),
	.S(n_48),
	.A(n_43),
	.B(n_44),
	.CI(n_45));
   ADDFX1 g2022__1705 (.CO(n_45),
	.S(n_46),
	.A(n_41),
	.B(n_39),
	.CI(n_36));
   OAI211X1 g2023__5122 (.Y(n_44),
	.A0(n_9),
	.A1(n_34),
	.B0(n_14),
	.C0(n_21));
   OAI211X1 g2024__8246 (.Y(n_43),
	.A0(n_10),
	.A1(n_33),
	.B0(n_15),
	.C0(n_23));
   NOR2BX1 g2025__7098 (.Y(n_42),
	.AN(n_37),
	.B(n_38));
   OAI221X1 g2026__6131 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__1881 (.Y(n_39),
	.A0(n_27),
	.A1(n_1),
	.B0(n_14),
	.B1(b[2]),
	.C0(n_19));
   XNOR2X1 g2028__5115 (.Y(n_40),
	.A(n_35),
	.B(n_30));
   NOR2XL g2029__7482 (.Y(n_38),
	.A(n_32),
	.B(n_31));
   NAND2XL g2030__4733 (.Y(n_37),
	.A(n_32),
	.B(n_31));
   NOR2XL g2031__6161 (.Y(n_36),
	.A(n_35),
	.B(n_30));
   AOI22XL g2032__9315 (.Y(n_34),
	.A0(n_4),
	.A1(n_22),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__9945 (.Y(n_33),
	.A0(n_5),
	.A1(n_24),
	.B0(a[0]),
	.B1(n_11));
   AOI221X1 g2034__2883 (.Y(n_35),
	.A0(n_10),
	.A1(n_16),
	.B0(a[3]),
	.B1(n_11),
	.C0(n_20));
   AOI222X1 g2035__2346 (.Y(n_32),
	.A0(n_7),
	.A1(n_16),
	.B0(a[2]),
	.B1(a[0]),
	.C0(a[1]),
	.C1(n_12));
   AOI221X1 g2036__1666 (.Y(n_31),
	.A0(b[0]),
	.A1(b[2]),
	.B0(b[1]),
	.B1(n_13),
	.C0(n_25));
   AOI221X1 g2037__7410 (.Y(n_30),
	.A0(b[3]),
	.A1(n_17),
	.B0(n_4),
	.B1(n_8),
	.C0(n_26));
   OAI33X1 g2038__6417 (.Y(n_29),
	.A0(b[3]),
	.A1(n_19),
	.A2(b[2]),
	.B0(a[3]),
	.B1(a[2]),
	.B2(n_18));
   AOI31X1 g2039__5477 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_12));
   AOI31X1 g2040__2398 (.Y(n_27),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_0),
	.B0(n_13));
   NOR2XL g2041__5107 (.Y(n_26),
	.A(n_14),
	.B(n_8));
   NOR2XL g2042__6260 (.Y(n_25),
	.A(b[1]),
	.B(n_14));
   NOR2XL g2043__4319 (.Y(n_24),
	.A(a[3]),
	.B(n_11));
   NAND2XL g2044__8428 (.Y(n_23),
	.A(a[3]),
	.B(n_10));
   NOR2XL g2045__5526 (.Y(n_22),
	.A(b[3]),
	.B(n_17));
   NAND2XL g2046__6783 (.Y(n_21),
	.A(b[3]),
	.B(n_9));
   NOR2XL g2047__3680 (.Y(n_20),
	.A(a[0]),
	.B(n_10));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   NAND2XL g2049__1617 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2050__2802 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2051__1705 (.Y(n_17),
	.A(n_3),
	.B(b[2]));
   NOR2XL g2052__5122 (.Y(n_16),
	.A(n_5),
	.B(n_6));
   NAND2XL g2053__8246 (.Y(n_14),
	.A(b[0]),
	.B(b[3]));
   INVXL g2054 (.Y(n_8),
	.A(n_9));
   NOR2XL g2055__7098 (.Y(n_13),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__6131 (.Y(n_12),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__1881 (.Y(n_11),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__5115 (.Y(n_10),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__7482 (.Y(n_9),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVX1 g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVXL g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module gf_multiplier_485 (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__4733 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__6161 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__9315 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__9945 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__2883 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__2346 (.Y(n_74),
	.AN(n_68),
	.B(n_56),
	.C(n_61));
   NAND2XL g1996__1666 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__7410 (.Y(n_70),
	.A0(n_57),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__6417 (.Y(n_71),
	.A0(n_57),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__5477 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__2398 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__5107 (.Y(n_67),
	.A(n_57),
	.B(n_65));
   AOI21XL g2003__6260 (.Y(n_66),
	.A0(n_55),
	.A1(n_56),
	.B0(n_63));
   XNOR2X1 g2004__4319 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__8428 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__5526 (.Y(n_62),
	.A(n_56),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__6783 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__3680 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__1617 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__2802 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__1705 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__5122 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__8246 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI221X1 g2017__7098 (.Y(n_52),
	.A0(n_49),
	.A1(n_51),
	.B0(n_37),
	.B1(n_47),
	.C0(n_38));
   INVXL g2018 (.Y(n_51),
	.A(n_50));
   NAND3BXL g2019__6131 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__1881 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__5115 (.CO(n_47),
	.S(n_48),
	.A(n_44),
	.B(n_43),
	.CI(n_45));
   ADDFX1 g2022__7482 (.CO(n_45),
	.S(n_46),
	.A(n_39),
	.B(n_41),
	.CI(n_36));
   OAI211X1 g2023__4733 (.Y(n_44),
	.A0(n_9),
	.A1(n_34),
	.B0(n_14),
	.C0(n_21));
   OAI211X1 g2024__6161 (.Y(n_43),
	.A0(n_10),
	.A1(n_33),
	.B0(n_16),
	.C0(n_23));
   NAND2BXL g2025__9315 (.Y(n_42),
	.AN(n_38),
	.B(n_37));
   OAI221X1 g2026__9945 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_16),
	.C0(n_18));
   OAI221X1 g2027__2883 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_14),
	.C0(n_19));
   XNOR2X1 g2028__2346 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__1666 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__7410 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__6417 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__5477 (.Y(n_34),
	.A0(n_4),
	.A1(n_22),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__2398 (.Y(n_33),
	.A0(n_5),
	.A1(n_24),
	.B0(a[0]),
	.B1(n_11));
   AOI221X1 g2034__5107 (.Y(n_35),
	.A0(n_15),
	.A1(n_10),
	.B0(a[3]),
	.B1(n_11),
	.C0(n_20));
   AOI222X1 g2035__6260 (.Y(n_32),
	.A0(n_7),
	.A1(n_15),
	.B0(a[0]),
	.B1(a[2]),
	.C0(a[1]),
	.C1(n_12));
   AOI221X1 g2036__4319 (.Y(n_31),
	.A0(b[2]),
	.A1(b[0]),
	.B0(b[1]),
	.B1(n_13),
	.C0(n_25));
   AOI221X1 g2037__8428 (.Y(n_30),
	.A0(b[3]),
	.A1(n_17),
	.B0(n_4),
	.B1(n_8),
	.C0(n_26));
   OAI33X1 g2038__5526 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[2]),
	.B1(a[3]),
	.B2(n_18));
   AOI31X1 g2039__6783 (.Y(n_28),
	.A0(a[0]),
	.A1(a[1]),
	.A2(n_6),
	.B0(n_12));
   AOI31X1 g2040__3680 (.Y(n_27),
	.A0(n_0),
	.A1(b[0]),
	.A2(b[1]),
	.B0(n_13));
   NOR2XL g2041__1617 (.Y(n_26),
	.A(n_14),
	.B(n_8));
   NOR2XL g2042__2802 (.Y(n_25),
	.A(b[1]),
	.B(n_14));
   NOR2XL g2043__1705 (.Y(n_24),
	.A(a[3]),
	.B(n_11));
   NAND2XL g2044__5122 (.Y(n_23),
	.A(a[3]),
	.B(n_10));
   NOR2XL g2045__8246 (.Y(n_22),
	.A(b[3]),
	.B(n_17));
   NAND2XL g2046__7098 (.Y(n_21),
	.A(b[3]),
	.B(n_9));
   NOR2XL g2047__6131 (.Y(n_20),
	.A(a[0]),
	.B(n_10));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   NAND2XL g2049__1881 (.Y(n_19),
	.A(n_4),
	.B(n_3));
   NAND2XL g2050__5115 (.Y(n_18),
	.A(n_5),
	.B(n_7));
   NOR2XL g2051__7482 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NAND2XL g2052__4733 (.Y(n_16),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2053__6161 (.Y(n_14),
	.A(b[3]),
	.B(b[0]));
   INVXL g2054 (.Y(n_8),
	.A(n_9));
   NOR2XL g2055__9315 (.Y(n_13),
	.A(n_0),
	.B(b[0]));
   NOR2XL g2056__9945 (.Y(n_12),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__2883 (.Y(n_11),
	.A(n_7),
	.B(a[2]));
   NOR2XL g2058__2346 (.Y(n_10),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__1666 (.Y(n_9),
	.A(n_1),
	.B(b[1]));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVXL g2061 (.Y(n_6),
	.A(a[3]));
   INVXL g2062 (.Y(n_5),
	.A(a[0]));
   INVX1 g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVX1 g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module xor_4 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__7410 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__6417 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__5477 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__2398 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module xor_4_490 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__5107 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__6260 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__4319 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__8428 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module xor_4_489 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__5526 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__6783 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__3680 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__1617 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module xor_4_488 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__2802 (.Y(y[3]),
	.A(b[3]),
	.B(a[3]));
   CLKXOR2X1 g38__1705 (.Y(y[1]),
	.A(b[1]),
	.B(a[1]));
   CLKXOR2X1 g39__5122 (.Y(y[0]),
	.A(b[0]),
	.B(a[0]));
   CLKXOR2X1 g40__8246 (.Y(y[2]),
	.A(b[2]),
	.B(a[2]));
endmodule

module bch_bm_block (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	lambda1, 
	lambda2);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   output [3:0] lambda1;
   output [3:0] lambda2;

   // Internal wires
   wire [3:0] xor2;
   wire [3:0] div1;
   wire [3:0] xor1;
   wire [3:0] div2;
   wire [3:0] lambda1_next;
   wire [3:0] lambda2_next;
   wire [3:0] mult1;
   wire [3:0] mult2;
   wire [3:0] mult3;
   wire [3:0] mult4;
   wire [3:0] xor4;
   wire [3:0] xor3;
   wire n_0;

   gf_divider u_div1 (.a(xor2),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.q(div1));
   gf_divider_484 u_div2 (.a(xor1),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.q(div2));
   ff_4 u_lamb1 (.clk(clk),
	.rst(rst),
	.a(lambda1_next),
	.q(lambda1));
   ff_4_615 u_lamb2 (.clk(clk),
	.rst(rst),
	.a(lambda2_next),
	.q(lambda2));
   gf_multiplier u_mult1 (.a(lambda1),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.p(mult1));
   gf_multiplier_487 u_mult2 (.a(lambda1),
	.b(S2),
	.p(mult2));
   gf_multiplier_486 u_mult3 (.a(lambda2),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.p(mult3));
   gf_multiplier_485 u_mult4 (.a(lambda1_next),
	.b(S2),
	.p(mult4));
   xor_4 u_xor1 (.a(xor4),
	.b(mult4),
	.y(xor1));
   xor_4_490 u_xor2 (.a(S2),
	.b(mult1),
	.y(xor2));
   xor_4_489 u_xor3 (.a(S3),
	.b(mult2),
	.y(xor3));
   xor_4_488 u_xor4 (.a(xor3),
	.b(mult3),
	.y(xor4));
   AND2X1 g68__7098 (.Y(lambda2_next[3]),
	.A(div2[3]),
	.B(n_0));
   AND2X1 g69__6131 (.Y(lambda2_next[2]),
	.A(div2[2]),
	.B(n_0));
   AND2X1 g70__1881 (.Y(lambda2_next[0]),
	.A(div2[0]),
	.B(n_0));
   AND2X1 g71__5115 (.Y(lambda2_next[1]),
	.A(div2[1]),
	.B(n_0));
   AND2X1 g77__7482 (.Y(lambda1_next[3]),
	.A(div1[3]),
	.B(n_0));
   AND2X1 g78__4733 (.Y(lambda1_next[2]),
	.A(div1[2]),
	.B(n_0));
   AND2X1 g79__6161 (.Y(lambda1_next[1]),
	.A(div1[1]),
	.B(n_0));
   AND2X1 g80__9315 (.Y(lambda1_next[0]),
	.A(div1[0]),
	.B(n_0));
   OR4X1 g81__9945 (.Y(n_0),
	.A(S1[1]),
	.B(S1[0]),
	.C(S2[3]),
	.D(S2[1]));
endmodule

module bch_chien_block (
	lambda1, 
	lambda2, 
	error_vector, 
	error_found);
   input [3:0] lambda1;
   input [3:0] lambda2;
   output [14:0] error_vector;
   output error_found;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_282;
   wire n_283;
   wire n_286;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;

   OR4X1 g329347__2883 (.Y(error_found),
	.A(error_vector[6]),
	.B(error_vector[2]),
	.C(error_vector[11]),
	.D(n_298));
   OR4X1 g329348__2346 (.Y(n_298),
	.A(error_vector[7]),
	.B(error_vector[9]),
	.C(error_vector[10]),
	.D(n_297));
   OR4X1 g329349__1666 (.Y(n_297),
	.A(error_vector[1]),
	.B(error_vector[3]),
	.C(error_vector[8]),
	.D(n_296));
   OR3XL g329350__7410 (.Y(n_296),
	.A(error_vector[0]),
	.B(error_vector[14]),
	.C(n_295));
   OR4X1 g329351__6417 (.Y(n_295),
	.A(error_vector[13]),
	.B(error_vector[12]),
	.C(error_vector[4]),
	.D(error_vector[5]));
   AOI221X1 g329352__5477 (.Y(error_vector[6]),
	.A0(n_180),
	.A1(n_195),
	.B0(n_179),
	.B1(n_194),
	.C0(n_282));
   AOI221X1 g329353__2398 (.Y(error_vector[4]),
	.A0(n_224),
	.A1(n_209),
	.B0(n_225),
	.B1(n_210),
	.C0(n_286));
   NOR4X1 g329354__5107 (.Y(error_vector[9]),
	.A(n_252),
	.B(n_261),
	.C(n_236),
	.D(n_238));
   NOR4X1 g329355__6260 (.Y(error_vector[7]),
	.A(n_201),
	.B(n_246),
	.C(n_259),
	.D(n_270));
   AOI221X1 g329356__4319 (.Y(error_vector[5]),
	.A0(n_180),
	.A1(n_206),
	.B0(n_179),
	.B1(n_205),
	.C0(n_283));
   NOR4X1 g329357__8428 (.Y(error_vector[8]),
	.A(n_220),
	.B(n_248),
	.C(n_260),
	.D(n_271));
   OAI211X1 g329358__5526 (.Y(n_286),
	.A0(n_203),
	.A1(n_191),
	.B0(n_226),
	.C0(n_279));
   AOI221X1 g329359__6783 (.Y(error_vector[10]),
	.A0(n_197),
	.A1(n_213),
	.B0(n_196),
	.B1(n_214),
	.C0(n_278));
   AOI221X1 g329360__3680 (.Y(error_vector[11]),
	.A0(n_198),
	.A1(n_209),
	.B0(n_199),
	.B1(n_210),
	.C0(n_272));
   OAI221X1 g329361__1617 (.Y(n_283),
	.A0(n_195),
	.A1(n_258),
	.B0(n_194),
	.B1(n_257),
	.C0(n_276));
   OAI211X1 g329362__2802 (.Y(n_282),
	.A0(n_39),
	.A1(n_258),
	.B0(n_266),
	.C0(n_277));
   AOI221X1 g329363__1705 (.Y(error_vector[3]),
	.A0(lambda1[0]),
	.A1(n_213),
	.B0(n_13),
	.B1(n_214),
	.C0(n_273));
   AOI221X1 g329364__5122 (.Y(error_vector[12]),
	.A0(n_199),
	.A1(n_191),
	.B0(n_198),
	.B1(n_190),
	.C0(n_280));
   OAI211X1 g329365__8246 (.Y(n_280),
	.A0(n_228),
	.A1(n_229),
	.B0(n_232),
	.C0(n_262));
   AOI221X1 g329366__7098 (.Y(n_279),
	.A0(n_180),
	.A1(n_218),
	.B0(n_179),
	.B1(n_217),
	.C0(n_264));
   OAI221X1 g329367__6131 (.Y(n_278),
	.A0(n_212),
	.A1(n_209),
	.B0(n_211),
	.B1(n_210),
	.C0(n_268));
   AOI221X1 g329368__1881 (.Y(n_277),
	.A0(n_8),
	.A1(n_243),
	.B0(lambda2[1]),
	.B1(n_242),
	.C0(n_247));
   AOI221X1 g329369__5115 (.Y(n_276),
	.A0(n_230),
	.A1(n_217),
	.B0(n_231),
	.B1(n_218),
	.C0(n_263));
   NOR4X1 g329370__7482 (.Y(error_vector[1]),
	.A(n_38),
	.B(n_35),
	.C(n_202),
	.D(n_253));
   OAI211X1 g329371__4733 (.Y(n_273),
	.A0(n_240),
	.A1(n_241),
	.B0(n_251),
	.C0(n_235));
   OAI211X1 g329372__6161 (.Y(n_272),
	.A0(n_207),
	.A1(n_245),
	.B0(n_256),
	.C0(n_254));
   OAI22XL g329373__9315 (.Y(n_271),
	.A0(n_12),
	.A1(n_258),
	.B0(lambda2[2]),
	.B1(n_257));
   OAI22XL g329374__9945 (.Y(n_270),
	.A0(n_8),
	.A1(n_258),
	.B0(lambda2[1]),
	.B1(n_257));
   AOI221X1 g329375__2883 (.Y(error_vector[2]),
	.A0(lambda1[3]),
	.A1(n_183),
	.B0(n_9),
	.B1(n_184),
	.C0(n_265));
   AOI221X1 g329376__2346 (.Y(error_vector[13]),
	.A0(lambda1[1]),
	.A1(n_194),
	.B0(n_10),
	.B1(n_195),
	.C0(n_267));
   AOI221X1 g329377__1666 (.Y(n_268),
	.A0(n_223),
	.A1(n_216),
	.B0(n_222),
	.B1(n_215),
	.C0(n_221));
   OAI221X1 g329378__7410 (.Y(n_267),
	.A0(lambda1[2]),
	.A1(n_40),
	.B0(n_15),
	.B1(n_39),
	.C0(n_255));
   NAND2XL g329379__6417 (.Y(n_266),
	.A(n_39),
	.B(n_258));
   OAI221X1 g329380__5477 (.Y(n_265),
	.A0(n_224),
	.A1(n_214),
	.B0(n_225),
	.B1(n_213),
	.C0(n_249));
   NOR2XL g329381__2398 (.Y(error_vector[14]),
	.A(n_67),
	.B(n_250));
   AOI22XL g329382__5107 (.Y(n_264),
	.A0(n_230),
	.A1(n_244),
	.B0(n_231),
	.B1(n_245));
   AOI22XL g329383__6260 (.Y(n_263),
	.A0(n_204),
	.A1(n_244),
	.B0(n_203),
	.B1(n_245));
   AOI22XL g329384__4319 (.Y(n_262),
	.A0(n_212),
	.A1(n_244),
	.B0(n_211),
	.B1(n_245));
   AOI22XL g329385__8428 (.Y(n_261),
	.A0(n_14),
	.A1(n_243),
	.B0(lambda2[0]),
	.B1(n_242));
   AOI22XL g329386__5526 (.Y(n_260),
	.A0(n_11),
	.A1(n_243),
	.B0(lambda2[3]),
	.B1(n_242));
   AOI22XL g329387__6783 (.Y(n_259),
	.A0(n_12),
	.A1(n_243),
	.B0(lambda2[2]),
	.B1(n_242));
   INVX1 g329388 (.Y(n_257),
	.A(n_258));
   AOI221X1 g329389__3680 (.Y(n_256),
	.A0(n_197),
	.A1(n_188),
	.B0(n_196),
	.B1(n_189),
	.C0(n_233));
   AOI221X1 g329390__1617 (.Y(n_255),
	.A0(n_212),
	.A1(n_218),
	.B0(n_211),
	.B1(n_217),
	.C0(n_237));
   NAND2XL g329391__2802 (.Y(n_254),
	.A(n_207),
	.B(n_245));
   OAI22XL g329392__1705 (.Y(n_253),
	.A0(n_225),
	.A1(n_216),
	.B0(n_224),
	.B1(n_215));
   OAI22XL g329393__5122 (.Y(n_252),
	.A0(n_183),
	.A1(n_222),
	.B0(n_184),
	.B1(n_223));
   NAND3BXL g329394__8246 (.Y(n_258),
	.AN(n_77),
	.B(n_0),
	.C(n_219));
   OAI22XL g329395__7098 (.Y(n_251),
	.A0(n_225),
	.A1(n_189),
	.B0(n_224),
	.B1(n_188));
   OAI221X1 g329396__6131 (.Y(n_250),
	.A0(n_10),
	.A1(n_40),
	.B0(lambda1[1]),
	.B1(n_39),
	.C0(n_239));
   AOI221X1 g329397__1881 (.Y(n_249),
	.A0(lambda1[0]),
	.A1(n_215),
	.B0(n_13),
	.B1(n_216),
	.C0(n_234));
   AOI22XL g329398__5115 (.Y(n_248),
	.A0(n_14),
	.A1(n_223),
	.B0(lambda2[0]),
	.B1(n_222));
   AOI22XL g329399__7482 (.Y(n_247),
	.A0(n_230),
	.A1(n_205),
	.B0(n_231),
	.B1(n_206));
   AOI22XL g329400__4733 (.Y(n_246),
	.A0(lambda2[3]),
	.A1(n_223),
	.B0(n_11),
	.B1(n_222));
   INVX1 g329401 (.Y(n_244),
	.A(n_245));
   INVX1 g329402 (.Y(n_242),
	.A(n_243));
   NOR2XL g329403__6161 (.Y(n_241),
	.A(n_231),
	.B(n_191));
   NOR2XL g329404__9315 (.Y(n_240),
	.A(n_190),
	.B(n_230));
   AOI22XL g329405__9945 (.Y(n_239),
	.A0(n_195),
	.A1(n_208),
	.B0(n_194),
	.B1(n_207));
   OAI22XL g329406__2883 (.Y(n_238),
	.A0(n_199),
	.A1(n_214),
	.B0(n_198),
	.B1(n_213));
   OAI211X1 g329407__2346 (.Y(n_245),
	.A0(n_58),
	.A1(n_186),
	.B0(n_56),
	.C0(n_109));
   AOI31X1 g329408__1666 (.Y(n_243),
	.A0(n_114),
	.A1(n_149),
	.A2(n_181),
	.B0(n_227));
   OAI22XL g329409__7410 (.Y(n_237),
	.A0(n_207),
	.A1(n_205),
	.B0(n_208),
	.B1(n_206));
   AOI22XL g329410__6417 (.Y(n_236),
	.A0(n_196),
	.A1(n_215),
	.B0(n_197),
	.B1(n_216));
   AOI22XL g329411__5477 (.Y(n_235),
	.A0(n_204),
	.A1(n_209),
	.B0(n_203),
	.B1(n_210));
   AOI22XL g329412__2398 (.Y(n_234),
	.A0(n_204),
	.A1(n_189),
	.B0(n_203),
	.B1(n_188));
   AOI22XL g329413__5107 (.Y(n_233),
	.A0(n_211),
	.A1(n_191),
	.B0(n_212),
	.B1(n_190));
   OAI22XL g329414__6260 (.Y(n_232),
	.A0(n_10),
	.A1(n_206),
	.B0(lambda1[1]),
	.B1(n_205));
   INVX1 g329415 (.Y(n_230),
	.A(n_231));
   NOR2XL g329416__4319 (.Y(n_229),
	.A(n_208),
	.B(n_218));
   NOR2XL g329417__8428 (.Y(n_228),
	.A(n_207),
	.B(n_217));
   OAI31X1 g329418__5526 (.Y(n_227),
	.A0(n_105),
	.A1(n_150),
	.A2(n_181),
	.B0(n_93));
   NAND2XL g329419__6783 (.Y(n_226),
	.A(n_203),
	.B(n_191));
   NAND2XL g329420__3680 (.Y(n_231),
	.A(n_87),
	.B(n_200));
   INVX1 g329421 (.Y(n_224),
	.A(n_225));
   INVX1 g329422 (.Y(n_222),
	.A(n_223));
   AOI22XL g329423__1617 (.Y(n_221),
	.A0(n_198),
	.A1(n_188),
	.B0(n_199),
	.B1(n_189));
   OAI22XL g329424__2802 (.Y(n_220),
	.A0(n_197),
	.A1(n_184),
	.B0(n_196),
	.B1(n_183));
   AOI33XL g329425__1705 (.Y(n_219),
	.A0(n_55),
	.A1(n_124),
	.A2(n_178),
	.B0(n_127),
	.B1(1'b1),
	.B2(n_143));
   OAI211X1 g329426__5122 (.Y(n_225),
	.A0(n_54),
	.A1(n_113),
	.B0(n_2),
	.C0(n_185));
   AOI221X1 g329427__8246 (.Y(n_223),
	.A0(n_142),
	.A1(n_181),
	.B0(n_100),
	.B1(n_159),
	.C0(n_90));
   INVX1 g329428 (.Y(n_217),
	.A(n_218));
   INVX1 g329429 (.Y(n_215),
	.A(n_216));
   INVX1 g329430 (.Y(n_213),
	.A(n_214));
   INVX1 g329431 (.Y(n_211),
	.A(n_212));
   INVX1 g329432 (.Y(n_209),
	.A(n_210));
   NOR2XL g329433__7098 (.Y(n_218),
	.A(n_107),
	.B(n_192));
   OAI211X1 g329434__6131 (.Y(n_216),
	.A0(n_84),
	.A1(n_129),
	.B0(n_97),
	.C0(n_182));
   NAND2XL g329435__1881 (.Y(n_214),
	.A(n_86),
	.B(n_193));
   OAI211X1 g329436__5115 (.Y(n_212),
	.A0(n_112),
	.A1(n_172),
	.B0(n_75),
	.C0(n_88));
   AOI211XL g329437__7482 (.Y(n_210),
	.A0(n_152),
	.A1(n_167),
	.B0(n_41),
	.C0(n_80));
   INVX1 g329438 (.Y(n_207),
	.A(n_208));
   INVX1 g329439 (.Y(n_205),
	.A(n_206));
   INVX1 g329440 (.Y(n_203),
	.A(n_204));
   OAI22XL g329441__4733 (.Y(n_202),
	.A0(n_13),
	.A1(n_184),
	.B0(lambda1[0]),
	.B1(n_183));
   OAI22XL g329442__6161 (.Y(n_201),
	.A0(n_39),
	.A1(n_179),
	.B0(n_40),
	.B1(n_180));
   AOI33XL g329443__9315 (.Y(n_200),
	.A0(n_68),
	.A1(n_112),
	.A2(n_160),
	.B0(n_149),
	.B1(n_128),
	.B2(n_155));
   AOI222X1 g329444__9945 (.Y(n_208),
	.A0(n_121),
	.A1(n_173),
	.B0(n_115),
	.B1(n_134),
	.C0(n_148),
	.C1(n_146));
   OAI211X1 g329445__2883 (.Y(n_206),
	.A0(n_151),
	.A1(n_169),
	.B0(n_1),
	.C0(n_51));
   AOI31X1 g329446__2346 (.Y(n_204),
	.A0(n_55),
	.A1(n_114),
	.A2(n_120),
	.B0(n_187));
   INVX1 g329447 (.Y(n_198),
	.A(n_199));
   INVX1 g329448 (.Y(n_196),
	.A(n_197));
   INVX1 g329449 (.Y(n_194),
	.A(n_195));
   AOI33XL g329450__1666 (.Y(n_193),
	.A0(n_133),
	.A1(n_152),
	.A2(n_168),
	.B0(n_136),
	.B1(n_97),
	.B2(n_167));
   AOI211XL g329451__7410 (.Y(n_192),
	.A0(n_139),
	.A1(n_141),
	.B0(n_117),
	.C0(n_7));
   OAI211X1 g329452__6417 (.Y(n_199),
	.A0(n_114),
	.A1(n_150),
	.B0(n_2),
	.C0(n_171));
   OAI211X1 g329453__5477 (.Y(n_197),
	.A0(n_102),
	.A1(n_115),
	.B0(n_79),
	.C0(n_170));
   OAI211X1 g329454__2398 (.Y(n_195),
	.A0(n_106),
	.A1(n_122),
	.B0(n_73),
	.C0(n_175));
   INVX1 g329455 (.Y(n_190),
	.A(n_191));
   INVX1 g329456 (.Y(n_188),
	.A(n_189));
   OAI32X1 g329457__5107 (.Y(n_187),
	.A0(n_118),
	.A1(n_126),
	.A2(n_147),
	.B0(n_130),
	.B1(n_176));
   OAI211X1 g329458__6260 (.Y(n_186),
	.A0(n_123),
	.A1(n_140),
	.B0(n_106),
	.C0(n_164));
   OAI211X1 g329459__4319 (.Y(n_185),
	.A0(n_69),
	.A1(n_121),
	.B0(n_134),
	.C0(n_161));
   AOI22XL g329460__8428 (.Y(n_191),
	.A0(n_139),
	.A1(n_169),
	.B0(n_122),
	.B1(n_152));
   OAI211X1 g329461__5526 (.Y(n_189),
	.A0(n_6),
	.A1(n_168),
	.B0(n_144),
	.C0(n_162));
   INVX1 g329462 (.Y(n_183),
	.A(n_184));
   OAI221X1 g329463__6783 (.Y(n_182),
	.A0(n_133),
	.A1(n_152),
	.B0(n_41),
	.B1(n_117),
	.C0(n_168));
   OAI31X1 g329464__3680 (.Y(n_184),
	.A0(n_25),
	.A1(n_58),
	.A2(n_133),
	.B0(n_165));
   INVX1 g329465 (.Y(n_179),
	.A(n_180));
   AOI21XL g329466__1617 (.Y(n_178),
	.A0(n_59),
	.A1(n_138),
	.B0(n_156));
   OAI21XL g329467__2802 (.Y(n_181),
	.A0(n_148),
	.A1(n_137),
	.B0(n_177));
   AOI221X1 g329468__1705 (.Y(n_180),
	.A0(n_131),
	.A1(n_148),
	.B0(n_111),
	.B1(n_113),
	.C0(n_174));
   INVXL g329469 (.Y(n_177),
	.A(n_156));
   INVXL g329470 (.Y(n_176),
	.A(n_161));
   OAI211X1 g329471__5122 (.Y(n_175),
	.A0(n_57),
	.A1(n_153),
	.B0(n_145),
	.C0(n_135));
   NOR2BX1 g329472__8246 (.Y(n_174),
	.AN(n_160),
	.B(n_124));
   NOR2BX1 g329473__7098 (.Y(n_173),
	.AN(n_163),
	.B(n_105));
   OAI2BB1X1 g329474__6131 (.Y(n_172),
	.A0N(n_105),
	.A1N(n_120),
	.B0(n_163));
   OAI211X1 g329475__1881 (.Y(n_171),
	.A0(n_132),
	.A1(n_113),
	.B0(n_126),
	.C0(n_158));
   INVXL g329476 (.Y(n_170),
	.A(n_166));
   INVXL g329477 (.Y(n_167),
	.A(n_168));
   AOI211XL g329478__5115 (.Y(n_166),
	.A0(n_24),
	.A1(n_148),
	.B0(n_134),
	.C0(n_142));
   AO22X1 g329479__7482 (.Y(n_165),
	.A0(n_1),
	.A1(n_154),
	.B0(n_122),
	.B1(n_157));
   XNOR2X1 g329481__4733 (.Y(n_164),
	.A(n_110),
	.B(n_157));
   XNOR2X1 g329482__6161 (.Y(n_169),
	.A(n_141),
	.B(n_157));
   XNOR2X1 g329483__9315 (.Y(n_168),
	.A(n_104),
	.B(n_157));
   OAI21XL g329484__9945 (.Y(n_162),
	.A0(n_57),
	.A1(n_116),
	.B0(n_157));
   NAND2XL g329485__2883 (.Y(n_163),
	.A(n_53),
	.B(n_158));
   XNOR2X1 g329486__2346 (.Y(n_159),
	.A(n_103),
	.B(n_148));
   OAI2BB1X1 g329487__1666 (.Y(n_161),
	.A0N(n_111),
	.A1N(n_148),
	.B0(n_155));
   XNOR2X1 g329488__7410 (.Y(n_160),
	.A(n_93),
	.B(n_147));
   NAND2XL g329490__6417 (.Y(n_158),
	.A(n_95),
	.B(n_147));
   NOR2XL g329491__5477 (.Y(n_157),
	.A(n_58),
	.B(n_153));
   OAI2BB1X1 g329492__2398 (.Y(n_154),
	.A0N(n_98),
	.A1N(n_140),
	.B0(n_86));
   NOR2XL g329493__5107 (.Y(n_156),
	.A(n_103),
	.B(n_147));
   OR2X1 g329494__6260 (.Y(n_155),
	.A(n_111),
	.B(n_148));
   AND2X1 g329495__4319 (.Y(n_151),
	.A(n_140),
	.B(n_106));
   NAND3XL g329496__8428 (.Y(n_153),
	.A(n_51),
	.B(n_44),
	.C(n_5));
   NAND2XL g329497__5526 (.Y(n_152),
	.A(n_104),
	.B(n_140));
   INVX1 g329498 (.Y(n_147),
	.A(n_148));
   AOI211XL g329499__6783 (.Y(n_146),
	.A0(n_101),
	.A1(n_118),
	.B0(n_71),
	.C0(n_112));
   OAI2BB1X1 g329500__3680 (.Y(n_150),
	.A0N(n_95),
	.A1N(n_121),
	.B0(n_55));
   NAND2XL g329501__1617 (.Y(n_149),
	.A(n_64),
	.B(n_143));
   NAND3XL g329502__2802 (.Y(n_148),
	.A(n_53),
	.B(n_79),
	.C(n_119));
   NAND2XL g329504__1705 (.Y(n_145),
	.A(n_109),
	.B(n_125));
   OAI2BB1X1 g329505__5122 (.Y(n_144),
	.A0N(n_44),
	.A1N(n_86),
	.B0(n_133));
   INVXL g329506 (.Y(n_139),
	.A(n_140));
   AOI21XL g329507__8246 (.Y(n_143),
	.A0(n_82),
	.A1(n_101),
	.B0(n_43));
   AOI21XL g329508__7098 (.Y(n_142),
	.A0(n_99),
	.A1(n_115),
	.B0(n_102));
   NOR3BXL g329509__6131 (.Y(n_141),
	.AN(n_104),
	.B(n_49),
	.C(n_84));
   NOR4BX1 g329510__1881 (.Y(n_140),
	.AN(n_97),
	.B(n_61),
	.C(n_57),
	.D(n_76));
   INVXL g329511 (.Y(n_138),
	.A(n_137));
   INVXL g329512 (.Y(n_136),
	.A(n_135));
   NOR2XL g329513__5115 (.Y(n_132),
	.A(n_71),
	.B(n_102));
   NAND2BXL g329514__7482 (.Y(n_131),
	.AN(n_112),
	.B(n_53));
   NOR2XL g329515__4733 (.Y(n_130),
	.A(n_69),
	.B(n_111));
   OR2X1 g329516__6161 (.Y(n_129),
	.A(n_58),
	.B(n_108));
   NAND2XL g329517__9315 (.Y(n_137),
	.A(n_45),
	.B(n_103));
   NOR2XL g329518__9945 (.Y(n_135),
	.A(n_52),
	.B(n_116));
   NOR2BX1 g329519__2883 (.Y(n_134),
	.AN(n_99),
	.B(n_111));
   NOR2XL g329520__2346 (.Y(n_133),
	.A(n_4),
	.B(n_107));
   INVXL g329521 (.Y(n_128),
	.A(n_127));
   INVXL g329523 (.Y(n_123),
	.A(n_122));
   INVX1 g329524 (.Y(n_120),
	.A(n_121));
   NOR4X1 g329525__1666 (.Y(n_119),
	.A(n_43),
	.B(n_42),
	.C(n_62),
	.D(n_74));
   NAND3BXL g329527__7410 (.Y(n_127),
	.AN(n_90),
	.B(n_53),
	.C(n_78));
   NAND3BXL g329528__6417 (.Y(n_126),
	.AN(n_77),
	.B(n_87),
	.C(n_95));
   NAND4XL g329529__5477 (.Y(n_125),
	.A(n_60),
	.B(n_70),
	.C(n_72),
	.D(n_81));
   OAI21XL g329530__2398 (.Y(n_124),
	.A0(n_89),
	.A1(n_94),
	.B0(n_78));
   AND3XL g329531__5107 (.Y(n_122),
	.A(n_51),
	.B(n_70),
	.C(n_86));
   NAND3BXL g329532__6260 (.Y(n_121),
	.AN(n_89),
	.B(n_0),
	.C(n_93));
   NAND2XL g329533__4319 (.Y(n_118),
	.A(n_87),
	.B(n_88));
   NOR2XL g329534__8428 (.Y(n_110),
	.A(n_63),
	.B(n_96));
   NAND2XL g329535__5526 (.Y(n_117),
	.A(n_85),
	.B(n_98));
   NAND2XL g329536__6783 (.Y(n_116),
	.A(n_81),
	.B(n_98));
   NOR2XL g329537__3680 (.Y(n_115),
	.A(n_66),
	.B(n_90));
   AND2X1 g329538__1617 (.Y(n_114),
	.A(n_88),
	.B(n_82));
   AND2X1 g329539__2802 (.Y(n_113),
	.A(n_95),
	.B(n_79));
   NAND2BXL g329540__1705 (.Y(n_112),
	.AN(n_89),
	.B(n_88));
   NAND2XL g329541__5122 (.Y(n_111),
	.A(n_64),
	.B(n_87));
   INVXL g329542 (.Y(n_101),
	.A(n_102));
   NAND2XL g329543__8246 (.Y(n_100),
	.A(n_24),
	.B(n_87));
   NOR2XL g329544__7098 (.Y(n_109),
	.A(n_47),
	.B(n_84));
   NOR3BXL g329545__6131 (.Y(n_108),
	.AN(n_72),
	.B(n_52),
	.C(n_4));
   OAI21XL g329546__1881 (.Y(n_107),
	.A0(lambda2[1]),
	.A1(n_16),
	.B0(n_85));
   NOR3BXL g329547__5115 (.Y(n_106),
	.AN(n_70),
	.B(n_80),
	.C(n_84));
   NAND4XL g329548__7482 (.Y(n_105),
	.A(n_2),
	.B(n_59),
	.C(n_3),
	.D(n_68));
   NOR2BX1 g329549__4733 (.Y(n_104),
	.AN(n_86),
	.B(n_80));
   AND2X1 g329550__6161 (.Y(n_103),
	.A(n_99),
	.B(n_24));
   NAND2XL g329551__9315 (.Y(n_102),
	.A(n_79),
	.B(n_92));
   INVXL g329552 (.Y(n_94),
	.A(n_93));
   NOR2XL g329553__9945 (.Y(n_92),
	.A(n_62),
	.B(n_77));
   NOR2BX1 g329554__2883 (.Y(n_99),
	.AN(n_78),
	.B(n_71));
   NOR2BX1 g329555__2346 (.Y(n_98),
	.AN(n_70),
	.B(n_63));
   NOR2BX1 g329556__1666 (.Y(n_97),
	.AN(n_73),
	.B(n_83));
   NAND2BXL g329557__7410 (.Y(n_96),
	.AN(n_4),
	.B(n_81));
   NOR2XL g329558__6417 (.Y(n_95),
	.A(n_65),
	.B(n_71));
   NOR2BX1 g329559__5477 (.Y(n_93),
	.AN(n_3),
	.B(n_77));
   INVX1 g329560 (.Y(n_84),
	.A(n_85));
   NOR4X1 g329561__2398 (.Y(error_vector[0]),
	.A(n_37),
	.B(n_33),
	.C(n_34),
	.D(n_32));
   NAND2BXL g329562__5107 (.Y(n_90),
	.AN(n_42),
	.B(n_82));
   OAI21XL g329563__6260 (.Y(n_89),
	.A0(n_19),
	.A1(n_24),
	.B0(n_78));
   NOR2XL g329564__4319 (.Y(n_88),
	.A(n_66),
	.B(n_69));
   AND3XL g329565__8428 (.Y(n_87),
	.A(n_0),
	.B(n_59),
	.C(n_2));
   AND2X1 g329566__5526 (.Y(n_86),
	.A(n_72),
	.B(n_46));
   NOR2XL g329567__6783 (.Y(n_85),
	.A(n_52),
	.B(n_76));
   NAND2XL g329568__3680 (.Y(n_83),
	.A(n_50),
	.B(n_1));
   NOR2BX1 g329569__1617 (.Y(n_82),
	.AN(n_3),
	.B(n_43));
   NOR2XL g329570__2802 (.Y(n_81),
	.A(n_41),
	.B(n_61));
   NAND2BXL g329571__1705 (.Y(n_80),
	.AN(n_47),
	.B(n_44));
   AND2X1 g329573__5122 (.Y(n_79),
	.A(n_59),
	.B(n_48));
   NOR2XL g329574__8246 (.Y(n_78),
	.A(n_65),
	.B(n_62));
   NAND2BXL g329575__7098 (.Y(n_77),
	.AN(n_42),
	.B(n_64));
   INVXL g329576 (.Y(n_75),
	.A(n_74));
   INVXL g329577 (.Y(n_68),
	.A(n_69));
   OAI221X1 g329578__6131 (.Y(n_67),
	.A0(lambda2[2]),
	.A1(lambda1[3]),
	.B0(n_12),
	.B1(n_9),
	.C0(n_36));
   OAI21XL g329579__1881 (.Y(n_76),
	.A0(n_20),
	.A1(n_17),
	.B0(n_60));
   OAI21XL g329580__5115 (.Y(n_74),
	.A0(n_23),
	.A1(n_24),
	.B0(n_0));
   OA21X1 g329581__7482 (.Y(n_73),
	.A0(n_31),
	.A1(n_16),
	.B0(n_46));
   OA21X1 g329582__4733 (.Y(n_72),
	.A0(n_16),
	.A1(n_25),
	.B0(n_1));
   NAND2XL g329583__6161 (.Y(n_71),
	.A(n_55),
	.B(n_53));
   NOR2BX1 g329584__9315 (.Y(n_70),
	.AN(n_50),
	.B(n_49));
   NAND2XL g329585__9945 (.Y(n_69),
	.A(n_45),
	.B(n_48));
   INVXL g329588 (.Y(n_56),
	.A(n_57));
   INVXL g329589 (.Y(n_54),
	.A(n_55));
   INVX1 g329590 (.Y(n_51),
	.A(n_52));
   NOR2XL g329591__2883 (.Y(n_66),
	.A(n_28),
	.B(n_22));
   NOR2XL g329592__2346 (.Y(n_65),
	.A(n_28),
	.B(n_18));
   NAND2BXL g329593__1666 (.Y(n_64),
	.AN(n_19),
	.B(n_30));
   NOR2XL g329594__7410 (.Y(n_63),
	.A(n_31),
	.B(n_17));
   NOR2XL g329595__6417 (.Y(n_62),
	.A(n_28),
	.B(n_24));
   NOR2XL g329596__5477 (.Y(n_61),
	.A(n_26),
	.B(n_20));
   NAND2BXL g329597__2398 (.Y(n_60),
	.AN(n_31),
	.B(n_27));
   NAND2BXL g329599__5107 (.Y(n_59),
	.AN(n_23),
	.B(n_30));
   NOR2BX1 g329603__6260 (.Y(n_58),
	.AN(n_27),
	.B(n_25));
   NOR2XL g329604__4319 (.Y(n_57),
	.A(n_26),
	.B(n_25));
   NAND2XL g329605__8428 (.Y(n_55),
	.A(n_30),
	.B(n_29));
   NAND2BXL g329606__5526 (.Y(n_53),
	.AN(n_28),
	.B(n_30));
   NOR2XL g329607__6783 (.Y(n_52),
	.A(n_26),
	.B(n_21));
   INVX1 g329608 (.Y(n_39),
	.A(n_40));
   OAI22XL g329609__3680 (.Y(n_38),
	.A0(lambda2[0]),
	.A1(n_9),
	.B0(lambda1[3]),
	.B1(n_14));
   AOI22XL g329610__1617 (.Y(n_37),
	.A0(n_8),
	.A1(n_10),
	.B0(lambda2[1]),
	.B1(lambda1[1]));
   AOI22XL g329611__2802 (.Y(n_36),
	.A0(lambda1[2]),
	.A1(n_8),
	.B0(lambda2[1]),
	.B1(n_15));
   OAI22XL g329612__1705 (.Y(n_35),
	.A0(lambda2[3]),
	.A1(n_15),
	.B0(lambda1[2]),
	.B1(n_11));
   OAI22XL g329613__5122 (.Y(n_34),
	.A0(lambda2[3]),
	.A1(n_9),
	.B0(lambda1[3]),
	.B1(n_11));
   AOI22XL g329614__8246 (.Y(n_33),
	.A0(lambda1[0]),
	.A1(n_14),
	.B0(lambda2[0]),
	.B1(n_13));
   OAI22XL g329615__7098 (.Y(n_32),
	.A0(lambda2[2]),
	.A1(n_15),
	.B0(lambda1[2]),
	.B1(n_12));
   OR2X1 g329616__6131 (.Y(n_50),
	.A(n_17),
	.B(n_21));
   NOR2XL g329617__1881 (.Y(n_49),
	.A(n_20),
	.B(n_16));
   OR2X1 g329618__5115 (.Y(n_48),
	.A(n_18),
	.B(n_23));
   NOR2XL g329619__7482 (.Y(n_47),
	.A(n_21),
	.B(n_16));
   NAND2BXL g329620__4733 (.Y(n_46),
	.AN(n_20),
	.B(n_27));
   OR2X1 g329621__6161 (.Y(n_45),
	.A(n_19),
	.B(n_22));
   OR2X1 g329622__9315 (.Y(n_44),
	.A(n_25),
	.B(n_17));
   NOR2XL g329623__9945 (.Y(n_43),
	.A(n_19),
	.B(n_18));
   NOR2XL g329624__2883 (.Y(n_42),
	.A(n_22),
	.B(n_23));
   NOR2XL g329625__2346 (.Y(n_41),
	.A(n_26),
	.B(n_31));
   NAND2XL g329626__1666 (.Y(n_40),
	.A(n_17),
	.B(n_16));
   NAND2XL g329628__7410 (.Y(n_31),
	.A(lambda2[1]),
	.B(lambda2[2]));
   NOR2XL g329629__6417 (.Y(n_30),
	.A(lambda1[1]),
	.B(lambda1[2]));
   NOR2XL g329630__5477 (.Y(n_29),
	.A(lambda1[0]),
	.B(lambda1[3]));
   NAND2XL g329631__2398 (.Y(n_28),
	.A(lambda1[0]),
	.B(lambda1[3]));
   NOR2XL g329632__5107 (.Y(n_27),
	.A(lambda2[0]),
	.B(lambda2[3]));
   NAND2XL g329633__6260 (.Y(n_26),
	.A(lambda2[0]),
	.B(lambda2[3]));
   NAND2XL g329634__4319 (.Y(n_25),
	.A(n_12),
	.B(n_8));
   NAND2XL g329635__8428 (.Y(n_24),
	.A(lambda1[1]),
	.B(lambda1[2]));
   NAND2XL g329639__5526 (.Y(n_23),
	.A(lambda1[0]),
	.B(n_9));
   NAND2XL g329640__6783 (.Y(n_22),
	.A(lambda1[1]),
	.B(n_15));
   NAND2XL g329641__3680 (.Y(n_21),
	.A(lambda2[1]),
	.B(n_12));
   NAND2XL g329642__1617 (.Y(n_20),
	.A(lambda2[2]),
	.B(n_8));
   NAND2XL g329643__2802 (.Y(n_19),
	.A(lambda1[3]),
	.B(n_13));
   NAND2XL g329644__1705 (.Y(n_18),
	.A(lambda1[2]),
	.B(n_10));
   NAND2XL g329645__5122 (.Y(n_17),
	.A(lambda2[3]),
	.B(n_14));
   NAND2XL g329646__8246 (.Y(n_16),
	.A(lambda2[0]),
	.B(n_11));
   INVX1 g329647 (.Y(n_15),
	.A(lambda1[2]));
   INVX1 g329648 (.Y(n_14),
	.A(lambda2[0]));
   INVX1 g329649 (.Y(n_13),
	.A(lambda1[0]));
   INVX1 g329650 (.Y(n_12),
	.A(lambda2[2]));
   INVX1 g329651 (.Y(n_11),
	.A(lambda2[3]));
   INVX1 g329652 (.Y(n_10),
	.A(lambda1[1]));
   INVX1 g329653 (.Y(n_9),
	.A(lambda1[3]));
   INVX1 g329654 (.Y(n_8),
	.A(lambda2[1]));
   XOR2XL g2__7098 (.Y(n_7),
	.A(n_96),
	.B(n_157));
   NAND2BX1 g329655__6131 (.Y(n_6),
	.AN(n_125),
	.B(n_108));
   NOR4BX1 g329656__1881 (.Y(n_5),
	.AN(n_60),
	.B(n_61),
	.C(n_63),
	.D(n_83));
   NAND2BX1 g329657__5115 (.Y(n_4),
	.AN(n_58),
	.B(n_56));
   NAND2BX1 g329658__7482 (.Y(n_3),
	.AN(n_24),
	.B(n_29));
   NAND2BX1 g329659__4733 (.Y(n_2),
	.AN(n_22),
	.B(n_29));
   NAND2BX1 g329660__6161 (.Y(n_1),
	.AN(n_21),
	.B(n_27));
   NAND2BX1 g329661__9315 (.Y(n_0),
	.AN(n_18),
	.B(n_29));
endmodule

module bch_corrector (
	corruptedWord, 
	errorVector, 
	correctedWord);
   input [14:0] corruptedWord;
   input [14:0] errorVector;
   output [14:0] correctedWord;

   CLKXOR2X1 g136__9945 (.Y(correctedWord[10]),
	.A(corruptedWord[10]),
	.B(errorVector[10]));
   CLKXOR2X1 g137__2883 (.Y(correctedWord[12]),
	.A(corruptedWord[12]),
	.B(errorVector[12]));
   CLKXOR2X1 g138__2346 (.Y(correctedWord[11]),
	.A(corruptedWord[11]),
	.B(errorVector[11]));
   CLKXOR2X1 g139__1666 (.Y(correctedWord[1]),
	.A(corruptedWord[1]),
	.B(errorVector[1]));
   CLKXOR2X1 g140__7410 (.Y(correctedWord[0]),
	.A(corruptedWord[0]),
	.B(errorVector[0]));
   CLKXOR2X1 g141__6417 (.Y(correctedWord[7]),
	.A(corruptedWord[7]),
	.B(errorVector[7]));
   CLKXOR2X1 g142__5477 (.Y(correctedWord[14]),
	.A(corruptedWord[14]),
	.B(errorVector[14]));
   CLKXOR2X1 g143__2398 (.Y(correctedWord[4]),
	.A(corruptedWord[4]),
	.B(errorVector[4]));
   CLKXOR2X1 g144__5107 (.Y(correctedWord[5]),
	.A(corruptedWord[5]),
	.B(errorVector[5]));
   CLKXOR2X1 g145__6260 (.Y(correctedWord[13]),
	.A(corruptedWord[13]),
	.B(errorVector[13]));
   CLKXOR2X1 g146__4319 (.Y(correctedWord[9]),
	.A(corruptedWord[9]),
	.B(errorVector[9]));
   CLKXOR2X1 g147__8428 (.Y(correctedWord[6]),
	.A(corruptedWord[6]),
	.B(errorVector[6]));
   CLKXOR2X1 g148__5526 (.Y(correctedWord[8]),
	.A(corruptedWord[8]),
	.B(errorVector[8]));
   CLKXOR2X1 g149__6783 (.Y(correctedWord[3]),
	.A(corruptedWord[3]),
	.B(errorVector[3]));
   CLKXOR2X1 g150__3680 (.Y(correctedWord[2]),
	.A(corruptedWord[2]),
	.B(errorVector[2]));
endmodule

module bch_syndrome_block (
	codeword, 
	S1, 
	S2, 
	S3);
   input [14:0] codeword;
   output [3:0] S1;
   output [3:0] S2;
   output [3:0] S3;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_35;
   wire n_36;
   wire n_37;

   XNOR2X1 g957__1617 (.Y(S3[3]),
	.A(n_30),
	.B(n_36));
   XNOR2X1 g958__2802 (.Y(S3[0]),
	.A(n_9),
	.B(n_35));
   XNOR2X1 g959__1705 (.Y(S1[2]),
	.A(n_17),
	.B(n_31));
   XNOR2X1 g960__5122 (.Y(S2[0]),
	.A(n_24),
	.B(n_37));
   XNOR2X1 g961__8246 (.Y(S3[1]),
	.A(n_26),
	.B(n_28));
   XNOR2X1 g962__7098 (.Y(S3[2]),
	.A(n_23),
	.B(n_28));
   XNOR2X1 g963__6131 (.Y(n_37),
	.A(n_4),
	.B(n_29));
   XNOR2X1 g964__1881 (.Y(n_36),
	.A(n_29),
	.B(n_28));
   XNOR2X1 g965__5115 (.Y(n_35),
	.A(codeword[0]),
	.B(n_28));
   XNOR2X1 g966__7482 (.Y(S1[1]),
	.A(n_21),
	.B(n_0));
   XNOR2X1 g967__4733 (.Y(S2[2]),
	.A(n_1),
	.B(n_20));
   XNOR2X1 g968__6161 (.Y(S1[0]),
	.A(n_19),
	.B(n_27));
   XNOR2X1 g970__9315 (.Y(n_31),
	.A(n_25),
	.B(n_29));
   XNOR2X1 g971__9945 (.Y(n_30),
	.A(n_13),
	.B(n_22));
   XNOR2X1 g972__2883 (.Y(n_27),
	.A(n_6),
	.B(n_7));
   XNOR2X1 g973__2346 (.Y(n_26),
	.A(codeword[8]),
	.B(n_10));
   MX2X1 g974__1666 (.Y(n_25),
	.A(n_9),
	.B(n_8),
	.S0(codeword[12]));
   XNOR2X1 g975__7410 (.Y(n_24),
	.A(codeword[0]),
	.B(n_7));
   XNOR2X1 g976__6417 (.Y(n_23),
	.A(codeword[2]),
	.B(n_6));
   XNOR2X1 g977__5477 (.Y(n_29),
	.A(codeword[2]),
	.B(n_11));
   XNOR2X1 g978__2398 (.Y(n_28),
	.A(codeword[9]),
	.B(n_7));
   XNOR2X1 g980__5107 (.Y(n_21),
	.A(n_5),
	.B(n_16));
   XNOR2X1 g983__6260 (.Y(n_20),
	.A(n_15),
	.B(n_8));
   XNOR2X1 g984__4319 (.Y(n_19),
	.A(n_14),
	.B(n_17));
   XNOR2X1 g985__8428 (.Y(n_18),
	.A(n_12),
	.B(n_11));
   XNOR2X1 g986__5526 (.Y(n_22),
	.A(n_10),
	.B(n_6));
   XNOR2X1 g987__6783 (.Y(n_16),
	.A(codeword[9]),
	.B(codeword[11]));
   XNOR2X1 g988__3680 (.Y(n_15),
	.A(codeword[1]),
	.B(codeword[6]));
   XNOR2X1 g989__1617 (.Y(n_14),
	.A(codeword[0]),
	.B(codeword[10]));
   XNOR2X1 g990__2802 (.Y(n_13),
	.A(codeword[1]),
	.B(codeword[8]));
   XNOR2X1 g991__1705 (.Y(n_12),
	.A(codeword[9]),
	.B(codeword[14]));
   XNOR2X1 g992__5122 (.Y(n_17),
	.A(codeword[8]),
	.B(codeword[13]));
   INVX1 g993 (.Y(n_8),
	.A(n_9));
   XNOR2X1 g996__8246 (.Y(n_5),
	.A(codeword[1]),
	.B(codeword[4]));
   XNOR2X1 g997__7098 (.Y(n_4),
	.A(codeword[5]),
	.B(codeword[7]));
   XNOR2X1 g998__6131 (.Y(n_11),
	.A(codeword[6]),
	.B(codeword[11]));
   XNOR2X1 g999__1881 (.Y(n_10),
	.A(codeword[3]),
	.B(codeword[13]));
   XNOR2X1 g1000__5115 (.Y(n_9),
	.A(codeword[5]),
	.B(codeword[10]));
   CLKXOR2X1 g1001__7482 (.Y(n_7),
	.A(codeword[4]),
	.B(codeword[14]));
   XNOR2X1 g1002__4733 (.Y(n_6),
	.A(codeword[7]),
	.B(codeword[12]));
   XOR2XL g2__6161 (.Y(S1[3]),
	.A(n_18),
	.B(n_22));
   XOR2XL g1003__9315 (.Y(n_1),
	.A(n_7),
	.B(n_10));
   MXI2XL g1004__9945 (.Y(n_0),
	.A(n_8),
	.B(n_9),
	.S0(n_6));
endmodule

module bch_toplevel (
	clk, 
	rst, 
	codeword, 
	corrected_codeword, 
	error_flag);
   input clk;
   input rst;
   input [14:0] codeword;
   output [14:0] corrected_codeword;
   output error_flag;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;
   wire [3:0] S3;
   wire [3:0] lambda1;
   wire [3:0] lambda2;
   wire [14:0] error_vector;
   wire [14:0] corrector_o;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;
   wire error_found;

   bch_bm_block bm (.clk(clk),
	.rst(rst),
	.S1({ UNCONNECTED_HIER_Z0,
		UNCONNECTED_HIER_Z,
		S1[1],
		S1[0] }),
	.S2({ S1[3],
		S2[2],
		S1[2],
		S2[0] }),
	.S3(S3),
	.lambda1(lambda1),
	.lambda2(lambda2));
   bch_chien_block cb (.lambda1(lambda1),
	.lambda2(lambda2),
	.error_vector(error_vector),
	.error_found(error_found));
   bch_corrector cr (.corruptedWord(codeword),
	.errorVector(error_vector),
	.correctedWord(corrector_o));
   bch_syndrome_block sb (.codeword(codeword),
	.S1(S1),
	.S2({ UNCONNECTED0,
		S2[2],
		UNCONNECTED,
		S2[0] }),
	.S3(S3));
   DFFRX2 \corrected_codeword_reg[5]  (.Q(corrected_codeword[5]),
	.QN(UNCONNECTED1),
	.D(corrector_o[5]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[11]  (.Q(corrected_codeword[11]),
	.QN(UNCONNECTED2),
	.D(corrector_o[11]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[7]  (.Q(corrected_codeword[7]),
	.QN(UNCONNECTED3),
	.D(corrector_o[7]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[14]  (.Q(corrected_codeword[14]),
	.QN(UNCONNECTED4),
	.D(corrector_o[14]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[6]  (.Q(corrected_codeword[6]),
	.QN(UNCONNECTED5),
	.D(corrector_o[6]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[10]  (.Q(corrected_codeword[10]),
	.QN(UNCONNECTED6),
	.D(corrector_o[10]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[13]  (.Q(corrected_codeword[13]),
	.QN(UNCONNECTED7),
	.D(corrector_o[13]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[4]  (.Q(corrected_codeword[4]),
	.QN(UNCONNECTED8),
	.D(corrector_o[4]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[12]  (.Q(corrected_codeword[12]),
	.QN(UNCONNECTED9),
	.D(corrector_o[12]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[9]  (.Q(corrected_codeword[9]),
	.QN(UNCONNECTED10),
	.D(corrector_o[9]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[3]  (.Q(corrected_codeword[3]),
	.QN(UNCONNECTED11),
	.D(corrector_o[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[2]  (.Q(corrected_codeword[2]),
	.QN(UNCONNECTED12),
	.D(corrector_o[2]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[8]  (.Q(corrected_codeword[8]),
	.QN(UNCONNECTED13),
	.D(corrector_o[8]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[1]  (.Q(corrected_codeword[1]),
	.QN(UNCONNECTED14),
	.D(corrector_o[1]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \corrected_codeword_reg[0]  (.Q(corrected_codeword[0]),
	.QN(UNCONNECTED15),
	.D(corrector_o[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 error_flag_reg (.Q(error_flag),
	.QN(UNCONNECTED16),
	.D(error_found),
	.RN(rst),
	.CK(clk));
endmodule

