/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Oct  6 17:06:00 2025
#  Design:            bch_pipelined
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_pipelined/bch_pipelined_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 26 2025 15:15:31 -03 (Sep 26 2025 18:15:31 UTC)
// Verification Directory fv/bch_pipelined 
module gf_divider (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_68;
   wire n_70;

   OAI221X1 g1907__2398 (.Y(q[2]),
	.A0(n_22),
	.A1(n_53),
	.B0(b[0]),
	.B1(n_30),
	.C0(n_70));
   OR4X1 g1908__5107 (.Y(q[0]),
	.A(n_32),
	.B(n_56),
	.C(n_48),
	.D(n_65));
   AOI31X1 g1909__6260 (.Y(n_70),
	.A0(n_24),
	.A1(n_11),
	.A2(n_23),
	.B0(n_68));
   NAND4XL g1910__4319 (.Y(q[3]),
	.A(n_58),
	.B(n_50),
	.C(n_57),
	.D(n_64));
   OAI2BB1X1 g1911__8428 (.Y(n_68),
	.A0N(b[2]),
	.A1N(n_43),
	.B0(n_66));
   NAND4XL g1912__5526 (.Y(q[1]),
	.A(n_49),
	.B(n_59),
	.C(n_61),
	.D(n_55));
   AOI221X1 g1913__6783 (.Y(n_66),
	.A0(n_17),
	.A1(n_33),
	.B0(b[1]),
	.B1(n_28),
	.C0(n_62));
   OAI31X1 g1914__3680 (.Y(n_65),
	.A0(b[2]),
	.A1(n_0),
	.A2(n_9),
	.B0(n_63));
   AOI221X1 g1915__1617 (.Y(n_64),
	.A0(n_9),
	.A1(n_28),
	.B0(n_18),
	.B1(n_29),
	.C0(n_60));
   AOI32X1 g1916__2802 (.Y(n_63),
	.A0(b[1]),
	.A1(n_18),
	.A2(n_7),
	.B0(n_6),
	.B1(n_52));
   OAI32X1 g1917__1705 (.Y(n_62),
	.A0(n_22),
	.A1(n_16),
	.A2(n_35),
	.B0(b[3]),
	.B1(n_54));
   AOI32X1 g1918__5122 (.Y(n_61),
	.A0(b[3]),
	.A1(n_1),
	.A2(n_12),
	.B0(n_24),
	.B1(n_51));
   OAI31X1 g1919__8246 (.Y(n_60),
	.A0(a[0]),
	.A1(n_3),
	.A2(n_16),
	.B0(n_47));
   OA22X1 g1920__7098 (.Y(n_59),
	.A0(b[0]),
	.A1(n_45),
	.B0(n_7),
	.B1(n_39));
   AOI32X1 g1921__6131 (.Y(n_58),
	.A0(b[2]),
	.A1(n_26),
	.A2(n_20),
	.B0(n_8),
	.B1(n_37));
   AOI22XL g1922__1881 (.Y(n_57),
	.A0(n_11),
	.A1(n_42),
	.B0(n_21),
	.B1(n_46));
   OAI22XL g1923__5115 (.Y(n_56),
	.A0(n_22),
	.A1(n_38),
	.B0(n_1),
	.B1(n_40));
   AOI33XL g1924__7482 (.Y(n_55),
	.A0(n_2),
	.A1(n_11),
	.A2(n_28),
	.B0(n_4),
	.B1(b[3]),
	.B2(n_29));
   AOI22XL g1925__4733 (.Y(n_54),
	.A0(a[2]),
	.A1(n_27),
	.B0(n_18),
	.B1(n_6));
   AOI21XL g1926__6161 (.Y(n_53),
	.A0(n_1),
	.A1(n_35),
	.B0(n_14));
   OAI2BB1X1 g1927__9315 (.Y(n_52),
	.A0N(n_1),
	.A1N(n_11),
	.B0(n_41));
   OAI221X1 g1928__9945 (.Y(n_51),
	.A0(b[2]),
	.A1(n_10),
	.B0(a[2]),
	.B1(n_5),
	.C0(n_15));
   OA22X1 g1929__2883 (.Y(n_50),
	.A0(n_7),
	.A1(n_34),
	.B0(n_0),
	.B1(n_30));
   AOI22XL g1930__2346 (.Y(n_49),
	.A0(n_26),
	.A1(n_31),
	.B0(n_3),
	.B1(n_32));
   OAI21XL g1931__1666 (.Y(n_48),
	.A0(a[0]),
	.A1(n_34),
	.B0(n_44));
   AOI32X1 g1932__7410 (.Y(n_47),
	.A0(b[1]),
	.A1(n_2),
	.A2(n_14),
	.B0(n_12),
	.B1(n_36));
   OAI21XL g1933__6417 (.Y(n_46),
	.A0(b[2]),
	.A1(n_6),
	.B0(n_13));
   AOI21XL g1934__5477 (.Y(n_45),
	.A0(n_4),
	.A1(n_21),
	.B0(n_36));
   NAND2XL g1935__2398 (.Y(n_44),
	.A(n_20),
	.B(n_28));
   AO21X1 g1936__5107 (.Y(n_43),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_29));
   OAI22XL g1937__6260 (.Y(n_42),
	.A0(b[2]),
	.A1(n_7),
	.B0(a[2]),
	.B1(n_0));
   MX2X1 g1938__4319 (.Y(n_41),
	.A(n_16),
	.B(n_19),
	.S0(n_20));
   AOI22XL g1939__8428 (.Y(n_40),
	.A0(b[3]),
	.A1(n_8),
	.B0(b[0]),
	.B1(n_11));
   AOI22XL g1940__5526 (.Y(n_39),
	.A0(b[3]),
	.A1(n_19),
	.B0(b[1]),
	.B1(a[2]));
   OA22X1 g1941__6783 (.Y(n_38),
	.A0(a[0]),
	.A1(n_23),
	.B0(a[2]),
	.B1(n_25));
   OAI22XL g1942__3680 (.Y(n_37),
	.A0(n_3),
	.A1(n_23),
	.B0(n_0),
	.B1(n_15));
   NOR2XL g1943__1617 (.Y(n_36),
	.A(n_5),
	.B(n_16));
   NOR2XL g1944__2802 (.Y(n_35),
	.A(n_24),
	.B(n_26));
   NAND2XL g1945__1705 (.Y(n_34),
	.A(n_17),
	.B(n_23));
   NOR2XL g1946__5122 (.Y(n_33),
	.A(b[2]),
	.B(n_7));
   INVXL g1947 (.Y(n_31),
	.A(n_30));
   NAND2XL g1948__8246 (.Y(n_27),
	.A(n_9),
	.B(n_13));
   NOR2XL g1949__7098 (.Y(n_32),
	.A(n_19),
	.B(n_13));
   NAND2XL g1950__6131 (.Y(n_30),
	.A(n_17),
	.B(n_18));
   NOR2XL g1951__1881 (.Y(n_29),
	.A(a[0]),
	.B(n_9));
   NOR2XL g1952__5115 (.Y(n_28),
	.A(a[0]),
	.B(n_15));
   INVXL g1953 (.Y(n_25),
	.A(n_24));
   INVXL g1954 (.Y(n_21),
	.A(n_22));
   INVX1 g1955 (.Y(n_18),
	.A(n_19));
   NOR2XL g1956__7482 (.Y(n_26),
	.A(b[0]),
	.B(a[0]));
   NOR2XL g1957__4733 (.Y(n_24),
	.A(n_2),
	.B(n_0));
   NOR2XL g1958__6161 (.Y(n_23),
	.A(b[2]),
	.B(a[2]));
   NAND2XL g1959__9315 (.Y(n_22),
	.A(b[1]),
	.B(b[3]));
   NOR2XL g1960__9945 (.Y(n_20),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g1961__2883 (.Y(n_19),
	.A(b[2]),
	.B(a[2]));
   INVXL g1962 (.Y(n_14),
	.A(n_15));
   INVX1 g1963 (.Y(n_12),
	.A(n_13));
   INVXL g1964 (.Y(n_10),
	.A(n_11));
   INVX1 g1965 (.Y(n_8),
	.A(n_9));
   INVX1 g1966 (.Y(n_6),
	.A(n_7));
   NOR2XL g1967__2346 (.Y(n_17),
	.A(b[1]),
	.B(n_3));
   NAND2XL g1968__1666 (.Y(n_16),
	.A(a[2]),
	.B(n_4));
   NAND2XL g1969__7410 (.Y(n_15),
	.A(b[2]),
	.B(n_1));
   NAND2XL g1970__6417 (.Y(n_13),
	.A(b[0]),
	.B(n_0));
   NOR2XL g1971__5477 (.Y(n_11),
	.A(b[3]),
	.B(n_5));
   NAND2XL g1972__2398 (.Y(n_9),
	.A(b[0]),
	.B(n_5));
   NAND2XL g1973__5107 (.Y(n_7),
	.A(a[0]),
	.B(n_2));
   INVX1 g1974 (.Y(n_5),
	.A(b[1]));
   INVX1 g1975 (.Y(n_4),
	.A(b[2]));
   INVX1 g1976 (.Y(n_3),
	.A(b[3]));
   INVX1 g1977 (.Y(n_2),
	.A(b[0]));
   INVX1 g1978 (.Y(n_1),
	.A(a[2]));
   INVX1 g1979 (.Y(n_0),
	.A(a[0]));
endmodule

module bm_stage_1 (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	l1_1, 
	S1_o, 
	S2_o, 
	S3_o);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   output [3:0] l1_1;
   output [3:0] S1_o;
   output [3:0] S2_o;
   output [3:0] S3_o;

   // Internal wires
   wire [3:0] div1;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;

   gf_divider u_div1 (.a({ UNCONNECTED_HIER_Z0,
		S2[2],
		UNCONNECTED_HIER_Z,
		S2[0] }),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.q(div1));
   DFFRHQX1 \l1_1_reg[0]  (.Q(l1_1[0]),
	.D(div1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_1_reg[2]  (.Q(l1_1[2]),
	.D(div1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_1_reg[1]  (.Q(l1_1[1]),
	.D(div1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_1_reg[3]  (.Q(l1_1[3]),
	.D(div1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[2]  (.Q(S3_o[2]),
	.D(S3[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[1]  (.Q(S1_o[1]),
	.D(S1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[0]  (.Q(S1_o[0]),
	.D(S1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[3]  (.Q(S3_o[3]),
	.D(S3[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[1]  (.Q(S3_o[1]),
	.D(S3[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_o_reg[2]  (.Q(S2_o[2]),
	.D(S2[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[3]  (.Q(S1_o[3]),
	.D(S2[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_o_reg[0]  (.Q(S3_o[0]),
	.D(S3[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_o_reg[0]  (.Q(S2_o[0]),
	.D(S2[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[2]  (.Q(S1_o[2]),
	.D(S2[1]),
	.RN(rst),
	.CK(clk));
endmodule

module gf_multiplier (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__6260 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__4319 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__8428 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__5526 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__6783 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__3680 (.Y(n_74),
	.AN(n_68),
	.B(n_56),
	.C(n_61));
   NAND2XL g1996__1617 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__2802 (.Y(n_70),
	.A0(n_57),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__1705 (.Y(n_71),
	.A0(n_57),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__5122 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__8246 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__7098 (.Y(n_67),
	.A(n_57),
	.B(n_65));
   AOI21XL g2003__6131 (.Y(n_66),
	.A0(n_55),
	.A1(n_56),
	.B0(n_63));
   XNOR2X1 g2004__1881 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__5115 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__7482 (.Y(n_62),
	.A(n_56),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__4733 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__6161 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__9315 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__9945 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__2883 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__2346 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__1666 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI221X1 g2017__7410 (.Y(n_52),
	.A0(n_49),
	.A1(n_51),
	.B0(n_37),
	.B1(n_47),
	.C0(n_38));
   INVXL g2018 (.Y(n_51),
	.A(n_50));
   NAND3BXL g2019__6417 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__5477 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__2398 (.CO(n_47),
	.S(n_48),
	.A(n_43),
	.B(n_44),
	.CI(n_45));
   ADDFX1 g2022__5107 (.CO(n_45),
	.S(n_46),
	.A(n_41),
	.B(n_39),
	.CI(n_36));
   OAI211X1 g2023__6260 (.Y(n_44),
	.A0(n_9),
	.A1(n_34),
	.B0(n_14),
	.C0(n_21));
   OAI211X1 g2024__4319 (.Y(n_43),
	.A0(n_10),
	.A1(n_33),
	.B0(n_16),
	.C0(n_23));
   NAND2BXL g2025__8428 (.Y(n_42),
	.AN(n_38),
	.B(n_37));
   OAI221X1 g2026__5526 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_16),
	.C0(n_18));
   OAI221X1 g2027__6783 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_14),
	.C0(n_19));
   XNOR2X1 g2028__3680 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__1617 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__2802 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__1705 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__5122 (.Y(n_34),
	.A0(n_4),
	.A1(n_22),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__8246 (.Y(n_33),
	.A0(n_5),
	.A1(n_24),
	.B0(a[0]),
	.B1(n_11));
   AOI221X1 g2034__7098 (.Y(n_35),
	.A0(n_15),
	.A1(n_10),
	.B0(a[3]),
	.B1(n_11),
	.C0(n_20));
   AOI222X1 g2035__6131 (.Y(n_32),
	.A0(n_7),
	.A1(n_15),
	.B0(a[2]),
	.B1(a[0]),
	.C0(a[1]),
	.C1(n_12));
   AOI221X1 g2036__1881 (.Y(n_31),
	.A0(b[1]),
	.A1(n_13),
	.B0(b[2]),
	.B1(b[0]),
	.C0(n_25));
   AOI221X1 g2037__5115 (.Y(n_30),
	.A0(b[3]),
	.A1(n_17),
	.B0(n_4),
	.B1(n_8),
	.C0(n_26));
   OAI33X1 g2038__7482 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[3]),
	.B1(a[2]),
	.B2(n_18));
   AOI31X1 g2039__4733 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_12));
   AOI31X1 g2040__6161 (.Y(n_27),
	.A0(b[0]),
	.A1(b[1]),
	.A2(n_0),
	.B0(n_13));
   NOR2XL g2041__9315 (.Y(n_26),
	.A(n_14),
	.B(n_8));
   NOR2XL g2042__9945 (.Y(n_25),
	.A(b[1]),
	.B(n_14));
   NOR2XL g2043__2883 (.Y(n_24),
	.A(a[3]),
	.B(n_11));
   NAND2XL g2044__2346 (.Y(n_23),
	.A(a[3]),
	.B(n_10));
   NOR2XL g2045__1666 (.Y(n_22),
	.A(b[3]),
	.B(n_17));
   NAND2XL g2046__7410 (.Y(n_21),
	.A(b[3]),
	.B(n_9));
   NOR2XL g2047__6417 (.Y(n_20),
	.A(a[0]),
	.B(n_10));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   NAND2XL g2049__5477 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2050__2398 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2051__5107 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NAND2XL g2052__6260 (.Y(n_16),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2053__4319 (.Y(n_14),
	.A(b[0]),
	.B(b[3]));
   INVXL g2054 (.Y(n_8),
	.A(n_9));
   NOR2XL g2055__8428 (.Y(n_13),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__5526 (.Y(n_12),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__6783 (.Y(n_11),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__3680 (.Y(n_10),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__1617 (.Y(n_9),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVXL g2061 (.Y(n_6),
	.A(a[3]));
   INVXL g2062 (.Y(n_5),
	.A(a[0]));
   INVX1 g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module xor_4 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__2802 (.Y(y[3]),
	.A(b[3]),
	.B(a[3]));
   CLKXOR2X1 g38__1705 (.Y(y[1]),
	.A(b[1]),
	.B(a[1]));
   CLKXOR2X1 g39__5122 (.Y(y[0]),
	.A(b[0]),
	.B(a[0]));
   CLKXOR2X1 g40__8246 (.Y(y[2]),
	.A(b[2]),
	.B(a[2]));
endmodule

module bm_stage_2 (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	l1_1, 
	l1_2, 
	l2_2, 
	S1_o);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   input [3:0] l1_1;
   output [3:0] l1_2;
   output [3:0] l2_2;
   output [3:0] S1_o;

   // Internal wires
   wire [3:0] mult1;
   wire [3:0] xor1;

   gf_multiplier u_mult1 (.a(l1_1),
	.b(S2),
	.p(mult1));
   xor_4 u_xor1 (.a(mult1),
	.b(S3),
	.y(xor1));
   DFFRHQX1 \l2_2_reg[1]  (.Q(l2_2[1]),
	.D(xor1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_2_reg[3]  (.Q(l2_2[3]),
	.D(xor1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_2_reg[2]  (.Q(l2_2[2]),
	.D(xor1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_2_reg[0]  (.Q(l2_2[0]),
	.D(xor1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[3]  (.Q(l1_2[3]),
	.D(l1_1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[2]  (.Q(l1_2[2]),
	.D(l1_1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[1]  (.Q(l1_2[1]),
	.D(l1_1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_2_reg[0]  (.Q(l1_2[0]),
	.D(l1_1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[2]  (.Q(S1_o[2]),
	.D(S2[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[3]  (.Q(S1_o[3]),
	.D(S2[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[1]  (.Q(S1_o[1]),
	.D(S1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_o_reg[0]  (.Q(S1_o[0]),
	.D(S1[0]),
	.RN(rst),
	.CK(clk));
endmodule

module gf_divider_494 (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;

   NAND3BXL g2032__7098 (.Y(q[2]),
	.AN(n_77),
	.B(n_76),
	.C(n_67));
   OAI211X1 g2033__6131 (.Y(q[0]),
	.A0(n_66),
	.A1(n_68),
	.B0(n_73),
	.C0(n_67));
   OAI211X1 g2034__1881 (.Y(q[1]),
	.A0(n_65),
	.A1(n_68),
	.B0(n_76),
	.C0(n_72));
   OAI211X1 g2035__5115 (.Y(q[3]),
	.A0(n_28),
	.A1(n_70),
	.B0(n_74),
	.C0(n_67));
   OAI22XL g2036__7482 (.Y(n_77),
	.A0(n_53),
	.A1(n_75),
	.B0(n_61),
	.B1(n_68));
   NOR2XL g2037__4733 (.Y(n_75),
	.A(n_69),
	.B(n_71));
   NAND2XL g2038__6161 (.Y(n_76),
	.A(n_61),
	.B(n_69));
   OAI21XL g2039__9315 (.Y(n_74),
	.A0(n_53),
	.A1(n_63),
	.B0(n_71));
   NAND3BXL g2040__9945 (.Y(n_73),
	.AN(n_53),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2041__2883 (.Y(n_72),
	.AN(n_61),
	.B(n_29),
	.C(n_64));
   NAND2XL g2042__2346 (.Y(n_70),
	.A(n_65),
	.B(n_64));
   NOR2XL g2043__1666 (.Y(n_71),
	.A(n_28),
	.B(n_66));
   NOR3BXL g2044__7410 (.Y(n_69),
	.AN(n_65),
	.B(n_28),
	.C(n_63));
   NAND3BXL g2045__6417 (.Y(n_68),
	.AN(n_28),
	.B(n_53),
	.C(n_63));
   NAND4XL g2046__5477 (.Y(n_67),
	.A(n_29),
	.B(n_60),
	.C(n_63),
	.D(n_65));
   OR2X1 g2047__2398 (.Y(n_66),
	.A(n_60),
	.B(n_65));
   XNOR2X1 g2048__5107 (.Y(n_65),
	.A(n_58),
	.B(n_62));
   CLKXOR2X1 g2049__6260 (.Y(n_64),
	.A(n_53),
	.B(n_63));
   ADDFX1 g2050__4319 (.CO(n_62),
	.S(n_63),
	.A(n_55),
	.B(n_54),
	.CI(n_59));
   INVXL g2051 (.Y(n_60),
	.A(n_61));
   ADDFX1 g2052__8428 (.CO(n_59),
	.S(n_61),
	.A(n_35),
	.B(n_50),
	.CI(n_52));
   XNOR2X1 g2053__5526 (.Y(n_58),
	.A(n_56),
	.B(n_57));
   XNOR2X1 g2054__6783 (.Y(n_57),
	.A(n_27),
	.B(n_51));
   OAI21XL g2055__3680 (.Y(n_56),
	.A0(n_42),
	.A1(n_49),
	.B0(n_43));
   OAI21XL g2056__1617 (.Y(n_55),
	.A0(n_40),
	.A1(n_49),
	.B0(n_38));
   XNOR2X1 g2057__2802 (.Y(n_54),
	.A(n_44),
	.B(n_49));
   XNOR2X1 g2058__1705 (.Y(n_52),
	.A(n_41),
	.B(n_49));
   XNOR2X1 g2059__5122 (.Y(n_51),
	.A(n_26),
	.B(n_49));
   XNOR2X1 g2060__8246 (.Y(n_53),
	.A(n_37),
	.B(n_49));
   NOR2BX1 g2061__7098 (.Y(n_50),
	.AN(n_37),
	.B(n_49));
   OAI21XL g2062__6131 (.Y(n_49),
	.A0(n_26),
	.A1(n_47),
	.B0(n_48));
   OAI2BB1X1 g2063__1881 (.Y(n_48),
	.A0N(n_26),
	.A1N(n_47),
	.B0(n_27));
   OA21X1 g2064__5115 (.Y(n_47),
	.A0(n_42),
	.A1(n_46),
	.B0(n_43));
   AND2X1 g2065__7482 (.Y(n_46),
	.A(n_45),
	.B(n_38));
   NAND2BXL g2066__4733 (.Y(n_45),
	.AN(n_40),
	.B(n_35));
   XNOR2X1 g2067__6161 (.Y(n_44),
	.A(n_36),
	.B(n_39));
   NAND2BXL g2068__9315 (.Y(n_43),
	.AN(n_39),
	.B(n_36));
   NOR2BX1 g2069__9945 (.Y(n_42),
	.AN(n_39),
	.B(n_36));
   XNOR2X1 g2070__2883 (.Y(n_41),
	.A(n_32),
	.B(n_33));
   NOR2BX1 g2071__2346 (.Y(n_40),
	.AN(n_33),
	.B(n_32));
   OAI211X1 g2072__1666 (.Y(n_39),
	.A0(b[2]),
	.A1(n_7),
	.B0(n_12),
	.C0(n_25));
   NAND2BXL g2073__7410 (.Y(n_38),
	.AN(n_33),
	.B(n_32));
   OAI21XL g2074__6417 (.Y(n_37),
	.A0(n_30),
	.A1(n_31),
	.B0(n_35));
   NAND2XL g2075__5477 (.Y(n_36),
	.A(n_13),
	.B(n_34));
   AOI31X1 g2076__2398 (.Y(n_34),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_1),
	.B0(n_24));
   NAND2XL g2077__5107 (.Y(n_35),
	.A(n_30),
	.B(n_31));
   OAI222XL g2078__6260 (.Y(n_33),
	.A0(b[0]),
	.A1(n_18),
	.B0(n_5),
	.B1(n_17),
	.C0(b[2]),
	.C1(n_12));
   OAI222XL g2079__4319 (.Y(n_32),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_4),
	.B1(n_19),
	.C0(a[2]),
	.C1(n_13));
   INVX1 g2080 (.Y(n_28),
	.A(n_29));
   OAI222XL g2081__8428 (.Y(n_31),
	.A0(b[0]),
	.A1(n_8),
	.B0(n_12),
	.B1(n_9),
	.C0(b[2]),
	.C1(n_16));
   AOI221X1 g2082__5526 (.Y(n_30),
	.A0(n_1),
	.A1(n_15),
	.B0(n_4),
	.B1(n_10),
	.C0(n_21));
   NOR2XL g2083__6783 (.Y(n_29),
	.A(n_22),
	.B(n_23));
   AOI32X1 g2084__3680 (.Y(n_25),
	.A0(b[2]),
	.A1(n_5),
	.A2(n_11),
	.B0(b[3]),
	.B1(n_8));
   OAI22XL g2085__1617 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2086__2802 (.Y(n_27),
	.A0(n_1),
	.A1(n_4),
	.B0(a[1]),
	.B1(n_13),
	.C0(a[0]),
	.C1(n_14));
   OAI222XL g2087__1705 (.Y(n_26),
	.A0(n_0),
	.A1(n_5),
	.B0(b[1]),
	.B1(n_12),
	.C0(b[0]),
	.C1(n_16));
   NOR4X1 g2088__5122 (.Y(n_23),
	.A(a[3]),
	.B(a[1]),
	.C(a[2]),
	.D(a[0]));
   NOR4X1 g2089__8246 (.Y(n_22),
	.A(b[3]),
	.B(b[1]),
	.C(b[2]),
	.D(b[0]));
   NOR2XL g2090__7098 (.Y(n_21),
	.A(n_13),
	.B(n_10));
   AOI21XL g2091__6131 (.Y(n_20),
	.A0(a[3]),
	.A1(a[2]),
	.B0(n_3));
   AOI21XL g2092__1881 (.Y(n_18),
	.A0(b[3]),
	.A1(b[2]),
	.B0(n_2));
   NAND2XL g2093__5115 (.Y(n_17),
	.A(b[2]),
	.B(n_11));
   NAND3XL g2094__7482 (.Y(n_19),
	.A(a[2]),
	.B(a[1]),
	.C(n_6));
   INVXL g2095 (.Y(n_15),
	.A(n_14));
   NAND2XL g2096__4733 (.Y(n_16),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g2097__6161 (.Y(n_14),
	.A(a[1]),
	.B(a[3]));
   NAND2XL g2098__9315 (.Y(n_13),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2099__9945 (.Y(n_12),
	.A(b[0]),
	.B(b[3]));
   INVXL g2100 (.Y(n_9),
	.A(n_8));
   NOR2XL g2101__2883 (.Y(n_11),
	.A(b[3]),
	.B(n_2));
   NAND2XL g2102__2346 (.Y(n_7),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2103__1666 (.Y(n_10),
	.A(a[2]),
	.B(n_3));
   NOR2XL g2104__7410 (.Y(n_8),
	.A(b[1]),
	.B(n_0));
   INVXL g2105 (.Y(n_6),
	.A(a[3]));
   INVX1 g2106 (.Y(n_5),
	.A(b[0]));
   INVX1 g2107 (.Y(n_4),
	.A(a[0]));
   INVXL g2108 (.Y(n_3),
	.A(a[1]));
   INVXL g2109 (.Y(n_2),
	.A(b[1]));
   INVX1 g2110 (.Y(n_1),
	.A(a[2]));
   INVXL g2111 (.Y(n_0),
	.A(b[2]));
endmodule

module bm_stage_3 (
	clk, 
	rst, 
	S1, 
	l1_2, 
	l2_2, 
	l1, 
	l2);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] l1_2;
   input [3:0] l2_2;
   output [3:0] l1;
   output [3:0] l2;

   // Internal wires
   wire [3:0] div1;

   gf_divider_494 u_div1 (.a(l2_2),
	.b(S1),
	.q(div1));
   DFFRHQX1 \l2_reg[1]  (.Q(l2[1]),
	.D(div1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_reg[2]  (.Q(l2[2]),
	.D(div1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_reg[3]  (.Q(l2[3]),
	.D(div1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l2_reg[0]  (.Q(l2[0]),
	.D(div1[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_reg[3]  (.Q(l1[3]),
	.D(l1_2[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_reg[2]  (.Q(l1[2]),
	.D(l1_2[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_reg[1]  (.Q(l1[1]),
	.D(l1_2[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \l1_reg[0]  (.Q(l1[0]),
	.D(l1_2[0]),
	.RN(rst),
	.CK(clk));
endmodule

module bch_chien_block (
	lambda1, 
	lambda2, 
	error_vector, 
	error_found);
   input [3:0] lambda1;
   input [3:0] lambda2;
   output [14:0] error_vector;
   output error_found;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_282;
   wire n_283;
   wire n_286;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;

   OR4X1 g329347__6417 (.Y(error_found),
	.A(error_vector[6]),
	.B(error_vector[11]),
	.C(error_vector[2]),
	.D(n_298));
   OR4X1 g329348__5477 (.Y(n_298),
	.A(error_vector[7]),
	.B(error_vector[9]),
	.C(error_vector[10]),
	.D(n_297));
   OR4X1 g329349__2398 (.Y(n_297),
	.A(error_vector[1]),
	.B(error_vector[3]),
	.C(error_vector[8]),
	.D(n_296));
   OR3XL g329350__5107 (.Y(n_296),
	.A(error_vector[0]),
	.B(error_vector[14]),
	.C(n_295));
   OR4X1 g329351__6260 (.Y(n_295),
	.A(error_vector[13]),
	.B(error_vector[12]),
	.C(error_vector[4]),
	.D(error_vector[5]));
   AOI221X1 g329352__4319 (.Y(error_vector[6]),
	.A0(n_195),
	.A1(n_180),
	.B0(n_179),
	.B1(n_194),
	.C0(n_282));
   AOI221X1 g329353__8428 (.Y(error_vector[4]),
	.A0(n_224),
	.A1(n_209),
	.B0(n_225),
	.B1(n_210),
	.C0(n_286));
   NOR4X1 g329354__5526 (.Y(error_vector[9]),
	.A(n_252),
	.B(n_261),
	.C(n_236),
	.D(n_238));
   NOR4X1 g329355__6783 (.Y(error_vector[7]),
	.A(n_201),
	.B(n_246),
	.C(n_259),
	.D(n_270));
   AOI221X1 g329356__3680 (.Y(error_vector[5]),
	.A0(n_180),
	.A1(n_206),
	.B0(n_179),
	.B1(n_205),
	.C0(n_283));
   NOR4X1 g329357__1617 (.Y(error_vector[8]),
	.A(n_220),
	.B(n_248),
	.C(n_260),
	.D(n_271));
   OAI211X1 g329358__2802 (.Y(n_286),
	.A0(n_203),
	.A1(n_191),
	.B0(n_226),
	.C0(n_279));
   AOI221X1 g329359__1705 (.Y(error_vector[10]),
	.A0(n_197),
	.A1(n_213),
	.B0(n_196),
	.B1(n_214),
	.C0(n_278));
   AOI221X1 g329360__5122 (.Y(error_vector[11]),
	.A0(n_198),
	.A1(n_209),
	.B0(n_199),
	.B1(n_210),
	.C0(n_272));
   OAI221X1 g329361__8246 (.Y(n_283),
	.A0(n_195),
	.A1(n_258),
	.B0(n_194),
	.B1(n_257),
	.C0(n_276));
   OAI211X1 g329362__7098 (.Y(n_282),
	.A0(n_40),
	.A1(n_258),
	.B0(n_266),
	.C0(n_277));
   AOI221X1 g329363__6131 (.Y(error_vector[3]),
	.A0(lambda1[0]),
	.A1(n_213),
	.B0(n_13),
	.B1(n_214),
	.C0(n_273));
   AOI221X1 g329364__1881 (.Y(error_vector[12]),
	.A0(n_199),
	.A1(n_191),
	.B0(n_198),
	.B1(n_190),
	.C0(n_280));
   OAI211X1 g329365__5115 (.Y(n_280),
	.A0(n_228),
	.A1(n_229),
	.B0(n_232),
	.C0(n_262));
   AOI221X1 g329366__7482 (.Y(n_279),
	.A0(n_180),
	.A1(n_218),
	.B0(n_179),
	.B1(n_217),
	.C0(n_264));
   OAI221X1 g329367__4733 (.Y(n_278),
	.A0(n_212),
	.A1(n_209),
	.B0(n_211),
	.B1(n_210),
	.C0(n_268));
   AOI221X1 g329368__6161 (.Y(n_277),
	.A0(n_8),
	.A1(n_243),
	.B0(lambda2[1]),
	.B1(n_242),
	.C0(n_247));
   AOI221X1 g329369__9315 (.Y(n_276),
	.A0(n_230),
	.A1(n_217),
	.B0(n_231),
	.B1(n_218),
	.C0(n_263));
   NOR4X1 g329370__9945 (.Y(error_vector[1]),
	.A(n_38),
	.B(n_35),
	.C(n_202),
	.D(n_253));
   OAI211X1 g329371__2883 (.Y(n_273),
	.A0(n_240),
	.A1(n_241),
	.B0(n_251),
	.C0(n_235));
   OAI211X1 g329372__2346 (.Y(n_272),
	.A0(n_207),
	.A1(n_245),
	.B0(n_256),
	.C0(n_254));
   OAI22XL g329373__1666 (.Y(n_271),
	.A0(n_12),
	.A1(n_258),
	.B0(lambda2[2]),
	.B1(n_257));
   OAI22XL g329374__7410 (.Y(n_270),
	.A0(n_8),
	.A1(n_258),
	.B0(lambda2[1]),
	.B1(n_257));
   AOI221X1 g329375__6417 (.Y(error_vector[2]),
	.A0(lambda1[3]),
	.A1(n_183),
	.B0(n_9),
	.B1(n_184),
	.C0(n_265));
   AOI221X1 g329376__5477 (.Y(error_vector[13]),
	.A0(lambda1[1]),
	.A1(n_194),
	.B0(n_10),
	.B1(n_195),
	.C0(n_267));
   AOI221X1 g329377__2398 (.Y(n_268),
	.A0(n_223),
	.A1(n_216),
	.B0(n_222),
	.B1(n_215),
	.C0(n_221));
   OAI221X1 g329378__5107 (.Y(n_267),
	.A0(lambda1[2]),
	.A1(n_39),
	.B0(n_15),
	.B1(n_40),
	.C0(n_255));
   NAND2XL g329379__6260 (.Y(n_266),
	.A(n_40),
	.B(n_258));
   OAI221X1 g329380__4319 (.Y(n_265),
	.A0(n_224),
	.A1(n_214),
	.B0(n_225),
	.B1(n_213),
	.C0(n_249));
   NOR2XL g329381__8428 (.Y(error_vector[14]),
	.A(n_67),
	.B(n_250));
   AOI22XL g329382__5526 (.Y(n_264),
	.A0(n_230),
	.A1(n_244),
	.B0(n_231),
	.B1(n_245));
   AOI22XL g329383__6783 (.Y(n_263),
	.A0(n_204),
	.A1(n_244),
	.B0(n_203),
	.B1(n_245));
   AOI22XL g329384__3680 (.Y(n_262),
	.A0(n_212),
	.A1(n_244),
	.B0(n_211),
	.B1(n_245));
   AOI22XL g329385__1617 (.Y(n_261),
	.A0(n_14),
	.A1(n_243),
	.B0(lambda2[0]),
	.B1(n_242));
   AOI22XL g329386__2802 (.Y(n_260),
	.A0(n_11),
	.A1(n_243),
	.B0(lambda2[3]),
	.B1(n_242));
   AOI22XL g329387__1705 (.Y(n_259),
	.A0(n_12),
	.A1(n_243),
	.B0(lambda2[2]),
	.B1(n_242));
   INVX1 g329388 (.Y(n_257),
	.A(n_258));
   AOI221X1 g329389__5122 (.Y(n_256),
	.A0(n_197),
	.A1(n_188),
	.B0(n_196),
	.B1(n_189),
	.C0(n_233));
   AOI221X1 g329390__8246 (.Y(n_255),
	.A0(n_212),
	.A1(n_218),
	.B0(n_211),
	.B1(n_217),
	.C0(n_237));
   NAND2XL g329391__7098 (.Y(n_254),
	.A(n_207),
	.B(n_245));
   OAI22XL g329392__6131 (.Y(n_253),
	.A0(n_225),
	.A1(n_216),
	.B0(n_224),
	.B1(n_215));
   OAI22XL g329393__1881 (.Y(n_252),
	.A0(n_183),
	.A1(n_222),
	.B0(n_184),
	.B1(n_223));
   NAND3BXL g329394__5115 (.Y(n_258),
	.AN(n_77),
	.B(n_0),
	.C(n_219));
   OAI22XL g329395__7482 (.Y(n_251),
	.A0(n_225),
	.A1(n_189),
	.B0(n_224),
	.B1(n_188));
   OAI221X1 g329396__4733 (.Y(n_250),
	.A0(n_10),
	.A1(n_39),
	.B0(lambda1[1]),
	.B1(n_40),
	.C0(n_239));
   AOI221X1 g329397__6161 (.Y(n_249),
	.A0(lambda1[0]),
	.A1(n_215),
	.B0(n_13),
	.B1(n_216),
	.C0(n_234));
   AOI22XL g329398__9315 (.Y(n_248),
	.A0(n_14),
	.A1(n_223),
	.B0(lambda2[0]),
	.B1(n_222));
   AOI22XL g329399__9945 (.Y(n_247),
	.A0(n_230),
	.A1(n_205),
	.B0(n_231),
	.B1(n_206));
   AOI22XL g329400__2883 (.Y(n_246),
	.A0(lambda2[3]),
	.A1(n_223),
	.B0(n_11),
	.B1(n_222));
   INVX1 g329401 (.Y(n_244),
	.A(n_245));
   INVX1 g329402 (.Y(n_242),
	.A(n_243));
   NOR2XL g329403__2346 (.Y(n_241),
	.A(n_191),
	.B(n_231));
   NOR2XL g329404__1666 (.Y(n_240),
	.A(n_190),
	.B(n_230));
   AOI22XL g329405__7410 (.Y(n_239),
	.A0(n_195),
	.A1(n_208),
	.B0(n_194),
	.B1(n_207));
   OAI22XL g329406__6417 (.Y(n_238),
	.A0(n_199),
	.A1(n_214),
	.B0(n_198),
	.B1(n_213));
   OAI211X1 g329407__5477 (.Y(n_245),
	.A0(n_58),
	.A1(n_186),
	.B0(n_56),
	.C0(n_109));
   AOI31X1 g329408__2398 (.Y(n_243),
	.A0(n_114),
	.A1(n_149),
	.A2(n_181),
	.B0(n_227));
   OAI22XL g329409__5107 (.Y(n_237),
	.A0(n_207),
	.A1(n_205),
	.B0(n_208),
	.B1(n_206));
   AOI22XL g329410__6260 (.Y(n_236),
	.A0(n_196),
	.A1(n_215),
	.B0(n_197),
	.B1(n_216));
   AOI22XL g329411__4319 (.Y(n_235),
	.A0(n_204),
	.A1(n_209),
	.B0(n_203),
	.B1(n_210));
   AOI22XL g329412__8428 (.Y(n_234),
	.A0(n_204),
	.A1(n_189),
	.B0(n_203),
	.B1(n_188));
   AOI22XL g329413__5526 (.Y(n_233),
	.A0(n_191),
	.A1(n_211),
	.B0(n_190),
	.B1(n_212));
   OAI22XL g329414__6783 (.Y(n_232),
	.A0(n_10),
	.A1(n_206),
	.B0(lambda1[1]),
	.B1(n_205));
   INVX1 g329415 (.Y(n_230),
	.A(n_231));
   NOR2XL g329416__3680 (.Y(n_229),
	.A(n_208),
	.B(n_218));
   NOR2XL g329417__1617 (.Y(n_228),
	.A(n_207),
	.B(n_217));
   OAI31X1 g329418__2802 (.Y(n_227),
	.A0(n_105),
	.A1(n_150),
	.A2(n_181),
	.B0(n_93));
   NAND2XL g329419__1705 (.Y(n_226),
	.A(n_203),
	.B(n_191));
   NAND2XL g329420__5122 (.Y(n_231),
	.A(n_87),
	.B(n_200));
   INVX1 g329421 (.Y(n_224),
	.A(n_225));
   INVX1 g329422 (.Y(n_222),
	.A(n_223));
   AOI22XL g329423__8246 (.Y(n_221),
	.A0(n_198),
	.A1(n_188),
	.B0(n_199),
	.B1(n_189));
   OAI22XL g329424__7098 (.Y(n_220),
	.A0(n_197),
	.A1(n_184),
	.B0(n_196),
	.B1(n_183));
   AOI33XL g329425__6131 (.Y(n_219),
	.A0(n_55),
	.A1(n_124),
	.A2(n_178),
	.B0(n_127),
	.B1(1'b1),
	.B2(n_143));
   OAI211X1 g329426__1881 (.Y(n_225),
	.A0(n_54),
	.A1(n_113),
	.B0(n_2),
	.C0(n_185));
   AOI221X1 g329427__5115 (.Y(n_223),
	.A0(n_142),
	.A1(n_181),
	.B0(n_100),
	.B1(n_159),
	.C0(n_90));
   INVX1 g329428 (.Y(n_217),
	.A(n_218));
   INVX1 g329429 (.Y(n_215),
	.A(n_216));
   INVX1 g329430 (.Y(n_213),
	.A(n_214));
   INVX1 g329431 (.Y(n_211),
	.A(n_212));
   INVX1 g329432 (.Y(n_209),
	.A(n_210));
   NOR2XL g329433__7482 (.Y(n_218),
	.A(n_107),
	.B(n_192));
   OAI211X1 g329434__4733 (.Y(n_216),
	.A0(n_84),
	.A1(n_129),
	.B0(n_97),
	.C0(n_182));
   NAND2XL g329435__6161 (.Y(n_214),
	.A(n_86),
	.B(n_193));
   OAI211X1 g329436__9315 (.Y(n_212),
	.A0(n_112),
	.A1(n_172),
	.B0(n_75),
	.C0(n_88));
   AOI211XL g329437__9945 (.Y(n_210),
	.A0(n_152),
	.A1(n_167),
	.B0(n_41),
	.C0(n_80));
   INVX1 g329438 (.Y(n_207),
	.A(n_208));
   INVX1 g329439 (.Y(n_205),
	.A(n_206));
   INVX1 g329440 (.Y(n_203),
	.A(n_204));
   OAI22XL g329441__2883 (.Y(n_202),
	.A0(n_13),
	.A1(n_184),
	.B0(lambda1[0]),
	.B1(n_183));
   OAI22XL g329442__2346 (.Y(n_201),
	.A0(n_40),
	.A1(n_179),
	.B0(n_39),
	.B1(n_180));
   AOI33XL g329443__1666 (.Y(n_200),
	.A0(n_68),
	.A1(n_112),
	.A2(n_160),
	.B0(n_149),
	.B1(n_128),
	.B2(n_155));
   AOI222X1 g329444__7410 (.Y(n_208),
	.A0(n_121),
	.A1(n_173),
	.B0(n_115),
	.B1(n_134),
	.C0(n_148),
	.C1(n_146));
   OAI211X1 g329445__6417 (.Y(n_206),
	.A0(n_151),
	.A1(n_169),
	.B0(n_1),
	.C0(n_51));
   AOI31X1 g329446__5477 (.Y(n_204),
	.A0(n_55),
	.A1(n_114),
	.A2(n_120),
	.B0(n_187));
   INVX1 g329447 (.Y(n_198),
	.A(n_199));
   INVX1 g329448 (.Y(n_196),
	.A(n_197));
   INVX1 g329449 (.Y(n_194),
	.A(n_195));
   AOI33XL g329450__2398 (.Y(n_193),
	.A0(n_133),
	.A1(n_152),
	.A2(n_168),
	.B0(n_136),
	.B1(n_97),
	.B2(n_167));
   AOI211XL g329451__5107 (.Y(n_192),
	.A0(n_139),
	.A1(n_141),
	.B0(n_117),
	.C0(n_7));
   OAI211X1 g329452__6260 (.Y(n_199),
	.A0(n_114),
	.A1(n_150),
	.B0(n_2),
	.C0(n_171));
   OAI211X1 g329453__4319 (.Y(n_197),
	.A0(n_102),
	.A1(n_115),
	.B0(n_79),
	.C0(n_170));
   OAI211X1 g329454__8428 (.Y(n_195),
	.A0(n_106),
	.A1(n_122),
	.B0(n_73),
	.C0(n_175));
   INVX1 g329455 (.Y(n_190),
	.A(n_191));
   INVX1 g329456 (.Y(n_188),
	.A(n_189));
   OAI32X1 g329457__5526 (.Y(n_187),
	.A0(n_118),
	.A1(n_126),
	.A2(n_147),
	.B0(n_130),
	.B1(n_176));
   OAI211X1 g329458__6783 (.Y(n_186),
	.A0(n_123),
	.A1(n_140),
	.B0(n_106),
	.C0(n_164));
   OAI211X1 g329459__3680 (.Y(n_185),
	.A0(n_69),
	.A1(n_121),
	.B0(n_134),
	.C0(n_161));
   AOI22XL g329460__1617 (.Y(n_191),
	.A0(n_139),
	.A1(n_169),
	.B0(n_122),
	.B1(n_152));
   OAI211X1 g329461__2802 (.Y(n_189),
	.A0(n_6),
	.A1(n_168),
	.B0(n_144),
	.C0(n_162));
   INVX1 g329462 (.Y(n_183),
	.A(n_184));
   OAI221X1 g329463__1705 (.Y(n_182),
	.A0(n_133),
	.A1(n_152),
	.B0(n_41),
	.B1(n_117),
	.C0(n_168));
   OAI31X1 g329464__5122 (.Y(n_184),
	.A0(n_25),
	.A1(n_58),
	.A2(n_133),
	.B0(n_165));
   INVX1 g329465 (.Y(n_179),
	.A(n_180));
   AOI21XL g329466__8246 (.Y(n_178),
	.A0(n_59),
	.A1(n_138),
	.B0(n_156));
   OAI21XL g329467__7098 (.Y(n_181),
	.A0(n_148),
	.A1(n_137),
	.B0(n_177));
   AOI221X1 g329468__6131 (.Y(n_180),
	.A0(n_131),
	.A1(n_148),
	.B0(n_111),
	.B1(n_113),
	.C0(n_174));
   INVXL g329469 (.Y(n_177),
	.A(n_156));
   INVXL g329470 (.Y(n_176),
	.A(n_161));
   OAI211X1 g329471__1881 (.Y(n_175),
	.A0(n_57),
	.A1(n_153),
	.B0(n_145),
	.C0(n_135));
   NOR2BX1 g329472__5115 (.Y(n_174),
	.AN(n_160),
	.B(n_124));
   NOR2BX1 g329473__7482 (.Y(n_173),
	.AN(n_163),
	.B(n_105));
   OAI2BB1X1 g329474__4733 (.Y(n_172),
	.A0N(n_105),
	.A1N(n_120),
	.B0(n_163));
   OAI211X1 g329475__6161 (.Y(n_171),
	.A0(n_132),
	.A1(n_113),
	.B0(n_126),
	.C0(n_158));
   INVXL g329476 (.Y(n_170),
	.A(n_166));
   INVXL g329477 (.Y(n_167),
	.A(n_168));
   AOI211XL g329478__9315 (.Y(n_166),
	.A0(n_24),
	.A1(n_148),
	.B0(n_134),
	.C0(n_142));
   AO22X1 g329479__9945 (.Y(n_165),
	.A0(n_1),
	.A1(n_154),
	.B0(n_122),
	.B1(n_157));
   XNOR2X1 g329481__2883 (.Y(n_164),
	.A(n_110),
	.B(n_157));
   XNOR2X1 g329482__2346 (.Y(n_169),
	.A(n_141),
	.B(n_157));
   XNOR2X1 g329483__1666 (.Y(n_168),
	.A(n_104),
	.B(n_157));
   OAI21XL g329484__7410 (.Y(n_162),
	.A0(n_57),
	.A1(n_116),
	.B0(n_157));
   NAND2XL g329485__6417 (.Y(n_163),
	.A(n_53),
	.B(n_158));
   XNOR2X1 g329486__5477 (.Y(n_159),
	.A(n_103),
	.B(n_148));
   OAI2BB1X1 g329487__2398 (.Y(n_161),
	.A0N(n_111),
	.A1N(n_148),
	.B0(n_155));
   XNOR2X1 g329488__5107 (.Y(n_160),
	.A(n_93),
	.B(n_147));
   NAND2XL g329490__6260 (.Y(n_158),
	.A(n_95),
	.B(n_147));
   NOR2XL g329491__4319 (.Y(n_157),
	.A(n_58),
	.B(n_153));
   OAI2BB1X1 g329492__8428 (.Y(n_154),
	.A0N(n_98),
	.A1N(n_140),
	.B0(n_86));
   NOR2XL g329493__5526 (.Y(n_156),
	.A(n_103),
	.B(n_147));
   OR2X1 g329494__6783 (.Y(n_155),
	.A(n_111),
	.B(n_148));
   AND2X1 g329495__3680 (.Y(n_151),
	.A(n_140),
	.B(n_106));
   NAND3XL g329496__1617 (.Y(n_153),
	.A(n_51),
	.B(n_44),
	.C(n_5));
   NAND2XL g329497__2802 (.Y(n_152),
	.A(n_104),
	.B(n_140));
   INVX1 g329498 (.Y(n_147),
	.A(n_148));
   AOI211XL g329499__1705 (.Y(n_146),
	.A0(n_101),
	.A1(n_118),
	.B0(n_71),
	.C0(n_112));
   OAI2BB1X1 g329500__5122 (.Y(n_150),
	.A0N(n_95),
	.A1N(n_121),
	.B0(n_55));
   NAND2XL g329501__8246 (.Y(n_149),
	.A(n_64),
	.B(n_143));
   NAND3XL g329502__7098 (.Y(n_148),
	.A(n_53),
	.B(n_79),
	.C(n_119));
   NAND2XL g329504__6131 (.Y(n_145),
	.A(n_109),
	.B(n_125));
   OAI2BB1X1 g329505__1881 (.Y(n_144),
	.A0N(n_44),
	.A1N(n_86),
	.B0(n_133));
   INVXL g329506 (.Y(n_139),
	.A(n_140));
   AOI21XL g329507__5115 (.Y(n_143),
	.A0(n_82),
	.A1(n_101),
	.B0(n_43));
   AOI21XL g329508__7482 (.Y(n_142),
	.A0(n_99),
	.A1(n_115),
	.B0(n_102));
   NOR3BXL g329509__4733 (.Y(n_141),
	.AN(n_104),
	.B(n_49),
	.C(n_84));
   NOR4BX1 g329510__6161 (.Y(n_140),
	.AN(n_97),
	.B(n_61),
	.C(n_57),
	.D(n_76));
   INVXL g329511 (.Y(n_138),
	.A(n_137));
   INVXL g329512 (.Y(n_136),
	.A(n_135));
   NOR2XL g329513__9315 (.Y(n_132),
	.A(n_71),
	.B(n_102));
   NAND2BXL g329514__9945 (.Y(n_131),
	.AN(n_112),
	.B(n_53));
   NOR2XL g329515__2883 (.Y(n_130),
	.A(n_69),
	.B(n_111));
   OR2X1 g329516__2346 (.Y(n_129),
	.A(n_58),
	.B(n_108));
   NAND2XL g329517__1666 (.Y(n_137),
	.A(n_45),
	.B(n_103));
   NOR2XL g329518__7410 (.Y(n_135),
	.A(n_52),
	.B(n_116));
   NOR2BX1 g329519__6417 (.Y(n_134),
	.AN(n_99),
	.B(n_111));
   NOR2XL g329520__5477 (.Y(n_133),
	.A(n_4),
	.B(n_107));
   INVXL g329521 (.Y(n_128),
	.A(n_127));
   INVXL g329523 (.Y(n_123),
	.A(n_122));
   INVX1 g329524 (.Y(n_120),
	.A(n_121));
   NOR4X1 g329525__2398 (.Y(n_119),
	.A(n_42),
	.B(n_43),
	.C(n_62),
	.D(n_74));
   NAND3BXL g329527__5107 (.Y(n_127),
	.AN(n_90),
	.B(n_53),
	.C(n_78));
   NAND3BXL g329528__6260 (.Y(n_126),
	.AN(n_77),
	.B(n_87),
	.C(n_95));
   NAND4XL g329529__4319 (.Y(n_125),
	.A(n_60),
	.B(n_70),
	.C(n_81),
	.D(n_72));
   OAI21XL g329530__8428 (.Y(n_124),
	.A0(n_89),
	.A1(n_94),
	.B0(n_78));
   AND3XL g329531__5526 (.Y(n_122),
	.A(n_51),
	.B(n_70),
	.C(n_86));
   NAND3BXL g329532__6783 (.Y(n_121),
	.AN(n_89),
	.B(n_0),
	.C(n_93));
   NAND2XL g329533__3680 (.Y(n_118),
	.A(n_87),
	.B(n_88));
   NOR2XL g329534__1617 (.Y(n_110),
	.A(n_63),
	.B(n_96));
   NAND2XL g329535__2802 (.Y(n_117),
	.A(n_85),
	.B(n_98));
   NAND2XL g329536__1705 (.Y(n_116),
	.A(n_81),
	.B(n_98));
   NOR2XL g329537__5122 (.Y(n_115),
	.A(n_66),
	.B(n_90));
   AND2X1 g329538__8246 (.Y(n_114),
	.A(n_88),
	.B(n_82));
   AND2X1 g329539__7098 (.Y(n_113),
	.A(n_95),
	.B(n_79));
   NAND2BXL g329540__6131 (.Y(n_112),
	.AN(n_89),
	.B(n_88));
   NAND2XL g329541__1881 (.Y(n_111),
	.A(n_64),
	.B(n_87));
   INVXL g329542 (.Y(n_101),
	.A(n_102));
   NAND2XL g329543__5115 (.Y(n_100),
	.A(n_24),
	.B(n_87));
   NOR2XL g329544__7482 (.Y(n_109),
	.A(n_47),
	.B(n_84));
   NOR3BXL g329545__4733 (.Y(n_108),
	.AN(n_72),
	.B(n_52),
	.C(n_4));
   OAI21XL g329546__6161 (.Y(n_107),
	.A0(lambda2[1]),
	.A1(n_16),
	.B0(n_85));
   NOR3BXL g329547__9315 (.Y(n_106),
	.AN(n_70),
	.B(n_80),
	.C(n_84));
   NAND4XL g329548__9945 (.Y(n_105),
	.A(n_2),
	.B(n_59),
	.C(n_3),
	.D(n_68));
   NOR2BX1 g329549__2883 (.Y(n_104),
	.AN(n_86),
	.B(n_80));
   AND2X1 g329550__2346 (.Y(n_103),
	.A(n_99),
	.B(n_24));
   NAND2XL g329551__1666 (.Y(n_102),
	.A(n_79),
	.B(n_92));
   INVXL g329552 (.Y(n_94),
	.A(n_93));
   NOR2XL g329553__7410 (.Y(n_92),
	.A(n_62),
	.B(n_77));
   NOR2BX1 g329554__6417 (.Y(n_99),
	.AN(n_78),
	.B(n_71));
   NOR2BX1 g329555__5477 (.Y(n_98),
	.AN(n_70),
	.B(n_63));
   NOR2BX1 g329556__2398 (.Y(n_97),
	.AN(n_73),
	.B(n_83));
   NAND2BXL g329557__5107 (.Y(n_96),
	.AN(n_4),
	.B(n_81));
   NOR2XL g329558__6260 (.Y(n_95),
	.A(n_65),
	.B(n_71));
   NOR2BX1 g329559__4319 (.Y(n_93),
	.AN(n_3),
	.B(n_77));
   INVX1 g329560 (.Y(n_84),
	.A(n_85));
   NOR4X1 g329561__8428 (.Y(error_vector[0]),
	.A(n_33),
	.B(n_34),
	.C(n_32),
	.D(n_37));
   NAND2BXL g329562__5526 (.Y(n_90),
	.AN(n_42),
	.B(n_82));
   OAI21XL g329563__6783 (.Y(n_89),
	.A0(n_24),
	.A1(n_19),
	.B0(n_78));
   NOR2XL g329564__3680 (.Y(n_88),
	.A(n_66),
	.B(n_69));
   AND3XL g329565__1617 (.Y(n_87),
	.A(n_0),
	.B(n_59),
	.C(n_2));
   AND2X1 g329566__2802 (.Y(n_86),
	.A(n_72),
	.B(n_46));
   NOR2XL g329567__1705 (.Y(n_85),
	.A(n_52),
	.B(n_76));
   NAND2XL g329568__5122 (.Y(n_83),
	.A(n_50),
	.B(n_1));
   NOR2BX1 g329569__8246 (.Y(n_82),
	.AN(n_3),
	.B(n_43));
   NOR2XL g329570__7098 (.Y(n_81),
	.A(n_41),
	.B(n_61));
   NAND2BXL g329571__6131 (.Y(n_80),
	.AN(n_47),
	.B(n_44));
   AND2X1 g329573__1881 (.Y(n_79),
	.A(n_59),
	.B(n_48));
   NOR2XL g329574__5115 (.Y(n_78),
	.A(n_65),
	.B(n_62));
   NAND2BXL g329575__7482 (.Y(n_77),
	.AN(n_42),
	.B(n_64));
   INVXL g329576 (.Y(n_75),
	.A(n_74));
   INVXL g329577 (.Y(n_68),
	.A(n_69));
   OAI221X1 g329578__4733 (.Y(n_67),
	.A0(lambda2[2]),
	.A1(lambda1[3]),
	.B0(n_12),
	.B1(n_9),
	.C0(n_36));
   OAI21XL g329579__6161 (.Y(n_76),
	.A0(n_20),
	.A1(n_17),
	.B0(n_60));
   OAI21XL g329580__9315 (.Y(n_74),
	.A0(n_24),
	.A1(n_23),
	.B0(n_0));
   OA21X1 g329581__9945 (.Y(n_73),
	.A0(n_31),
	.A1(n_16),
	.B0(n_46));
   OA21X1 g329582__2883 (.Y(n_72),
	.A0(n_16),
	.A1(n_25),
	.B0(n_1));
   NAND2XL g329583__2346 (.Y(n_71),
	.A(n_55),
	.B(n_53));
   NOR2BX1 g329584__1666 (.Y(n_70),
	.AN(n_50),
	.B(n_49));
   NAND2XL g329585__7410 (.Y(n_69),
	.A(n_45),
	.B(n_48));
   INVXL g329588 (.Y(n_56),
	.A(n_57));
   INVXL g329589 (.Y(n_54),
	.A(n_55));
   INVX1 g329590 (.Y(n_51),
	.A(n_52));
   NOR2XL g329591__6417 (.Y(n_66),
	.A(n_28),
	.B(n_22));
   NOR2XL g329592__5477 (.Y(n_65),
	.A(n_28),
	.B(n_18));
   NAND2BXL g329593__2398 (.Y(n_64),
	.AN(n_19),
	.B(n_30));
   NOR2XL g329594__5107 (.Y(n_63),
	.A(n_31),
	.B(n_17));
   NOR2XL g329595__6260 (.Y(n_62),
	.A(n_28),
	.B(n_24));
   NOR2XL g329596__4319 (.Y(n_61),
	.A(n_26),
	.B(n_20));
   NAND2BXL g329597__8428 (.Y(n_60),
	.AN(n_31),
	.B(n_27));
   NAND2BXL g329599__5526 (.Y(n_59),
	.AN(n_23),
	.B(n_30));
   NOR2BX1 g329603__6783 (.Y(n_58),
	.AN(n_27),
	.B(n_25));
   NOR2XL g329604__3680 (.Y(n_57),
	.A(n_26),
	.B(n_25));
   NAND2XL g329605__1617 (.Y(n_55),
	.A(n_30),
	.B(n_29));
   NAND2BXL g329606__2802 (.Y(n_53),
	.AN(n_28),
	.B(n_30));
   NOR2XL g329607__1705 (.Y(n_52),
	.A(n_26),
	.B(n_21));
   INVX1 g329608 (.Y(n_39),
	.A(n_40));
   OAI22XL g329609__5122 (.Y(n_38),
	.A0(lambda2[0]),
	.A1(n_9),
	.B0(lambda1[3]),
	.B1(n_14));
   AOI22XL g329610__8246 (.Y(n_37),
	.A0(n_10),
	.A1(n_8),
	.B0(lambda2[1]),
	.B1(lambda1[1]));
   AOI22XL g329611__7098 (.Y(n_36),
	.A0(lambda1[2]),
	.A1(n_8),
	.B0(lambda2[1]),
	.B1(n_15));
   OAI22XL g329612__6131 (.Y(n_35),
	.A0(lambda2[3]),
	.A1(n_15),
	.B0(lambda1[2]),
	.B1(n_11));
   OAI22XL g329613__1881 (.Y(n_34),
	.A0(lambda2[3]),
	.A1(n_9),
	.B0(lambda1[3]),
	.B1(n_11));
   AOI22XL g329614__5115 (.Y(n_33),
	.A0(lambda1[0]),
	.A1(n_14),
	.B0(lambda2[0]),
	.B1(n_13));
   OAI22XL g329615__7482 (.Y(n_32),
	.A0(lambda2[2]),
	.A1(n_15),
	.B0(lambda1[2]),
	.B1(n_12));
   OR2X1 g329616__4733 (.Y(n_50),
	.A(n_17),
	.B(n_21));
   NOR2XL g329617__6161 (.Y(n_49),
	.A(n_20),
	.B(n_16));
   OR2X1 g329618__9315 (.Y(n_48),
	.A(n_18),
	.B(n_23));
   NOR2XL g329619__9945 (.Y(n_47),
	.A(n_21),
	.B(n_16));
   NAND2BXL g329620__2883 (.Y(n_46),
	.AN(n_20),
	.B(n_27));
   OR2X1 g329621__2346 (.Y(n_45),
	.A(n_19),
	.B(n_22));
   OR2X1 g329622__1666 (.Y(n_44),
	.A(n_25),
	.B(n_17));
   NOR2XL g329623__7410 (.Y(n_43),
	.A(n_19),
	.B(n_18));
   NOR2XL g329624__6417 (.Y(n_42),
	.A(n_22),
	.B(n_23));
   NOR2XL g329625__5477 (.Y(n_41),
	.A(n_26),
	.B(n_31));
   AND2X1 g329626__2398 (.Y(n_40),
	.A(n_17),
	.B(n_16));
   NAND2XL g329628__5107 (.Y(n_31),
	.A(lambda2[1]),
	.B(lambda2[2]));
   NOR2XL g329629__6260 (.Y(n_30),
	.A(lambda1[1]),
	.B(lambda1[2]));
   NOR2XL g329630__4319 (.Y(n_29),
	.A(lambda1[0]),
	.B(lambda1[3]));
   NAND2XL g329631__8428 (.Y(n_28),
	.A(lambda1[0]),
	.B(lambda1[3]));
   NOR2XL g329632__5526 (.Y(n_27),
	.A(lambda2[0]),
	.B(lambda2[3]));
   NAND2XL g329633__6783 (.Y(n_26),
	.A(lambda2[0]),
	.B(lambda2[3]));
   NAND2XL g329634__3680 (.Y(n_25),
	.A(n_12),
	.B(n_8));
   NAND2XL g329635__1617 (.Y(n_24),
	.A(lambda1[1]),
	.B(lambda1[2]));
   NAND2XL g329639__2802 (.Y(n_23),
	.A(lambda1[0]),
	.B(n_9));
   NAND2XL g329640__1705 (.Y(n_22),
	.A(lambda1[1]),
	.B(n_15));
   NAND2XL g329641__5122 (.Y(n_21),
	.A(lambda2[1]),
	.B(n_12));
   NAND2XL g329642__8246 (.Y(n_20),
	.A(lambda2[2]),
	.B(n_8));
   NAND2XL g329643__7098 (.Y(n_19),
	.A(lambda1[3]),
	.B(n_13));
   NAND2XL g329644__6131 (.Y(n_18),
	.A(lambda1[2]),
	.B(n_10));
   NAND2XL g329645__1881 (.Y(n_17),
	.A(lambda2[3]),
	.B(n_14));
   NAND2XL g329646__5115 (.Y(n_16),
	.A(lambda2[0]),
	.B(n_11));
   INVX1 g329647 (.Y(n_15),
	.A(lambda1[2]));
   INVX1 g329648 (.Y(n_14),
	.A(lambda2[0]));
   INVX1 g329649 (.Y(n_13),
	.A(lambda1[0]));
   INVX1 g329650 (.Y(n_12),
	.A(lambda2[2]));
   INVX1 g329651 (.Y(n_11),
	.A(lambda2[3]));
   INVX1 g329652 (.Y(n_10),
	.A(lambda1[1]));
   INVX1 g329653 (.Y(n_9),
	.A(lambda1[3]));
   INVX1 g329654 (.Y(n_8),
	.A(lambda2[1]));
   XOR2XL g2__7482 (.Y(n_7),
	.A(n_96),
	.B(n_157));
   NAND2BX1 g329655__4733 (.Y(n_6),
	.AN(n_125),
	.B(n_108));
   NOR4BX1 g329656__6161 (.Y(n_5),
	.AN(n_60),
	.B(n_63),
	.C(n_61),
	.D(n_83));
   NAND2BX1 g329657__9315 (.Y(n_4),
	.AN(n_58),
	.B(n_56));
   NAND2BX1 g329658__9945 (.Y(n_3),
	.AN(n_24),
	.B(n_29));
   NAND2BX1 g329659__2883 (.Y(n_2),
	.AN(n_22),
	.B(n_29));
   NAND2BX1 g329660__2346 (.Y(n_1),
	.AN(n_21),
	.B(n_27));
   NAND2BX1 g329661__1666 (.Y(n_0),
	.AN(n_18),
	.B(n_29));
endmodule

module cb_stage_1 (
	clk, 
	rst, 
	lambda1, 
	lambda2, 
	error_vector, 
	error_found);
   input clk;
   input rst;
   input [3:0] lambda1;
   input [3:0] lambda2;
   output [14:0] error_vector;
   output error_found;

   // Internal wires
   wire [14:0] error_vector_r;
   wire error_found_r;

   bch_chien_block cb (.lambda1(lambda1),
	.lambda2(lambda2),
	.error_vector(error_vector_r),
	.error_found(error_found_r));
   DFFRHQX1 \error_vector_reg[11]  (.Q(error_vector[11]),
	.D(error_vector_r[11]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[8]  (.Q(error_vector[8]),
	.D(error_vector_r[8]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[13]  (.Q(error_vector[13]),
	.D(error_vector_r[13]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[12]  (.Q(error_vector[12]),
	.D(error_vector_r[12]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 error_found_reg (.Q(error_found),
	.D(error_found_r),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[10]  (.Q(error_vector[10]),
	.D(error_vector_r[10]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[9]  (.Q(error_vector[9]),
	.D(error_vector_r[9]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[14]  (.Q(error_vector[14]),
	.D(error_vector_r[14]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[7]  (.Q(error_vector[7]),
	.D(error_vector_r[7]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[6]  (.Q(error_vector[6]),
	.D(error_vector_r[6]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[5]  (.Q(error_vector[5]),
	.D(error_vector_r[5]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[4]  (.Q(error_vector[4]),
	.D(error_vector_r[4]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[3]  (.Q(error_vector[3]),
	.D(error_vector_r[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[2]  (.Q(error_vector[2]),
	.D(error_vector_r[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[1]  (.Q(error_vector[1]),
	.D(error_vector_r[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \error_vector_reg[0]  (.Q(error_vector[0]),
	.D(error_vector_r[0]),
	.RN(rst),
	.CK(clk));
endmodule

module bch_corrector (
	corruptedWord, 
	errorVector, 
	correctedWord);
   input [14:0] corruptedWord;
   input [14:0] errorVector;
   output [14:0] correctedWord;

   CLKXOR2X2 g136__7410 (.Y(correctedWord[10]),
	.A(corruptedWord[10]),
	.B(errorVector[10]));
   CLKXOR2X2 g137__6417 (.Y(correctedWord[12]),
	.A(corruptedWord[12]),
	.B(errorVector[12]));
   CLKXOR2X2 g138__5477 (.Y(correctedWord[11]),
	.A(corruptedWord[11]),
	.B(errorVector[11]));
   CLKXOR2X2 g139__2398 (.Y(correctedWord[1]),
	.A(corruptedWord[1]),
	.B(errorVector[1]));
   CLKXOR2X2 g140__5107 (.Y(correctedWord[0]),
	.A(corruptedWord[0]),
	.B(errorVector[0]));
   CLKXOR2X2 g141__6260 (.Y(correctedWord[7]),
	.A(corruptedWord[7]),
	.B(errorVector[7]));
   CLKXOR2X2 g142__4319 (.Y(correctedWord[14]),
	.A(corruptedWord[14]),
	.B(errorVector[14]));
   CLKXOR2X2 g143__8428 (.Y(correctedWord[4]),
	.A(corruptedWord[4]),
	.B(errorVector[4]));
   CLKXOR2X2 g144__5526 (.Y(correctedWord[5]),
	.A(corruptedWord[5]),
	.B(errorVector[5]));
   CLKXOR2X2 g145__6783 (.Y(correctedWord[13]),
	.A(corruptedWord[13]),
	.B(errorVector[13]));
   CLKXOR2X2 g146__3680 (.Y(correctedWord[9]),
	.A(corruptedWord[9]),
	.B(errorVector[9]));
   CLKXOR2X2 g147__1617 (.Y(correctedWord[6]),
	.A(corruptedWord[6]),
	.B(errorVector[6]));
   CLKXOR2X2 g148__2802 (.Y(correctedWord[8]),
	.A(corruptedWord[8]),
	.B(errorVector[8]));
   CLKXOR2X2 g149__1705 (.Y(correctedWord[3]),
	.A(corruptedWord[3]),
	.B(errorVector[3]));
   CLKXOR2X2 g150__5122 (.Y(correctedWord[2]),
	.A(corruptedWord[2]),
	.B(errorVector[2]));
endmodule

module fifo (
	clk, 
	rst, 
	d_in, 
	d_out);
   input clk;
   input rst;
   input [14:0] d_in;
   output [14:0] d_out;

   // Internal wires
   wire [14:0] \mem[3] ;
   wire [14:0] \mem[2] ;
   wire [14:0] \mem[1] ;
   wire [14:0] \mem[0] ;

   DFFRHQX1 \d_out_reg[5]  (.Q(d_out[5]),
	.D(\mem[3] [5]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[13]  (.Q(d_out[13]),
	.D(\mem[3] [13]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[11]  (.Q(d_out[11]),
	.D(\mem[3] [11]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[7]  (.Q(d_out[7]),
	.D(\mem[3] [7]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[6]  (.Q(d_out[6]),
	.D(\mem[3] [6]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[10]  (.Q(d_out[10]),
	.D(\mem[3] [10]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[14]  (.Q(d_out[14]),
	.D(\mem[3] [14]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[2]  (.Q(d_out[2]),
	.D(\mem[3] [2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[12]  (.Q(d_out[12]),
	.D(\mem[3] [12]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[9]  (.Q(d_out[9]),
	.D(\mem[3] [9]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[3]  (.Q(d_out[3]),
	.D(\mem[3] [3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[4]  (.Q(d_out[4]),
	.D(\mem[3] [4]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[8]  (.Q(d_out[8]),
	.D(\mem[3] [8]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[1]  (.Q(d_out[1]),
	.D(\mem[3] [1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \d_out_reg[0]  (.Q(d_out[0]),
	.D(\mem[3] [0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][6]  (.Q(\mem[3] [6]),
	.D(\mem[2] [6]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][1]  (.Q(\mem[3] [1]),
	.D(\mem[2] [1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][2]  (.Q(\mem[3] [2]),
	.D(\mem[2] [2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][3]  (.Q(\mem[3] [3]),
	.D(\mem[2] [3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][4]  (.Q(\mem[3] [4]),
	.D(\mem[2] [4]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][5]  (.Q(\mem[3] [5]),
	.D(\mem[2] [5]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][0]  (.Q(\mem[3] [0]),
	.D(\mem[2] [0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][11]  (.Q(\mem[3] [11]),
	.D(\mem[2] [11]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][8]  (.Q(\mem[3] [8]),
	.D(\mem[2] [8]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][9]  (.Q(\mem[3] [9]),
	.D(\mem[2] [9]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][10]  (.Q(\mem[3] [10]),
	.D(\mem[2] [10]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][7]  (.Q(\mem[3] [7]),
	.D(\mem[2] [7]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][12]  (.Q(\mem[3] [12]),
	.D(\mem[2] [12]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][13]  (.Q(\mem[3] [13]),
	.D(\mem[2] [13]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[3][14]  (.Q(\mem[3] [14]),
	.D(\mem[2] [14]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][11]  (.Q(\mem[2] [11]),
	.D(\mem[1] [11]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][14]  (.Q(\mem[2] [14]),
	.D(\mem[1] [14]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][12]  (.Q(\mem[2] [12]),
	.D(\mem[1] [12]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][0]  (.Q(\mem[2] [0]),
	.D(\mem[1] [0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][1]  (.Q(\mem[2] [1]),
	.D(\mem[1] [1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][2]  (.Q(\mem[2] [2]),
	.D(\mem[1] [2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][8]  (.Q(\mem[2] [8]),
	.D(\mem[1] [8]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][7]  (.Q(\mem[2] [7]),
	.D(\mem[1] [7]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][9]  (.Q(\mem[2] [9]),
	.D(\mem[1] [9]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][10]  (.Q(\mem[2] [10]),
	.D(\mem[1] [10]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][13]  (.Q(\mem[2] [13]),
	.D(\mem[1] [13]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][5]  (.Q(\mem[2] [5]),
	.D(\mem[1] [5]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][6]  (.Q(\mem[2] [6]),
	.D(\mem[1] [6]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][4]  (.Q(\mem[2] [4]),
	.D(\mem[1] [4]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[2][3]  (.Q(\mem[2] [3]),
	.D(\mem[1] [3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][9]  (.Q(\mem[1] [9]),
	.D(\mem[0] [9]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][0]  (.Q(\mem[1] [0]),
	.D(\mem[0] [0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][2]  (.Q(\mem[1] [2]),
	.D(\mem[0] [2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][4]  (.Q(\mem[1] [4]),
	.D(\mem[0] [4]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][6]  (.Q(\mem[1] [6]),
	.D(\mem[0] [6]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][8]  (.Q(\mem[1] [8]),
	.D(\mem[0] [8]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][11]  (.Q(\mem[1] [11]),
	.D(\mem[0] [11]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][3]  (.Q(\mem[1] [3]),
	.D(\mem[0] [3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][13]  (.Q(\mem[1] [13]),
	.D(\mem[0] [13]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][12]  (.Q(\mem[1] [12]),
	.D(\mem[0] [12]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][14]  (.Q(\mem[1] [14]),
	.D(\mem[0] [14]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][10]  (.Q(\mem[1] [10]),
	.D(\mem[0] [10]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][7]  (.Q(\mem[1] [7]),
	.D(\mem[0] [7]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][5]  (.Q(\mem[1] [5]),
	.D(\mem[0] [5]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[1][1]  (.Q(\mem[1] [1]),
	.D(\mem[0] [1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][8]  (.Q(\mem[0] [8]),
	.D(d_in[8]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][14]  (.Q(\mem[0] [14]),
	.D(d_in[14]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][6]  (.Q(\mem[0] [6]),
	.D(d_in[6]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][13]  (.Q(\mem[0] [13]),
	.D(d_in[13]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][10]  (.Q(\mem[0] [10]),
	.D(d_in[10]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][9]  (.Q(\mem[0] [9]),
	.D(d_in[9]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][12]  (.Q(\mem[0] [12]),
	.D(d_in[12]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][4]  (.Q(\mem[0] [4]),
	.D(d_in[4]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][3]  (.Q(\mem[0] [3]),
	.D(d_in[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][0]  (.Q(\mem[0] [0]),
	.D(d_in[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][1]  (.Q(\mem[0] [1]),
	.D(d_in[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][5]  (.Q(\mem[0] [5]),
	.D(d_in[5]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][2]  (.Q(\mem[0] [2]),
	.D(d_in[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][7]  (.Q(\mem[0] [7]),
	.D(d_in[7]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \mem_reg[0][11]  (.Q(\mem[0] [11]),
	.D(d_in[11]),
	.RN(rst),
	.CK(clk));
endmodule

module bch_syndrome_block (
	codeword, 
	S1, 
	S2, 
	S3);
   input [14:0] codeword;
   output [3:0] S1;
   output [3:0] S2;
   output [3:0] S3;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_35;
   wire n_36;
   wire n_37;

   XNOR2X1 g957__8246 (.Y(S3[3]),
	.A(n_30),
	.B(n_36));
   XNOR2X1 g958__7098 (.Y(S3[0]),
	.A(n_9),
	.B(n_35));
   XNOR2X1 g959__6131 (.Y(S1[2]),
	.A(n_17),
	.B(n_31));
   XNOR2X1 g960__1881 (.Y(S2[0]),
	.A(n_24),
	.B(n_37));
   XNOR2X1 g961__5115 (.Y(S3[1]),
	.A(n_26),
	.B(n_28));
   XNOR2X1 g962__7482 (.Y(S3[2]),
	.A(n_23),
	.B(n_28));
   XNOR2X1 g963__4733 (.Y(n_37),
	.A(n_4),
	.B(n_29));
   XNOR2X1 g964__6161 (.Y(n_36),
	.A(n_29),
	.B(n_28));
   XNOR2X1 g965__9315 (.Y(n_35),
	.A(codeword[0]),
	.B(n_28));
   XNOR2X1 g966__9945 (.Y(S1[1]),
	.A(n_21),
	.B(n_0));
   XNOR2X1 g967__2883 (.Y(S2[2]),
	.A(n_1),
	.B(n_20));
   XNOR2X1 g968__2346 (.Y(S1[0]),
	.A(n_19),
	.B(n_27));
   XNOR2X1 g970__1666 (.Y(n_31),
	.A(n_25),
	.B(n_29));
   XNOR2X1 g971__7410 (.Y(n_30),
	.A(n_13),
	.B(n_22));
   XNOR2X1 g972__6417 (.Y(n_27),
	.A(n_6),
	.B(n_7));
   XNOR2X1 g973__5477 (.Y(n_26),
	.A(codeword[8]),
	.B(n_10));
   MX2X1 g974__2398 (.Y(n_25),
	.A(n_9),
	.B(n_8),
	.S0(codeword[12]));
   XNOR2X1 g975__5107 (.Y(n_24),
	.A(codeword[0]),
	.B(n_7));
   XNOR2X1 g976__6260 (.Y(n_23),
	.A(codeword[2]),
	.B(n_6));
   XNOR2X1 g977__4319 (.Y(n_29),
	.A(codeword[2]),
	.B(n_11));
   XNOR2X1 g978__8428 (.Y(n_28),
	.A(codeword[9]),
	.B(n_7));
   XNOR2X1 g980__5526 (.Y(n_21),
	.A(n_5),
	.B(n_16));
   XNOR2X1 g983__6783 (.Y(n_20),
	.A(n_15),
	.B(n_8));
   XNOR2X1 g984__3680 (.Y(n_19),
	.A(n_14),
	.B(n_17));
   XNOR2X1 g985__1617 (.Y(n_18),
	.A(n_12),
	.B(n_11));
   XNOR2X1 g986__2802 (.Y(n_22),
	.A(n_10),
	.B(n_6));
   XNOR2X1 g987__1705 (.Y(n_16),
	.A(codeword[9]),
	.B(codeword[11]));
   XNOR2X1 g988__5122 (.Y(n_15),
	.A(codeword[1]),
	.B(codeword[6]));
   XNOR2X1 g989__8246 (.Y(n_14),
	.A(codeword[0]),
	.B(codeword[10]));
   XNOR2X1 g990__7098 (.Y(n_13),
	.A(codeword[1]),
	.B(codeword[8]));
   XNOR2X1 g991__6131 (.Y(n_12),
	.A(codeword[9]),
	.B(codeword[14]));
   XNOR2X1 g992__1881 (.Y(n_17),
	.A(codeword[8]),
	.B(codeword[13]));
   INVX1 g993 (.Y(n_8),
	.A(n_9));
   XNOR2X1 g996__5115 (.Y(n_5),
	.A(codeword[1]),
	.B(codeword[4]));
   XNOR2X1 g997__7482 (.Y(n_4),
	.A(codeword[5]),
	.B(codeword[7]));
   XNOR2X1 g998__4733 (.Y(n_11),
	.A(codeword[6]),
	.B(codeword[11]));
   XNOR2X1 g999__6161 (.Y(n_10),
	.A(codeword[3]),
	.B(codeword[13]));
   XNOR2X1 g1000__9315 (.Y(n_9),
	.A(codeword[5]),
	.B(codeword[10]));
   CLKXOR2X1 g1001__9945 (.Y(n_7),
	.A(codeword[4]),
	.B(codeword[14]));
   XNOR2X1 g1002__2883 (.Y(n_6),
	.A(codeword[7]),
	.B(codeword[12]));
   XOR2XL g2__2346 (.Y(S1[3]),
	.A(n_18),
	.B(n_22));
   XOR2XL g1003__1666 (.Y(n_1),
	.A(n_7),
	.B(n_10));
   MXI2XL g1004__7410 (.Y(n_0),
	.A(n_8),
	.B(n_9),
	.S0(n_6));
endmodule

module sy_stage_1 (
	clk, 
	rst, 
	codeword, 
	S1, 
	S2, 
	S3);
   input clk;
   input rst;
   input [14:0] codeword;
   output [3:0] S1;
   output [3:0] S2;
   output [3:0] S3;

   // Internal wires
   wire [3:0] oS1;
   wire [3:0] oS2;
   wire [3:0] oS3;
   wire UNCONNECTED;
   wire UNCONNECTED0;

   bch_syndrome_block sy (.codeword(codeword),
	.S1(oS1),
	.S2({ UNCONNECTED0,
		oS2[2],
		UNCONNECTED,
		oS2[0] }),
	.S3(oS3));
   DFFRHQX1 \S3_reg[3]  (.Q(S3[3]),
	.D(oS3[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_reg[1]  (.Q(S1[1]),
	.D(oS1[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_reg[3]  (.Q(S1[3]),
	.D(oS1[3]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_reg[0]  (.Q(S2[0]),
	.D(oS2[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_reg[0]  (.Q(S3[0]),
	.D(oS3[0]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S2_reg[2]  (.Q(S2[2]),
	.D(oS2[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_reg[1]  (.Q(S3[1]),
	.D(oS3[1]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S3_reg[2]  (.Q(S3[2]),
	.D(oS3[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_reg[2]  (.Q(S1[2]),
	.D(oS1[2]),
	.RN(rst),
	.CK(clk));
   DFFRHQX1 \S1_reg[0]  (.Q(S1[0]),
	.D(oS1[0]),
	.RN(rst),
	.CK(clk));
endmodule

module bch_pipelined (
	clk, 
	rst, 
	codeword, 
	corrected_codeword, 
	error_flag);
   input clk;
   input rst;
   input [14:0] codeword;
   output [14:0] corrected_codeword;
   output error_flag;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;
   wire [3:0] S3;
   wire [3:0] l1_1;
   wire [3:0] S1_o;
   wire [3:0] S2_o;
   wire [3:0] S3_o;
   wire [3:0] l1_2;
   wire [3:0] l2_2;
   wire [3:0] S1_o2;
   wire [3:0] lambda1;
   wire [3:0] lambda2;
   wire [14:0] error_vector;
   wire [14:0] corruptedWord;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED_HIER_Z1;
   wire UNCONNECTED_HIER_Z2;
   wire UNCONNECTED_HIER_Z3;
   wire UNCONNECTED_HIER_Z4;
   wire error_flag_reg_36;

   bm_stage_1 b1 (.clk(clk),
	.rst(rst),
	.S1({ UNCONNECTED_HIER_Z2,
		UNCONNECTED_HIER_Z1,
		S1[1],
		S1[0] }),
	.S2({ S1[3],
		S2[2],
		S1[2],
		S2[0] }),
	.S3(S3),
	.l1_1(l1_1),
	.S1_o(S1_o),
	.S2_o({ UNCONNECTED2,
		S2_o[2],
		UNCONNECTED1,
		S2_o[0] }),
	.S3_o(S3_o));
   bm_stage_2 b2 (.clk(clk),
	.rst(rst),
	.S1({ UNCONNECTED_HIER_Z4,
		UNCONNECTED_HIER_Z3,
		S1_o[1],
		S1_o[0] }),
	.S2({ S1_o[3],
		S2_o[2],
		S1_o[2],
		S2_o[0] }),
	.S3(S3_o),
	.l1_1(l1_1),
	.l1_2(l1_2),
	.l2_2(l2_2),
	.S1_o(S1_o2));
   bm_stage_3 b3 (.clk(clk),
	.rst(rst),
	.S1(S1_o2),
	.l1_2(l1_2),
	.l2_2(l2_2),
	.l1(lambda1),
	.l2(lambda2));
   cb_stage_1 cb (.clk(clk),
	.rst(rst),
	.lambda1(lambda1),
	.lambda2(lambda2),
	.error_vector(error_vector),
	.error_found(error_flag_reg_36));
   bch_corrector cr (.corruptedWord(corruptedWord),
	.errorVector(error_vector),
	.correctedWord(corrected_codeword));
   fifo fi (.clk(clk),
	.rst(rst),
	.d_in(codeword),
	.d_out(corruptedWord));
   sy_stage_1 sb (.clk(clk),
	.rst(rst),
	.codeword(codeword),
	.S1(S1),
	.S2({ UNCONNECTED4,
		S2[2],
		UNCONNECTED3,
		S2[0] }),
	.S3(S3));
   DFFRX2 error_flag_reg (.Q(error_flag),
	.QN(UNCONNECTED5),
	.D(error_flag_reg_36),
	.RN(rst),
	.CK(clk));
endmodule

