/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Sep  8 10:16:20 2025
#  Design:            h_decoder_11_7
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  8 2025 10:15:03 -03 (Sep  8 2025 13:15:03 UTC)
// Verification Directory fv/h_decoder_11_7 
module h_decoder_11_7 (
	i_CodeWord, 
	o_DecodWord, 
	o_Syndrome, 
	o_ErrorC, 
	o_ErrorD);
   input [11:0] i_CodeWord;
   output [6:0] o_DecodWord;
   output [4:0] o_Syndrome;
   output o_ErrorC;
   output o_ErrorD;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_16;
   wire n_17;
   wire n_20;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_34;
   wire n_36;

   XNOR2X2 g1242__2398 (.Y(o_DecodWord[0]),
	.A(n_36),
	.B(i_CodeWord[3]));
   XNOR2X2 g1245__5107 (.Y(o_DecodWord[6]),
	.A(n_27),
	.B(i_CodeWord[11]));
   CLKXOR2X2 g1247__6260 (.Y(o_DecodWord[5]),
	.A(n_29),
	.B(i_CodeWord[10]));
   XNOR2X2 g1246__4319 (.Y(o_DecodWord[3]),
	.A(n_34),
	.B(i_CodeWord[7]));
   CLKXOR2X2 g1248__8428 (.Y(o_DecodWord[2]),
	.A(n_31),
	.B(i_CodeWord[6]));
   XNOR2X2 g1244__5526 (.Y(o_DecodWord[4]),
	.A(n_26),
	.B(i_CodeWord[9]));
   XNOR2X2 g1243__6783 (.Y(o_DecodWord[1]),
	.A(n_24),
	.B(i_CodeWord[5]));
   NAND3BXL g1249__3680 (.Y(n_36),
	.AN(o_Syndrome[4]),
	.B(n_30),
	.C(n_32));
   NAND2XL g1253__1617 (.Y(n_34),
	.A(o_Syndrome[3]),
	.B(n_32));
   NOR2XL g1251__2802 (.Y(n_31),
	.A(n_30),
	.B(n_28));
   NOR2XL g1250__1705 (.Y(n_29),
	.A(n_16),
	.B(n_28));
   NAND2XL g1252__5122 (.Y(n_27),
	.A(o_Syndrome[4]),
	.B(n_32));
   NAND2XL g1254__8246 (.Y(n_26),
	.A(o_Syndrome[4]),
	.B(n_23));
   AND2X1 g1258__7098 (.Y(n_32),
	.A(n_22),
	.B(o_Syndrome[1]));
   NAND2XL g1255__6131 (.Y(n_24),
	.A(o_Syndrome[3]),
	.B(n_23));
   NAND2XL g1256__1881 (.Y(n_28),
	.A(n_20),
	.B(n_22));
   NOR3BXL g1257__5115 (.Y(n_23),
	.AN(o_ErrorC),
	.B(n_20),
	.C(o_Syndrome[2]));
   AND2X2 g1259__7482 (.Y(o_ErrorD),
	.A(n_14),
	.B(n_17));
   NOR2XL g1260__4733 (.Y(n_22),
	.A(n_13),
	.B(n_17));
   INVXL g1261 (.Y(n_17),
	.A(o_ErrorC));
   OA21X2 g1262__6161 (.Y(o_ErrorC),
	.A0(n_30),
	.A1(n_16),
	.B0(o_Syndrome[0]));
   XNOR2X2 g1263__9315 (.Y(o_Syndrome[0]),
	.A(n_10),
	.B(n_12));
   NAND4XL g1264__9945 (.Y(n_14),
	.A(n_30),
	.B(n_16),
	.C(n_20),
	.D(n_13));
   XNOR2X1 g1265__2883 (.Y(n_12),
	.A(o_Syndrome[2]),
	.B(i_CodeWord[0]));
   INVXL g1266 (.Y(n_13),
	.A(o_Syndrome[2]));
   CLKXOR2X2 g1267__2346 (.Y(o_Syndrome[2]),
	.A(i_CodeWord[2]),
	.B(n_11));
   XNOR2X1 g1268__1666 (.Y(n_11),
	.A(i_CodeWord[10]),
	.B(n_9));
   XNOR2X1 g1269__7410 (.Y(n_10),
	.A(i_CodeWord[8]),
	.B(n_8));
   INVXL g1270 (.Y(n_16),
	.A(o_Syndrome[4]));
   INVXL g1273 (.Y(n_20),
	.A(o_Syndrome[1]));
   XNOR2X1 g1271__6417 (.Y(n_9),
	.A(i_CodeWord[6]),
	.B(n_7));
   CLKXOR2X2 g1272__5477 (.Y(o_Syndrome[4]),
	.A(i_CodeWord[10]),
	.B(n_5));
   XNOR2X1 g1274__2398 (.Y(n_8),
	.A(i_CodeWord[4]),
	.B(n_6));
   CLKXOR2X2 g1275__5107 (.Y(o_Syndrome[1]),
	.A(n_7),
	.B(n_6));
   INVXL g1278 (.Y(n_30),
	.A(o_Syndrome[3]));
   XNOR2X1 g1276__6260 (.Y(n_5),
	.A(i_CodeWord[8]),
	.B(n_1));
   XNOR2X1 g1279__4319 (.Y(n_7),
	.A(i_CodeWord[11]),
	.B(n_0));
   XNOR2X1 g1277__8428 (.Y(n_6),
	.A(i_CodeWord[9]),
	.B(n_3));
   CLKXOR2X2 g1280__5526 (.Y(o_Syndrome[3]),
	.A(n_2),
	.B(n_4));
   XNOR2X1 g1282__6783 (.Y(n_4),
	.A(i_CodeWord[4]),
	.B(i_CodeWord[7]));
   XNOR2X1 g1283__3680 (.Y(n_3),
	.A(i_CodeWord[1]),
	.B(i_CodeWord[5]));
   XNOR2X1 g1281__1617 (.Y(n_2),
	.A(i_CodeWord[5]),
	.B(i_CodeWord[6]));
   XNOR2X1 g1284__2802 (.Y(n_1),
	.A(i_CodeWord[9]),
	.B(i_CodeWord[11]));
   XNOR2X1 g1285__1705 (.Y(n_0),
	.A(i_CodeWord[3]),
	.B(i_CodeWord[7]));
endmodule

