/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Oct  6 16:22:18 2025
#  Design:            bch_comb_top
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct  6 2025 14:44:15 -03 (Oct  6 2025 17:44:15 UTC)
// Verification Directory fv/bch_comb_top 
module gf_divider (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_68;
   wire n_70;

   OAI221X1 g1908__2398 (.Y(q[2]),
	.A0(n_22),
	.A1(n_53),
	.B0(b[0]),
	.B1(n_30),
	.C0(n_70));
   OR4X1 g1909__5107 (.Y(q[0]),
	.A(n_32),
	.B(n_56),
	.C(n_48),
	.D(n_65));
   AOI31X1 g1910__6260 (.Y(n_70),
	.A0(n_11),
	.A1(n_24),
	.A2(n_23),
	.B0(n_68));
   NAND4XL g1911__4319 (.Y(q[3]),
	.A(n_58),
	.B(n_50),
	.C(n_57),
	.D(n_64));
   OAI2BB1X1 g1912__8428 (.Y(n_68),
	.A0N(b[2]),
	.A1N(n_43),
	.B0(n_66));
   NAND4XL g1913__5526 (.Y(q[1]),
	.A(n_61),
	.B(n_49),
	.C(n_59),
	.D(n_55));
   AOI221X1 g1914__6783 (.Y(n_66),
	.A0(b[1]),
	.A1(n_28),
	.B0(n_17),
	.B1(n_33),
	.C0(n_62));
   OAI31X1 g1915__3680 (.Y(n_65),
	.A0(n_8),
	.A1(b[2]),
	.A2(n_0),
	.B0(n_63));
   AOI221X1 g1916__1617 (.Y(n_64),
	.A0(n_29),
	.A1(n_18),
	.B0(n_8),
	.B1(n_28),
	.C0(n_60));
   AOI32X1 g1917__2802 (.Y(n_63),
	.A0(b[1]),
	.A1(n_18),
	.A2(n_6),
	.B0(n_7),
	.B1(n_52));
   OAI32X1 g1918__1705 (.Y(n_62),
	.A0(n_22),
	.A1(n_16),
	.A2(n_35),
	.B0(b[3]),
	.B1(n_54));
   AOI32X1 g1919__5122 (.Y(n_61),
	.A0(b[3]),
	.A1(n_1),
	.A2(n_12),
	.B0(n_24),
	.B1(n_51));
   OAI31X1 g1920__8246 (.Y(n_60),
	.A0(n_3),
	.A1(a[0]),
	.A2(n_16),
	.B0(n_47));
   OA22X1 g1921__7098 (.Y(n_59),
	.A0(b[0]),
	.A1(n_45),
	.B0(n_6),
	.B1(n_39));
   AOI32X1 g1922__6131 (.Y(n_58),
	.A0(b[2]),
	.A1(n_20),
	.A2(n_26),
	.B0(n_9),
	.B1(n_37));
   AOI22XL g1923__1881 (.Y(n_57),
	.A0(n_11),
	.A1(n_42),
	.B0(n_21),
	.B1(n_46));
   OAI22XL g1924__5115 (.Y(n_56),
	.A0(n_22),
	.A1(n_38),
	.B0(n_1),
	.B1(n_40));
   AOI33XL g1925__7482 (.Y(n_55),
	.A0(n_2),
	.A1(n_11),
	.A2(n_28),
	.B0(n_4),
	.B1(b[3]),
	.B2(n_29));
   AOI22XL g1926__4733 (.Y(n_54),
	.A0(a[2]),
	.A1(n_27),
	.B0(n_18),
	.B1(n_7));
   AOI21XL g1927__6161 (.Y(n_53),
	.A0(n_1),
	.A1(n_35),
	.B0(n_14));
   OAI2BB1X1 g1928__9315 (.Y(n_52),
	.A0N(n_1),
	.A1N(n_11),
	.B0(n_41));
   OAI221X1 g1929__9945 (.Y(n_51),
	.A0(n_10),
	.A1(b[2]),
	.B0(a[2]),
	.B1(n_5),
	.C0(n_15));
   OA22X1 g1930__2883 (.Y(n_50),
	.A0(n_6),
	.A1(n_34),
	.B0(n_0),
	.B1(n_30));
   AOI22XL g1931__2346 (.Y(n_49),
	.A0(n_26),
	.A1(n_31),
	.B0(n_3),
	.B1(n_32));
   OAI21XL g1932__1666 (.Y(n_48),
	.A0(a[0]),
	.A1(n_34),
	.B0(n_44));
   AOI32X1 g1933__7410 (.Y(n_47),
	.A0(b[1]),
	.A1(n_2),
	.A2(n_14),
	.B0(n_12),
	.B1(n_36));
   OAI21XL g1934__6417 (.Y(n_46),
	.A0(b[2]),
	.A1(n_7),
	.B0(n_13));
   AOI21XL g1935__5477 (.Y(n_45),
	.A0(n_21),
	.A1(n_4),
	.B0(n_36));
   NAND2XL g1936__2398 (.Y(n_44),
	.A(n_20),
	.B(n_28));
   AO21X1 g1937__5107 (.Y(n_43),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_29));
   OAI22XL g1938__6260 (.Y(n_42),
	.A0(b[2]),
	.A1(n_6),
	.B0(a[2]),
	.B1(n_0));
   MX2X1 g1939__4319 (.Y(n_41),
	.A(n_16),
	.B(n_19),
	.S0(n_20));
   AOI22XL g1940__8428 (.Y(n_40),
	.A0(b[3]),
	.A1(n_9),
	.B0(b[0]),
	.B1(n_11));
   AOI22XL g1941__5526 (.Y(n_39),
	.A0(b[3]),
	.A1(n_19),
	.B0(b[1]),
	.B1(a[2]));
   OA22X1 g1942__6783 (.Y(n_38),
	.A0(a[0]),
	.A1(n_23),
	.B0(a[2]),
	.B1(n_25));
   OAI22XL g1943__3680 (.Y(n_37),
	.A0(n_3),
	.A1(n_23),
	.B0(n_0),
	.B1(n_15));
   NOR2XL g1944__1617 (.Y(n_36),
	.A(n_5),
	.B(n_16));
   NOR2XL g1945__2802 (.Y(n_35),
	.A(n_26),
	.B(n_24));
   NAND2XL g1946__1705 (.Y(n_34),
	.A(n_17),
	.B(n_23));
   NOR2XL g1947__5122 (.Y(n_33),
	.A(b[2]),
	.B(n_6));
   INVXL g1948 (.Y(n_31),
	.A(n_30));
   NAND2XL g1949__8246 (.Y(n_27),
	.A(n_8),
	.B(n_13));
   NOR2XL g1950__7098 (.Y(n_32),
	.A(n_13),
	.B(n_19));
   NAND2XL g1951__6131 (.Y(n_30),
	.A(n_17),
	.B(n_18));
   NOR2XL g1952__1881 (.Y(n_29),
	.A(n_8),
	.B(a[0]));
   NOR2XL g1953__5115 (.Y(n_28),
	.A(a[0]),
	.B(n_15));
   INVXL g1954 (.Y(n_25),
	.A(n_24));
   INVXL g1955 (.Y(n_21),
	.A(n_22));
   INVX1 g1956 (.Y(n_18),
	.A(n_19));
   NOR2XL g1957__7482 (.Y(n_26),
	.A(b[0]),
	.B(a[0]));
   NOR2XL g1958__4733 (.Y(n_24),
	.A(n_2),
	.B(n_0));
   NOR2XL g1959__6161 (.Y(n_23),
	.A(a[2]),
	.B(b[2]));
   NAND2XL g1960__9315 (.Y(n_22),
	.A(b[1]),
	.B(b[3]));
   NOR2XL g1961__9945 (.Y(n_20),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g1962__2883 (.Y(n_19),
	.A(a[2]),
	.B(b[2]));
   INVXL g1963 (.Y(n_14),
	.A(n_15));
   INVX1 g1964 (.Y(n_12),
	.A(n_13));
   INVXL g1965 (.Y(n_10),
	.A(n_11));
   INVX1 g1966 (.Y(n_8),
	.A(n_9));
   INVX1 g1967 (.Y(n_6),
	.A(n_7));
   NOR2XL g1968__2346 (.Y(n_17),
	.A(b[1]),
	.B(n_3));
   NAND2XL g1969__1666 (.Y(n_16),
	.A(a[2]),
	.B(n_4));
   NAND2XL g1970__7410 (.Y(n_15),
	.A(n_1),
	.B(b[2]));
   NAND2XL g1971__6417 (.Y(n_13),
	.A(b[0]),
	.B(n_0));
   NOR2XL g1972__5477 (.Y(n_11),
	.A(b[3]),
	.B(n_5));
   NOR2XL g1973__2398 (.Y(n_9),
	.A(b[1]),
	.B(n_2));
   NOR2XL g1974__5107 (.Y(n_7),
	.A(b[0]),
	.B(n_0));
   INVX1 g1975 (.Y(n_5),
	.A(b[1]));
   INVX1 g1976 (.Y(n_4),
	.A(b[2]));
   INVX1 g1977 (.Y(n_3),
	.A(b[3]));
   INVX1 g1978 (.Y(n_2),
	.A(b[0]));
   INVX1 g1979 (.Y(n_1),
	.A(a[2]));
   INVX1 g1980 (.Y(n_0),
	.A(a[0]));
endmodule

module gf_divider_482 (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;

   NAND3BXL g2032__6260 (.Y(q[2]),
	.AN(n_77),
	.B(n_76),
	.C(n_67));
   OAI211X1 g2033__4319 (.Y(q[0]),
	.A0(n_66),
	.A1(n_68),
	.B0(n_73),
	.C0(n_67));
   OAI211X1 g2034__8428 (.Y(q[1]),
	.A0(n_65),
	.A1(n_68),
	.B0(n_76),
	.C0(n_72));
   OAI211X1 g2035__5526 (.Y(q[3]),
	.A0(n_28),
	.A1(n_70),
	.B0(n_74),
	.C0(n_67));
   OAI22XL g2036__6783 (.Y(n_77),
	.A0(n_53),
	.A1(n_75),
	.B0(n_61),
	.B1(n_68));
   NOR2XL g2037__3680 (.Y(n_75),
	.A(n_69),
	.B(n_71));
   NAND2XL g2038__1617 (.Y(n_76),
	.A(n_61),
	.B(n_69));
   OAI21XL g2039__2802 (.Y(n_74),
	.A0(n_53),
	.A1(n_63),
	.B0(n_71));
   NAND3BXL g2040__1705 (.Y(n_73),
	.AN(n_53),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2041__5122 (.Y(n_72),
	.AN(n_61),
	.B(n_29),
	.C(n_64));
   NAND2XL g2042__8246 (.Y(n_70),
	.A(n_65),
	.B(n_64));
   NOR2XL g2043__7098 (.Y(n_71),
	.A(n_28),
	.B(n_66));
   NOR3BXL g2044__6131 (.Y(n_69),
	.AN(n_65),
	.B(n_28),
	.C(n_63));
   NAND3BXL g2045__1881 (.Y(n_68),
	.AN(n_28),
	.B(n_53),
	.C(n_63));
   NAND4XL g2046__5115 (.Y(n_67),
	.A(n_29),
	.B(n_60),
	.C(n_65),
	.D(n_63));
   OR2X1 g2047__7482 (.Y(n_66),
	.A(n_60),
	.B(n_65));
   XNOR2X1 g2048__4733 (.Y(n_65),
	.A(n_58),
	.B(n_62));
   CLKXOR2X1 g2049__6161 (.Y(n_64),
	.A(n_53),
	.B(n_63));
   ADDFX1 g2050__9315 (.CO(n_62),
	.S(n_63),
	.A(n_55),
	.B(n_54),
	.CI(n_59));
   INVXL g2051 (.Y(n_60),
	.A(n_61));
   ADDFX1 g2052__9945 (.CO(n_59),
	.S(n_61),
	.A(n_35),
	.B(n_50),
	.CI(n_52));
   XNOR2X1 g2053__2883 (.Y(n_58),
	.A(n_56),
	.B(n_57));
   XNOR2X1 g2054__2346 (.Y(n_57),
	.A(n_27),
	.B(n_51));
   OAI21XL g2055__1666 (.Y(n_56),
	.A0(n_42),
	.A1(n_49),
	.B0(n_43));
   OAI21XL g2056__7410 (.Y(n_55),
	.A0(n_40),
	.A1(n_49),
	.B0(n_38));
   XNOR2X1 g2057__6417 (.Y(n_54),
	.A(n_44),
	.B(n_49));
   XNOR2X1 g2058__5477 (.Y(n_52),
	.A(n_41),
	.B(n_49));
   XNOR2X1 g2059__2398 (.Y(n_51),
	.A(n_26),
	.B(n_49));
   XNOR2X1 g2060__5107 (.Y(n_53),
	.A(n_37),
	.B(n_49));
   NOR2BX1 g2061__6260 (.Y(n_50),
	.AN(n_37),
	.B(n_49));
   OAI21XL g2062__4319 (.Y(n_49),
	.A0(n_26),
	.A1(n_47),
	.B0(n_48));
   OAI2BB1X1 g2063__8428 (.Y(n_48),
	.A0N(n_26),
	.A1N(n_47),
	.B0(n_27));
   OA21X1 g2064__5526 (.Y(n_47),
	.A0(n_42),
	.A1(n_46),
	.B0(n_43));
   AND2X1 g2065__6783 (.Y(n_46),
	.A(n_45),
	.B(n_38));
   NAND2BXL g2066__3680 (.Y(n_45),
	.AN(n_40),
	.B(n_35));
   XNOR2X1 g2067__1617 (.Y(n_44),
	.A(n_39),
	.B(n_36));
   NAND2BXL g2068__2802 (.Y(n_43),
	.AN(n_39),
	.B(n_36));
   NOR2BX1 g2069__1705 (.Y(n_42),
	.AN(n_39),
	.B(n_36));
   XNOR2X1 g2070__5122 (.Y(n_41),
	.A(n_33),
	.B(n_32));
   NOR2BX1 g2071__8246 (.Y(n_40),
	.AN(n_33),
	.B(n_32));
   OAI211X1 g2072__7098 (.Y(n_39),
	.A0(n_7),
	.A1(b[2]),
	.B0(n_12),
	.C0(n_25));
   NAND2BXL g2073__6131 (.Y(n_38),
	.AN(n_33),
	.B(n_32));
   OAI21XL g2074__1881 (.Y(n_37),
	.A0(n_31),
	.A1(n_30),
	.B0(n_35));
   NAND2XL g2075__5115 (.Y(n_36),
	.A(n_13),
	.B(n_34));
   AOI31X1 g2076__7482 (.Y(n_34),
	.A0(a[1]),
	.A1(n_1),
	.A2(a[0]),
	.B0(n_24));
   NAND2XL g2077__4733 (.Y(n_35),
	.A(n_31),
	.B(n_30));
   OAI222XL g2078__6161 (.Y(n_33),
	.A0(b[0]),
	.A1(n_18),
	.B0(n_5),
	.B1(n_17),
	.C0(n_12),
	.C1(b[2]));
   OAI222XL g2079__9315 (.Y(n_32),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_4),
	.B1(n_19),
	.C0(a[2]),
	.C1(n_13));
   INVX1 g2080 (.Y(n_28),
	.A(n_29));
   OAI222XL g2081__9945 (.Y(n_31),
	.A0(b[0]),
	.A1(n_8),
	.B0(n_12),
	.B1(n_9),
	.C0(n_16),
	.C1(b[2]));
   AOI221X1 g2082__2883 (.Y(n_30),
	.A0(n_10),
	.A1(n_4),
	.B0(n_1),
	.B1(n_15),
	.C0(n_21));
   NOR2XL g2083__2346 (.Y(n_29),
	.A(n_22),
	.B(n_23));
   AOI32X1 g2084__1666 (.Y(n_25),
	.A0(n_5),
	.A1(n_11),
	.A2(b[2]),
	.B0(b[3]),
	.B1(n_8));
   OAI22XL g2085__7410 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_10),
	.B1(n_6));
   OAI222XL g2086__6417 (.Y(n_27),
	.A0(n_1),
	.A1(n_4),
	.B0(a[1]),
	.B1(n_13),
	.C0(a[0]),
	.C1(n_14));
   OAI222XL g2087__5477 (.Y(n_26),
	.A0(n_5),
	.A1(n_0),
	.B0(b[1]),
	.B1(n_12),
	.C0(b[0]),
	.C1(n_16));
   NOR4X1 g2088__2398 (.Y(n_23),
	.A(a[1]),
	.B(a[2]),
	.C(a[3]),
	.D(a[0]));
   NOR4X1 g2089__5107 (.Y(n_22),
	.A(b[1]),
	.B(b[0]),
	.C(b[3]),
	.D(b[2]));
   NOR2XL g2090__6260 (.Y(n_21),
	.A(n_10),
	.B(n_13));
   AOI21XL g2091__4319 (.Y(n_20),
	.A0(a[2]),
	.A1(a[3]),
	.B0(n_3));
   AOI21XL g2092__8428 (.Y(n_18),
	.A0(b[3]),
	.A1(b[2]),
	.B0(n_2));
   NAND2XL g2093__5526 (.Y(n_17),
	.A(n_11),
	.B(b[2]));
   NAND3XL g2094__6783 (.Y(n_19),
	.A(a[2]),
	.B(a[1]),
	.C(n_6));
   INVXL g2095 (.Y(n_15),
	.A(n_14));
   NAND2XL g2096__3680 (.Y(n_16),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g2097__1617 (.Y(n_14),
	.A(a[1]),
	.B(a[3]));
   NAND2XL g2098__2802 (.Y(n_13),
	.A(a[3]),
	.B(a[0]));
   NAND2XL g2099__1705 (.Y(n_12),
	.A(b[0]),
	.B(b[3]));
   INVXL g2100 (.Y(n_9),
	.A(n_8));
   NOR2XL g2101__5122 (.Y(n_11),
	.A(b[3]),
	.B(n_2));
   NAND2XL g2102__8246 (.Y(n_7),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2103__7098 (.Y(n_10),
	.A(a[2]),
	.B(n_3));
   NOR2XL g2104__6131 (.Y(n_8),
	.A(b[1]),
	.B(n_0));
   INVXL g2105 (.Y(n_6),
	.A(a[3]));
   INVX1 g2106 (.Y(n_5),
	.A(b[0]));
   INVX1 g2107 (.Y(n_4),
	.A(a[0]));
   INVXL g2108 (.Y(n_3),
	.A(a[1]));
   INVXL g2109 (.Y(n_2),
	.A(b[1]));
   INVX1 g2110 (.Y(n_1),
	.A(a[2]));
   INVXL g2111 (.Y(n_0),
	.A(b[2]));
endmodule

module gf_multiplier (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   CLKXOR2X1 g874__1881 (.Y(p[2]),
	.A(b[1]),
	.B(b[3]));
   CLKXOR2X1 g875__5115 (.Y(p[0]),
	.A(b[2]),
	.B(b[0]));
endmodule

module xor_4 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__7482 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__4733 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__6161 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__9315 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module bch_pipe2 (
	S1, 
	S2, 
	S3, 
	l1, 
	l2);
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   output [3:0] l1;
   output [3:0] l2;

   // Internal wires
   wire [3:0] D2;
   wire [3:0] X1;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;
   wire UNCONNECTED_HIER_Z1;
   wire UNCONNECTED_HIER_Z2;
   wire UNCONNECTED_HIER_Z3;
   wire UNCONNECTED_HIER_Z4;

   gf_divider u_div1 (.a({ UNCONNECTED_HIER_Z0,
		S2[2],
		UNCONNECTED_HIER_Z,
		S2[0] }),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.q(l1));
   gf_divider_482 u_div2 (.a(S3),
	.b({ S2[3],
		S2[1],
		S1[1],
		S1[0] }),
	.q(D2));
   gf_multiplier u_mult1 (.a({ UNCONNECTED_HIER_Z4,
		UNCONNECTED_HIER_Z3,
		UNCONNECTED_HIER_Z2,
		UNCONNECTED_HIER_Z1 }),
	.b(l1),
	.p({ UNCONNECTED0,
		X1[2],
		UNCONNECTED,
		X1[0] }));
   xor_4 u_xor1 (.a({ l1[3],
		X1[2],
		l1[2],
		X1[0] }),
	.b(D2),
	.y(l2));
endmodule

module bch_chien_block (
	lambda1, 
	lambda2, 
	error_vector, 
	error_found);
   input [3:0] lambda1;
   input [3:0] lambda2;
   output [14:0] error_vector;
   output error_found;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_281;
   wire n_283;
   wire n_284;
   wire n_287;
   wire n_296;
   wire n_297;
   wire n_298;
   wire n_299;
   wire n_300;

   OR2X2 g329347__9945 (.Y(error_found),
	.A(error_vector[11]),
	.B(n_300));
   OR4X1 g329348__2883 (.Y(n_300),
	.A(error_vector[6]),
	.B(error_vector[10]),
	.C(error_vector[2]),
	.D(n_299));
   OR4X1 g329349__2346 (.Y(n_299),
	.A(error_vector[7]),
	.B(error_vector[8]),
	.C(error_vector[9]),
	.D(n_298));
   NAND2BXL g329350__1666 (.Y(n_298),
	.AN(error_vector[3]),
	.B(n_297));
   NOR4X1 g329351__7410 (.Y(n_297),
	.A(error_vector[0]),
	.B(error_vector[14]),
	.C(error_vector[1]),
	.D(n_296));
   OR4X1 g329352__6417 (.Y(n_296),
	.A(error_vector[13]),
	.B(error_vector[12]),
	.C(error_vector[4]),
	.D(error_vector[5]));
   AOI221X1 g329353__5477 (.Y(error_vector[6]),
	.A0(n_181),
	.A1(n_196),
	.B0(n_180),
	.B1(n_195),
	.C0(n_283));
   AOI221X1 g329354__2398 (.Y(error_vector[4]),
	.A0(n_225),
	.A1(n_210),
	.B0(n_226),
	.B1(n_211),
	.C0(n_287));
   NOR4X1 g329355__5107 (.Y(error_vector[9]),
	.A(n_262),
	.B(n_253),
	.C(n_237),
	.D(n_239));
   NOR4X1 g329356__6260 (.Y(error_vector[7]),
	.A(n_247),
	.B(n_271),
	.C(n_260),
	.D(n_202));
   AOI221X1 g329357__4319 (.Y(error_vector[5]),
	.A0(n_181),
	.A1(n_207),
	.B0(n_180),
	.B1(n_206),
	.C0(n_284));
   NOR4X1 g329358__8428 (.Y(error_vector[8]),
	.A(n_261),
	.B(n_249),
	.C(n_272),
	.D(n_221));
   OAI211X1 g329359__5526 (.Y(n_287),
	.A0(n_204),
	.A1(n_192),
	.B0(n_227),
	.C0(n_280));
   AOI221X1 g329360__6783 (.Y(error_vector[10]),
	.A0(n_198),
	.A1(n_214),
	.B0(n_197),
	.B1(n_215),
	.C0(n_279));
   AOI221X1 g329361__3680 (.Y(error_vector[11]),
	.A0(n_199),
	.A1(n_210),
	.B0(n_200),
	.B1(n_211),
	.C0(n_273));
   OAI221X1 g329362__1617 (.Y(n_284),
	.A0(n_259),
	.A1(n_196),
	.B0(n_258),
	.B1(n_195),
	.C0(n_277));
   OAI211X1 g329363__2802 (.Y(n_283),
	.A0(n_259),
	.A1(n_38),
	.B0(n_267),
	.C0(n_278));
   AOI221X1 g329364__1705 (.Y(error_vector[3]),
	.A0(lambda1[0]),
	.A1(n_214),
	.B0(n_12),
	.B1(n_215),
	.C0(n_274));
   AOI221X1 g329365__5122 (.Y(error_vector[12]),
	.A0(n_200),
	.A1(n_192),
	.B0(n_199),
	.B1(n_191),
	.C0(n_281));
   OAI211X1 g329366__8246 (.Y(n_281),
	.A0(n_229),
	.A1(n_230),
	.B0(n_233),
	.C0(n_263));
   AOI221X1 g329367__7098 (.Y(n_280),
	.A0(n_181),
	.A1(n_219),
	.B0(n_180),
	.B1(n_218),
	.C0(n_265));
   OAI221X1 g329368__6131 (.Y(n_279),
	.A0(n_213),
	.A1(n_210),
	.B0(n_212),
	.B1(n_211),
	.C0(n_269));
   AOI221X1 g329369__1881 (.Y(n_278),
	.A0(n_244),
	.A1(n_7),
	.B0(n_243),
	.B1(lambda2[1]),
	.C0(n_248));
   AOI221X1 g329370__5115 (.Y(n_277),
	.A0(n_231),
	.A1(n_218),
	.B0(n_232),
	.B1(n_219),
	.C0(n_264));
   NOR4X1 g329371__7482 (.Y(error_vector[1]),
	.A(n_34),
	.B(n_37),
	.C(n_203),
	.D(n_254));
   OAI211X1 g329372__4733 (.Y(n_274),
	.A0(n_242),
	.A1(n_241),
	.B0(n_252),
	.C0(n_236));
   OAI211X1 g329373__6161 (.Y(n_273),
	.A0(n_208),
	.A1(n_246),
	.B0(n_257),
	.C0(n_255));
   OAI22XL g329374__9315 (.Y(n_272),
	.A0(n_259),
	.A1(n_11),
	.B0(n_258),
	.B1(lambda2[2]));
   OAI22XL g329375__9945 (.Y(n_271),
	.A0(n_259),
	.A1(n_7),
	.B0(n_258),
	.B1(lambda2[1]));
   AOI221X1 g329376__2883 (.Y(error_vector[2]),
	.A0(lambda1[3]),
	.A1(n_184),
	.B0(n_8),
	.B1(n_185),
	.C0(n_266));
   AOI221X1 g329377__2346 (.Y(error_vector[13]),
	.A0(lambda1[1]),
	.A1(n_195),
	.B0(n_9),
	.B1(n_196),
	.C0(n_268));
   AOI221X1 g329378__1666 (.Y(n_269),
	.A0(n_224),
	.A1(n_217),
	.B0(n_223),
	.B1(n_216),
	.C0(n_222));
   OAI221X1 g329379__7410 (.Y(n_268),
	.A0(lambda1[2]),
	.A1(n_39),
	.B0(n_14),
	.B1(n_38),
	.C0(n_256));
   NAND2XL g329380__6417 (.Y(n_267),
	.A(n_259),
	.B(n_38));
   OAI221X1 g329381__5477 (.Y(n_266),
	.A0(n_225),
	.A1(n_215),
	.B0(n_226),
	.B1(n_214),
	.C0(n_250));
   NOR2XL g329382__2398 (.Y(error_vector[14]),
	.A(n_67),
	.B(n_251));
   AOI22XL g329383__5107 (.Y(n_265),
	.A0(n_231),
	.A1(n_245),
	.B0(n_232),
	.B1(n_246));
   AOI22XL g329384__6260 (.Y(n_264),
	.A0(n_205),
	.A1(n_245),
	.B0(n_204),
	.B1(n_246));
   AOI22XL g329385__4319 (.Y(n_263),
	.A0(n_213),
	.A1(n_245),
	.B0(n_212),
	.B1(n_246));
   AOI22XL g329386__8428 (.Y(n_262),
	.A0(n_244),
	.A1(n_13),
	.B0(n_243),
	.B1(lambda2[0]));
   AOI22XL g329387__5526 (.Y(n_261),
	.A0(n_244),
	.A1(n_10),
	.B0(n_243),
	.B1(lambda2[3]));
   AOI22XL g329388__6783 (.Y(n_260),
	.A0(n_244),
	.A1(n_11),
	.B0(n_243),
	.B1(lambda2[2]));
   INVX1 g329389 (.Y(n_258),
	.A(n_259));
   AOI221X1 g329390__3680 (.Y(n_257),
	.A0(n_198),
	.A1(n_189),
	.B0(n_197),
	.B1(n_190),
	.C0(n_234));
   AOI221X1 g329391__1617 (.Y(n_256),
	.A0(n_213),
	.A1(n_219),
	.B0(n_212),
	.B1(n_218),
	.C0(n_238));
   NAND2XL g329392__2802 (.Y(n_255),
	.A(n_208),
	.B(n_246));
   OAI22XL g329393__1705 (.Y(n_254),
	.A0(n_226),
	.A1(n_217),
	.B0(n_225),
	.B1(n_216));
   OAI22XL g329394__5122 (.Y(n_253),
	.A0(n_223),
	.A1(n_184),
	.B0(n_224),
	.B1(n_185));
   NAND3BXL g329395__8246 (.Y(n_259),
	.AN(n_77),
	.B(n_0),
	.C(n_220));
   OAI22XL g329396__7098 (.Y(n_252),
	.A0(n_226),
	.A1(n_190),
	.B0(n_225),
	.B1(n_189));
   OAI221X1 g329397__6131 (.Y(n_251),
	.A0(n_9),
	.A1(n_39),
	.B0(lambda1[1]),
	.B1(n_38),
	.C0(n_240));
   AOI221X1 g329398__1881 (.Y(n_250),
	.A0(lambda1[0]),
	.A1(n_216),
	.B0(n_12),
	.B1(n_217),
	.C0(n_235));
   AOI22XL g329399__5115 (.Y(n_249),
	.A0(n_224),
	.A1(n_13),
	.B0(n_223),
	.B1(lambda2[0]));
   AOI22XL g329400__7482 (.Y(n_248),
	.A0(n_231),
	.A1(n_206),
	.B0(n_232),
	.B1(n_207));
   AOI22XL g329401__4733 (.Y(n_247),
	.A0(n_224),
	.A1(lambda2[3]),
	.B0(n_223),
	.B1(n_10));
   INVX1 g329402 (.Y(n_245),
	.A(n_246));
   INVX1 g329403 (.Y(n_243),
	.A(n_244));
   NOR2XL g329404__6161 (.Y(n_242),
	.A(n_232),
	.B(n_192));
   NOR2XL g329405__9315 (.Y(n_241),
	.A(n_231),
	.B(n_191));
   AOI22XL g329406__9945 (.Y(n_240),
	.A0(n_209),
	.A1(n_196),
	.B0(n_208),
	.B1(n_195));
   OAI22XL g329407__2883 (.Y(n_239),
	.A0(n_200),
	.A1(n_215),
	.B0(n_199),
	.B1(n_214));
   OAI211X1 g329408__2346 (.Y(n_246),
	.A0(n_57),
	.A1(n_187),
	.B0(n_55),
	.C0(n_109));
   AOI31X1 g329409__1666 (.Y(n_244),
	.A0(n_114),
	.A1(n_150),
	.A2(n_182),
	.B0(n_228));
   OAI22XL g329410__7410 (.Y(n_238),
	.A0(n_208),
	.A1(n_206),
	.B0(n_209),
	.B1(n_207));
   AOI22XL g329411__6417 (.Y(n_237),
	.A0(n_197),
	.A1(n_216),
	.B0(n_198),
	.B1(n_217));
   AOI22XL g329412__5477 (.Y(n_236),
	.A0(n_205),
	.A1(n_210),
	.B0(n_204),
	.B1(n_211));
   AOI22XL g329413__2398 (.Y(n_235),
	.A0(n_205),
	.A1(n_190),
	.B0(n_204),
	.B1(n_189));
   AOI22XL g329414__5107 (.Y(n_234),
	.A0(n_212),
	.A1(n_192),
	.B0(n_213),
	.B1(n_191));
   OAI22XL g329415__6260 (.Y(n_233),
	.A0(n_9),
	.A1(n_207),
	.B0(lambda1[1]),
	.B1(n_206));
   INVX1 g329416 (.Y(n_231),
	.A(n_232));
   NOR2XL g329417__4319 (.Y(n_230),
	.A(n_209),
	.B(n_219));
   NOR2XL g329418__8428 (.Y(n_229),
	.A(n_208),
	.B(n_218));
   OAI31X1 g329419__5526 (.Y(n_228),
	.A0(n_105),
	.A1(n_151),
	.A2(n_182),
	.B0(n_93));
   NAND2XL g329420__6783 (.Y(n_227),
	.A(n_204),
	.B(n_192));
   NAND2XL g329421__3680 (.Y(n_232),
	.A(n_87),
	.B(n_201));
   INVX1 g329422 (.Y(n_225),
	.A(n_226));
   INVX1 g329423 (.Y(n_223),
	.A(n_224));
   AOI22XL g329424__1617 (.Y(n_222),
	.A0(n_199),
	.A1(n_189),
	.B0(n_200),
	.B1(n_190));
   OAI22XL g329425__2802 (.Y(n_221),
	.A0(n_198),
	.A1(n_185),
	.B0(n_197),
	.B1(n_184));
   AOI33XL g329426__1705 (.Y(n_220),
	.A0(n_54),
	.A1(n_125),
	.A2(n_179),
	.B0(n_128),
	.B1(1'b1),
	.B2(n_144));
   OAI211X1 g329427__5122 (.Y(n_226),
	.A0(n_53),
	.A1(n_113),
	.B0(n_2),
	.C0(n_186));
   AOI221X1 g329428__8246 (.Y(n_224),
	.A0(n_143),
	.A1(n_182),
	.B0(n_100),
	.B1(n_160),
	.C0(n_90));
   INVX1 g329429 (.Y(n_218),
	.A(n_219));
   INVX1 g329430 (.Y(n_216),
	.A(n_217));
   INVX1 g329431 (.Y(n_214),
	.A(n_215));
   INVX1 g329432 (.Y(n_212),
	.A(n_213));
   INVX1 g329433 (.Y(n_210),
	.A(n_211));
   NOR2XL g329434__7098 (.Y(n_219),
	.A(n_107),
	.B(n_193));
   OAI211X1 g329435__6131 (.Y(n_217),
	.A0(n_84),
	.A1(n_130),
	.B0(n_97),
	.C0(n_183));
   NAND2XL g329436__1881 (.Y(n_215),
	.A(n_86),
	.B(n_194));
   OAI211X1 g329437__5115 (.Y(n_213),
	.A0(n_112),
	.A1(n_173),
	.B0(n_75),
	.C0(n_88));
   AOI211XL g329438__7482 (.Y(n_211),
	.A0(n_153),
	.A1(n_168),
	.B0(n_40),
	.C0(n_80));
   INVX1 g329439 (.Y(n_208),
	.A(n_209));
   INVX1 g329440 (.Y(n_206),
	.A(n_207));
   INVX1 g329441 (.Y(n_204),
	.A(n_205));
   OAI22XL g329442__4733 (.Y(n_203),
	.A0(n_12),
	.A1(n_185),
	.B0(lambda1[0]),
	.B1(n_184));
   OAI22XL g329443__6161 (.Y(n_202),
	.A0(n_180),
	.A1(n_38),
	.B0(n_181),
	.B1(n_39));
   AOI33XL g329444__9315 (.Y(n_201),
	.A0(n_68),
	.A1(n_112),
	.A2(n_161),
	.B0(n_150),
	.B1(n_129),
	.B2(n_156));
   AOI222X1 g329445__9945 (.Y(n_209),
	.A0(n_149),
	.A1(n_147),
	.B0(n_122),
	.B1(n_174),
	.C0(n_115),
	.C1(n_135));
   OAI211X1 g329446__2883 (.Y(n_207),
	.A0(n_152),
	.A1(n_170),
	.B0(n_1),
	.C0(n_50));
   AOI31X1 g329447__2346 (.Y(n_205),
	.A0(n_54),
	.A1(n_114),
	.A2(n_121),
	.B0(n_188));
   INVX1 g329448 (.Y(n_199),
	.A(n_200));
   INVX1 g329449 (.Y(n_197),
	.A(n_198));
   INVX1 g329450 (.Y(n_195),
	.A(n_196));
   AOI33XL g329451__1666 (.Y(n_194),
	.A0(n_134),
	.A1(n_153),
	.A2(n_169),
	.B0(n_137),
	.B1(n_97),
	.B2(n_168));
   AOI211XL g329452__7410 (.Y(n_193),
	.A0(n_140),
	.A1(n_142),
	.B0(n_117),
	.C0(n_6));
   OAI211X1 g329453__6417 (.Y(n_200),
	.A0(n_114),
	.A1(n_151),
	.B0(n_2),
	.C0(n_172));
   OAI211X1 g329454__5477 (.Y(n_198),
	.A0(n_102),
	.A1(n_115),
	.B0(n_79),
	.C0(n_171));
   OAI211X1 g329455__2398 (.Y(n_196),
	.A0(n_106),
	.A1(n_123),
	.B0(n_73),
	.C0(n_176));
   INVX1 g329456 (.Y(n_191),
	.A(n_192));
   INVX1 g329457 (.Y(n_189),
	.A(n_190));
   OAI32X1 g329458__5107 (.Y(n_188),
	.A0(n_118),
	.A1(n_127),
	.A2(n_148),
	.B0(n_131),
	.B1(n_177));
   OAI211X1 g329459__6260 (.Y(n_187),
	.A0(n_124),
	.A1(n_141),
	.B0(n_106),
	.C0(n_165));
   OAI211X1 g329460__4319 (.Y(n_186),
	.A0(n_69),
	.A1(n_122),
	.B0(n_135),
	.C0(n_162));
   AOI22XL g329461__8428 (.Y(n_192),
	.A0(n_140),
	.A1(n_170),
	.B0(n_123),
	.B1(n_153));
   OAI211X1 g329462__5526 (.Y(n_190),
	.A0(n_5),
	.A1(n_169),
	.B0(n_145),
	.C0(n_163));
   INVX1 g329463 (.Y(n_184),
	.A(n_185));
   OAI221X1 g329464__6783 (.Y(n_183),
	.A0(n_134),
	.A1(n_153),
	.B0(n_40),
	.B1(n_117),
	.C0(n_169));
   OAI31X1 g329465__3680 (.Y(n_185),
	.A0(n_24),
	.A1(n_57),
	.A2(n_134),
	.B0(n_166));
   INVX1 g329466 (.Y(n_180),
	.A(n_181));
   AOI21XL g329467__1617 (.Y(n_179),
	.A0(n_58),
	.A1(n_139),
	.B0(n_157));
   OAI21XL g329468__2802 (.Y(n_182),
	.A0(n_149),
	.A1(n_138),
	.B0(n_178));
   AOI221X1 g329469__1705 (.Y(n_181),
	.A0(n_132),
	.A1(n_149),
	.B0(n_111),
	.B1(n_113),
	.C0(n_175));
   INVXL g329470 (.Y(n_178),
	.A(n_157));
   INVXL g329471 (.Y(n_177),
	.A(n_162));
   OAI211X1 g329472__5122 (.Y(n_176),
	.A0(n_56),
	.A1(n_154),
	.B0(n_146),
	.C0(n_136));
   NOR2BX1 g329473__8246 (.Y(n_175),
	.AN(n_161),
	.B(n_125));
   NOR2BX1 g329474__7098 (.Y(n_174),
	.AN(n_164),
	.B(n_105));
   OAI2BB1X1 g329475__6131 (.Y(n_173),
	.A0N(n_105),
	.A1N(n_121),
	.B0(n_164));
   OAI211X1 g329476__1881 (.Y(n_172),
	.A0(n_133),
	.A1(n_113),
	.B0(n_127),
	.C0(n_159));
   INVXL g329477 (.Y(n_171),
	.A(n_167));
   INVXL g329478 (.Y(n_168),
	.A(n_169));
   AOI211XL g329479__5115 (.Y(n_167),
	.A0(n_23),
	.A1(n_149),
	.B0(n_135),
	.C0(n_143));
   AO22X1 g329480__7482 (.Y(n_166),
	.A0(n_1),
	.A1(n_155),
	.B0(n_123),
	.B1(n_158));
   XNOR2X1 g329482__4733 (.Y(n_165),
	.A(n_110),
	.B(n_158));
   XNOR2X1 g329483__6161 (.Y(n_170),
	.A(n_158),
	.B(n_142));
   XNOR2X1 g329484__9315 (.Y(n_169),
	.A(n_104),
	.B(n_158));
   OAI21XL g329485__9945 (.Y(n_163),
	.A0(n_56),
	.A1(n_116),
	.B0(n_158));
   NAND2XL g329486__2883 (.Y(n_164),
	.A(n_52),
	.B(n_159));
   XNOR2X1 g329487__2346 (.Y(n_160),
	.A(n_103),
	.B(n_149));
   OAI2BB1X1 g329488__1666 (.Y(n_162),
	.A0N(n_111),
	.A1N(n_149),
	.B0(n_156));
   XNOR2X1 g329489__7410 (.Y(n_161),
	.A(n_93),
	.B(n_148));
   NAND2XL g329491__6417 (.Y(n_159),
	.A(n_95),
	.B(n_148));
   NOR2XL g329492__5477 (.Y(n_158),
	.A(n_57),
	.B(n_154));
   OAI2BB1X1 g329493__2398 (.Y(n_155),
	.A0N(n_98),
	.A1N(n_141),
	.B0(n_86));
   NOR2XL g329494__5107 (.Y(n_157),
	.A(n_103),
	.B(n_148));
   OR2X1 g329495__6260 (.Y(n_156),
	.A(n_111),
	.B(n_149));
   AND2X1 g329496__4319 (.Y(n_152),
	.A(n_141),
	.B(n_106));
   NAND3XL g329497__8428 (.Y(n_154),
	.A(n_50),
	.B(n_43),
	.C(n_119));
   NAND2XL g329498__5526 (.Y(n_153),
	.A(n_104),
	.B(n_141));
   INVX1 g329499 (.Y(n_148),
	.A(n_149));
   AOI211XL g329500__6783 (.Y(n_147),
	.A0(n_101),
	.A1(n_118),
	.B0(n_71),
	.C0(n_112));
   OAI2BB1X1 g329501__3680 (.Y(n_151),
	.A0N(n_95),
	.A1N(n_122),
	.B0(n_54));
   NAND2XL g329502__1617 (.Y(n_150),
	.A(n_64),
	.B(n_144));
   NAND3XL g329503__2802 (.Y(n_149),
	.A(n_52),
	.B(n_79),
	.C(n_120));
   NAND2XL g329505__1705 (.Y(n_146),
	.A(n_109),
	.B(n_126));
   OAI2BB1X1 g329506__5122 (.Y(n_145),
	.A0N(n_43),
	.A1N(n_86),
	.B0(n_134));
   INVXL g329507 (.Y(n_140),
	.A(n_141));
   AOI21XL g329508__8246 (.Y(n_144),
	.A0(n_82),
	.A1(n_101),
	.B0(n_42));
   AOI21XL g329509__7098 (.Y(n_143),
	.A0(n_99),
	.A1(n_115),
	.B0(n_102));
   NOR3BXL g329510__6131 (.Y(n_142),
	.AN(n_104),
	.B(n_48),
	.C(n_84));
   NOR4BX1 g329511__1881 (.Y(n_141),
	.AN(n_97),
	.B(n_61),
	.C(n_56),
	.D(n_76));
   INVXL g329512 (.Y(n_139),
	.A(n_138));
   INVXL g329513 (.Y(n_137),
	.A(n_136));
   NOR2XL g329514__5115 (.Y(n_133),
	.A(n_71),
	.B(n_102));
   NAND2BXL g329515__7482 (.Y(n_132),
	.AN(n_112),
	.B(n_52));
   NOR2XL g329516__4733 (.Y(n_131),
	.A(n_69),
	.B(n_111));
   OR2X1 g329517__6161 (.Y(n_130),
	.A(n_57),
	.B(n_108));
   NAND2XL g329518__9315 (.Y(n_138),
	.A(n_44),
	.B(n_103));
   NOR2XL g329519__9945 (.Y(n_136),
	.A(n_51),
	.B(n_116));
   NOR2BX1 g329520__2883 (.Y(n_135),
	.AN(n_99),
	.B(n_111));
   NOR2XL g329521__2346 (.Y(n_134),
	.A(n_4),
	.B(n_107));
   INVXL g329522 (.Y(n_129),
	.A(n_128));
   INVXL g329524 (.Y(n_124),
	.A(n_123));
   INVX1 g329525 (.Y(n_121),
	.A(n_122));
   NOR4X1 g329526__1666 (.Y(n_120),
	.A(n_62),
	.B(n_41),
	.C(n_42),
	.D(n_74));
   NOR4X1 g329527__7410 (.Y(n_119),
	.A(n_63),
	.B(n_61),
	.C(n_59),
	.D(n_83));
   NAND3BXL g329528__6417 (.Y(n_128),
	.AN(n_90),
	.B(n_52),
	.C(n_78));
   NAND3BXL g329529__5477 (.Y(n_127),
	.AN(n_77),
	.B(n_87),
	.C(n_95));
   NAND4XL g329530__2398 (.Y(n_126),
	.A(n_60),
	.B(n_70),
	.C(n_72),
	.D(n_81));
   OAI21XL g329531__5107 (.Y(n_125),
	.A0(n_89),
	.A1(n_94),
	.B0(n_78));
   AND3XL g329532__6260 (.Y(n_123),
	.A(n_50),
	.B(n_70),
	.C(n_86));
   NAND3BXL g329533__4319 (.Y(n_122),
	.AN(n_89),
	.B(n_0),
	.C(n_93));
   NAND2XL g329534__8428 (.Y(n_118),
	.A(n_87),
	.B(n_88));
   NOR2XL g329535__5526 (.Y(n_110),
	.A(n_63),
	.B(n_96));
   NAND2XL g329536__6783 (.Y(n_117),
	.A(n_98),
	.B(n_85));
   NAND2XL g329537__3680 (.Y(n_116),
	.A(n_81),
	.B(n_98));
   NOR2XL g329538__1617 (.Y(n_115),
	.A(n_66),
	.B(n_90));
   AND2X1 g329539__2802 (.Y(n_114),
	.A(n_88),
	.B(n_82));
   AND2X1 g329540__1705 (.Y(n_113),
	.A(n_95),
	.B(n_79));
   NAND2BXL g329541__5122 (.Y(n_112),
	.AN(n_89),
	.B(n_88));
   NAND2XL g329542__8246 (.Y(n_111),
	.A(n_64),
	.B(n_87));
   INVXL g329543 (.Y(n_101),
	.A(n_102));
   NAND2XL g329544__7098 (.Y(n_100),
	.A(n_23),
	.B(n_87));
   NOR2XL g329545__6131 (.Y(n_109),
	.A(n_46),
	.B(n_84));
   NOR3BXL g329546__1881 (.Y(n_108),
	.AN(n_72),
	.B(n_51),
	.C(n_4));
   OAI21XL g329547__5115 (.Y(n_107),
	.A0(lambda2[1]),
	.A1(n_15),
	.B0(n_85));
   NOR3BXL g329548__7482 (.Y(n_106),
	.AN(n_70),
	.B(n_80),
	.C(n_84));
   NAND4XL g329549__4733 (.Y(n_105),
	.A(n_58),
	.B(n_2),
	.C(n_3),
	.D(n_68));
   NOR2BX1 g329550__6161 (.Y(n_104),
	.AN(n_86),
	.B(n_80));
   AND2X1 g329551__9315 (.Y(n_103),
	.A(n_99),
	.B(n_23));
   NAND2XL g329552__9945 (.Y(n_102),
	.A(n_79),
	.B(n_92));
   INVXL g329553 (.Y(n_94),
	.A(n_93));
   NOR2XL g329554__2883 (.Y(n_92),
	.A(n_62),
	.B(n_77));
   NOR2BX1 g329555__2346 (.Y(n_99),
	.AN(n_78),
	.B(n_71));
   NOR2BX1 g329556__1666 (.Y(n_98),
	.AN(n_70),
	.B(n_63));
   NOR2BX1 g329557__7410 (.Y(n_97),
	.AN(n_73),
	.B(n_83));
   NAND2BXL g329558__6417 (.Y(n_96),
	.AN(n_4),
	.B(n_81));
   NOR2XL g329559__5477 (.Y(n_95),
	.A(n_65),
	.B(n_71));
   NOR2BX1 g329560__2398 (.Y(n_93),
	.AN(n_3),
	.B(n_77));
   INVX1 g329561 (.Y(n_84),
	.A(n_85));
   NOR4X1 g329562__5107 (.Y(error_vector[0]),
	.A(n_33),
	.B(n_36),
	.C(n_32),
	.D(n_31));
   NAND2BXL g329563__6260 (.Y(n_90),
	.AN(n_41),
	.B(n_82));
   OAI21XL g329564__4319 (.Y(n_89),
	.A0(n_23),
	.A1(n_18),
	.B0(n_78));
   NOR2XL g329565__8428 (.Y(n_88),
	.A(n_66),
	.B(n_69));
   AND3XL g329566__5526 (.Y(n_87),
	.A(n_58),
	.B(n_0),
	.C(n_2));
   AND2X1 g329567__6783 (.Y(n_86),
	.A(n_72),
	.B(n_45));
   NOR2XL g329568__3680 (.Y(n_85),
	.A(n_51),
	.B(n_76));
   NAND2XL g329569__1617 (.Y(n_83),
	.A(n_49),
	.B(n_1));
   NOR2BX1 g329570__2802 (.Y(n_82),
	.AN(n_3),
	.B(n_42));
   NOR2XL g329571__1705 (.Y(n_81),
	.A(n_61),
	.B(n_40));
   NAND2BXL g329572__5122 (.Y(n_80),
	.AN(n_46),
	.B(n_43));
   AND2X1 g329574__8246 (.Y(n_79),
	.A(n_58),
	.B(n_47));
   NOR2XL g329575__7098 (.Y(n_78),
	.A(n_65),
	.B(n_62));
   NAND2BXL g329576__6131 (.Y(n_77),
	.AN(n_41),
	.B(n_64));
   INVXL g329577 (.Y(n_75),
	.A(n_74));
   INVXL g329578 (.Y(n_68),
	.A(n_69));
   OAI221X1 g329579__1881 (.Y(n_67),
	.A0(lambda1[3]),
	.A1(lambda2[2]),
	.B0(n_8),
	.B1(n_11),
	.C0(n_35));
   OAI21XL g329580__5115 (.Y(n_76),
	.A0(n_16),
	.A1(n_19),
	.B0(n_60));
   OAI21XL g329581__7482 (.Y(n_74),
	.A0(n_23),
	.A1(n_22),
	.B0(n_0));
   OA21X1 g329582__4733 (.Y(n_73),
	.A0(n_15),
	.A1(n_30),
	.B0(n_45));
   OA21X1 g329583__6161 (.Y(n_72),
	.A0(n_15),
	.A1(n_24),
	.B0(n_1));
   NAND2XL g329584__9315 (.Y(n_71),
	.A(n_52),
	.B(n_54));
   NOR2BX1 g329585__9945 (.Y(n_70),
	.AN(n_49),
	.B(n_48));
   NAND2XL g329586__2883 (.Y(n_69),
	.A(n_47),
	.B(n_44));
   INVXL g329587 (.Y(n_60),
	.A(n_59));
   INVXL g329589 (.Y(n_55),
	.A(n_56));
   INVXL g329590 (.Y(n_53),
	.A(n_54));
   INVX1 g329591 (.Y(n_50),
	.A(n_51));
   NOR2XL g329592__2346 (.Y(n_66),
	.A(n_21),
	.B(n_27));
   NOR2XL g329593__1666 (.Y(n_65),
	.A(n_17),
	.B(n_27));
   NAND2BXL g329594__7410 (.Y(n_64),
	.AN(n_18),
	.B(n_29));
   NOR2XL g329595__6417 (.Y(n_63),
	.A(n_16),
	.B(n_30));
   NOR2XL g329596__5477 (.Y(n_62),
	.A(n_23),
	.B(n_27));
   NOR2XL g329597__2398 (.Y(n_61),
	.A(n_25),
	.B(n_19));
   NOR2BX1 g329598__5107 (.Y(n_59),
	.AN(n_26),
	.B(n_30));
   NAND2BXL g329600__6260 (.Y(n_58),
	.AN(n_22),
	.B(n_29));
   NOR2BX1 g329604__4319 (.Y(n_57),
	.AN(n_26),
	.B(n_24));
   NOR2XL g329605__8428 (.Y(n_56),
	.A(n_25),
	.B(n_24));
   NAND2XL g329606__5526 (.Y(n_54),
	.A(n_29),
	.B(n_28));
   NAND2BXL g329607__6783 (.Y(n_52),
	.AN(n_27),
	.B(n_29));
   NOR2XL g329608__3680 (.Y(n_51),
	.A(n_25),
	.B(n_20));
   INVX1 g329609 (.Y(n_38),
	.A(n_39));
   OAI22XL g329610__1617 (.Y(n_37),
	.A0(n_8),
	.A1(lambda2[0]),
	.B0(lambda1[3]),
	.B1(n_13));
   AOI22XL g329611__2802 (.Y(n_36),
	.A0(n_9),
	.A1(n_7),
	.B0(lambda1[1]),
	.B1(lambda2[1]));
   AOI22XL g329612__1705 (.Y(n_35),
	.A0(lambda1[2]),
	.A1(n_7),
	.B0(n_14),
	.B1(lambda2[1]));
   OAI22XL g329613__5122 (.Y(n_34),
	.A0(n_14),
	.A1(lambda2[3]),
	.B0(lambda1[2]),
	.B1(n_10));
   OAI22XL g329614__8246 (.Y(n_33),
	.A0(n_8),
	.A1(lambda2[3]),
	.B0(lambda1[3]),
	.B1(n_10));
   AOI22XL g329615__7098 (.Y(n_32),
	.A0(lambda1[0]),
	.A1(n_13),
	.B0(n_12),
	.B1(lambda2[0]));
   OAI22XL g329616__6131 (.Y(n_31),
	.A0(n_14),
	.A1(lambda2[2]),
	.B0(lambda1[2]),
	.B1(n_11));
   OR2X1 g329617__1881 (.Y(n_49),
	.A(n_16),
	.B(n_20));
   NOR2XL g329618__5115 (.Y(n_48),
	.A(n_15),
	.B(n_19));
   OR2X1 g329619__7482 (.Y(n_47),
	.A(n_17),
	.B(n_22));
   NOR2XL g329620__4733 (.Y(n_46),
	.A(n_15),
	.B(n_20));
   NAND2BXL g329621__6161 (.Y(n_45),
	.AN(n_19),
	.B(n_26));
   OR2X1 g329622__9315 (.Y(n_44),
	.A(n_21),
	.B(n_18));
   OR2X1 g329623__9945 (.Y(n_43),
	.A(n_16),
	.B(n_24));
   NOR2XL g329624__2883 (.Y(n_42),
	.A(n_17),
	.B(n_18));
   NOR2XL g329625__2346 (.Y(n_41),
	.A(n_21),
	.B(n_22));
   NOR2XL g329626__1666 (.Y(n_40),
	.A(n_25),
	.B(n_30));
   NAND2XL g329627__7410 (.Y(n_39),
	.A(n_16),
	.B(n_15));
   NAND2XL g329629__6417 (.Y(n_30),
	.A(lambda2[1]),
	.B(lambda2[2]));
   NOR2XL g329630__5477 (.Y(n_29),
	.A(lambda1[1]),
	.B(lambda1[2]));
   NOR2XL g329631__2398 (.Y(n_28),
	.A(lambda1[3]),
	.B(lambda1[0]));
   NAND2XL g329632__5107 (.Y(n_27),
	.A(lambda1[3]),
	.B(lambda1[0]));
   NOR2XL g329633__6260 (.Y(n_26),
	.A(lambda2[3]),
	.B(lambda2[0]));
   NAND2XL g329634__4319 (.Y(n_25),
	.A(lambda2[3]),
	.B(lambda2[0]));
   NAND2XL g329635__8428 (.Y(n_24),
	.A(n_7),
	.B(n_11));
   NAND2XL g329636__5526 (.Y(n_23),
	.A(lambda1[1]),
	.B(lambda1[2]));
   NAND2XL g329640__6783 (.Y(n_22),
	.A(n_8),
	.B(lambda1[0]));
   NAND2XL g329641__3680 (.Y(n_21),
	.A(lambda1[1]),
	.B(n_14));
   NAND2XL g329642__1617 (.Y(n_20),
	.A(lambda2[1]),
	.B(n_11));
   NAND2XL g329643__2802 (.Y(n_19),
	.A(n_7),
	.B(lambda2[2]));
   NAND2XL g329644__1705 (.Y(n_18),
	.A(lambda1[3]),
	.B(n_12));
   NAND2XL g329645__5122 (.Y(n_17),
	.A(n_9),
	.B(lambda1[2]));
   NAND2XL g329646__8246 (.Y(n_16),
	.A(lambda2[3]),
	.B(n_13));
   NAND2XL g329647__7098 (.Y(n_15),
	.A(n_10),
	.B(lambda2[0]));
   INVX1 g329648 (.Y(n_14),
	.A(lambda1[2]));
   INVX1 g329649 (.Y(n_13),
	.A(lambda2[0]));
   INVX1 g329650 (.Y(n_12),
	.A(lambda1[0]));
   INVX1 g329651 (.Y(n_11),
	.A(lambda2[2]));
   INVX1 g329652 (.Y(n_10),
	.A(lambda2[3]));
   INVX1 g329653 (.Y(n_9),
	.A(lambda1[1]));
   INVX1 g329654 (.Y(n_8),
	.A(lambda1[3]));
   INVX1 g329655 (.Y(n_7),
	.A(lambda2[1]));
   XOR2XL g2__6131 (.Y(n_6),
	.A(n_96),
	.B(n_158));
   NAND2BX1 g329656__1881 (.Y(n_5),
	.AN(n_126),
	.B(n_108));
   NAND2BX1 g329657__5115 (.Y(n_4),
	.AN(n_57),
	.B(n_55));
   NAND2BX1 g329658__7482 (.Y(n_3),
	.AN(n_23),
	.B(n_28));
   NAND2BX1 g329659__4733 (.Y(n_2),
	.AN(n_21),
	.B(n_28));
   NAND2BX1 g329660__6161 (.Y(n_1),
	.AN(n_20),
	.B(n_26));
   NAND2BX1 g329661__9315 (.Y(n_0),
	.AN(n_17),
	.B(n_28));
endmodule

module bch_corrector (
	corruptedWord, 
	errorVector, 
	correctedWord);
   input [14:0] corruptedWord;
   input [14:0] errorVector;
   output [14:0] correctedWord;

   CLKXOR2X2 g136__9945 (.Y(correctedWord[10]),
	.A(corruptedWord[10]),
	.B(errorVector[10]));
   CLKXOR2X2 g137__2883 (.Y(correctedWord[12]),
	.A(corruptedWord[12]),
	.B(errorVector[12]));
   CLKXOR2X2 g138__2346 (.Y(correctedWord[11]),
	.A(corruptedWord[11]),
	.B(errorVector[11]));
   CLKXOR2X2 g139__1666 (.Y(correctedWord[1]),
	.A(corruptedWord[1]),
	.B(errorVector[1]));
   CLKXOR2X2 g140__7410 (.Y(correctedWord[0]),
	.A(corruptedWord[0]),
	.B(errorVector[0]));
   CLKXOR2X2 g141__6417 (.Y(correctedWord[7]),
	.A(corruptedWord[7]),
	.B(errorVector[7]));
   CLKXOR2X2 g142__5477 (.Y(correctedWord[14]),
	.A(corruptedWord[14]),
	.B(errorVector[14]));
   CLKXOR2X2 g143__2398 (.Y(correctedWord[4]),
	.A(corruptedWord[4]),
	.B(errorVector[4]));
   CLKXOR2X2 g144__5107 (.Y(correctedWord[5]),
	.A(corruptedWord[5]),
	.B(errorVector[5]));
   CLKXOR2X2 g145__6260 (.Y(correctedWord[13]),
	.A(corruptedWord[13]),
	.B(errorVector[13]));
   CLKXOR2X2 g146__4319 (.Y(correctedWord[9]),
	.A(corruptedWord[9]),
	.B(errorVector[9]));
   CLKXOR2X2 g147__8428 (.Y(correctedWord[6]),
	.A(corruptedWord[6]),
	.B(errorVector[6]));
   CLKXOR2X2 g148__5526 (.Y(correctedWord[8]),
	.A(corruptedWord[8]),
	.B(errorVector[8]));
   CLKXOR2X2 g149__6783 (.Y(correctedWord[3]),
	.A(corruptedWord[3]),
	.B(errorVector[3]));
   CLKXOR2X2 g150__3680 (.Y(correctedWord[2]),
	.A(corruptedWord[2]),
	.B(errorVector[2]));
endmodule

module bch_syndrome_block (
	codeword, 
	S1, 
	S2, 
	S3);
   input [14:0] codeword;
   output [3:0] S1;
   output [3:0] S2;
   output [3:0] S3;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_35;
   wire n_36;
   wire n_37;

   XNOR2X1 g957__1617 (.Y(S3[3]),
	.A(n_30),
	.B(n_36));
   XNOR2X1 g958__2802 (.Y(S3[0]),
	.A(n_9),
	.B(n_35));
   XNOR2X1 g959__1705 (.Y(S1[2]),
	.A(n_17),
	.B(n_31));
   XNOR2X1 g960__5122 (.Y(S2[0]),
	.A(n_24),
	.B(n_37));
   XNOR2X1 g961__8246 (.Y(S3[1]),
	.A(n_26),
	.B(n_28));
   XNOR2X1 g962__7098 (.Y(S3[2]),
	.A(n_23),
	.B(n_28));
   XNOR2X1 g963__6131 (.Y(n_37),
	.A(n_4),
	.B(n_29));
   XNOR2X1 g964__1881 (.Y(n_36),
	.A(n_29),
	.B(n_28));
   XNOR2X1 g965__5115 (.Y(n_35),
	.A(codeword[0]),
	.B(n_28));
   XNOR2X1 g966__7482 (.Y(S1[1]),
	.A(n_21),
	.B(n_0));
   XNOR2X1 g967__4733 (.Y(S2[2]),
	.A(n_1),
	.B(n_20));
   XNOR2X1 g968__6161 (.Y(S1[0]),
	.A(n_19),
	.B(n_27));
   XNOR2X1 g970__9315 (.Y(n_31),
	.A(n_25),
	.B(n_29));
   XNOR2X1 g971__9945 (.Y(n_30),
	.A(n_13),
	.B(n_22));
   XNOR2X1 g972__2883 (.Y(n_27),
	.A(n_6),
	.B(n_7));
   XNOR2X1 g973__2346 (.Y(n_26),
	.A(codeword[8]),
	.B(n_10));
   MX2X1 g974__1666 (.Y(n_25),
	.A(n_9),
	.B(n_8),
	.S0(codeword[12]));
   XNOR2X1 g975__7410 (.Y(n_24),
	.A(codeword[0]),
	.B(n_7));
   XNOR2X1 g976__6417 (.Y(n_23),
	.A(codeword[2]),
	.B(n_6));
   XNOR2X1 g977__5477 (.Y(n_29),
	.A(codeword[2]),
	.B(n_11));
   XNOR2X1 g978__2398 (.Y(n_28),
	.A(codeword[9]),
	.B(n_7));
   XNOR2X1 g980__5107 (.Y(n_21),
	.A(n_5),
	.B(n_16));
   XNOR2X1 g983__6260 (.Y(n_20),
	.A(n_15),
	.B(n_8));
   XNOR2X1 g984__4319 (.Y(n_19),
	.A(n_14),
	.B(n_17));
   XNOR2X1 g985__8428 (.Y(n_18),
	.A(n_12),
	.B(n_11));
   XNOR2X1 g986__5526 (.Y(n_22),
	.A(n_10),
	.B(n_6));
   XNOR2X1 g987__6783 (.Y(n_16),
	.A(codeword[9]),
	.B(codeword[11]));
   XNOR2X1 g988__3680 (.Y(n_15),
	.A(codeword[1]),
	.B(codeword[6]));
   XNOR2X1 g989__1617 (.Y(n_14),
	.A(codeword[0]),
	.B(codeword[10]));
   XNOR2X1 g990__2802 (.Y(n_13),
	.A(codeword[1]),
	.B(codeword[8]));
   XNOR2X1 g991__1705 (.Y(n_12),
	.A(codeword[9]),
	.B(codeword[14]));
   XNOR2X1 g992__5122 (.Y(n_17),
	.A(codeword[8]),
	.B(codeword[13]));
   INVX1 g993 (.Y(n_8),
	.A(n_9));
   XNOR2X1 g996__8246 (.Y(n_5),
	.A(codeword[1]),
	.B(codeword[4]));
   XNOR2X1 g997__7098 (.Y(n_4),
	.A(codeword[5]),
	.B(codeword[7]));
   XNOR2X1 g998__6131 (.Y(n_11),
	.A(codeword[6]),
	.B(codeword[11]));
   XNOR2X1 g999__1881 (.Y(n_10),
	.A(codeword[3]),
	.B(codeword[13]));
   XNOR2X1 g1000__5115 (.Y(n_9),
	.A(codeword[5]),
	.B(codeword[10]));
   CLKXOR2X1 g1001__7482 (.Y(n_7),
	.A(codeword[4]),
	.B(codeword[14]));
   XNOR2X1 g1002__4733 (.Y(n_6),
	.A(codeword[7]),
	.B(codeword[12]));
   XOR2XL g2__6161 (.Y(S1[3]),
	.A(n_18),
	.B(n_22));
   XOR2XL g1003__9315 (.Y(n_1),
	.A(n_7),
	.B(n_10));
   MXI2XL g1004__9945 (.Y(n_0),
	.A(n_8),
	.B(n_9),
	.S0(n_6));
endmodule

module bch_comb_top (
	codeword, 
	corrected_codeword, 
	error_flag);
   input [14:0] codeword;
   output [14:0] corrected_codeword;
   output error_flag;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;
   wire [3:0] S3;
   wire [3:0] lambda1;
   wire [3:0] lambda2;
   wire [14:0] error_vector;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED_HIER_Z5;
   wire UNCONNECTED_HIER_Z6;

   bch_pipe2 bm (.S1({ UNCONNECTED_HIER_Z6,
		UNCONNECTED_HIER_Z5,
		S1[1],
		S1[0] }),
	.S2({ S1[3],
		S2[2],
		S1[2],
		S2[0] }),
	.S3(S3),
	.l1(lambda1),
	.l2(lambda2));
   bch_chien_block cb (.lambda1(lambda1),
	.lambda2(lambda2),
	.error_vector(error_vector),
	.error_found(error_flag));
   bch_corrector cr (.corruptedWord(codeword),
	.errorVector(error_vector),
	.correctedWord(corrected_codeword));
   bch_syndrome_block sb (.codeword(codeword),
	.S1(S1),
	.S2({ UNCONNECTED2,
		S2[2],
		UNCONNECTED1,
		S2[0] }),
	.S3(S3));
endmodule

