/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Oct  6 17:10:23 2025
#  Design:            h_decoder_21_16
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/h_decoder_21_16/h_decoder_21_16_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 29 2025 16:29:22 -03 (Sep 29 2025 19:29:22 UTC)
// Verification Directory fv/h_decoder_21_16 
module h_decoder_21_16 (
	i_CodeWord, 
	o_DecodWord, 
	o_ErrorC, 
	o_ErrorD);
   input [21:0] i_CodeWord;
   output [15:0] o_DecodWord;
   output o_ErrorC;
   output o_ErrorD;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_44;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;

   assign o_DecodWord[15] = i_CodeWord[21] ;

   XNOR2X2 g1258__2398 (.Y(o_DecodWord[10]),
	.A(n_77),
	.B(i_CodeWord[15]));
   XNOR2X2 g1255__5107 (.Y(o_DecodWord[9]),
	.A(n_76),
	.B(i_CodeWord[14]));
   CLKXOR2X2 g1259__6260 (.Y(o_DecodWord[8]),
	.A(n_69),
	.B(i_CodeWord[13]));
   CLKXOR2X2 g1260__4319 (.Y(o_DecodWord[7]),
	.A(n_74),
	.B(i_CodeWord[12]));
   XNOR2X2 g1261__8428 (.Y(o_DecodWord[6]),
	.A(i_CodeWord[11]),
	.B(n_72));
   XNOR2X2 g1257__5526 (.Y(o_DecodWord[5]),
	.A(i_CodeWord[10]),
	.B(n_66));
   CLKXOR2X2 g1262__6783 (.Y(o_DecodWord[4]),
	.A(n_73),
	.B(i_CodeWord[9]));
   XNOR2X2 g1254__3680 (.Y(o_DecodWord[3]),
	.A(i_CodeWord[7]),
	.B(n_56));
   XNOR2X2 g1256__1617 (.Y(o_DecodWord[2]),
	.A(i_CodeWord[6]),
	.B(n_59));
   CLKXOR2X2 g1263__2802 (.Y(o_DecodWord[1]),
	.A(i_CodeWord[5]),
	.B(n_58));
   NAND2XL g1278__1705 (.Y(n_77),
	.A(n_70),
	.B(n_75));
   NAND2XL g1271__5122 (.Y(n_76),
	.A(n_65),
	.B(n_75));
   NOR2XL g1267__8246 (.Y(n_74),
	.A(n_35),
	.B(n_67));
   NOR2XL g1265__7098 (.Y(n_73),
	.A(n_68),
	.B(n_71));
   NAND2BXL g1269__6131 (.Y(n_72),
	.AN(n_71),
	.B(n_70));
   NOR2XL g1266__1881 (.Y(n_69),
	.A(n_68),
	.B(n_67));
   NAND2BXL g1270__5115 (.Y(n_66),
	.AN(n_71),
	.B(n_65));
   XNOR2X2 g1274__7482 (.Y(o_DecodWord[13]),
	.A(n_48),
	.B(i_CodeWord[19]));
   XNOR2X2 g1272__4733 (.Y(o_DecodWord[11]),
	.A(i_CodeWord[17]),
	.B(n_53));
   XNOR2X2 g1273__6161 (.Y(o_DecodWord[14]),
	.A(i_CodeWord[20]),
	.B(n_50));
   XNOR2X2 g1275__9315 (.Y(o_DecodWord[12]),
	.A(n_54),
	.B(i_CodeWord[18]));
   XNOR2X2 g1264__9945 (.Y(o_DecodWord[0]),
	.A(n_51),
	.B(i_CodeWord[3]));
   NAND2BXL g1277__2883 (.Y(n_59),
	.AN(n_57),
	.B(n_65));
   INVXL g1279 (.Y(n_75),
	.A(n_67));
   NOR2XL g1268__2346 (.Y(n_58),
	.A(n_68),
	.B(n_57));
   NAND2BXL g1276__1666 (.Y(n_56),
	.AN(n_57),
	.B(n_70));
   NAND2XL g1280__7410 (.Y(n_71),
	.A(n_29),
	.B(n_55));
   NAND2XL g1281__6417 (.Y(n_67),
	.A(n_49),
	.B(n_55));
   NAND2XL g1286__5477 (.Y(n_54),
	.A(n_65),
	.B(n_52));
   NAND2BXL g1287__2398 (.Y(n_53),
	.AN(n_68),
	.B(n_52));
   NAND3BXL g1282__5107 (.Y(n_51),
	.AN(n_40),
	.B(n_70),
	.C(n_47));
   NAND2XL g1284__6260 (.Y(n_50),
	.A(n_49),
	.B(n_52));
   NAND2XL g1285__4319 (.Y(n_48),
	.A(n_70),
	.B(n_52));
   NAND3XL g1283__8428 (.Y(n_57),
	.A(n_46),
	.B(n_49),
	.C(n_47));
   NOR2BX1 g1288__5526 (.Y(n_55),
	.AN(n_47),
	.B(n_46));
   NOR2XL g1289__6783 (.Y(n_52),
	.A(n_42),
	.B(n_44));
   AND2X2 g1290__3680 (.Y(o_ErrorD),
	.A(n_37),
	.B(n_44));
   AND2X1 g1291__1617 (.Y(n_47),
	.A(o_ErrorC),
	.B(n_42));
   INVXL g1292 (.Y(n_44),
	.A(o_ErrorC));
   OA21X2 g1293__2802 (.Y(o_ErrorC),
	.A0(n_39),
	.A1(n_38),
	.B0(n_41));
   AOI32X1 g1294__1705 (.Y(n_41),
	.A0(n_36),
	.A1(n_40),
	.A2(n_34),
	.B0(n_39),
	.B1(n_38));
   XNOR2X1 g1295__5122 (.Y(n_38),
	.A(n_1),
	.B(n_33));
   OR3XL g1296__8246 (.Y(n_37),
	.A(n_36),
	.B(n_40),
	.C(n_35));
   NAND2BXL g1297__7098 (.Y(n_34),
	.AN(n_35),
	.B(n_46));
   XNOR2X1 g1298__6131 (.Y(n_33),
	.A(n_26),
	.B(n_30));
   NAND2XL g1299__1881 (.Y(n_35),
	.A(n_32),
	.B(n_31));
   NOR2XL g1300__5115 (.Y(n_70),
	.A(n_32),
	.B(n_31));
   NAND2XL g1302__7482 (.Y(n_68),
	.A(n_32),
	.B(n_30));
   NOR2XL g1301__4733 (.Y(n_65),
	.A(n_32),
	.B(n_30));
   INVXL g1303 (.Y(n_31),
	.A(n_30));
   XNOR2X1 g1304__6161 (.Y(n_30),
	.A(n_18),
	.B(n_28));
   NAND2XL g1305__9315 (.Y(n_40),
	.A(n_46),
	.B(n_29));
   INVXL g1308 (.Y(n_29),
	.A(n_49));
   XNOR2X1 g1306__9945 (.Y(n_28),
	.A(n_23),
	.B(n_27));
   XNOR2X1 g1307__2883 (.Y(n_32),
	.A(n_19),
	.B(n_24));
   XNOR2X1 g1309__2346 (.Y(n_46),
	.A(n_13),
	.B(n_25));
   CLKXOR2X1 g1310__1666 (.Y(n_49),
	.A(n_27),
	.B(n_26));
   INVXL g1313 (.Y(n_42),
	.A(n_36));
   XNOR2X1 g1315__7410 (.Y(n_25),
	.A(n_12),
	.B(n_22));
   XNOR2X1 g1311__6417 (.Y(n_26),
	.A(n_6),
	.B(n_20));
   XNOR2X1 g1314__5477 (.Y(n_24),
	.A(n_23),
	.B(n_22));
   XNOR2X1 g1312__2398 (.Y(n_27),
	.A(n_15),
	.B(n_21));
   CLKXOR2X1 g1316__5107 (.Y(n_36),
	.A(n_4),
	.B(n_17));
   XNOR2X1 g1318__6260 (.Y(n_21),
	.A(i_CodeWord[15]),
	.B(n_14));
   XNOR2X1 g1317__4319 (.Y(n_20),
	.A(i_CodeWord[20]),
	.B(n_10));
   XNOR2X1 g1319__8428 (.Y(n_19),
	.A(n_3),
	.B(n_5));
   XNOR2X1 g1321__5526 (.Y(n_18),
	.A(n_7),
	.B(n_0));
   XNOR2X1 g1320__6783 (.Y(n_17),
	.A(n_9),
	.B(n_16));
   XNOR2X1 g1322__3680 (.Y(n_39),
	.A(n_2),
	.B(n_16));
   XNOR2X1 g1323__1617 (.Y(n_22),
	.A(n_11),
	.B(n_8));
   XNOR2X1 g1334__2802 (.Y(n_15),
	.A(i_CodeWord[5]),
	.B(i_CodeWord[7]));
   XNOR2X1 g1331__1705 (.Y(n_14),
	.A(i_CodeWord[13]),
	.B(i_CodeWord[21]));
   XNOR2X1 g1336__5122 (.Y(n_13),
	.A(i_CodeWord[9]),
	.B(i_CodeWord[13]));
   XNOR2X1 g1337__8246 (.Y(n_12),
	.A(i_CodeWord[8]),
	.B(i_CodeWord[12]));
   XNOR2X1 g1338__7098 (.Y(n_11),
	.A(i_CodeWord[10]),
	.B(i_CodeWord[15]));
   XNOR2X1 g1340__6131 (.Y(n_10),
	.A(i_CodeWord[12]),
	.B(i_CodeWord[14]));
   XNOR2X1 g1335__1881 (.Y(n_9),
	.A(i_CodeWord[17]),
	.B(i_CodeWord[21]));
   XNOR2X1 g1339__5115 (.Y(n_8),
	.A(i_CodeWord[11]),
	.B(i_CodeWord[14]));
   XNOR2X1 g1332__7482 (.Y(n_23),
	.A(i_CodeWord[3]),
	.B(i_CodeWord[19]));
   XNOR2X1 g1329__4733 (.Y(n_7),
	.A(i_CodeWord[1]),
	.B(i_CodeWord[17]));
   XNOR2X1 g1324__6161 (.Y(n_6),
	.A(i_CodeWord[4]),
	.B(i_CodeWord[6]));
   XNOR2X1 g1325__9315 (.Y(n_5),
	.A(i_CodeWord[6]),
	.B(i_CodeWord[7]));
   XNOR2X1 g1330__9945 (.Y(n_4),
	.A(i_CodeWord[19]),
	.B(i_CodeWord[20]));
   XNOR2X1 g1326__2883 (.Y(n_3),
	.A(i_CodeWord[2]),
	.B(i_CodeWord[18]));
   XNOR2X1 g1333__2346 (.Y(n_2),
	.A(i_CodeWord[0]),
	.B(i_CodeWord[8]));
   XNOR2X1 g1327__1666 (.Y(n_1),
	.A(i_CodeWord[2]),
	.B(i_CodeWord[10]));
   XNOR2X1 g1328__7410 (.Y(n_0),
	.A(i_CodeWord[9]),
	.B(i_CodeWord[11]));
   XNOR2X1 g1341__6417 (.Y(n_16),
	.A(i_CodeWord[16]),
	.B(i_CodeWord[18]));
endmodule

