/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Mon Oct  6 17:11:10 2025
#  Design:            h_decoder_16_11
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/h_decoder_16_11/h_decoder_16_11_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 29 2025 16:43:26 -03 (Sep 29 2025 19:43:26 UTC)
// Verification Directory fv/h_decoder_16_11 
module h_decoder_16_11 (
	i_CodeWord, 
	o_DecodWord, 
	o_ErrorC, 
	o_ErrorD);
   input [15:0] i_CodeWord;
   output [10:0] o_DecodWord;
   output o_ErrorC;
   output o_ErrorD;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_28;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;

   XNOR2X2 g966__2398 (.Y(o_DecodWord[1]),
	.A(n_49),
	.B(i_CodeWord[5]));
   XNOR2X2 g970__5107 (.Y(o_DecodWord[6]),
	.A(n_33),
	.B(i_CodeWord[11]));
   XNOR2X2 g975__6260 (.Y(o_DecodWord[7]),
	.A(i_CodeWord[12]),
	.B(n_43));
   XNOR2X2 g969__4319 (.Y(o_DecodWord[10]),
	.A(n_35),
	.B(i_CodeWord[15]));
   XNOR2X2 g968__8428 (.Y(o_DecodWord[3]),
	.A(i_CodeWord[7]),
	.B(n_42));
   XNOR2X2 g971__5526 (.Y(o_DecodWord[0]),
	.A(i_CodeWord[3]),
	.B(n_37));
   XNOR2X2 g972__6783 (.Y(o_DecodWord[2]),
	.A(i_CodeWord[6]),
	.B(n_39));
   XNOR2X2 g974__3680 (.Y(o_DecodWord[4]),
	.A(i_CodeWord[9]),
	.B(n_46));
   XNOR2X2 g967__1617 (.Y(o_DecodWord[9]),
	.A(n_41),
	.B(i_CodeWord[14]));
   XNOR2X2 g973__2802 (.Y(o_DecodWord[8]),
	.A(i_CodeWord[13]),
	.B(n_48));
   NAND3XL g976__1705 (.Y(n_49),
	.A(n_23),
	.B(n_24),
	.C(n_47));
   NAND2XL g981__5122 (.Y(n_48),
	.A(n_45),
	.B(n_47));
   NAND2XL g985__8246 (.Y(n_46),
	.A(n_45),
	.B(n_36));
   XNOR2X2 g977__7098 (.Y(o_DecodWord[5]),
	.A(n_28),
	.B(i_CodeWord[10]));
   NAND2XL g986__6131 (.Y(n_43),
	.A(n_45),
	.B(n_40));
   NAND2XL g979__1881 (.Y(n_42),
	.A(n_38),
	.B(n_47));
   NAND2XL g978__5115 (.Y(n_41),
	.A(n_34),
	.B(n_40));
   NAND2XL g983__7482 (.Y(n_39),
	.A(n_38),
	.B(n_40));
   NAND2XL g982__4733 (.Y(n_37),
	.A(n_38),
	.B(n_36));
   NAND2XL g980__6161 (.Y(n_35),
	.A(n_34),
	.B(n_47));
   NAND2XL g984__9315 (.Y(n_33),
	.A(n_34),
	.B(n_36));
   NOR3XL g988__9945 (.Y(n_47),
	.A(n_32),
	.B(n_31),
	.C(n_30));
   NOR3BXL g990__2883 (.Y(n_36),
	.AN(n_32),
	.B(n_31),
	.C(n_30));
   NOR3BXL g991__2346 (.Y(n_40),
	.AN(n_31),
	.B(n_32),
	.C(n_30));
   AND2X2 g987__1666 (.Y(o_ErrorD),
	.A(n_26),
	.B(n_30));
   NAND3BXL g989__7410 (.Y(n_28),
	.AN(n_25),
	.B(n_34),
	.C(o_ErrorC));
   INVXL g992 (.Y(n_30),
	.A(o_ErrorC));
   XNOR2X2 g993__6417 (.Y(o_ErrorC),
	.A(n_14),
	.B(n_22));
   NAND3BXL g994__5477 (.Y(n_26),
	.AN(n_25),
	.B(n_24),
	.C(n_23));
   MX2X1 g995__2398 (.Y(n_22),
	.A(n_23),
	.B(n_21),
	.S0(n_16));
   NOR2XL g998__5107 (.Y(n_38),
	.A(n_21),
	.B(n_24));
   AND2X1 g999__6260 (.Y(n_45),
	.A(n_21),
	.B(n_24));
   NAND2XL g996__4319 (.Y(n_25),
	.A(n_32),
	.B(n_31));
   NOR2XL g997__8428 (.Y(n_34),
	.A(n_24),
	.B(n_23));
   INVXL g1001 (.Y(n_21),
	.A(n_23));
   XNOR2X1 g1000__5526 (.Y(n_31),
	.A(n_6),
	.B(n_20));
   XNOR2X1 g1002__6783 (.Y(n_24),
	.A(n_10),
	.B(n_19));
   XNOR2X1 g1003__3680 (.Y(n_23),
	.A(n_3),
	.B(n_17));
   XNOR2X1 g1004__1617 (.Y(n_20),
	.A(n_9),
	.B(n_18));
   XNOR2X1 g1005__2802 (.Y(n_19),
	.A(n_8),
	.B(n_18));
   XNOR2X1 g1006__1705 (.Y(n_17),
	.A(n_0),
	.B(n_15));
   XNOR2X1 g1007__5122 (.Y(n_32),
	.A(n_16),
	.B(n_15));
   XNOR2X1 g1008__8246 (.Y(n_16),
	.A(n_1),
	.B(n_2));
   XNOR2X1 g1009__7098 (.Y(n_15),
	.A(n_13),
	.B(n_11));
   XNOR2X1 g1010__6131 (.Y(n_14),
	.A(n_5),
	.B(n_4));
   XNOR2X1 g1011__1881 (.Y(n_18),
	.A(n_7),
	.B(n_12));
   XNOR2X1 g1017__5115 (.Y(n_13),
	.A(i_CodeWord[12]),
	.B(i_CodeWord[13]));
   XNOR2X1 g1013__7482 (.Y(n_12),
	.A(i_CodeWord[11]),
	.B(i_CodeWord[15]));
   XNOR2X1 g1021__4733 (.Y(n_11),
	.A(i_CodeWord[14]),
	.B(i_CodeWord[15]));
   XNOR2X1 g1014__6161 (.Y(n_10),
	.A(i_CodeWord[6]),
	.B(i_CodeWord[14]));
   XNOR2X1 g1015__9315 (.Y(n_9),
	.A(i_CodeWord[1]),
	.B(i_CodeWord[9]));
   XNOR2X1 g1016__9945 (.Y(n_8),
	.A(i_CodeWord[2]),
	.B(i_CodeWord[10]));
   XNOR2X1 g1012__2883 (.Y(n_7),
	.A(i_CodeWord[3]),
	.B(i_CodeWord[7]));
   XNOR2X1 g1024__2346 (.Y(n_6),
	.A(i_CodeWord[5]),
	.B(i_CodeWord[13]));
   XNOR2X1 g1019__1666 (.Y(n_5),
	.A(i_CodeWord[0]),
	.B(i_CodeWord[1]));
   XNOR2X1 g1025__7410 (.Y(n_4),
	.A(i_CodeWord[2]),
	.B(i_CodeWord[3]));
   XNOR2X1 g1020__6417 (.Y(n_3),
	.A(i_CodeWord[10]),
	.B(i_CodeWord[11]));
   XNOR2X1 g1022__5477 (.Y(n_2),
	.A(i_CodeWord[5]),
	.B(i_CodeWord[7]));
   XNOR2X1 g1023__2398 (.Y(n_1),
	.A(i_CodeWord[4]),
	.B(i_CodeWord[6]));
   XNOR2X1 g1018__5107 (.Y(n_0),
	.A(i_CodeWord[8]),
	.B(i_CodeWord[9]));
endmodule

