
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 29 2025 16:48:19 -03 (Sep 29 2025 19:48:19 UTC)

// Verification Directory fv/syndrome_block_se 

module syndrome_block_se(i_CodeWord, o_DecodWord, o_ErrorC, o_ErrorD);
  input [14:0] i_CodeWord;
  output [6:0] o_DecodWord;
  output o_ErrorC, o_ErrorD;
  wire [14:0] i_CodeWord;
  wire [6:0] o_DecodWord;
  wire o_ErrorC, o_ErrorD;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_63, n_64, n_65, n_66, n_68, n_72;
  wire n_75, n_76, n_77, n_85, n_86;
  AND2X2 g3191__2398(.A (n_50), .B (n_77), .Y (o_ErrorD));
  AO21X2 g3192__5107(.A0 (n_49), .A1 (n_54), .B0 (n_76), .Y (o_ErrorC));
  INVXL g3193(.A (n_76), .Y (n_77));
  NAND4XL g3194__6260(.A (n_68), .B (n_66), .C (n_72), .D (n_75), .Y
       (n_76));
  AOI221X1 g3195__4319(.A0 (n_30), .A1 (n_65), .B0 (n_56), .B1 (n_57),
       .C0 (n_61), .Y (n_75));
  XNOR2X2 g3205__8428(.A (i_CodeWord[14]), .B (n_64), .Y
       (o_DecodWord[6]));
  XNOR2X2 g3198__5526(.A (i_CodeWord[11]), .B (n_72), .Y
       (o_DecodWord[3]));
  XNOR2X2 g3200__6783(.A (i_CodeWord[10]), .B (n_60), .Y
       (o_DecodWord[2]));
  XNOR2X2 g3203__3680(.A (i_CodeWord[12]), .B (n_52), .Y
       (o_DecodWord[4]));
  XNOR2X2 g3196__1617(.A (n_68), .B (i_CodeWord[13]), .Y
       (o_DecodWord[5]));
  XNOR2X2 g3197__2802(.A (n_66), .B (i_CodeWord[9]), .Y
       (o_DecodWord[1]));
  NAND4XL g3202__1705(.A (n_38), .B (n_63), .C (n_51), .D (n_58), .Y
       (n_65));
  OR2X1 g3212__5122(.A (n_59), .B (n_63), .Y (n_64));
  CLKMX2X2 g3204__8246(.A (i_CodeWord[8]), .B (n_20), .S0 (n_61), .Y
       (o_DecodWord[0]));
  OR2X1 g3209__7098(.A (n_59), .B (n_58), .Y (n_60));
  OAI32X1 g3210__6131(.A0 (n_32), .A1 (n_53), .A2 (n_39), .B0 (n_47),
       .B1 (n_55), .Y (n_57));
  OR4X1 g3208__1881(.A (n_44), .B (n_56), .C (n_43), .D (n_55), .Y
       (n_72));
  OAI22XL g3211__5115(.A0 (n_27), .A1 (n_33), .B0 (n_56), .B1 (n_53),
       .Y (n_54));
  NAND2XL g3199__7482(.A (n_48), .B (n_45), .Y (n_68));
  OR2X1 g3213__4733(.A (n_59), .B (n_51), .Y (n_52));
  OAI211X1 g3214__6161(.A0 (n_56), .A1 (n_37), .B0 (n_40), .C0 (n_49),
       .Y (n_50));
  NAND2XL g3201__9315(.A (n_48), .B (n_42), .Y (n_66));
  NAND4XL g3215__9945(.A (n_25), .B (n_48), .C (n_24), .D (n_46), .Y
       (n_58));
  NAND3BXL g3217__2883(.AN (n_47), .B (n_35), .C (n_46), .Y (n_63));
  NOR4X1 g3206__2346(.A (n_44), .B (n_43), .C (n_41), .D (n_59), .Y
       (n_45));
  NOR4X1 g3207__1666(.A (n_56), .B (n_36), .C (n_34), .D (n_41), .Y
       (n_42));
  NOR4X1 g3216__7410(.A (n_56), .B (n_31), .C (n_40), .D (n_39), .Y
       (n_61));
  NAND3BXL g3219__6417(.AN (n_47), .B (n_48), .C (n_37), .Y (n_38));
  NAND3BXL g3218__5477(.AN (n_36), .B (n_35), .C (n_37), .Y (n_51));
  NAND3BXL g3220__2398(.AN (n_53), .B (n_35), .C (n_34), .Y (n_55));
  NOR2XL g3221__5107(.A (n_47), .B (n_39), .Y (n_49));
  OA21X1 g3222__6260(.A0 (n_29), .A1 (n_28), .B0 (n_41), .Y (n_33));
  AND2X1 g3229__4319(.A (n_31), .B (n_26), .Y (n_32));
  INVXL g3223(.A (n_40), .Y (n_46));
  INVXL g3228(.A (n_59), .Y (n_30));
  INVXL g3224(.A (n_37), .Y (n_53));
  NAND2XL g3225__8428(.A (n_48), .B (n_34), .Y (n_39));
  NAND2BXL g3226__5526(.AN (n_29), .B (n_28), .Y (n_40));
  NOR2BX1 g3227__6783(.AN (n_29), .B (n_28), .Y (n_37));
  NAND2BXL g3232__3680(.AN (n_43), .B (n_44), .Y (n_31));
  NAND2XL g3230__1617(.A (n_29), .B (n_28), .Y (n_41));
  OR2X1 g3231__2802(.A (n_27), .B (n_34), .Y (n_59));
  NAND3BXL g3237__1705(.AN (n_25), .B (n_18), .C (n_24), .Y (n_26));
  NAND3BXL g3233__5122(.AN (n_24), .B (n_23), .C (n_44), .Y (n_36));
  NAND2XL g3236__8246(.A (n_86), .B (n_24), .Y (n_47));
  OR2X1 g3238__7098(.A (n_23), .B (n_24), .Y (n_43));
  XNOR2X1 g3235__6131(.A (i_CodeWord[6]), .B (n_21), .Y (n_28));
  XNOR2X1 g3234__1881(.A (i_CodeWord[12]), .B (n_22), .Y (n_34));
  XNOR2X1 g3241__5115(.A (n_2), .B (n_16), .Y (n_24));
  XNOR2X1 g3239__7482(.A (i_CodeWord[5]), .B (n_19), .Y (n_22));
  XNOR2X1 g3240__4733(.A (n_20), .B (n_19), .Y (n_21));
  INVXL g3242(.A (n_56), .Y (n_27));
  INVXL g3250(.A (n_86), .Y (n_18));
  XNOR2X1 g3243__6161(.A (i_CodeWord[12]), .B (n_15), .Y (n_16));
  XNOR2X1 g3244__9315(.A (i_CodeWord[0]), .B (n_15), .Y (n_56));
  INVXL g3245(.A (n_48), .Y (n_35));
  XNOR2X1 g3246__2883(.A (i_CodeWord[13]), .B (n_12), .Y (n_19));
  XNOR2X1 g3247__2346(.A (i_CodeWord[8]), .B (n_13), .Y (n_29));
  NOR2BX1 g3249__1666(.AN (n_23), .B (n_44), .Y (n_25));
  XNOR2X1 g3248__7410(.A (i_CodeWord[11]), .B (n_10), .Y (n_48));
  XNOR2X1 g3257__6417(.A (n_85), .B (n_4), .Y (n_23));
  XNOR2X1 g3256__5477(.A (n_6), .B (i_CodeWord[9]), .Y (n_15));
  XNOR2X1 g3258__2398(.A (n_8), .B (n_3), .Y (n_44));
  XNOR2X1 g3252__5107(.A (i_CodeWord[7]), .B (n_11), .Y (n_13));
  XNOR2X1 g3253__6260(.A (i_CodeWord[9]), .B (n_11), .Y (n_12));
  XNOR2X1 g3254__4319(.A (i_CodeWord[12]), .B (n_1), .Y (n_10));
  AOI22XL g3263__5526(.A0 (i_CodeWord[11]), .A1 (n_7), .B0
       (i_CodeWord[10]), .B1 (n_5), .Y (n_8));
  AOI22XL g3265__6783(.A0 (i_CodeWord[11]), .A1 (n_20), .B0
       (i_CodeWord[8]), .B1 (n_5), .Y (n_6));
  XNOR2X1 g3259__3680(.A (i_CodeWord[1]), .B (i_CodeWord[12]), .Y
       (n_4));
  XNOR2X1 g3261__1617(.A (i_CodeWord[2]), .B (i_CodeWord[13]), .Y
       (n_3));
  XNOR2X1 g3260__2802(.A (i_CodeWord[4]), .B (i_CodeWord[13]), .Y
       (n_2));
  XNOR2X1 g3264__1705(.A (i_CodeWord[3]), .B (i_CodeWord[14]), .Y
       (n_1));
  XNOR2X1 g3266__5122(.A (i_CodeWord[10]), .B (i_CodeWord[14]), .Y
       (n_11));
  INVXL g3268(.A (i_CodeWord[10]), .Y (n_7));
  INVXL g3269(.A (i_CodeWord[8]), .Y (n_20));
  INVXL g3270(.A (i_CodeWord[11]), .Y (n_5));
  MXI2XL g2(.A (n_7), .B (i_CodeWord[10]), .S0 (i_CodeWord[9]), .Y
       (n_85));
  NOR2BX1 g3271(.AN (n_44), .B (n_23), .Y (n_86));
endmodule

