
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  4 2025 14:30:41 -03 (Sep  4 2025 17:30:41 UTC)

// Verification Directory fv/syndrome_block_se 

module syndrome_block_se(i_CodeWord, o_Syndrome, o_DecodWord,
     o_ErrorFlag);
  input [14:0] i_CodeWord;
  output [7:0] o_Syndrome;
  output [6:0] o_DecodWord;
  output o_ErrorFlag;
  wire [14:0] i_CodeWord;
  wire [7:0] o_Syndrome;
  wire [6:0] o_DecodWord;
  wire o_ErrorFlag;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_29, n_30, n_31, n_33, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_46, n_48, n_50, n_54, n_55, n_57, n_58, n_59;
  wire n_62, n_64, n_66, n_74;
  AO22X2 g2140__2398(.A0 (i_CodeWord[8]), .A1 (n_66), .B0
       (o_Syndrome[7]), .B1 (n_36), .Y (o_DecodWord[0]));
  NAND2XL g2141__5107(.A (n_40), .B (n_64), .Y (n_66));
  AND2X2 g2142__6260(.A (n_35), .B (n_64), .Y (o_ErrorFlag));
  CLKMX2X2 g2146__4319(.A (i_CodeWord[10]), .B (n_13), .S0 (n_62), .Y
       (o_DecodWord[2]));
  NOR4X1 g2143__8428(.A (n_50), .B (n_58), .C (n_59), .D (n_62), .Y
       (n_64));
  XNOR2X2 g2151__5526(.A (n_57), .B (i_CodeWord[14]), .Y
       (o_DecodWord[6]));
  CLKMX2X2 g2145__6783(.A (i_CodeWord[12]), .B (n_11), .S0 (n_59), .Y
       (o_DecodWord[4]));
  NAND4XL g2144__3680(.A (n_48), .B (n_42), .C (n_55), .D (n_57), .Y
       (n_58));
  NOR2XL g2149__1617(.A (n_43), .B (n_54), .Y (n_62));
  XNOR2X2 g2148__2802(.A (n_55), .B (i_CodeWord[13]), .Y
       (o_DecodWord[5]));
  OR4X1 g2153__1705(.A (o_Syndrome[3]), .B (o_Syndrome[2]), .C (n_46),
       .D (n_44), .Y (n_54));
  CLKMX2X2 g2150__5122(.A (i_CodeWord[11]), .B (n_9), .S0 (n_50), .Y
       (o_DecodWord[3]));
  XNOR2X2 g2147__8246(.A (n_48), .B (i_CodeWord[9]), .Y
       (o_DecodWord[1]));
  NOR4X1 g2152__7098(.A (o_Syndrome[1]), .B (n_46), .C (o_Syndrome[6]),
       .D (n_38), .Y (n_59));
  NAND3BXL g2157__6131(.AN (n_44), .B (n_43), .C (n_24), .Y (n_57));
  NAND4XL g2159__1881(.A (o_Syndrome[1]), .B (n_29), .C (n_41), .D
       (n_39), .Y (n_55));
  AOI32X1 g2154__5115(.A0 (n_43), .A1 (n_41), .A2 (n_37), .B0 (n_31),
       .B1 (n_40), .Y (n_42));
  NAND2XL g2163__7482(.A (o_Syndrome[6]), .B (n_39), .Y (n_44));
  NAND4XL g2162__4733(.A (o_Syndrome[2]), .B (o_Syndrome[3]), .C
       (n_30), .D (n_33), .Y (n_38));
  NOR3BXL g2158__6161(.AN (n_37), .B (n_43), .C (n_23), .Y (n_50));
  NOR2XL g2155__9315(.A (i_CodeWord[8]), .B (n_35), .Y (n_36));
  NAND4XL g2156__9945(.A (o_Syndrome[7]), .B (o_Syndrome[0]), .C
       (o_Syndrome[6]), .D (n_27), .Y (n_48));
  AND2X1 g2166__2883(.A (n_33), .B (o_Syndrome[5]), .Y (n_39));
  INVXL g2160(.A (n_40), .Y (n_35));
  NOR4X1 g2164__2346(.A (n_31), .B (n_30), .C (n_29), .D
       (o_Syndrome[4]), .Y (n_37));
  NOR4X1 g2161__1666(.A (o_Syndrome[0]), .B (o_Syndrome[6]), .C
       (o_Syndrome[4]), .D (n_26), .Y (n_40));
  NOR2XL g2165__7410(.A (n_25), .B (n_26), .Y (n_27));
  NOR2XL g2167__6417(.A (o_Syndrome[7]), .B (n_25), .Y (n_33));
  INVXL g2169(.A (o_Syndrome[4]), .Y (n_25));
  INVXL g2172(.A (n_23), .Y (n_24));
  NOR3XL g2171__5477(.A (o_Syndrome[2]), .B (n_22), .C (o_Syndrome[0]),
       .Y (n_41));
  OR4X1 g2168__2398(.A (o_Syndrome[3]), .B (o_Syndrome[2]), .C
       (o_Syndrome[1]), .D (o_Syndrome[5]), .Y (n_26));
  XNOR2X2 g2170__5107(.A (n_12), .B (n_21), .Y (o_Syndrome[4]));
  NAND3BXL g2173__6260(.AN (o_Syndrome[0]), .B (n_22), .C
       (o_Syndrome[2]), .Y (n_23));
  INVXL g2174(.A (o_Syndrome[6]), .Y (n_29));
  INVXL g2175(.A (o_Syndrome[0]), .Y (n_46));
  INVXL g2178(.A (o_Syndrome[5]), .Y (n_30));
  XNOR2X2 g2176__4319(.A (n_19), .B (n_2), .Y (o_Syndrome[6]));
  XNOR2X2 g2177__8428(.A (n_20), .B (i_CodeWord[0]), .Y
       (o_Syndrome[0]));
  CLKXOR2X1 g2179__5526(.A (i_CodeWord[4]), .B (n_20), .Y (n_21));
  XNOR2X2 g2180__6783(.A (n_4), .B (n_19), .Y (o_Syndrome[5]));
  INVXL g2181(.A (o_Syndrome[1]), .Y (n_43));
  INVXL g2185(.A (o_Syndrome[7]), .Y (n_31));
  INVXL g2186(.A (o_Syndrome[3]), .Y (n_22));
  XNOR2X1 g2182__3680(.A (n_10), .B (i_CodeWord[8]), .Y (n_20));
  XNOR2X2 g2184__1617(.A (n_6), .B (n_3), .Y (o_Syndrome[1]));
  XNOR2X2 g2183__2802(.A (n_15), .B (n_1), .Y (o_Syndrome[2]));
  XNOR2X1 g2187__1705(.A (n_17), .B (n_18), .Y (n_19));
  XNOR2X2 g2189__5122(.A (n_5), .B (n_7), .Y (o_Syndrome[3]));
  XNOR2X2 g2188__8246(.A (n_18), .B (n_74), .Y (o_Syndrome[7]));
  OAI22XL g2201__7098(.A0 (i_CodeWord[9]), .A1 (n_14), .B0
       (i_CodeWord[13]), .B1 (n_8), .Y (n_17));
  OAI22XL g2200__1881(.A0 (i_CodeWord[10]), .A1 (n_14), .B0
       (i_CodeWord[13]), .B1 (n_13), .Y (n_15));
  OAI22XL g2198__5115(.A0 (i_CodeWord[12]), .A1 (n_14), .B0
       (i_CodeWord[13]), .B1 (n_11), .Y (n_12));
  OAI22XL g2196__7482(.A0 (i_CodeWord[9]), .A1 (n_9), .B0
       (i_CodeWord[11]), .B1 (n_8), .Y (n_10));
  XNOR2X1 g2190__4733(.A (i_CodeWord[14]), .B (n_11), .Y (n_7));
  OAI22XL g2199__6161(.A0 (i_CodeWord[10]), .A1 (n_11), .B0
       (i_CodeWord[12]), .B1 (n_13), .Y (n_6));
  XNOR2X1 g2202__9315(.A (i_CodeWord[3]), .B (i_CodeWord[11]), .Y
       (n_5));
  XNOR2X1 g2191__9945(.A (i_CodeWord[5]), .B (i_CodeWord[12]), .Y
       (n_4));
  XNOR2X1 g2192__2883(.A (i_CodeWord[1]), .B (i_CodeWord[9]), .Y (n_3));
  XNOR2X1 g2193__2346(.A (i_CodeWord[6]), .B (i_CodeWord[8]), .Y (n_2));
  XNOR2X1 g2194__1666(.A (i_CodeWord[2]), .B (i_CodeWord[11]), .Y
       (n_1));
  XNOR2X1 g2195__7410(.A (i_CodeWord[10]), .B (i_CodeWord[14]), .Y
       (n_18));
  INVXL g2205(.A (i_CodeWord[9]), .Y (n_8));
  INVXL g2208(.A (i_CodeWord[12]), .Y (n_11));
  INVXL g2203(.A (i_CodeWord[11]), .Y (n_9));
  INVXL g2204(.A (i_CodeWord[13]), .Y (n_14));
  INVXL g2207(.A (i_CodeWord[10]), .Y (n_13));
  XOR2XL g2(.A (i_CodeWord[8]), .B (i_CodeWord[7]), .Y (n_74));
endmodule

