
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  5 2025 16:03:51 -03 (Sep  5 2025 19:03:51 UTC)

// Verification Directory fv/syndrome_block_se 

module syndrome_block_se(i_CodeWord, o_Syndrome, o_DecodWord, o_ErrorC,
     o_ErrorD);
  input [14:0] i_CodeWord;
  output [7:0] o_Syndrome;
  output [6:0] o_DecodWord;
  output o_ErrorC, o_ErrorD;
  wire [14:0] i_CodeWord;
  wire [7:0] o_Syndrome;
  wire [6:0] o_DecodWord;
  wire o_ErrorC, o_ErrorD;
  wire n_3, n_4, n_5, n_6, n_7, n_10, n_12, n_13;
  wire n_14, n_16, n_17, n_18, n_19, n_20, n_23, n_24;
  wire n_25, n_26, n_27, n_29, n_30, n_31, n_32, n_34;
  wire n_35, n_37, n_39, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_64;
  wire n_65, n_67, n_69, n_71, n_74, n_77, n_79, n_80;
  wire n_81, n_82, n_91, n_92, n_93, n_94;
  OR2X2 g3426__2398(.A (n_61), .B (n_82), .Y (o_ErrorC));
  AND2X2 g3425__5107(.A (n_60), .B (n_81), .Y (o_ErrorD));
  INVXL g3427(.A (n_81), .Y (n_82));
  NOR4X1 g3428__6260(.A (n_55), .B (n_67), .C (n_74), .D (n_80), .Y
       (n_81));
  NAND4XL g3429__4319(.A (n_65), .B (n_71), .C (n_69), .D (n_79), .Y
       (n_80));
  AOI32X1 g3432__8428(.A0 (n_57), .A1 (n_46), .A2 (n_32), .B0 (n_56),
       .B1 (n_77), .Y (n_79));
  XNOR2X2 g3434__5526(.A (n_64), .B (i_CodeWord[10]), .Y
       (o_DecodWord[2]));
  OAI21XL g3436__6783(.A0 (o_Syndrome[3]), .A1 (n_59), .B0 (n_52), .Y
       (n_77));
  CLKMX2X2 g3430__3680(.A (i_CodeWord[9]), .B (n_17), .S0 (n_74), .Y
       (o_DecodWord[1]));
  XNOR2X2 g3442__1617(.A (n_53), .B (i_CodeWord[14]), .Y
       (o_DecodWord[6]));
  XNOR2X2 g3438__2802(.A (n_71), .B (i_CodeWord[12]), .Y
       (o_DecodWord[4]));
  XNOR2X2 g3435__1705(.A (n_69), .B (i_CodeWord[11]), .Y
       (o_DecodWord[3]));
  CLKMX2X2 g3431__5122(.A (i_CodeWord[13]), .B (n_10), .S0 (n_67), .Y
       (o_DecodWord[5]));
  XNOR2X2 g3439__8246(.A (i_CodeWord[8]), .B (n_65), .Y
       (o_DecodWord[0]));
  NAND4XL g3441__7098(.A (o_Syndrome[1]), .B (n_58), .C
       (o_Syndrome[5]), .D (n_48), .Y (n_64));
  NOR2XL g3444__6131(.A (n_25), .B (n_60), .Y (n_61));
  AOI31X1 g3447__1881(.A0 (o_Syndrome[1]), .A1 (n_58), .A2 (n_47), .B0
       (n_49), .Y (n_59));
  NOR4X1 g3433__5115(.A (o_Syndrome[3]), .B (n_58), .C (n_57), .D
       (n_44), .Y (n_74));
  OR2X1 g3445__7482(.A (o_Syndrome[5]), .B (n_42), .Y (n_65));
  NOR4X1 g3437__4733(.A (n_54), .B (n_58), .C (n_57), .D (n_35), .Y
       (n_67));
  NAND3BXL g3448__6161(.AN (n_43), .B (n_56), .C (n_50), .Y (n_71));
  NOR4X1 g3440__9315(.A (n_54), .B (o_Syndrome[5]), .C (n_45), .D
       (n_39), .Y (n_55));
  NAND2BXL g3450__9945(.AN (n_52), .B (n_56), .Y (n_53));
  NAND4XL g3443__2883(.A (o_Syndrome[0]), .B (n_34), .C (n_57), .D
       (n_50), .Y (n_69));
  NAND3BXL g3452__2346(.AN (o_Syndrome[3]), .B (n_57), .C (n_49), .Y
       (n_60));
  NOR2BX1 g3453__1666(.AN (n_47), .B (n_54), .Y (n_48));
  OAI32X1 g3459__7410(.A0 (n_41), .A1 (o_Syndrome[0]), .A2 (n_45), .B0
       (n_54), .B1 (n_30), .Y (n_46));
  NAND3BXL g3446__6417(.AN (n_43), .B (o_Syndrome[0]), .C (n_37), .Y
       (n_44));
  NAND4XL g3451__5477(.A (n_41), .B (o_Syndrome[0]), .C (n_29), .D
       (n_93), .Y (n_42));
  NAND3BXL g3455__2398(.AN (n_45), .B (o_Syndrome[3]), .C (n_93), .Y
       (n_52));
  AOI21XL g3458__5107(.A0 (o_Syndrome[7]), .A1 (n_31), .B0 (n_37), .Y
       (n_39));
  AND2X1 g3456__6260(.A (n_93), .B (o_Syndrome[2]), .Y (n_47));
  NAND2XL g3449__4319(.A (n_34), .B (n_37), .Y (n_35));
  AND3XL g3454__8428(.A (o_Syndrome[3]), .B (o_Syndrome[4]), .C (n_32),
       .Y (n_50));
  NOR2BX1 g3457__5526(.AN (n_32), .B (n_45), .Y (n_49));
  AOI21XL g3463__3680(.A0 (n_58), .A1 (n_27), .B0 (n_29), .Y (n_30));
  NOR2XL g3462__1617(.A (o_Syndrome[7]), .B (n_31), .Y (n_37));
  NOR2XL g3461__2802(.A (o_Syndrome[7]), .B (o_Syndrome[6]), .Y (n_32));
  INVXL g3464(.A (o_Syndrome[6]), .Y (n_31));
  NOR2XL g3466__1705(.A (n_26), .B (n_58), .Y (n_29));
  XNOR2X2 g3465__5122(.A (i_CodeWord[6]), .B (n_24), .Y
       (o_Syndrome[6]));
  NOR2XL g3467__8246(.A (o_Syndrome[0]), .B (n_57), .Y (n_56));
  NAND2BXL g3469__7098(.AN (n_34), .B (n_43), .Y (n_27));
  OR2X1 g3468__6131(.A (n_26), .B (o_Syndrome[4]), .Y (n_45));
  INVXL g3471(.A (o_Syndrome[4]), .Y (n_58));
  XNOR2X2 g3473__1881(.A (i_CodeWord[12]), .B (n_19), .Y
       (o_Syndrome[4]));
  INVXL g3472(.A (o_Syndrome[5]), .Y (n_57));
  NOR2XL g3477__5115(.A (o_Syndrome[1]), .B (n_20), .Y (n_34));
  NAND2XL g3478__7482(.A (o_Syndrome[1]), .B (n_20), .Y (n_43));
  NAND2XL g3476__4733(.A (n_41), .B (n_25), .Y (n_54));
  XNOR2X1 g3470__6161(.A (i_CodeWord[8]), .B (n_23), .Y (n_24));
  OR2X1 g3475__9315(.A (o_Syndrome[1]), .B (o_Syndrome[2]), .Y (n_26));
  XNOR2X2 g3474__9945(.A (n_23), .B (n_6), .Y (o_Syndrome[5]));
  INVXL g3479(.A (o_Syndrome[0]), .Y (n_25));
  INVXL g3485(.A (o_Syndrome[2]), .Y (n_20));
  XNOR2X1 g3481__2883(.A (n_3), .B (n_18), .Y (n_19));
  XNOR2X2 g3489__2346(.A (i_CodeWord[2]), .B (n_16), .Y
       (o_Syndrome[2]));
  INVXL g3480(.A (o_Syndrome[3]), .Y (n_41));
  XNOR2X2 g3488__1666(.A (i_CodeWord[7]), .B (n_94), .Y
       (o_Syndrome[7]));
  XNOR2X2 g3482__7410(.A (i_CodeWord[0]), .B (n_18), .Y
       (o_Syndrome[0]));
  XNOR2X2 g3490__6417(.A (n_17), .B (n_12), .Y (o_Syndrome[1]));
  XNOR2X1 g3487__5477(.A (n_17), .B (n_14), .Y (n_23));
  XNOR2X1 g3495__5107(.A (n_91), .B (i_CodeWord[11]), .Y (n_16));
  XNOR2X1 g3496__4319(.A (n_92), .B (i_CodeWord[11]), .Y (n_18));
  XNOR2X1 g3492__8428(.A (i_CodeWord[13]), .B (n_7), .Y (n_14));
  XNOR2X1 g3493__5526(.A (i_CodeWord[11]), .B (n_4), .Y (n_13));
  XNOR2X1 g3494__6783(.A (i_CodeWord[10]), .B (n_5), .Y (n_12));
  XNOR2X1 g3498__2802(.A (i_CodeWord[5]), .B (i_CodeWord[12]), .Y
       (n_6));
  XNOR2X1 g3499__1705(.A (i_CodeWord[1]), .B (i_CodeWord[12]), .Y
       (n_5));
  XNOR2X1 g3501__5122(.A (i_CodeWord[3]), .B (i_CodeWord[14]), .Y
       (n_4));
  XNOR2X1 g3502__8246(.A (i_CodeWord[4]), .B (i_CodeWord[13]), .Y
       (n_3));
  XNOR2X1 g3504__7098(.A (i_CodeWord[10]), .B (i_CodeWord[14]), .Y
       (n_7));
  INVXL g3505(.A (i_CodeWord[13]), .Y (n_10));
  INVXL g3507(.A (i_CodeWord[9]), .Y (n_17));
  XOR2X2 g2(.A (i_CodeWord[12]), .B (n_13), .Y (o_Syndrome[3]));
  MXI2XL g3510(.A (n_10), .B (i_CodeWord[13]), .S0 (i_CodeWord[10]), .Y
       (n_91));
  MXI2XL g3511(.A (n_17), .B (i_CodeWord[9]), .S0 (i_CodeWord[8]), .Y
       (n_92));
  NOR2BX1 g3512(.AN (o_Syndrome[7]), .B (n_31), .Y (n_93));
  XOR2XL g3513(.A (i_CodeWord[8]), .B (n_7), .Y (n_94));
endmodule

