/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Oct  9 11:02:51 2025
#  Design:            bch_bm_block
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bch_bm_block/bch_bm_block_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 25 2025 17:37:47 -03 (Sep 25 2025 20:37:47 UTC)
// Verification Directory fv/bch_bm_block 
module gf_divider (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;

   NAND3BXL g2084__2398 (.Y(q[2]),
	.AN(n_78),
	.B(n_74),
	.C(n_77));
   OAI211X1 g2085__5107 (.Y(q[0]),
	.A0(n_70),
	.A1(n_71),
	.B0(n_76),
	.C0(n_77));
   OAI211X1 g2086__6260 (.Y(q[1]),
	.A0(n_67),
	.A1(n_71),
	.B0(n_72),
	.C0(n_74));
   OAI211X1 g2087__4319 (.Y(q[3]),
	.A0(n_69),
	.A1(n_68),
	.B0(n_75),
	.C0(n_77));
   OAI221X1 g2088__8428 (.Y(n_78),
	.A0(n_66),
	.A1(n_69),
	.B0(n_61),
	.B1(n_71),
	.C0(n_73));
   NAND3XL g2089__5526 (.Y(n_76),
	.A(n_29),
	.B(n_54),
	.C(n_70));
   NAND3BXL g2090__6783 (.Y(n_75),
	.AN(n_70),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2091__3680 (.Y(n_77),
	.AN(n_69),
	.B(n_62),
	.C(n_65));
   NAND3BXL g2092__1617 (.Y(n_73),
	.AN(n_70),
	.B(n_29),
	.C(n_54));
   NAND3BXL g2093__2802 (.Y(n_72),
	.AN(n_68),
	.B(n_29),
	.C(n_62));
   NAND3BXL g2094__1705 (.Y(n_74),
	.AN(n_69),
	.B(n_61),
	.C(n_64));
   NAND3BXL g2095__5122 (.Y(n_71),
	.AN(n_54),
	.B(n_29),
	.C(n_65));
   OR2X1 g2096__8246 (.Y(n_70),
	.A(n_62),
	.B(n_67));
   NAND2XL g2097__7098 (.Y(n_69),
	.A(n_29),
	.B(n_67));
   XNOR2X1 g2098__6131 (.Y(n_68),
	.A(n_54),
	.B(n_64));
   XNOR2X1 g2099__1881 (.Y(n_67),
	.A(n_59),
	.B(n_63));
   NAND2XL g2100__5115 (.Y(n_66),
	.A(n_54),
	.B(n_64));
   INVX1 g2101 (.Y(n_64),
	.A(n_65));
   ADDFX1 g2102__7482 (.CO(n_63),
	.S(n_65),
	.A(n_55),
	.B(n_52),
	.CI(n_60));
   INVX1 g2103 (.Y(n_62),
	.A(n_61));
   ADDFX1 g2104__4733 (.CO(n_60),
	.S(n_61),
	.A(n_37),
	.B(n_51),
	.CI(n_53));
   XNOR2X1 g2105__6161 (.Y(n_59),
	.A(n_57),
	.B(n_58));
   XNOR2X1 g2106__9315 (.Y(n_58),
	.A(n_27),
	.B(n_56));
   OAI21XL g2107__9945 (.Y(n_57),
	.A0(n_45),
	.A1(n_50),
	.B0(n_44));
   XNOR2X1 g2108__2883 (.Y(n_56),
	.A(n_26),
	.B(n_50));
   OAI21XL g2109__2346 (.Y(n_55),
	.A0(n_40),
	.A1(n_50),
	.B0(n_42));
   XNOR2X1 g2110__1666 (.Y(n_53),
	.A(n_43),
	.B(n_50));
   XNOR2X1 g2111__7410 (.Y(n_52),
	.A(n_46),
	.B(n_50));
   XNOR2X1 g2112__6417 (.Y(n_54),
	.A(n_39),
	.B(n_50));
   NOR2XL g2113__5477 (.Y(n_51),
	.A(n_39),
	.B(n_50));
   OAI22XL g2114__2398 (.Y(n_50),
	.A0(n_35),
	.A1(n_49),
	.B0(n_26),
	.B1(n_28));
   OA21X1 g2115__5107 (.Y(n_49),
	.A0(n_45),
	.A1(n_48),
	.B0(n_44));
   NOR2BX1 g2116__6260 (.Y(n_48),
	.AN(n_42),
	.B(n_47));
   NOR2BX1 g2117__4319 (.Y(n_47),
	.AN(n_37),
	.B(n_40));
   XNOR2X1 g2118__8428 (.Y(n_46),
	.A(n_41),
	.B(n_38));
   NOR2BX1 g2119__5526 (.Y(n_45),
	.AN(n_41),
	.B(n_38));
   NAND2BXL g2120__6783 (.Y(n_44),
	.AN(n_41),
	.B(n_38));
   XNOR2X1 g2121__3680 (.Y(n_43),
	.A(n_36),
	.B(n_34));
   NAND2BXL g2122__1617 (.Y(n_42),
	.AN(n_36),
	.B(n_34));
   NAND2XL g2123__2802 (.Y(n_41),
	.A(n_7),
	.B(n_33));
   NOR2BX1 g2124__1705 (.Y(n_40),
	.AN(n_36),
	.B(n_34));
   OA21X1 g2125__5122 (.Y(n_39),
	.A0(n_31),
	.A1(n_30),
	.B0(n_37));
   NAND2XL g2126__8246 (.Y(n_38),
	.A(n_9),
	.B(n_32));
   AND2X1 g2127__7098 (.Y(n_35),
	.A(n_28),
	.B(n_26));
   NAND2XL g2128__6131 (.Y(n_37),
	.A(n_31),
	.B(n_30));
   OAI211X1 g2129__1881 (.Y(n_36),
	.A0(n_3),
	.A1(n_20),
	.B0(n_16),
	.C0(n_23));
   AOI31X1 g2130__5115 (.Y(n_33),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_1),
	.B0(n_25));
   AOI31X1 g2131__7482 (.Y(n_32),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_0),
	.B0(n_24));
   OAI222XL g2132__4733 (.Y(n_34),
	.A0(a[0]),
	.A1(n_21),
	.B0(n_4),
	.B1(n_19),
	.C0(n_9),
	.C1(a[2]));
   OAI222XL g2133__6161 (.Y(n_31),
	.A0(b[0]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_12),
	.C0(b[2]),
	.C1(n_14));
   AOI221X1 g2134__9315 (.Y(n_30),
	.A0(n_18),
	.A1(n_0),
	.B0(n_4),
	.B1(n_10),
	.C0(n_22));
   AOI33XL g2135__9945 (.Y(n_29),
	.A0(n_2),
	.A1(n_1),
	.A2(n_15),
	.B0(n_13),
	.B1(n_4),
	.B2(n_0));
   INVXL g2136 (.Y(n_28),
	.A(n_27));
   OAI22XL g2137__2883 (.Y(n_25),
	.A0(b[0]),
	.A1(n_20),
	.B0(n_2),
	.B1(n_12));
   OAI22XL g2138__2346 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2139__1666 (.Y(n_27),
	.A0(n_4),
	.A1(n_0),
	.B0(a[1]),
	.B1(n_9),
	.C0(a[0]),
	.C1(n_17));
   OAI222XL g2140__7410 (.Y(n_26),
	.A0(b[1]),
	.A1(n_7),
	.B0(n_1),
	.B1(n_3),
	.C0(b[0]),
	.C1(n_14));
   AOI32X1 g2141__6417 (.Y(n_23),
	.A0(b[3]),
	.A1(b[2]),
	.A2(n_3),
	.B0(n_1),
	.B1(n_8));
   NOR2XL g2142__5477 (.Y(n_22),
	.A(n_9),
	.B(n_10));
   AOI21XL g2143__2398 (.Y(n_21),
	.A0(a[3]),
	.A1(a[2]),
	.B0(n_5));
   NAND3XL g2144__5107 (.Y(n_20),
	.A(b[1]),
	.B(b[2]),
	.C(n_2));
   NAND3BXL g2145__6260 (.Y(n_19),
	.AN(n_0),
	.B(n_6),
	.C(a[1]));
   INVXL g2146 (.Y(n_18),
	.A(n_17));
   INVXL g2147 (.Y(n_16),
	.A(n_15));
   NOR2XL g2148__4319 (.Y(n_13),
	.A(a[3]),
	.B(a[1]));
   NAND2XL g2149__8428 (.Y(n_17),
	.A(a[3]),
	.B(a[1]));
   NOR2XL g2150__5526 (.Y(n_15),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2151__6783 (.Y(n_14),
	.A(b[1]),
	.B(b[3]));
   INVXL g2152 (.Y(n_12),
	.A(n_11));
   INVXL g2153 (.Y(n_8),
	.A(n_7));
   NOR2XL g2154__3680 (.Y(n_11),
	.A(b[1]),
	.B(n_1));
   NAND2XL g2155__1617 (.Y(n_10),
	.A(n_5),
	.B(a[2]));
   NAND2XL g2156__2802 (.Y(n_9),
	.A(a[3]),
	.B(a[0]));
   NAND2XL g2157__1705 (.Y(n_7),
	.A(b[0]),
	.B(b[3]));
   INVXL g2158 (.Y(n_6),
	.A(a[3]));
   INVXL g2159 (.Y(n_5),
	.A(a[1]));
   INVX1 g2160 (.Y(n_4),
	.A(a[0]));
   INVX1 g2161 (.Y(n_3),
	.A(b[0]));
   INVX1 g2162 (.Y(n_2),
	.A(b[3]));
   INVX1 g2163 (.Y(n_1),
	.A(b[2]));
   INVX1 g2164 (.Y(n_0),
	.A(a[2]));
endmodule

module gf_divider_21 (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;

   NAND3BXL g2084__5122 (.Y(q[2]),
	.AN(n_78),
	.B(n_74),
	.C(n_77));
   OAI211X1 g2085__8246 (.Y(q[0]),
	.A0(n_70),
	.A1(n_71),
	.B0(n_76),
	.C0(n_77));
   OAI211X1 g2086__7098 (.Y(q[1]),
	.A0(n_67),
	.A1(n_71),
	.B0(n_74),
	.C0(n_72));
   OAI211X1 g2087__6131 (.Y(q[3]),
	.A0(n_69),
	.A1(n_68),
	.B0(n_75),
	.C0(n_77));
   OAI221X1 g2088__1881 (.Y(n_78),
	.A0(n_66),
	.A1(n_69),
	.B0(n_61),
	.B1(n_71),
	.C0(n_73));
   NAND3XL g2089__5115 (.Y(n_76),
	.A(n_29),
	.B(n_54),
	.C(n_70));
   NAND3BXL g2090__7482 (.Y(n_75),
	.AN(n_70),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2091__4733 (.Y(n_77),
	.AN(n_69),
	.B(n_62),
	.C(n_65));
   NAND3BXL g2092__6161 (.Y(n_73),
	.AN(n_70),
	.B(n_29),
	.C(n_54));
   NAND3BXL g2093__9315 (.Y(n_72),
	.AN(n_68),
	.B(n_29),
	.C(n_62));
   NAND3BXL g2094__9945 (.Y(n_74),
	.AN(n_69),
	.B(n_61),
	.C(n_64));
   NAND3BXL g2095__2883 (.Y(n_71),
	.AN(n_54),
	.B(n_29),
	.C(n_65));
   OR2X1 g2096__2346 (.Y(n_70),
	.A(n_62),
	.B(n_67));
   NAND2XL g2097__1666 (.Y(n_69),
	.A(n_29),
	.B(n_67));
   XNOR2X1 g2098__7410 (.Y(n_68),
	.A(n_54),
	.B(n_64));
   XNOR2X1 g2099__6417 (.Y(n_67),
	.A(n_59),
	.B(n_63));
   NAND2XL g2100__5477 (.Y(n_66),
	.A(n_54),
	.B(n_64));
   INVX1 g2101 (.Y(n_64),
	.A(n_65));
   ADDFX1 g2102__2398 (.CO(n_63),
	.S(n_65),
	.A(n_55),
	.B(n_52),
	.CI(n_60));
   INVX1 g2103 (.Y(n_62),
	.A(n_61));
   ADDFX1 g2104__5107 (.CO(n_60),
	.S(n_61),
	.A(n_37),
	.B(n_51),
	.CI(n_53));
   XNOR2X1 g2105__6260 (.Y(n_59),
	.A(n_57),
	.B(n_58));
   XNOR2X1 g2106__4319 (.Y(n_58),
	.A(n_27),
	.B(n_56));
   OAI21XL g2107__8428 (.Y(n_57),
	.A0(n_45),
	.A1(n_50),
	.B0(n_44));
   XNOR2X1 g2108__5526 (.Y(n_56),
	.A(n_26),
	.B(n_50));
   OAI21XL g2109__6783 (.Y(n_55),
	.A0(n_40),
	.A1(n_50),
	.B0(n_42));
   XNOR2X1 g2110__3680 (.Y(n_53),
	.A(n_43),
	.B(n_50));
   XNOR2X1 g2111__1617 (.Y(n_52),
	.A(n_46),
	.B(n_50));
   XNOR2X1 g2112__2802 (.Y(n_54),
	.A(n_39),
	.B(n_50));
   NOR2XL g2113__1705 (.Y(n_51),
	.A(n_39),
	.B(n_50));
   OAI22XL g2114__5122 (.Y(n_50),
	.A0(n_35),
	.A1(n_49),
	.B0(n_26),
	.B1(n_28));
   OA21X1 g2115__8246 (.Y(n_49),
	.A0(n_45),
	.A1(n_48),
	.B0(n_44));
   NOR2BX1 g2116__7098 (.Y(n_48),
	.AN(n_42),
	.B(n_47));
   NOR2BX1 g2117__6131 (.Y(n_47),
	.AN(n_37),
	.B(n_40));
   XNOR2X1 g2118__1881 (.Y(n_46),
	.A(n_41),
	.B(n_38));
   NOR2BX1 g2119__5115 (.Y(n_45),
	.AN(n_41),
	.B(n_38));
   NAND2BXL g2120__7482 (.Y(n_44),
	.AN(n_41),
	.B(n_38));
   XNOR2X1 g2121__4733 (.Y(n_43),
	.A(n_36),
	.B(n_34));
   NAND2BXL g2122__6161 (.Y(n_42),
	.AN(n_36),
	.B(n_34));
   NAND2XL g2123__9315 (.Y(n_41),
	.A(n_7),
	.B(n_33));
   NOR2BX1 g2124__9945 (.Y(n_40),
	.AN(n_36),
	.B(n_34));
   OA21X1 g2125__2883 (.Y(n_39),
	.A0(n_31),
	.A1(n_30),
	.B0(n_37));
   NAND2XL g2126__2346 (.Y(n_38),
	.A(n_9),
	.B(n_32));
   AND2X1 g2127__1666 (.Y(n_35),
	.A(n_28),
	.B(n_26));
   NAND2XL g2128__7410 (.Y(n_37),
	.A(n_31),
	.B(n_30));
   OAI211X1 g2129__6417 (.Y(n_36),
	.A0(n_3),
	.A1(n_20),
	.B0(n_16),
	.C0(n_23));
   AOI31X1 g2130__5477 (.Y(n_33),
	.A0(b[1]),
	.A1(b[0]),
	.A2(n_1),
	.B0(n_25));
   AOI31X1 g2131__2398 (.Y(n_32),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_0),
	.B0(n_24));
   OAI222XL g2132__5107 (.Y(n_34),
	.A0(a[0]),
	.A1(n_21),
	.B0(n_4),
	.B1(n_19),
	.C0(n_9),
	.C1(a[2]));
   OAI222XL g2133__6260 (.Y(n_31),
	.A0(b[0]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_12),
	.C0(b[2]),
	.C1(n_14));
   AOI221X1 g2134__4319 (.Y(n_30),
	.A0(n_4),
	.A1(n_10),
	.B0(n_18),
	.B1(n_0),
	.C0(n_22));
   AOI33XL g2135__8428 (.Y(n_29),
	.A0(n_2),
	.A1(n_1),
	.A2(n_15),
	.B0(n_13),
	.B1(n_4),
	.B2(n_0));
   INVXL g2136 (.Y(n_28),
	.A(n_27));
   OAI22XL g2137__5526 (.Y(n_25),
	.A0(b[0]),
	.A1(n_20),
	.B0(n_2),
	.B1(n_12));
   OAI22XL g2138__6783 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2139__3680 (.Y(n_27),
	.A0(n_4),
	.A1(n_0),
	.B0(a[1]),
	.B1(n_9),
	.C0(a[0]),
	.C1(n_17));
   OAI222XL g2140__1617 (.Y(n_26),
	.A0(b[1]),
	.A1(n_7),
	.B0(n_1),
	.B1(n_3),
	.C0(b[0]),
	.C1(n_14));
   AOI32X1 g2141__2802 (.Y(n_23),
	.A0(b[3]),
	.A1(b[2]),
	.A2(n_3),
	.B0(n_1),
	.B1(n_8));
   NOR2XL g2142__1705 (.Y(n_22),
	.A(n_9),
	.B(n_10));
   AOI21XL g2143__5122 (.Y(n_21),
	.A0(a[3]),
	.A1(a[2]),
	.B0(n_5));
   NAND3XL g2144__8246 (.Y(n_20),
	.A(b[1]),
	.B(b[2]),
	.C(n_2));
   NAND3BXL g2145__7098 (.Y(n_19),
	.AN(n_0),
	.B(n_6),
	.C(a[1]));
   INVXL g2146 (.Y(n_18),
	.A(n_17));
   INVXL g2147 (.Y(n_16),
	.A(n_15));
   NOR2XL g2148__6131 (.Y(n_13),
	.A(a[3]),
	.B(a[1]));
   NAND2XL g2149__1881 (.Y(n_17),
	.A(a[3]),
	.B(a[1]));
   NOR2XL g2150__5115 (.Y(n_15),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2151__7482 (.Y(n_14),
	.A(b[1]),
	.B(b[3]));
   INVXL g2152 (.Y(n_12),
	.A(n_11));
   INVXL g2153 (.Y(n_8),
	.A(n_7));
   NOR2XL g2154__4733 (.Y(n_11),
	.A(b[1]),
	.B(n_1));
   NAND2XL g2155__6161 (.Y(n_10),
	.A(n_5),
	.B(a[2]));
   NAND2XL g2156__9315 (.Y(n_9),
	.A(a[3]),
	.B(a[0]));
   NAND2XL g2157__9945 (.Y(n_7),
	.A(b[0]),
	.B(b[3]));
   INVXL g2158 (.Y(n_6),
	.A(a[3]));
   INVXL g2159 (.Y(n_5),
	.A(a[1]));
   INVX1 g2160 (.Y(n_4),
	.A(a[0]));
   INVX1 g2161 (.Y(n_3),
	.A(b[0]));
   INVX1 g2162 (.Y(n_2),
	.A(b[3]));
   INVX1 g2163 (.Y(n_1),
	.A(b[2]));
   INVX1 g2164 (.Y(n_0),
	.A(a[2]));
endmodule

module ff_4 (
	clk, 
	rst, 
	a, 
	q);
   input clk;
   input rst;
   input [3:0] a;
   output [3:0] q;

   // Internal wires
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;

   DFFRX2 \q_reg[0]  (.Q(q[0]),
	.QN(UNCONNECTED),
	.D(a[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \q_reg[3]  (.Q(q[3]),
	.QN(UNCONNECTED0),
	.D(a[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \q_reg[1]  (.Q(q[1]),
	.QN(UNCONNECTED1),
	.D(a[1]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \q_reg[2]  (.Q(q[2]),
	.QN(UNCONNECTED2),
	.D(a[2]),
	.RN(rst),
	.CK(clk));
endmodule

module ff_4_68 (
	clk, 
	rst, 
	a, 
	q);
   input clk;
   input rst;
   input [3:0] a;
   output [3:0] q;

   // Internal wires
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;

   DFFRX2 \q_reg[0]  (.Q(q[0]),
	.QN(UNCONNECTED3),
	.D(a[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \q_reg[3]  (.Q(q[3]),
	.QN(UNCONNECTED4),
	.D(a[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \q_reg[1]  (.Q(q[1]),
	.QN(UNCONNECTED5),
	.D(a[1]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \q_reg[2]  (.Q(q[2]),
	.QN(UNCONNECTED6),
	.D(a[2]),
	.RN(rst),
	.CK(clk));
endmodule

module gf_multiplier (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__2883 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__2346 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__1666 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__7410 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__6417 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__5477 (.Y(n_74),
	.AN(n_68),
	.B(n_56),
	.C(n_61));
   NAND2XL g1996__2398 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__5107 (.Y(n_70),
	.A0(n_57),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__6260 (.Y(n_71),
	.A0(n_57),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__4319 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__8428 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__5526 (.Y(n_67),
	.A(n_57),
	.B(n_65));
   AOI21XL g2003__6783 (.Y(n_66),
	.A0(n_55),
	.A1(n_56),
	.B0(n_63));
   XNOR2X1 g2004__3680 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__1617 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__2802 (.Y(n_62),
	.A(n_56),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__1705 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__5122 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__8246 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__7098 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__6131 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__1881 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__5115 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI221X1 g2017__7482 (.Y(n_52),
	.A0(n_49),
	.A1(n_51),
	.B0(n_37),
	.B1(n_47),
	.C0(n_38));
   INVXL g2018 (.Y(n_51),
	.A(n_50));
   NAND3BXL g2019__4733 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__6161 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__9315 (.CO(n_47),
	.S(n_48),
	.A(n_44),
	.B(n_43),
	.CI(n_45));
   ADDFX1 g2022__9945 (.CO(n_45),
	.S(n_46),
	.A(n_39),
	.B(n_41),
	.CI(n_36));
   OAI211X1 g2023__2883 (.Y(n_44),
	.A0(n_8),
	.A1(n_34),
	.B0(n_13),
	.C0(n_24));
   OAI211X1 g2024__2346 (.Y(n_43),
	.A0(n_9),
	.A1(n_33),
	.B0(n_15),
	.C0(n_22));
   NAND2BXL g2025__1666 (.Y(n_42),
	.AN(n_38),
	.B(n_37));
   OAI221X1 g2026__7410 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__6417 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_13),
	.C0(n_19));
   XNOR2X1 g2028__5477 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__2398 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__5107 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__6260 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__4319 (.Y(n_34),
	.A0(n_4),
	.A1(n_21),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__8428 (.Y(n_33),
	.A0(n_5),
	.A1(n_25),
	.B0(a[0]),
	.B1(n_10));
   AOI221X1 g2034__5526 (.Y(n_35),
	.A0(n_9),
	.A1(n_16),
	.B0(a[3]),
	.B1(n_10),
	.C0(n_23));
   AOI222X1 g2035__6783 (.Y(n_32),
	.A0(a[1]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_16),
	.C0(a[2]),
	.C1(a[0]));
   AOI221X1 g2036__3680 (.Y(n_31),
	.A0(b[0]),
	.A1(b[2]),
	.B0(b[1]),
	.B1(n_12),
	.C0(n_26));
   AOI221X1 g2037__1617 (.Y(n_30),
	.A0(n_14),
	.A1(n_8),
	.B0(b[3]),
	.B1(n_17),
	.C0(n_20));
   OAI33X1 g2038__2802 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[2]),
	.B1(a[3]),
	.B2(n_18));
   AOI31X1 g2039__1705 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_11));
   AOI31X1 g2040__5122 (.Y(n_27),
	.A0(b[0]),
	.A1(b[1]),
	.A2(n_0),
	.B0(n_12));
   NOR2XL g2041__8246 (.Y(n_26),
	.A(b[1]),
	.B(n_13));
   NOR2XL g2042__7098 (.Y(n_25),
	.A(a[3]),
	.B(n_10));
   NAND2XL g2043__6131 (.Y(n_24),
	.A(b[3]),
	.B(n_8));
   NOR2XL g2044__1881 (.Y(n_23),
	.A(a[0]),
	.B(n_9));
   NAND2XL g2045__5115 (.Y(n_22),
	.A(a[3]),
	.B(n_9));
   NOR2XL g2046__7482 (.Y(n_21),
	.A(b[3]),
	.B(n_17));
   NOR2XL g2047__4733 (.Y(n_20),
	.A(b[0]),
	.B(n_8));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   INVXL g2049 (.Y(n_14),
	.A(n_13));
   NAND2XL g2050__6161 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2051__9315 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2052__9945 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NOR2XL g2053__2883 (.Y(n_16),
	.A(n_6),
	.B(n_5));
   NAND2XL g2054__2346 (.Y(n_13),
	.A(b[0]),
	.B(b[3]));
   NOR2XL g2055__1666 (.Y(n_12),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__7410 (.Y(n_11),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__6417 (.Y(n_10),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__5477 (.Y(n_9),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__2398 (.Y(n_8),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVXL g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module gf_multiplier_24 (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__5107 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__6260 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__4319 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__8428 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__5526 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__6783 (.Y(n_74),
	.AN(n_68),
	.B(n_56),
	.C(n_61));
   NAND2XL g1996__3680 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__1617 (.Y(n_70),
	.A0(n_57),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__2802 (.Y(n_71),
	.A0(n_57),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__1705 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__5122 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__8246 (.Y(n_67),
	.A(n_57),
	.B(n_65));
   AOI21XL g2003__7098 (.Y(n_66),
	.A0(n_55),
	.A1(n_56),
	.B0(n_63));
   XNOR2X1 g2004__6131 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__1881 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__5115 (.Y(n_62),
	.A(n_56),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__7482 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__4733 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__6161 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__9315 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__9945 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__2883 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__2346 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI221X1 g2017__1666 (.Y(n_52),
	.A0(n_49),
	.A1(n_51),
	.B0(n_37),
	.B1(n_47),
	.C0(n_38));
   INVXL g2018 (.Y(n_51),
	.A(n_50));
   NAND3BXL g2019__7410 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__6417 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__5477 (.CO(n_47),
	.S(n_48),
	.A(n_44),
	.B(n_43),
	.CI(n_45));
   ADDFX1 g2022__2398 (.CO(n_45),
	.S(n_46),
	.A(n_39),
	.B(n_41),
	.CI(n_36));
   OAI211X1 g2023__5107 (.Y(n_44),
	.A0(n_8),
	.A1(n_34),
	.B0(n_13),
	.C0(n_24));
   OAI211X1 g2024__6260 (.Y(n_43),
	.A0(n_9),
	.A1(n_33),
	.B0(n_15),
	.C0(n_22));
   NAND2BXL g2025__4319 (.Y(n_42),
	.AN(n_38),
	.B(n_37));
   OAI221X1 g2026__8428 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__5526 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_13),
	.C0(n_19));
   XNOR2X1 g2028__6783 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__3680 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__1617 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__2802 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__1705 (.Y(n_34),
	.A0(n_4),
	.A1(n_21),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__5122 (.Y(n_33),
	.A0(n_5),
	.A1(n_25),
	.B0(a[0]),
	.B1(n_10));
   AOI221X1 g2034__8246 (.Y(n_35),
	.A0(n_9),
	.A1(n_16),
	.B0(a[3]),
	.B1(n_10),
	.C0(n_23));
   AOI222X1 g2035__7098 (.Y(n_32),
	.A0(a[1]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_16),
	.C0(a[2]),
	.C1(a[0]));
   AOI221X1 g2036__6131 (.Y(n_31),
	.A0(b[0]),
	.A1(b[2]),
	.B0(b[1]),
	.B1(n_12),
	.C0(n_26));
   AOI221X1 g2037__1881 (.Y(n_30),
	.A0(n_14),
	.A1(n_8),
	.B0(b[3]),
	.B1(n_17),
	.C0(n_20));
   OAI33X1 g2038__5115 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[2]),
	.B1(a[3]),
	.B2(n_18));
   AOI31X1 g2039__7482 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_11));
   AOI31X1 g2040__4733 (.Y(n_27),
	.A0(b[0]),
	.A1(b[1]),
	.A2(n_0),
	.B0(n_12));
   NOR2XL g2041__6161 (.Y(n_26),
	.A(b[1]),
	.B(n_13));
   NOR2XL g2042__9315 (.Y(n_25),
	.A(a[3]),
	.B(n_10));
   NAND2XL g2043__9945 (.Y(n_24),
	.A(b[3]),
	.B(n_8));
   NOR2XL g2044__2883 (.Y(n_23),
	.A(a[0]),
	.B(n_9));
   NAND2XL g2045__2346 (.Y(n_22),
	.A(a[3]),
	.B(n_9));
   NOR2XL g2046__1666 (.Y(n_21),
	.A(b[3]),
	.B(n_17));
   NOR2XL g2047__7410 (.Y(n_20),
	.A(b[0]),
	.B(n_8));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   INVXL g2049 (.Y(n_14),
	.A(n_13));
   NAND2XL g2050__6417 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2051__5477 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2052__2398 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NOR2XL g2053__5107 (.Y(n_16),
	.A(n_6),
	.B(n_5));
   NAND2XL g2054__6260 (.Y(n_13),
	.A(b[0]),
	.B(b[3]));
   NOR2XL g2055__4319 (.Y(n_12),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__8428 (.Y(n_11),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__5526 (.Y(n_10),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__6783 (.Y(n_9),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__3680 (.Y(n_8),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVXL g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module gf_multiplier_23 (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__1617 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__2802 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__1705 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__5122 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__8246 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__7098 (.Y(n_74),
	.AN(n_68),
	.B(n_56),
	.C(n_61));
   NAND2XL g1996__6131 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__1881 (.Y(n_70),
	.A0(n_57),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__5115 (.Y(n_71),
	.A0(n_57),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__7482 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__4733 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__6161 (.Y(n_67),
	.A(n_57),
	.B(n_65));
   AOI21XL g2003__9315 (.Y(n_66),
	.A0(n_55),
	.A1(n_56),
	.B0(n_63));
   XNOR2X1 g2004__9945 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__2883 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__2346 (.Y(n_62),
	.A(n_56),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__1666 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__7410 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__6417 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__5477 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__2398 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__5107 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__6260 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI221X1 g2017__4319 (.Y(n_52),
	.A0(n_49),
	.A1(n_51),
	.B0(n_37),
	.B1(n_47),
	.C0(n_38));
   INVXL g2018 (.Y(n_51),
	.A(n_50));
   NAND3BXL g2019__8428 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__5526 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__6783 (.CO(n_47),
	.S(n_48),
	.A(n_44),
	.B(n_43),
	.CI(n_45));
   ADDFX1 g2022__3680 (.CO(n_45),
	.S(n_46),
	.A(n_39),
	.B(n_41),
	.CI(n_36));
   OAI211X1 g2023__1617 (.Y(n_44),
	.A0(n_8),
	.A1(n_34),
	.B0(n_13),
	.C0(n_24));
   OAI211X1 g2024__2802 (.Y(n_43),
	.A0(n_9),
	.A1(n_33),
	.B0(n_15),
	.C0(n_22));
   NAND2BXL g2025__1705 (.Y(n_42),
	.AN(n_38),
	.B(n_37));
   OAI221X1 g2026__5122 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__8246 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_13),
	.C0(n_19));
   XNOR2X1 g2028__7098 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__6131 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__1881 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__5115 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__7482 (.Y(n_34),
	.A0(n_4),
	.A1(n_21),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__4733 (.Y(n_33),
	.A0(n_5),
	.A1(n_25),
	.B0(a[0]),
	.B1(n_10));
   AOI221X1 g2034__6161 (.Y(n_35),
	.A0(n_9),
	.A1(n_16),
	.B0(a[3]),
	.B1(n_10),
	.C0(n_23));
   AOI222X1 g2035__9315 (.Y(n_32),
	.A0(n_7),
	.A1(n_16),
	.B0(a[2]),
	.B1(a[0]),
	.C0(a[1]),
	.C1(n_11));
   AOI221X1 g2036__9945 (.Y(n_31),
	.A0(b[0]),
	.A1(b[2]),
	.B0(b[1]),
	.B1(n_12),
	.C0(n_26));
   AOI221X1 g2037__2883 (.Y(n_30),
	.A0(n_14),
	.A1(n_8),
	.B0(b[3]),
	.B1(n_17),
	.C0(n_20));
   OAI33X1 g2038__2346 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[3]),
	.B1(a[2]),
	.B2(n_18));
   AOI31X1 g2039__1666 (.Y(n_28),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_6),
	.B0(n_11));
   AOI31X1 g2040__7410 (.Y(n_27),
	.A0(b[0]),
	.A1(b[1]),
	.A2(n_0),
	.B0(n_12));
   NOR2XL g2041__6417 (.Y(n_26),
	.A(b[1]),
	.B(n_13));
   NOR2XL g2042__5477 (.Y(n_25),
	.A(a[3]),
	.B(n_10));
   NAND2XL g2043__2398 (.Y(n_24),
	.A(b[3]),
	.B(n_8));
   NOR2XL g2044__5107 (.Y(n_23),
	.A(a[0]),
	.B(n_9));
   NAND2XL g2045__6260 (.Y(n_22),
	.A(a[3]),
	.B(n_9));
   NOR2XL g2046__4319 (.Y(n_21),
	.A(b[3]),
	.B(n_17));
   NOR2XL g2047__8428 (.Y(n_20),
	.A(b[0]),
	.B(n_8));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   INVXL g2049 (.Y(n_14),
	.A(n_13));
   NAND2XL g2050__5526 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2051__6783 (.Y(n_18),
	.A(n_7),
	.B(n_5));
   NOR2XL g2052__3680 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NOR2XL g2053__1617 (.Y(n_16),
	.A(n_5),
	.B(n_6));
   NAND2XL g2054__2802 (.Y(n_13),
	.A(b[0]),
	.B(b[3]));
   NOR2XL g2055__1705 (.Y(n_12),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__5122 (.Y(n_11),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__8246 (.Y(n_10),
	.A(a[2]),
	.B(n_7));
   NOR2XL g2058__7098 (.Y(n_9),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__6131 (.Y(n_8),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVXL g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module gf_multiplier_22 (
	a, 
	b, 
	p);
   input [3:0] a;
   input [3:0] b;
   output [3:0] p;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;

   OAI221X1 g1990__1881 (.Y(p[2]),
	.A0(n_29),
	.A1(n_75),
	.B0(n_60),
	.B1(n_69),
	.C0(n_74));
   OAI222XL g1991__5115 (.Y(p[1]),
	.A0(n_59),
	.A1(n_70),
	.B0(n_29),
	.B1(n_73),
	.C0(n_64),
	.C1(n_68));
   OAI221X1 g1992__7482 (.Y(p[0]),
	.A0(n_29),
	.A1(n_66),
	.B0(n_61),
	.B1(n_69),
	.C0(n_74));
   OAI22XL g1993__4733 (.Y(p[3]),
	.A0(n_59),
	.A1(n_71),
	.B0(n_62),
	.B1(n_68));
   AOI22XL g1994__6161 (.Y(n_75),
	.A0(n_55),
	.A1(n_72),
	.B0(n_60),
	.B1(n_67));
   NAND3BXL g1995__9315 (.Y(n_74),
	.AN(n_68),
	.B(n_56),
	.C(n_61));
   NAND2XL g1996__9945 (.Y(n_73),
	.A(n_64),
	.B(n_67));
   INVXL g1997 (.Y(n_72),
	.A(n_71));
   AOI21XL g1998__2883 (.Y(n_70),
	.A0(n_57),
	.A1(n_65),
	.B0(n_62));
   AOI21XL g1999__2346 (.Y(n_71),
	.A0(n_57),
	.A1(n_60),
	.B0(n_67));
   NAND2BXL g2000__1666 (.Y(n_69),
	.AN(n_59),
	.B(n_65));
   NAND2BXL g2001__7410 (.Y(n_68),
	.AN(n_29),
	.B(n_65));
   NOR2XL g2002__6417 (.Y(n_67),
	.A(n_57),
	.B(n_65));
   AOI21XL g2003__5477 (.Y(n_66),
	.A0(n_55),
	.A1(n_56),
	.B0(n_63));
   XNOR2X1 g2004__2398 (.Y(n_65),
	.A(n_48),
	.B(n_58));
   INVXL g2005 (.Y(n_63),
	.A(n_64));
   NAND2XL g2006__5107 (.Y(n_64),
	.A(n_55),
	.B(n_61));
   NOR2XL g2007__6260 (.Y(n_62),
	.A(n_56),
	.B(n_60));
   INVX1 g2008 (.Y(n_61),
	.A(n_60));
   CLKXOR2X1 g2009__4319 (.Y(n_60),
	.A(n_46),
	.B(n_54));
   OR2X1 g2010__8428 (.Y(n_59),
	.A(n_29),
	.B(n_55));
   NAND2XL g2011__5526 (.Y(n_58),
	.A(n_46),
	.B(n_54));
   INVX1 g2012 (.Y(n_56),
	.A(n_57));
   XNOR2X1 g2013__6783 (.Y(n_57),
	.A(n_49),
	.B(n_53));
   XNOR2X1 g2014__3680 (.Y(n_55),
	.A(n_40),
	.B(n_52));
   NOR2XL g2015__1617 (.Y(n_54),
	.A(n_40),
	.B(n_52));
   NOR2XL g2016__2802 (.Y(n_53),
	.A(n_50),
	.B(n_52));
   AOI221X1 g2017__1705 (.Y(n_52),
	.A0(n_49),
	.A1(n_51),
	.B0(n_37),
	.B1(n_47),
	.C0(n_38));
   INVXL g2018 (.Y(n_51),
	.A(n_50));
   NAND3BXL g2019__5122 (.Y(n_50),
	.AN(n_40),
	.B(n_46),
	.C(n_48));
   XNOR2X1 g2020__8246 (.Y(n_49),
	.A(n_42),
	.B(n_47));
   ADDFX1 g2021__7098 (.CO(n_47),
	.S(n_48),
	.A(n_44),
	.B(n_43),
	.CI(n_45));
   ADDFX1 g2022__6131 (.CO(n_45),
	.S(n_46),
	.A(n_39),
	.B(n_41),
	.CI(n_36));
   OAI211X1 g2023__1881 (.Y(n_44),
	.A0(n_8),
	.A1(n_34),
	.B0(n_13),
	.C0(n_24));
   OAI211X1 g2024__5115 (.Y(n_43),
	.A0(n_9),
	.A1(n_33),
	.B0(n_15),
	.C0(n_22));
   NAND2BXL g2025__7482 (.Y(n_42),
	.AN(n_38),
	.B(n_37));
   OAI221X1 g2026__4733 (.Y(n_41),
	.A0(n_2),
	.A1(n_28),
	.B0(a[2]),
	.B1(n_15),
	.C0(n_18));
   OAI221X1 g2027__6161 (.Y(n_39),
	.A0(n_1),
	.A1(n_27),
	.B0(b[2]),
	.B1(n_13),
	.C0(n_19));
   XNOR2X1 g2028__9315 (.Y(n_40),
	.A(n_30),
	.B(n_35));
   NOR2XL g2029__9945 (.Y(n_38),
	.A(n_31),
	.B(n_32));
   NAND2XL g2030__2883 (.Y(n_37),
	.A(n_31),
	.B(n_32));
   NOR2XL g2031__2346 (.Y(n_36),
	.A(n_30),
	.B(n_35));
   AOI22XL g2032__1666 (.Y(n_34),
	.A0(n_4),
	.A1(n_21),
	.B0(b[0]),
	.B1(n_17));
   AOI22XL g2033__7410 (.Y(n_33),
	.A0(n_5),
	.A1(n_25),
	.B0(a[0]),
	.B1(n_10));
   AOI221X1 g2034__6417 (.Y(n_35),
	.A0(n_16),
	.A1(n_9),
	.B0(a[3]),
	.B1(n_10),
	.C0(n_23));
   AOI222X1 g2035__5477 (.Y(n_32),
	.A0(a[1]),
	.A1(n_11),
	.B0(n_7),
	.B1(n_16),
	.C0(a[0]),
	.C1(a[2]));
   AOI221X1 g2036__2398 (.Y(n_31),
	.A0(b[0]),
	.A1(b[2]),
	.B0(b[1]),
	.B1(n_12),
	.C0(n_26));
   AOI221X1 g2037__5107 (.Y(n_30),
	.A0(n_14),
	.A1(n_8),
	.B0(b[3]),
	.B1(n_17),
	.C0(n_20));
   OAI33X1 g2038__6260 (.Y(n_29),
	.A0(b[2]),
	.A1(b[3]),
	.A2(n_19),
	.B0(a[2]),
	.B1(a[3]),
	.B2(n_18));
   AOI31X1 g2039__4319 (.Y(n_28),
	.A0(a[0]),
	.A1(a[1]),
	.A2(n_6),
	.B0(n_11));
   AOI31X1 g2040__8428 (.Y(n_27),
	.A0(b[0]),
	.A1(b[1]),
	.A2(n_0),
	.B0(n_12));
   NOR2XL g2041__5526 (.Y(n_26),
	.A(b[1]),
	.B(n_13));
   NOR2XL g2042__6783 (.Y(n_25),
	.A(a[3]),
	.B(n_10));
   NAND2XL g2043__3680 (.Y(n_24),
	.A(b[3]),
	.B(n_8));
   NOR2XL g2044__1617 (.Y(n_23),
	.A(a[0]),
	.B(n_9));
   NAND2XL g2045__2802 (.Y(n_22),
	.A(a[3]),
	.B(n_9));
   NOR2XL g2046__1705 (.Y(n_21),
	.A(b[3]),
	.B(n_17));
   NOR2XL g2047__5122 (.Y(n_20),
	.A(b[0]),
	.B(n_8));
   INVX1 g2048 (.Y(n_15),
	.A(n_16));
   INVXL g2049 (.Y(n_14),
	.A(n_13));
   NAND2XL g2050__8246 (.Y(n_19),
	.A(n_3),
	.B(n_4));
   NAND2XL g2051__7098 (.Y(n_18),
	.A(n_5),
	.B(n_7));
   NOR2XL g2052__6131 (.Y(n_17),
	.A(b[2]),
	.B(n_3));
   NOR2XL g2053__1881 (.Y(n_16),
	.A(n_5),
	.B(n_6));
   NAND2XL g2054__5115 (.Y(n_13),
	.A(b[0]),
	.B(b[3]));
   NOR2XL g2055__7482 (.Y(n_12),
	.A(b[0]),
	.B(n_0));
   NOR2XL g2056__4733 (.Y(n_11),
	.A(a[0]),
	.B(n_6));
   NOR2XL g2057__6161 (.Y(n_10),
	.A(n_7),
	.B(a[2]));
   NOR2XL g2058__9315 (.Y(n_9),
	.A(a[1]),
	.B(n_2));
   NOR2XL g2059__9945 (.Y(n_8),
	.A(b[1]),
	.B(n_1));
   INVX1 g2060 (.Y(n_7),
	.A(a[1]));
   INVX1 g2061 (.Y(n_6),
	.A(a[3]));
   INVX1 g2062 (.Y(n_5),
	.A(a[0]));
   INVXL g2063 (.Y(n_4),
	.A(b[0]));
   INVXL g2064 (.Y(n_3),
	.A(b[1]));
   INVX1 g2065 (.Y(n_2),
	.A(a[2]));
   INVX1 g2066 (.Y(n_1),
	.A(b[2]));
   INVXL g2067 (.Y(n_0),
	.A(b[3]));
endmodule

module xor_4 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__2883 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__2346 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__1666 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__7410 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module xor_4_27 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__6417 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__5477 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__2398 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__5107 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module xor_4_26 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__6260 (.Y(y[3]),
	.A(a[3]),
	.B(b[3]));
   CLKXOR2X1 g38__4319 (.Y(y[1]),
	.A(a[1]),
	.B(b[1]));
   CLKXOR2X1 g39__8428 (.Y(y[0]),
	.A(a[0]),
	.B(b[0]));
   CLKXOR2X1 g40__5526 (.Y(y[2]),
	.A(a[2]),
	.B(b[2]));
endmodule

module xor_4_25 (
	a, 
	b, 
	y);
   input [3:0] a;
   input [3:0] b;
   output [3:0] y;

   CLKXOR2X1 g37__6783 (.Y(y[3]),
	.A(b[3]),
	.B(a[3]));
   CLKXOR2X1 g38__3680 (.Y(y[1]),
	.A(b[1]),
	.B(a[1]));
   CLKXOR2X1 g39__1617 (.Y(y[0]),
	.A(b[0]),
	.B(a[0]));
   CLKXOR2X1 g40__2802 (.Y(y[2]),
	.A(b[2]),
	.B(a[2]));
endmodule

module bch_bm_block (
	clk, 
	rst, 
	S1, 
	S2, 
	S3, 
	lambda1, 
	lambda2);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] S2;
   input [3:0] S3;
   output [3:0] lambda1;
   output [3:0] lambda2;

   // Internal wires
   wire [3:0] xor2;
   wire [3:0] div1;
   wire [3:0] xor1;
   wire [3:0] div2;
   wire [3:0] mult1;
   wire [3:0] mult2;
   wire [3:0] mult3;
   wire [3:0] mult4;
   wire [3:0] xor4;
   wire [3:0] xor3;

   gf_divider u_div1 (.a(xor2),
	.b(S1),
	.q(div1));
   gf_divider_21 u_div2 (.a(xor1),
	.b(S1),
	.q(div2));
   ff_4 u_lamb1 (.clk(clk),
	.rst(rst),
	.a(div1),
	.q(lambda1));
   ff_4_68 u_lamb2 (.clk(clk),
	.rst(rst),
	.a(div2),
	.q(lambda2));
   gf_multiplier u_mult1 (.a(lambda1),
	.b(S1),
	.p(mult1));
   gf_multiplier_24 u_mult2 (.a(lambda1),
	.b(S2),
	.p(mult2));
   gf_multiplier_23 u_mult3 (.a(lambda2),
	.b(S1),
	.p(mult3));
   gf_multiplier_22 u_mult4 (.a(div1),
	.b(S2),
	.p(mult4));
   xor_4 u_xor1 (.a(xor4),
	.b(mult4),
	.y(xor1));
   xor_4_27 u_xor2 (.a(S2),
	.b(mult1),
	.y(xor2));
   xor_4_26 u_xor3 (.a(S3),
	.b(mult2),
	.y(xor3));
   xor_4_25 u_xor4 (.a(xor3),
	.b(mult3),
	.y(xor4));
endmodule

