
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug 21 2025 12:38:29 -03 (Aug 21 2025 15:38:29 UTC)

// Verification Directory fv/and16 

module and16(a, y);
  input [15:0] a;
  output y;
  wire [15:0] a;
  wire y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_28;
  AND2X1 g192__2398(.A (n_1), .B (n_4), .Y (n_5));
  NOR4BBX1 g193__5107(.AN (a[5]), .BN (a[0]), .C (n_0), .D (n_3), .Y
       (n_4));
  NAND3BXL g194__6260(.AN (n_2), .B (a[14]), .C (a[15]), .Y (n_3));
  NAND4XL g196__4319(.A (a[6]), .B (a[7]), .C (a[10]), .D (a[11]), .Y
       (n_2));
  AND4X1 g195__8428(.A (a[1]), .B (a[2]), .C (a[3]), .D (a[4]), .Y
       (n_1));
  NAND4XL g197__5526(.A (a[8]), .B (a[9]), .C (a[12]), .D (a[13]), .Y
       (n_0));
  DLY1X1 fopt(.A (n_5), .Y (n_28));
  BUFX20 drc(.A (n_28), .Y (y));
endmodule

