
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 26 2025 14:24:16 -03 (Sep 26 2025 17:24:16 UTC)

// Verification Directory fv/bm_stage_2 

module gf_multiplier(a, b, p);
  input [3:0] a, b;
  output [3:0] p;
  wire [3:0] a, b;
  wire [3:0] p;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75;
  OAI221X1 g1990__2398(.A0 (n_29), .A1 (n_75), .B0 (n_60), .B1 (n_69),
       .C0 (n_74), .Y (p[2]));
  OAI222XL g1991__5107(.A0 (n_59), .A1 (n_70), .B0 (n_29), .B1 (n_73),
       .C0 (n_64), .C1 (n_68), .Y (p[1]));
  OAI221X1 g1992__6260(.A0 (n_29), .A1 (n_66), .B0 (n_61), .B1 (n_69),
       .C0 (n_74), .Y (p[0]));
  OAI22XL g1993__4319(.A0 (n_59), .A1 (n_71), .B0 (n_62), .B1 (n_68),
       .Y (p[3]));
  AOI22XL g1994__8428(.A0 (n_55), .A1 (n_72), .B0 (n_60), .B1 (n_67),
       .Y (n_75));
  NAND3BXL g1995__5526(.AN (n_68), .B (n_56), .C (n_61), .Y (n_74));
  NAND2XL g1996__6783(.A (n_64), .B (n_67), .Y (n_73));
  INVXL g1997(.A (n_71), .Y (n_72));
  AOI21XL g1998__3680(.A0 (n_57), .A1 (n_65), .B0 (n_62), .Y (n_70));
  AOI21XL g1999__1617(.A0 (n_57), .A1 (n_60), .B0 (n_67), .Y (n_71));
  NAND2BXL g2000__2802(.AN (n_59), .B (n_65), .Y (n_69));
  NAND2BXL g2001__1705(.AN (n_29), .B (n_65), .Y (n_68));
  NOR2XL g2002__5122(.A (n_57), .B (n_65), .Y (n_67));
  AOI21XL g2003__8246(.A0 (n_55), .A1 (n_56), .B0 (n_63), .Y (n_66));
  XNOR2X1 g2004__7098(.A (n_48), .B (n_58), .Y (n_65));
  INVXL g2005(.A (n_64), .Y (n_63));
  NAND2XL g2006__6131(.A (n_55), .B (n_61), .Y (n_64));
  NOR2XL g2007__1881(.A (n_56), .B (n_60), .Y (n_62));
  INVX1 g2008(.A (n_60), .Y (n_61));
  CLKXOR2X1 g2009__5115(.A (n_46), .B (n_54), .Y (n_60));
  OR2X1 g2010__7482(.A (n_29), .B (n_55), .Y (n_59));
  NAND2XL g2011__4733(.A (n_46), .B (n_54), .Y (n_58));
  INVX1 g2012(.A (n_57), .Y (n_56));
  XNOR2X1 g2013__6161(.A (n_49), .B (n_53), .Y (n_57));
  XNOR2X1 g2014__9315(.A (n_40), .B (n_52), .Y (n_55));
  NOR2XL g2015__9945(.A (n_40), .B (n_52), .Y (n_54));
  NOR2XL g2016__2883(.A (n_50), .B (n_52), .Y (n_53));
  AOI221X1 g2017__2346(.A0 (n_49), .A1 (n_51), .B0 (n_37), .B1 (n_47),
       .C0 (n_38), .Y (n_52));
  INVXL g2018(.A (n_50), .Y (n_51));
  NAND3BXL g2019__1666(.AN (n_40), .B (n_46), .C (n_48), .Y (n_50));
  XNOR2X1 g2020__7410(.A (n_42), .B (n_47), .Y (n_49));
  ADDFX1 g2021__6417(.A (n_43), .B (n_44), .CI (n_45), .CO (n_47), .S
       (n_48));
  ADDFX1 g2022__5477(.A (n_41), .B (n_39), .CI (n_36), .CO (n_45), .S
       (n_46));
  OAI211X1 g2023__2398(.A0 (n_8), .A1 (n_34), .B0 (n_13), .C0 (n_24),
       .Y (n_44));
  OAI211X1 g2024__5107(.A0 (n_9), .A1 (n_33), .B0 (n_16), .C0 (n_22),
       .Y (n_43));
  NAND2BXL g2025__6260(.AN (n_38), .B (n_37), .Y (n_42));
  OAI221X1 g2026__4319(.A0 (n_2), .A1 (n_28), .B0 (a[2]), .B1 (n_16),
       .C0 (n_18), .Y (n_41));
  OAI221X1 g2027__8428(.A0 (n_1), .A1 (n_27), .B0 (b[2]), .B1 (n_13),
       .C0 (n_19), .Y (n_39));
  XNOR2X1 g2028__5526(.A (n_30), .B (n_35), .Y (n_40));
  NOR2XL g2029__6783(.A (n_31), .B (n_32), .Y (n_38));
  NAND2XL g2030__3680(.A (n_31), .B (n_32), .Y (n_37));
  NOR2XL g2031__1617(.A (n_35), .B (n_30), .Y (n_36));
  AOI22XL g2032__2802(.A0 (n_4), .A1 (n_21), .B0 (b[0]), .B1 (n_17), .Y
       (n_34));
  AOI22XL g2033__1705(.A0 (n_5), .A1 (n_25), .B0 (a[0]), .B1 (n_10), .Y
       (n_33));
  AOI221X1 g2034__5122(.A0 (n_15), .A1 (n_9), .B0 (a[3]), .B1 (n_10),
       .C0 (n_23), .Y (n_35));
  AOI222X1 g2035__8246(.A0 (a[1]), .A1 (n_11), .B0 (n_7), .B1 (n_15),
       .C0 (a[0]), .C1 (a[2]), .Y (n_32));
  AOI221X1 g2036__7098(.A0 (b[0]), .A1 (b[2]), .B0 (b[1]), .B1 (n_12),
       .C0 (n_26), .Y (n_31));
  AOI221X1 g2037__6131(.A0 (n_14), .A1 (n_8), .B0 (b[3]), .B1 (n_17),
       .C0 (n_20), .Y (n_30));
  OAI33X1 g2038__1881(.A0 (b[2]), .A1 (b[3]), .A2 (n_19), .B0 (a[3]),
       .B1 (a[2]), .B2 (n_18), .Y (n_29));
  AOI31X1 g2039__5115(.A0 (a[0]), .A1 (a[1]), .A2 (n_6), .B0 (n_11), .Y
       (n_28));
  AOI31X1 g2040__7482(.A0 (b[0]), .A1 (b[1]), .A2 (n_0), .B0 (n_12), .Y
       (n_27));
  NOR2XL g2041__4733(.A (b[1]), .B (n_13), .Y (n_26));
  NOR2XL g2042__6161(.A (a[3]), .B (n_10), .Y (n_25));
  NAND2XL g2043__9315(.A (b[3]), .B (n_8), .Y (n_24));
  NOR2XL g2044__9945(.A (a[0]), .B (n_9), .Y (n_23));
  NAND2XL g2045__2883(.A (a[3]), .B (n_9), .Y (n_22));
  NOR2XL g2046__2346(.A (b[3]), .B (n_17), .Y (n_21));
  NOR2XL g2047__1666(.A (b[0]), .B (n_8), .Y (n_20));
  INVX1 g2048(.A (n_16), .Y (n_15));
  INVXL g2049(.A (n_13), .Y (n_14));
  NAND2XL g2050__7410(.A (n_3), .B (n_4), .Y (n_19));
  NAND2XL g2051__6417(.A (n_7), .B (n_5), .Y (n_18));
  NOR2XL g2052__5477(.A (b[2]), .B (n_3), .Y (n_17));
  NAND2XL g2053__2398(.A (a[0]), .B (a[3]), .Y (n_16));
  NAND2XL g2054__5107(.A (b[0]), .B (b[3]), .Y (n_13));
  NOR2XL g2055__6260(.A (b[0]), .B (n_0), .Y (n_12));
  NOR2XL g2056__4319(.A (a[0]), .B (n_6), .Y (n_11));
  NOR2XL g2057__8428(.A (a[2]), .B (n_7), .Y (n_10));
  NOR2XL g2058__5526(.A (a[1]), .B (n_2), .Y (n_9));
  NOR2XL g2059__6783(.A (b[1]), .B (n_1), .Y (n_8));
  INVX1 g2060(.A (a[1]), .Y (n_7));
  INVXL g2061(.A (a[3]), .Y (n_6));
  INVXL g2062(.A (a[0]), .Y (n_5));
  INVXL g2063(.A (b[0]), .Y (n_4));
  INVXL g2064(.A (b[1]), .Y (n_3));
  INVX1 g2065(.A (a[2]), .Y (n_2));
  INVX1 g2066(.A (b[2]), .Y (n_1));
  INVXL g2067(.A (b[3]), .Y (n_0));
endmodule

module xor_4(a, b, y);
  input [3:0] a, b;
  output [3:0] y;
  wire [3:0] a, b;
  wire [3:0] y;
  CLKXOR2X1 g37__3680(.A (b[3]), .B (a[3]), .Y (y[3]));
  CLKXOR2X1 g38__1617(.A (b[1]), .B (a[1]), .Y (y[1]));
  CLKXOR2X1 g39__2802(.A (b[0]), .B (a[0]), .Y (y[0]));
  CLKXOR2X1 g40__1705(.A (b[2]), .B (a[2]), .Y (y[2]));
endmodule

module bm_stage_2(clk, rst, S1, S2, S3, l1_1, l1_2, l2_2, S1_o);
  input clk, rst;
  input [3:0] S1, S2, S3, l1_1;
  output [3:0] l1_2, l2_2, S1_o;
  wire clk, rst;
  wire [3:0] S1, S2, S3, l1_1;
  wire [3:0] l1_2, l2_2, S1_o;
  wire [3:0] mult1;
  wire [3:0] xor1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10;
  gf_multiplier u_mult1(.a (l1_1), .b (S2), .p (mult1));
  xor_4 u_xor1(.a (mult1), .b (S3), .y (xor1));
  DFFRX2 \l2_2_reg[0] (.RN (rst), .CK (clk), .D (xor1[0]), .Q
       (l2_2[0]), .QN (UNCONNECTED));
  DFFRX2 \l2_2_reg[3] (.RN (rst), .CK (clk), .D (xor1[3]), .Q
       (l2_2[3]), .QN (UNCONNECTED0));
  DFFRX2 \l2_2_reg[2] (.RN (rst), .CK (clk), .D (xor1[2]), .Q
       (l2_2[2]), .QN (UNCONNECTED1));
  DFFRX2 \l2_2_reg[1] (.RN (rst), .CK (clk), .D (xor1[1]), .Q
       (l2_2[1]), .QN (UNCONNECTED2));
  DFFRX2 \l1_2_reg[2] (.RN (rst), .CK (clk), .D (l1_1[2]), .Q
       (l1_2[2]), .QN (UNCONNECTED3));
  DFFRX2 \l1_2_reg[0] (.RN (rst), .CK (clk), .D (l1_1[0]), .Q
       (l1_2[0]), .QN (UNCONNECTED4));
  DFFRX2 \l1_2_reg[3] (.RN (rst), .CK (clk), .D (l1_1[3]), .Q
       (l1_2[3]), .QN (UNCONNECTED5));
  DFFRX2 \S1_o_reg[3] (.RN (rst), .CK (clk), .D (S1[3]), .Q (S1_o[3]),
       .QN (UNCONNECTED6));
  DFFRX2 \l1_2_reg[1] (.RN (rst), .CK (clk), .D (l1_1[1]), .Q
       (l1_2[1]), .QN (UNCONNECTED7));
  DFFRX2 \S1_o_reg[1] (.RN (rst), .CK (clk), .D (S1[1]), .Q (S1_o[1]),
       .QN (UNCONNECTED8));
  DFFRX2 \S1_o_reg[2] (.RN (rst), .CK (clk), .D (S1[2]), .Q (S1_o[2]),
       .QN (UNCONNECTED9));
  DFFRX2 \S1_o_reg[0] (.RN (rst), .CK (clk), .D (S1[0]), .Q (S1_o[0]),
       .QN (UNCONNECTED10));
endmodule

