/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu Oct  9 11:19:25 2025
#  Design:            bm_stage_3
#  Command:           write_netlist /home/ci_inovador/Documentos/inge4-workspace/layout/bm_stage_3/bm_stage_3_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 26 2025 14:24:46 -03 (Sep 26 2025 17:24:46 UTC)
// Verification Directory fv/bm_stage_3 
module gf_divider (
	a, 
	b, 
	q);
   input [3:0] a;
   input [3:0] b;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;

   NAND3BXL g2032__2398 (.Y(q[2]),
	.AN(n_77),
	.B(n_76),
	.C(n_67));
   OAI211X1 g2033__5107 (.Y(q[0]),
	.A0(n_66),
	.A1(n_68),
	.B0(n_73),
	.C0(n_67));
   OAI211X1 g2034__6260 (.Y(q[1]),
	.A0(n_65),
	.A1(n_68),
	.B0(n_76),
	.C0(n_72));
   OAI211X1 g2035__4319 (.Y(q[3]),
	.A0(n_28),
	.A1(n_70),
	.B0(n_74),
	.C0(n_67));
   OAI22XL g2036__8428 (.Y(n_77),
	.A0(n_53),
	.A1(n_75),
	.B0(n_61),
	.B1(n_68));
   NOR2XL g2037__5526 (.Y(n_75),
	.A(n_69),
	.B(n_71));
   NAND2XL g2038__6783 (.Y(n_76),
	.A(n_61),
	.B(n_69));
   OAI21XL g2039__3680 (.Y(n_74),
	.A0(n_53),
	.A1(n_63),
	.B0(n_71));
   NAND3BXL g2040__1617 (.Y(n_73),
	.AN(n_53),
	.B(n_29),
	.C(n_66));
   NAND3BXL g2041__2802 (.Y(n_72),
	.AN(n_61),
	.B(n_29),
	.C(n_64));
   NAND2XL g2042__1705 (.Y(n_70),
	.A(n_65),
	.B(n_64));
   NOR2XL g2043__5122 (.Y(n_71),
	.A(n_28),
	.B(n_66));
   NOR3BXL g2044__8246 (.Y(n_69),
	.AN(n_65),
	.B(n_28),
	.C(n_63));
   NAND3XL g2045__7098 (.Y(n_68),
	.A(n_29),
	.B(n_53),
	.C(n_63));
   NAND4XL g2046__6131 (.Y(n_67),
	.A(n_29),
	.B(n_60),
	.C(n_63),
	.D(n_65));
   OR2X1 g2047__1881 (.Y(n_66),
	.A(n_60),
	.B(n_65));
   XNOR2X1 g2048__5115 (.Y(n_65),
	.A(n_58),
	.B(n_62));
   CLKXOR2X1 g2049__7482 (.Y(n_64),
	.A(n_53),
	.B(n_63));
   ADDFX1 g2050__4733 (.CO(n_62),
	.S(n_63),
	.A(n_55),
	.B(n_54),
	.CI(n_59));
   INVXL g2051 (.Y(n_60),
	.A(n_61));
   ADDFX1 g2052__6161 (.CO(n_59),
	.S(n_61),
	.A(n_35),
	.B(n_50),
	.CI(n_52));
   XNOR2X1 g2053__9315 (.Y(n_58),
	.A(n_56),
	.B(n_57));
   XNOR2X1 g2054__9945 (.Y(n_57),
	.A(n_27),
	.B(n_51));
   OAI21XL g2055__2883 (.Y(n_56),
	.A0(n_42),
	.A1(n_49),
	.B0(n_43));
   OAI21XL g2056__2346 (.Y(n_55),
	.A0(n_40),
	.A1(n_49),
	.B0(n_38));
   XNOR2X1 g2057__1666 (.Y(n_54),
	.A(n_44),
	.B(n_49));
   XNOR2X1 g2058__7410 (.Y(n_52),
	.A(n_41),
	.B(n_49));
   XNOR2X1 g2059__6417 (.Y(n_51),
	.A(n_26),
	.B(n_49));
   XNOR2X1 g2060__5477 (.Y(n_53),
	.A(n_37),
	.B(n_49));
   NOR2BX1 g2061__2398 (.Y(n_50),
	.AN(n_37),
	.B(n_49));
   OAI21XL g2062__5107 (.Y(n_49),
	.A0(n_26),
	.A1(n_47),
	.B0(n_48));
   OAI2BB1X1 g2063__6260 (.Y(n_48),
	.A0N(n_26),
	.A1N(n_47),
	.B0(n_27));
   OA21X1 g2064__4319 (.Y(n_47),
	.A0(n_42),
	.A1(n_46),
	.B0(n_43));
   AND2X1 g2065__8428 (.Y(n_46),
	.A(n_45),
	.B(n_38));
   NAND2BXL g2066__5526 (.Y(n_45),
	.AN(n_40),
	.B(n_35));
   XNOR2X1 g2067__6783 (.Y(n_44),
	.A(n_36),
	.B(n_39));
   NAND2BXL g2068__3680 (.Y(n_43),
	.AN(n_39),
	.B(n_36));
   NOR2BX1 g2069__1617 (.Y(n_42),
	.AN(n_39),
	.B(n_36));
   XNOR2X1 g2070__2802 (.Y(n_41),
	.A(n_32),
	.B(n_33));
   NOR2BX1 g2071__1705 (.Y(n_40),
	.AN(n_33),
	.B(n_32));
   OAI211X1 g2072__5122 (.Y(n_39),
	.A0(b[2]),
	.A1(n_7),
	.B0(n_12),
	.C0(n_25));
   NAND2BXL g2073__8246 (.Y(n_38),
	.AN(n_33),
	.B(n_32));
   OAI21XL g2074__7098 (.Y(n_37),
	.A0(n_30),
	.A1(n_31),
	.B0(n_35));
   NAND2XL g2075__6131 (.Y(n_36),
	.A(n_13),
	.B(n_34));
   AOI31X1 g2076__1881 (.Y(n_34),
	.A0(a[1]),
	.A1(a[0]),
	.A2(n_1),
	.B0(n_24));
   NAND2XL g2077__5115 (.Y(n_35),
	.A(n_30),
	.B(n_31));
   OAI222XL g2078__7482 (.Y(n_33),
	.A0(b[0]),
	.A1(n_18),
	.B0(n_5),
	.B1(n_17),
	.C0(b[2]),
	.C1(n_12));
   OAI222XL g2079__4733 (.Y(n_32),
	.A0(a[0]),
	.A1(n_20),
	.B0(n_4),
	.B1(n_19),
	.C0(a[2]),
	.C1(n_13));
   INVX1 g2080 (.Y(n_28),
	.A(n_29));
   OAI222XL g2081__6161 (.Y(n_31),
	.A0(b[0]),
	.A1(n_8),
	.B0(n_12),
	.B1(n_9),
	.C0(b[2]),
	.C1(n_16));
   AOI221X1 g2082__9315 (.Y(n_30),
	.A0(n_1),
	.A1(n_15),
	.B0(n_4),
	.B1(n_10),
	.C0(n_21));
   NOR2XL g2083__9945 (.Y(n_29),
	.A(n_22),
	.B(n_23));
   AOI32X1 g2084__2883 (.Y(n_25),
	.A0(b[2]),
	.A1(n_5),
	.A2(n_11),
	.B0(b[3]),
	.B1(n_8));
   OAI22XL g2085__2346 (.Y(n_24),
	.A0(a[0]),
	.A1(n_19),
	.B0(n_6),
	.B1(n_10));
   OAI222XL g2086__1666 (.Y(n_27),
	.A0(n_1),
	.A1(n_4),
	.B0(a[1]),
	.B1(n_13),
	.C0(a[0]),
	.C1(n_14));
   OAI222XL g2087__7410 (.Y(n_26),
	.A0(b[1]),
	.A1(n_12),
	.B0(n_0),
	.B1(n_5),
	.C0(b[0]),
	.C1(n_16));
   NOR4X1 g2088__6417 (.Y(n_23),
	.A(a[0]),
	.B(a[3]),
	.C(a[1]),
	.D(a[2]));
   NOR4X1 g2089__5477 (.Y(n_22),
	.A(b[0]),
	.B(b[3]),
	.C(b[1]),
	.D(b[2]));
   NOR2XL g2090__2398 (.Y(n_21),
	.A(n_13),
	.B(n_10));
   AOI21XL g2091__5107 (.Y(n_20),
	.A0(a[2]),
	.A1(a[3]),
	.B0(n_3));
   AOI21XL g2092__6260 (.Y(n_18),
	.A0(b[2]),
	.A1(b[3]),
	.B0(n_2));
   NAND2XL g2093__4319 (.Y(n_17),
	.A(b[2]),
	.B(n_11));
   NAND3XL g2094__8428 (.Y(n_19),
	.A(a[1]),
	.B(a[2]),
	.C(n_6));
   INVXL g2095 (.Y(n_15),
	.A(n_14));
   NAND2XL g2096__5526 (.Y(n_16),
	.A(b[1]),
	.B(b[3]));
   NAND2XL g2097__6783 (.Y(n_14),
	.A(a[1]),
	.B(a[3]));
   NAND2XL g2098__3680 (.Y(n_13),
	.A(a[0]),
	.B(a[3]));
   NAND2XL g2099__1617 (.Y(n_12),
	.A(b[0]),
	.B(b[3]));
   INVXL g2100 (.Y(n_9),
	.A(n_8));
   NOR2XL g2101__2802 (.Y(n_11),
	.A(b[3]),
	.B(n_2));
   NAND2XL g2102__1705 (.Y(n_7),
	.A(b[0]),
	.B(b[1]));
   NAND2XL g2103__5122 (.Y(n_10),
	.A(a[2]),
	.B(n_3));
   NOR2XL g2104__8246 (.Y(n_8),
	.A(b[1]),
	.B(n_0));
   INVXL g2105 (.Y(n_6),
	.A(a[3]));
   INVX1 g2106 (.Y(n_5),
	.A(b[0]));
   INVX1 g2107 (.Y(n_4),
	.A(a[0]));
   INVXL g2108 (.Y(n_3),
	.A(a[1]));
   INVXL g2109 (.Y(n_2),
	.A(b[1]));
   INVX1 g2110 (.Y(n_1),
	.A(a[2]));
   INVXL g2111 (.Y(n_0),
	.A(b[2]));
endmodule

module bm_stage_3 (
	clk, 
	rst, 
	S1, 
	l1_2, 
	l2_2, 
	l1, 
	l2);
   input clk;
   input rst;
   input [3:0] S1;
   input [3:0] l1_2;
   input [3:0] l2_2;
   output [3:0] l1;
   output [3:0] l2;

   // Internal wires
   wire [3:0] div1;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;

   gf_divider u_div1 (.a(l2_2),
	.b(S1),
	.q(div1));
   DFFRX2 \l2_reg[0]  (.Q(l2[0]),
	.QN(UNCONNECTED),
	.D(div1[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l2_reg[2]  (.Q(l2[2]),
	.QN(UNCONNECTED0),
	.D(div1[2]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l2_reg[3]  (.Q(l2[3]),
	.QN(UNCONNECTED1),
	.D(div1[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l2_reg[1]  (.Q(l2[1]),
	.QN(UNCONNECTED2),
	.D(div1[1]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[0]  (.Q(l1[0]),
	.QN(UNCONNECTED3),
	.D(l1_2[0]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[3]  (.Q(l1[3]),
	.QN(UNCONNECTED4),
	.D(l1_2[3]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[2]  (.Q(l1[2]),
	.QN(UNCONNECTED5),
	.D(l1_2[2]),
	.RN(rst),
	.CK(clk));
   DFFRX2 \l1_reg[1]  (.Q(l1[1]),
	.QN(UNCONNECTED6),
	.D(l1_2[1]),
	.RN(rst),
	.CK(clk));
endmodule

