
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug 21 2025 16:10:41 -03 (Aug 21 2025 19:10:41 UTC)

// Verification Directory fv/or16 

module or16(a, y);
  input [15:0] a;
  output y;
  wire [15:0] a;
  wire y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  OR2X1 g200__2398(.A (n_2), .B (n_5), .Y (n_6));
  OR4X1 g201__5107(.A (a[10]), .B (a[13]), .C (n_1), .D (n_4), .Y
       (n_5));
  NAND2XL g202__6260(.A (n_0), .B (n_3), .Y (n_4));
  NOR4X1 g204__4319(.A (a[4]), .B (a[5]), .C (a[14]), .D (a[15]), .Y
       (n_3));
  OR4X1 g203__8428(.A (a[8]), .B (a[11]), .C (a[9]), .D (a[12]), .Y
       (n_2));
  OR4X1 g205__5526(.A (a[2]), .B (a[3]), .C (a[6]), .D (a[7]), .Y
       (n_1));
  NOR2XL g206__6783(.A (a[0]), .B (a[1]), .Y (n_0));
  BUFX20 drc(.A (n_6), .Y (y));
endmodule

